### ISSUE TITLE
[TC-351] Generate new SSL keys fails after a while

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1004]
<p>After some Traffic Ops runtime (few days), we noticed that we can't generate certificate anymore and receiving these messages in the log: </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
[2017-05-23 12:32:11,175] [DEBUG] Routing to controller <span class="code-quote">"UI::SslKeys"</span> and action <span class="code-quote">"create"</span>.
[2017-05-23 12:32:11,572] [WARN] SSL keys <span class="code-keyword">for</span> 'test_deliveryservice' could not be created.  Response was Error creating key and csr. Result is -1
[2017-05-23 12:32:11,573] [DEBUG] 302 Found (0.399329s, 2.504/s).
</pre>
</div></div>

<p>The CSR and KEY is created and valid in /var/tmp.</p>

<p>Issuing a "service traffic_ops restart" fixes the issue.</p>

<p>The code which seems to be failing is here :</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
                        #generate key and csr
                        my $result = UI::Utils-&gt;exec_command(
                                <span class="code-quote">"openssl req -nodes -newkey rsa:2048 -keyout $TMP_LOCATION/$hostname.key -out $TMP_LOCATION/$hostname.csr -subj /C=\"</span>$country\<span class="code-quote">"/ST=\"</span>$state\<span class="code-quote">"/L=\"</span>$city\<span class="code-quote">"/O=\"</span>$org\<span class="code-quote">"/OU=\"</span>$unit\<span class="code-quote">"/CN=$hostname"</span>
                        );
                        <span class="code-keyword">if</span> ( $result != 0 ) {
                                $response = { _rc =&gt; 400, _content =&gt; <span class="code-quote">"Error creating key and csr. Result is $result"</span> };
                                <span class="code-keyword">return</span> $response;
                        }
</pre>
</div></div>

Author: Steve Malenfant
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-351">https://issues.apache.org/jira/browse/TC-351</a>
Found Version: 1.8.0

**Comment by mitchell852** [comment]
closing as this is related to the perl implementation of ssl key generation. please reopen if you disagree.
