### ISSUE TITLE
[TC-320] cache url config parameters not created at the Mid Caches

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1005]
<p>From GH issue <a href="https://github.com/Comcast/traffic_control/issues/1743:" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1743:</a></p>

<p>We created a new delivery service and used the Cache URL expression. The parameters got created for Edges, but not for the Mids. Thus making ORT and ATS complain.</p>

Author: Steve Malenfant
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-320">https://issues.apache.org/jira/browse/TC-320</a>

**Comment by mitchell852** [comment]
cache url has been deprecated.
