### ISSUE TITLE
[TC-308] hdr_rw_* gets inserted in profiles, but they don't get removed...

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1007]
<p>Moved from <a href="https://github.com/Comcast/traffic_control/issues/714" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/714</a></p>

<p>Spend lots of time troubleshooting an config file generation issue which referred to a delivery service that was deleted or renamed.</p>

<p>If you look at the Profile Parameters, you'll notice there is entries you probably never created yourselves. During configuration file generation, looks like it looks for "^hdr_rw_mid" to see if needs to generate a file.</p>

<p>If the parameter still exists and the delivery service doesn't, it throws an error on either line 1210 or 1216 (looks like edge_header_rewrite is causing a problem too).</p>

<p>Removing the parameter does fix the problem. Do we really need to insert those "locations" in the database?</p>

```perl
sub header_rewrite_dot_config {
    my $self = shift;
    my $id   = shift;
    my $file = shift;

   my $server    = $self-&gt;server_data($id);
    my $text      = $self-&gt;header_comment( $server-&gt;host_name );
    my $ds_xml_id = undef;
    if ( $file =~ /^hdr_rw_mid_(.*)\.config$/ ) {
        $ds_xml_id = $1;
        my $ds = $self-&gt;db-&gt;resultset('Deliveryservice')-&gt;search(
{ xml_id =&gt; $ds_xml_id }
,
{ prefetch =&gt; [ 'type', 'profile' ] }
)-&gt;single();
        my $actions = $ds-&gt;mid_header_rewrite;
        $text .= $actions . "\n";
    }
```

Author: Steve Malenfant
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-308">https://issues.apache.org/jira/browse/TC-308</a>
Found Version: 1.8.0

**Comment by mitchell852** [comment]
@limited - we are moving away from location params, therefore, i believe this may no longer be relevant with later releases of TC.

**Comment by rob05c** [comment]
DS Location Params are inferred now. They still get created as of this writing, but there's a case to fix that. I'm closing as a
Duplicate https://github.com/apache/trafficcontrol/issues/4889
