### ISSUE TITLE
[TC-306] API does not handle anymap revalidation requests properly

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1008]
<p>(pulled from the github issue tracker of old)</p>

<p>I issued an API call to invalidate some content for an ANY_MAP delivery service:</p>

<p><span class="error">&#91;coolguy@randomhost ccdn&#93;</span> curl -o $HOME/foobar.com.stuff_purge.out -b /tmp/cookie -c /tmp/cookie --insecure -H 'Accept: application/json' -X POST --data '</p>
{ "dsId":"441", "regex":"/\d+/foobar.com/stuff1/", "startTime":"2016-01-29 18:06:40", "ttl":168 }
<p>' <a href="https://qa-host.kabletown.net/api/1.2/user/current/jobs" class="external-link" rel="nofollow">https://qa-host.kabletown.net/api/1.2/user/current/jobs</a><br/>
% Total % Received % Xferd Average Speed Time Time Time Current<br/>
Dload Upload Total Spent Left Speed<br/>
214 116 116 116 0 98 10 8 0:00:11 0:00:11 -<del>:</del><del>:</del>- 5</p>

<p><span class="error">&#91;coolguy@randomhost ccdn&#93;</span> cat $HOME/foobar.com.stuff_purge.out<br/>
{"alerts":[</p>
{"level":"success","text":"Successfully created purge job for: /\d+/foobar.com/stuff1/(TTL:168h)"}
<p>]}<span class="error">&#91;Fri Jan 29&#93;</span><span class="error">&#91;18:07:23&#93;</span><br/>
<span class="error">&#91;coolguy@randomhost ccdn&#93;</span></p>

<p>I then went into the UI and issued a separate invalidation request but changed the URI slightly (stuff1 became stuff2).</p>

<p>If you run a report, you can see the difference:</p>

<p><span class="error">&#91;root@midhost coolguy&#93;</span># /opt/ort/traffic_ops_ort.pl report error <a href="https://qa-host.kabletown.net" class="external-link" rel="nofollow">https://qa-host.kabletown.net</a> admin:xxxxxxxx<br/>
Fri Jan 29 18:17:41 UTC 2016<br/>
Version of this script: 0.55c<br/>
ERROR Traffic Ops is signaling that an update is waiting to be applied.<br/>
ERROR Lines for /opt/trafficserver/etc/trafficserver/regex_revalidate.config from Traffic Ops do not match file on disk.<br/>
ERROR Config file regex_revalidate.config line only in TrOps: /\d+/foobar.com/stuff1/ 1454263660<br/>
ERROR Config file regex_revalidate.config line only in TrOps: <a href="http://slow-([a-z0-9]+)-([0-9]+).sys.kabletown.net/d+/foobar.com/stuff2" class="external-link" rel="nofollow">http://slow-([a-z0-9]+)-([0-9]+).sys.kabletown.net/\d+/foobar.com/stuff2</a> 1454264281<br/>
<span class="error">&#91;root@midhost coolguy&#93;</span>#</p>

<p>We're missing the hostname regex on the API call.</p>

Author: Derek Gelinas
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-306">https://issues.apache.org/jira/browse/TC-306</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
@dg4prez - pretty sure you can no longer create invalidation requests on a delivery service with no origin (i.e. any map delivery services). please reopen if you do not agree that this should have been closed.
