### ISSUE TITLE
[TC-302] Change Log Created On Edit Profile Details and Close - GH #1341

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1010]
<p>The original issue was <a href="https://github.com/Comcast/traffic_control/issues/1341" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1341</a></p>

<p>I was seeing some Change Log entries which made me question my team mates.</p>

<p>Update profile with name: EDGE_R730XD_532-733</p>

<p>They haven't changed anything, but here's the steps to reproduce.</p>

<p>Parameters -&gt; Select Profile<br/>
Select Profile Details<br/>
Select Edit<br/>
Select Close (So no change are done, they simply wanted to copy&amp;paste)<br/>
At this point, a change log entry is produced for something that wasn't updated.</p>

<p><a href="https://github.com/Comcast/traffic_control/blob/master/traffic_ops/app/lib/UI/Profile.pm#L190-L212" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/blob/master/traffic_ops/app/lib/UI/Profile.pm#L190-L212</a></p>

Author: Dewayne Richardson
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-302">https://issues.apache.org/jira/browse/TC-302</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
related to old TO UI. closing.
