### ISSUE TITLE
[TC-210] User agent and application versions incorrect

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1013]
<p>The experimental (golang) Traffic Monitors appear to have a hardcoded version in the user agent string. This shouldn't really be hardcoded, or if it is, should be search/replaced at compile-time.</p>

<p><tt>common/fetcher/fetcher.go:      req.Header.Set("User-Agent", "traffic_monitor/1.0") // TODO change to 2.0?</tt></p>

<p>Additionally, the version served up by the application does not match the RPM version.</p>

Author: Jeff Elsloo
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-210">https://issues.apache.org/jira/browse/TC-210</a>
Found Version: 2.1.0

**Comment by zrhoffman** [comment]
Fixed in 9defb11441.
