### ISSUE TITLE
[TC-115] ATS sometimes does not reload the config while receiving a "traffic_line -x"

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1015]
<p>If the owner of a config file (e.g. ssl_multicert.config) is not ats.ats, ATS does not reload the config while receiving a "traffic_line -x".</p>

Author: John Shen
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-115">https://issues.apache.org/jira/browse/TC-115</a>
Found Version: 2.1.0

**Comment by ocket8888** [comment]
This isn't a bug, it's a safety feature of Linux. If your files are created with the wrong owner, then ORT is probably being run as the wrong user. If there's a bug in ORT where it's writing files with a bad permission set for some reason, please open a new issue. Currently, ORT seems to be handling this correctly (see discussion on #211)
