### ISSUE TITLE
[TC-104] httpsPort key is missing in the CRConfig contentRouters section for 1.8

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1017]
<p>Don't think it's a show stopper, it'll default to 443.</p>

Author: Jan van Doorn
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-104">https://issues.apache.org/jira/browse/TC-104</a>
Found Version: 2.1.0

**Comment by knutsel** [comment]
not relevant anymore
