### ISSUE TITLE
[TC-77] Docker files need small updates

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1019]
<p>Docker files need some minor updates. </p>

<p>1) Traffic Ops: centos question is different (centos72.), and some other minor things</p>

<p>2) riak needs search installed : <a href="http://trafficcontrol.apache.org/docs/latest/admin/traffic_vault.html#configuring-riak-search" class="external-link" rel="nofollow">http://trafficcontrol.apache.org/docs/latest/admin/traffic_vault.html#configuring-riak-search</a></p>

<p>I will try to create a PR once I'm done w 1.8 testing, there may be more. </p>

Author: Jan van Doorn
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-77">https://issues.apache.org/jira/browse/TC-77</a>
Found Version: 1.8.0

**Comment by knutsel** [comment]
@dangogh has taken full control of docker, this is old.
