### ISSUE TITLE
[TC-60] CDN usage overview API always returns tps=0

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1020]
<p>/api/1.2/cdns/usage/overview always returns tps=0</p>

<p>I suspect the problem lies in the usage_overview_tps_query() query</p>

<p><a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Delegate/CdnStatistics.pm#L104" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Delegate/CdnStatistics.pm#L104</a></p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-60">https://issues.apache.org/jira/browse/TC-60</a>
Found Version: 1.7.0

**Comment by mitchell852** [comment]
This endpoint is being deprecated, therefore, no need to fix the bug. Closing.
