### ISSUE TITLE
[TC-378] "Network Subnet" server configuration, actually expects a netmask

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1024]
<p>Trying to install <a href="https://issues.apache.org/jira/browse/TC-2" title="Add &quot;wrap_count&quot; to server scripted dashboard" class="issue-link" data-issue-key="TC-2"><del>TC-2</del></a>.1, I see that the "netmask" field in the server configuration was renamed to "Network subnet". However, when setting the value to a subnet (e.g. 10.9.8.0/24) TO complain it is "not a valid subnet". A netmask style value (e.g. 255.255.255.0) is accepted.</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-378">https://issues.apache.org/jira/browse/TC-378</a>
Found Version: 2.1.0

**Comment by guzzijason** [comment]
IMHO, this (netmask) field should be eliminated completely, in favor of specifying IPv4 addresses in CIDR notation, with `/mask`. This would make it consistent with contemporary methods of configuring IPv4 interfaces in linux, and also make it consistent with how we are already specifying IPv6 interface addresses, which is also in CIDR notation.

**Comment by mitchell852** [comment]
This is fixed with the changes @ocket8888 introduced via #4747 to support multiple interfaces per server but I'll let @ocket8888 close this issue as he's the one that fixed it.

**Comment by ocket8888** [comment]
Fixed by #4747
