### ISSUE TITLE
[TC-530] TRAFFIC_ROUTER default profile points to non existing coverage-zone DB endpoint

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1027]
<p>The "coveragezone.polling.url" variable in the TRAFFIC_ROUTER default profile published at <a href="http://trafficcontrol.apache.org/downloads/profiles/2.0.x/default/TRAFFIC_ROUTER_PROFILE.traffic_ops" class="external-link" rel="nofollow">http://trafficcontrol.apache.org/downloads/profiles/2.0.x/default/TRAFFIC_ROUTER_PROFILE.traffic_ops</a> is set to <a href="http://$" class="external-link" rel="nofollow">http://$</a></p>
{toHostname}
<p>/cdn/CZF/current/czf-current.json</p>

<p>However, this path does not exists in my traffic ops.<br/>
However, the path "routing/coverage-zone.json" does exists</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-530">https://issues.apache.org/jira/browse/TC-530</a>
Found Version: 2.1.0

**Comment by zrhoffman** [comment]
@nir-sopher 
The 5.1.x Traffic Router profile no longer includes the incorrect URL. From https://github.com/apache/trafficcontrol-website/blob/c76ab1409d/downloads/profiles/5.1.x/TRAFFIC_ROUTER.traffic_ops#L23-L27:

```json
{
  "config_file": "CRConfig.json",
  "name": "coveragezone.polling.url",
  "value": "http://{{enter your czf location here}}"
},
```

**Comment by phusinh** [comment]
> @nir-sopher The 5.1.x Traffic Router profile no longer includes the incorrect URL. From https://github.com/apache/trafficcontrol-website/blob/c76ab1409d/downloads/profiles/5.1.x/TRAFFIC_ROUTER.traffic_ops#L23-L27:
> 
> ```json
> {
>   "config_file": "CRConfig.json",
>   "name": "coveragezone.polling.url",
>   "value": "http://{{enter your czf location here}}"
> },
> ```


how can i find my CZF address is it in traffic ops or traffic monitor or traffic server or is a json file i created myself and set default values.hope you can answer

**Comment by ocket8888** [comment]
Traffic Ops and Traffic Monitor do not serve arbitrary static files. The CZF has to be available over HTTP or HTTPS by whatever method you choose.

**Comment by phusinh** [comment]
> ```json
>  "value": "http://{{enter your czf location here}}"
> ```

I still don't understand what you mean. So where can I find the "http://{{enter your czf location here}}" part? Thank you

**Comment by ocket8888** [comment]
It's up to you to provide that. You have to have a URL where a czf can be requested, and you put it there.
