### ISSUE TITLE
[TC-528] Traffic Router - To support the ${toHostname} pattern when parsing the cr-config

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1030]
<p>Few variables in the TRAFFIC_ROUTER default profile published at <a href="http://trafficcontrol.apache.org/downloads/profiles/2.0.x/default/TRAFFIC_ROUTER_PROFILE.traffic_ops" class="external-link" rel="nofollow">http://trafficcontrol.apache.org/downloads/profiles/2.0.x/default/TRAFFIC_ROUTER_PROFILE.traffic_ops</a> use the pattern $</p>
{toHostname}
<p>, however, at least till commit  3980b41797c8f2b616277df4b74e73a011c48869, traffic router does not replace this pattern with the ops hostname.</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-528">https://issues.apache.org/jira/browse/TC-528</a>
Found Version: 2.1.0

**Comment by zrhoffman** [comment]
@nir-sopher
Fixed in [`RELEASE-2.1.0`](https://github.com/apache/trafficcontrol/commits/RELEASE-2.1.0).
