### ISSUE TITLE
[TC-166] lastConfigCheck stat should be updated if CrConfigs have a different checksum but the same timestamp

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1032]
<p>When Traffic Router checks for a new CrConfig it first checks to see if the CrConfig returned from Traffic Monitor has the same checksum as it's current version, if it doesn't then Traffic Router attempts to process it.  During processing, if the new CrConfig has the same timestamp as the current CrConfig, Traffic Router logs and info message and returns false.  A warning is then logged saying CrConfig has been rejected.  This is ok, however, the lastConfigCheck stat is not updated.  Since the CrConfigs are the same, the lastConfigCheck stat should be updated.</p>

<p>This is basically an edge case that we came across because we are running javaTM and goTM in parallel.  The lastConfigCheck stat was only being updated once every other poll, which cause our alarms to go off.</p>

Author: David Neuman
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-166">https://issues.apache.org/jira/browse/TC-166</a>
Found Version: 2.0.0

**Comment by dneuman64** [comment]
Closing since I closed #312
