### ISSUE TITLE
[TC-151] Delivery Service XML IDs should be limited to lower-case letters

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1038]
<p>The DNS system is case-insensitive. Since a delivery service XML ID is used as part of the FQDN of the cache being redirected to, two different DSs cannot differ only by case.<br/>
This leads to the conclusion that it is best if we limit the XML IDs of delivery services to be lower-case only.<br/>
This would achieve the following:<br/>
1. Make domain names used by TC 'conventional' (i.e. lower-case only)<br/>
2. Remove the possibility of a case-conflict between DSs<br/>
3. Currently, Traffic Router does not behave correctly when a DS XML ID contains upper case letters. Limiting to lower-case would prevent the need to fix this <img class="emoticon" src="https://issues.apache.org/jira/images/icons/emoticons/smile.png" height="16" width="16" align="absmiddle" alt="" border="0"/></p>

<p>Current problems with TR behaviour, when an XML ID contains opper-case letter are:<br/>
1. The TR sends a redirect to a host FQDN which contains a lower-case version of the DS XML ID<br/>
2. The TR does not resolve the lower-case version of the host FQDN.</p>

<p>Here is an example to demo current bug in TR. DS XML ID is opencachehub-DT, TR redirects to opencachehub-dt, and then refused to resolve the cache name using this DS (a lot of irrelevant data was removed fro this text):</p>

<p>$ curl -L -s -D - <a href="http://tr.opencachehub-DT.stage-cdn.tc-stage.cqloud.com/video01.mp4" class="external-link" rel="nofollow">http://tr.opencachehub-DT.stage-cdn.tc-stage.cqloud.com/video01.mp4</a> -v</p>
<ul>
	<li>Connected to tr.opencachehub-DT.stage-cdn.tc-stage.cqloud.com (54.244.152.242) port 80 (#0)<br/>
&gt; GET /video01.mp4 HTTP/1.1<br/>
&gt; Host: tr.opencachehub-DT.stage-cdn.tc-stage.cqloud.com<br/>
&gt; Accept: <b>/</b><br/>
&gt; <br/>
&lt; HTTP/1.1 302 Moved Temporarily<br/>
&lt; Location: <a href="http://p39-edge-lab.opencachehub-dt.stage-cdn.tc-stage.cqloud.com/video01.mp4" class="external-link" rel="nofollow">http://p39-edge-lab.opencachehub-dt.stage-cdn.tc-stage.cqloud.com/video01.mp4</a><br/>
&lt; Content-Length: 0</li>
</ul>

<p>&lt; </p>
<ul>
	<li>Connection #0 to host tr.opencachehub-DT.stage-cdn.tc-stage.cqloud.com left intact</li>
	<li>Issue another request to this URL: 'http://p39-edge-lab.opencachehub-dt.stage-cdn.tc-stage.cqloud.com/video01.mp4'</li>
	<li>getaddrinfo(3) failed for p39-edge-lab.opencachehub-dt.stage-cdn.tc-stage.cqloud.com:80</li>
	<li>Couldn't resolve host 'p39-edge-lab.opencachehub-dt.stage-cdn.tc-stage.cqloud.com'</li>
</ul>

Author: Oren Shemesh
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-151">https://issues.apache.org/jira/browse/TC-151</a>
Found Version: 1.7.0

**Comment by mitchell852** [comment]
TP will give you this validation message: `Must be a valid DNS label (no special characters, capital letters, periods, underscores, or spaces and cannot begin or end with a hyphen)` and I believe the TO API does the same validation. Closing.
