### ISSUE TITLE
[TC-118] Traffic Ops should get it's name from some configuration when generating CrConfig

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1040]
<p>The code that generates the CrConfig has a problem when creating the "stat" section.<br/>
It fills values for that section, such as "tm_host", based on the HTTP headers found in the request that triggered the CrConfig snapshot:</p>

<p>Here is a snippet from traffic_ops/app/lib/UI/Topology.pm:</p>

<p>    $data_obj-&gt;</p>
{'stats'}<del>&gt;{'tm_path'}    = $self</del>&gt;req-&gt;url-&gt;path-&gt;{'path'};<br/>
    $data_obj-&gt;{'stats'}
<p>-&gt;</p>
{'tm_host'}
<p>    = $self-&gt;req-&gt;headers-&gt;host;</p>

<p>I find this to be a problem for two reasons:</p>

<p>This code assumes that it is being run from the context of an HTTP transaction, which to me sounds like contaminating the logic of actually creating the CrConfig with details from the upper layer which currently uses this logic. <br/>
For example, if one would want to run this code from a different path (Maybe in a unit test), it would be a problem.</p>

<p>If the traffic ops is accessed through a NAT, then the host name known to the HTTP client issuing the 'Snapshot CrConfig' request is not necessarily the same as the traffic ops host name known to the other components of the system, e.g. the traffic router that uses this information.</p>

<p>(This is how I found out about this problem - we are experimenting with deploying TC in the cloud (Amazon EC2) and the host name visible to the outside world is not the same as the host names used internally)</p>

<p>I believe that tm_host should come from the database (Currently there is no entry from the traffic ops itself, but such an entry can be created for this purpose), or from cdn.conf.</p>

Author: Oren Shemesh
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-118">https://issues.apache.org/jira/browse/TC-118</a>
Found Version: 2.1.0

**Comment by ocket8888** [comment]
This was fixed by #3069
