### ISSUE TITLE
[TC-475] TO integration test warnings

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1044]
<p>while running traffic_ops integration tests, there are a lot of warnings like this:</p>

<blockquote>
<p>Use of uninitialized value $ats_ver in substr at /opt/traffic_ops/app/lib/UI/ConfigFiles.pm line 1099.</p>
<ol>
	<li>... server: atsec-phl-01 CDN1 EDGE1_CDN1_421_SSL</li>
</ol>
</blockquote>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-475">https://issues.apache.org/jira/browse/TC-475</a>
Found Version: 2.1.0

**Comment by dangogh** [comment]
warning no longer shows up
