### ISSUE TITLE
[TC-386] Docker Image for Traffic Ops Update

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1061]
<p>The traffic ops install process has changed and the docker image requires updating to be usable.</p>

Author: Dylan Volz
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-386">https://issues.apache.org/jira/browse/TC-386</a>
Found Version: 2.1.0

**Comment by ocket8888** [comment]
Is this still true? what docker image? what updates?

**Comment by mitchell852** [comment]
closing. please reopen if still applicable.
