### ISSUE TITLE
[TC-5] LSBify all init scripts

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1064]
<p>CentOS 7.x kicks out warnings like this:</p>

<p><span class="error">&#91;68482.268987&#93;</span> systemd-sysv-generator<span class="error">&#91;22518&#93;</span>: <span class="error">&#91;/etc/rc.d/init.d/traffic_ops:24&#93;</span> PID file not absolute. Ignoring.</p>

<p>thanks @elsloo!</p>

Author: Mark Torluemke
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-5">https://issues.apache.org/jira/browse/TC-5</a>

**Comment by mitchell852** [comment]
@mtorluemke @elsloo we believe this is fixed. please reopen if you disagree or have more info.
