### ISSUE TITLE
[TC-284] Strip "actionable" query strings

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1065]
<p>If an "actionable" query string is present in the incoming URL, strip it to prevent duplication of object storage in case the delivery service's setting is to consider the qstring at the edge. If it is, leaving the qstring in place will potentially cause the same object to be stored twice; one object with the "actionable" TR query parameters and one without, if there are clients that make both types of requests.</p>

<p>Specific query strings are <tt>?format=json</tt>, <tt>?trred=false</tt>, and <tt>?fakeClientIpAddress=foo</tt>.</p>

Author: Jeff Elsloo
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-284">https://issues.apache.org/jira/browse/TC-284</a>
Found Version: 2.0.0

**Comment by rawlinp** [comment]
In general I think this would be good, but my worry is that there might be come clients/origins out there actually using a `format` query parameter. `trred` and `fakeClientIpAddress` seem less likely to be used by clients/origins since those are pretty TR-specific.

**Comment by ocket8888** [comment]
#3554 would add an HTTP header for `format` so that you can do that instead of using the query string parameter, to help avoid that collision
