### ISSUE TITLE
[TC-307] Need remap stats by host in Influx

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1067]
<p>Traffic Stats should store status codes by host. Ideally this would be by host and deliveryservice so that you could find status codes for a DS per cache. Traffic Monitor seems to have all the data necessary, just need to get Traffic Stats to gather, parse, and write to Influxdb. From <a href="https://github.com/Comcast/traffic_control/issues/1372" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1372</a></p>

Author: Jan van Doorn
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-307">https://issues.apache.org/jira/browse/TC-307</a>

**Comment by knutsel** [comment]
Not relevant anymore.
