### ISSUE TITLE
[TC-310] Parts of URL to hash on should be configurable per delivery service

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1068]
<p>Traffic Ops, Traffic Router will need updates for this &#8211; currently Traffic Router hashes on the whole URL (short of the query parameters).</p>

<p>Config might be similar to what is done for URL signing &#8211; "useparts = 0110"</p>

<p>From <a href="https://github.com/Comcast/traffic_control/issues/1455" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1455</a></p>

Author: Jan van Doorn
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-310">https://issues.apache.org/jira/browse/TC-310</a>

**Comment by knutsel** [comment]
Jeff said this was on the short term roadmap. See also #985 (don't know why that doesn't link - https://github.com/apache/trafficcontrol/issues/985)

**Comment by mitchell852** [comment]
i believe this has been solved with the new consistent hash regex feature introduced on a per ds basis.
