### ISSUE TITLE
[TC-311] Change Traffic Monitor 2.0 Query Parameter Filter to a single interface

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1069]
<p>Technical Debt.</p>

<p>Currently, DsStats and CacheStats have separate but very similar Filter interfaces. These should be combined, if possible. If it isn't possible, at least their duplicate logic should be combined to a single function.</p>

Author: Robert Butts
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-311">https://issues.apache.org/jira/browse/TC-311</a>

**Comment by zrhoffman** [comment]
@rob05c We provide CacheStats by interface via `/publish/CacheStatsNew` as of #5031
