### ISSUE TITLE
[TC-127] Extensions Documentation

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1075]
<p>Need to write some documentation on how to leverage TO extensions.</p>

<p>Basically TO extensions allow you to extend the TO API with api endpoints that may be specific to your business. </p>

<p>For example, maybe you REALLY want this api but there's no way it will get approved and merged into the codebase:</p>

<p>GET /api/1.2/random_quote_of_the_day</p>

<p>you can create this api as an extension and everybody is happy...</p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-127">https://issues.apache.org/jira/browse/TC-127</a>

**Comment by mitchell852** [comment]
this is specific to Perl API extensions so closing

**Comment by ocket8888** [comment]
Documentation exists for creating Go API extensions, including example code: https://traffic-control-cdn.readthedocs.io/en/latest/development/traffic_ops.html#go-plugins
