### ISSUE TITLE
[TC-170] dbdump in HA environment can be slow

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1077]
<p>If Traffic Ops and the primary postgres db are on separate machines with some amount of network latency,  Tools-&gt;dbdump can take a while.</p>

<p>If network latency is low,  that db dump takes 2 seconds or less.  If not,  I've seen up to 70 seconds.  Not sure how much of an issue this will be in production,  but backups should be set up accordingly..</p>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-170">https://issues.apache.org/jira/browse/TC-170</a>
Found Version: 2.0.0

**Comment by dangogh** [comment]
Recommendation is for TrafficOps and postgres primary db be installed on machines with low network latency between them to mitigate this situation.
