### ISSUE TITLE
[TC-252]  Child server updates - Enhance POST /api/$version/servers/:id/queue_update to queue child servers only

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1078]
<p>Provide the ability to queue updates on a cache's children caches (aka the caches that belong to that cache's child cache groups.)</p>

<p>This is needed when a cache is set to admin down and all the child caches will need to fetch updates to get the change to parent.config (which will exclude the parent cache).</p>

<p>The support of a request property like </p>
{ "childrenOnly":true }
<p> would suffice. So you'd have a call like this:</p>

<p>POST /api/$version/servers/:id/queue_update </p>
{ "action": "queue", "childrenOnly": true }

<p>to queue the updates of the children caches only (not the parent cache).</p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-252">https://issues.apache.org/jira/browse/TC-252</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
no harm in queuing updates on the parent AND the children. closing.
