### ISSUE TITLE
[TC-274] cache_stats and deliveryservice_stats endpoints should use configurable retention period value

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1080]
<p>The implementation of the following APIs use hard-coded values for the Retention Period</p>

<p>GET api/version/cache_stats<br/>
GET api/version/deliveryservice_stats</p>

<p>notice the "monthly" in the queries:</p>

<p><a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Builder/CacheStatsBuilder.pm#L78" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Builder/CacheStatsBuilder.pm#L78</a></p>

<p><a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Builder/CacheStatsBuilder.pm#L95" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Builder/CacheStatsBuilder.pm#L95</a></p>

<p><a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Builder/DeliveryServiceStatsBuilder.pm#L81" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Builder/DeliveryServiceStatsBuilder.pm#L81</a></p>

<p><a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Builder/DeliveryServiceStatsBuilder.pm#L96" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/Builder/DeliveryServiceStatsBuilder.pm#L96</a></p>

<p>this retention period name should be configurable and probably stored in the influxdb.conf files.</p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-274">https://issues.apache.org/jira/browse/TC-274</a>

**Comment by mitchell852** [comment]
if you need to override the behavior of this endpoint, you can simply create a Go API plugin.
