### ISSUE TITLE
[TC-305] Deleting a delivery service does not delete SSL keys from Traffic Vault

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1081]
<p><a href="https://github.com/Comcast/traffic_control/issues/1325" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1325</a></p>

Author: Eric Friedrich
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-305">https://issues.apache.org/jira/browse/TC-305</a>

**Comment by mitchell852** [comment]
actually it does now. on cdn snapshot any ssl keys associated with deleted ds's are removed from riak.
