### ISSUE TITLE
[TC-331] LDAP search filter contains Active Directory specific attributes

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1084]
<p>Moved from <a href="https://github.com/Comcast/traffic_control/issues/1129" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1129</a></p>

<p>The search filter used to locate user DNs contains hard coded values that only work with Active Directory:</p>

<p>$mesg = $ldap-&gt;search( base =&gt; $search_base, filter =&gt; "(&amp;(objectCategory=person)(objectClass=user)(sAMAccountName=$username))" );</p>

<p>This search filter should be configurable and should be in ldap.conf. Instead, it's hard coded in TrafficOps.pm.</p>

<p>For example, this search filter would work with most non-AD based LDAP severs:</p>

<p>(&amp;(objectClass=inetOrgPerson)(uid=$username))</p>

Author: Jeff Elsloo
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-331">https://issues.apache.org/jira/browse/TC-331</a>

**Comment by jhg03a** [comment]
@DylanVolz is this resolved now?

**Comment by zrhoffman** [comment]
This is configurable in `ldap.conf` now. From `example-ldap.conf`:
https://github.com/apache/trafficcontrol/blob/348875a3fa0f0f60a6e40bc5f60fa666655eff16/traffic_ops/app/conf/example-ldap.conf#L6
