### ISSUE TITLE
[TC-300] Combine cache key change and dropping of query strings

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1085]
<p><a href="https://github.com/Comcast/traffic_control/issues/511" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/511</a></p>

<p>mtorluemke commented on Sep 11, 2015<br/>
Not sure exactly how best to do this. Perhaps:</p>

<p>Get rid of the drop_qstring column, and beef up the 'recipes' for the cacheurl field.<br/>
Add 'cache_key_string' column, and add smarts to combine the two when both fields are set.</p>

Author: Matt Mills
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-300">https://issues.apache.org/jira/browse/TC-300</a>

**Comment by mitchell852** [comment]
cacheurl is no longer used in later versions of ATS. @mtorluemke @MattMills mind closing this or adding more info?

**Comment by MattMills** [comment]
I'd leave it up to Mark, I think I was just copying the issue from the old Comcast repo into Jira.
