### ISSUE TITLE
[TC-338] Raw remap text for mid tier server

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1087]
<p>Right now for each Delivery Service there is a spot for "Raw remap text". Right now it only applies this text to edges. We also need to ability to apply this to the mid tier caches too</p>

<p>moved from <a href="https://github.com/Comcast/traffic_control/issues/1543" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1543</a></p>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-338">https://issues.apache.org/jira/browse/TC-338</a>

**Comment by dangogh** [comment]
originally filed by @jpappa200 -- no clear need for this feature.   If needed by someone, a new issue should be created with background info.
