### ISSUE TITLE
[TC-59] Traffic Ops Client should return HTTP body on Error response

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1089]
Currently, if the Traffic Ops client gets back an Error response from TO, the calling method is returned a struct containing the StatusCode and Status (<a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/client/traffic_ops.go#L180" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/client/traffic_ops.go#L180</a>).  Sometimes there is useful information in the body of the response as well - such as why...

Author: Dave Neuman
JIRA Link: https://issues.apache.org/jira/browse/TC-59
Found Version: 2.1.0

**Comment by moltzaum** [comment]
@dneuman64 It seems this should be closed?
