### ISSUE TITLE
[TC-250] RPM tries to back up nonexistent on-disk CRConfigs

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1092]
<p>The spec file for the Traffic Ops RPM backs up config files and restores them during an upgrade. The the &lt;2.0 versions of Traffic Ops stored the CRConfig config on disk, while it's in the database in &gt;=2.0. This should be removed from the 2.x spec file.</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
traffic_ops/build/traffic_ops.spec:	  cd %{PACKAGEDIR} &amp;&amp; tar cf /<span class="code-keyword">var</span>/tmp/traffic_ops-backup.tar app/<span class="code-keyword">public</span>/*Snapshots app/<span class="code-keyword">public</span>/routing  app/conf app/db/dbconf.yml app/local app/cpanfile.snapshot
</pre>
</div></div>

<p>Specifically, the <tt>app/public/*Snapshots</tt> path likely will not exist. There might be <tt>Trafficserver-Snapshots</tt> but definitely not CRConfig.</p>

Author: Jeff Elsloo
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-250">https://issues.apache.org/jira/browse/TC-250</a>
Found Version: 2.1.0

**Comment by zrhoffman** [comment]
`app/public/*Snapshots` was removed from that line in 50d2c3fe5f.
