### ISSUE TITLE
[TC-165] Warning "Useless use of distinct on a grouped resultset"

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1093]
<p>Looks like this just is a warning,  but ought to be looked into..   Happens during integration tests (`prove t_integration`):</p>

<p>DBIx::Class::ResultSet::_resolved_attrs(): Useless use of distinct on a grouped resultset ('distinct' is ignored when a 'group_by' is present) at /Users/dkirkw001c/Code/src/github.com/dangogh/incubator-trafficcontrol/traffic_ops/app/lib/UI/Topology.pm line 79</p>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-165">https://issues.apache.org/jira/browse/TC-165</a>
Found Version: 2.1.0

**Comment by dangogh** [comment]
with move to Go,  not worth looking into this
