### ISSUE TITLE
[TC-152] misc/release.pl incorrectly updates the VERSION file

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1094]
<p>for 1.8.0-RC10,  I ran `misc/release.pl ... cut` to create the git tag, sign it,  etc..</p>

<p>Unfortunately,  we found one more change to be made,  so I ran the same command with a `cleanup` argument instead,  then another `... cut`.   I think the `cleanup`  decremented the VERSION file in master.</p>

<p>I think we ought to handle the VERSION file separately from this script,  so it should not modify VERSION at all..</p>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-152">https://issues.apache.org/jira/browse/TC-152</a>
Found Version: 2.1.0

**Comment by dangogh** [comment]
not using release.pl any longer
