### ISSUE TITLE
[TC-123] UI route (/healthdatadeliveryservice) is broken as no related html template exists

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1095]
<p>/healthdatadeliveryservice returns a 404 as no related html template exists for this route. My guess is this route can be deleted entirely but some research is probably needed.</p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-123">https://issues.apache.org/jira/browse/TC-123</a>
Found Version: 2.1.0

**Comment by ocket8888** [comment]
Route is commented out in `TrafficOpsRoutes.pm`, which I believe is as far as we're willing to go until the rewrite is complete.
