### ISSUE TITLE
[TC-105] Change the default setting for RAM cache algorithm in the seeds and default data

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1096]
<p>CONFIG proxy.config.cache.ram_cache.algorithm INT 1<br/>
CONFIG proxy.config.cache.ram_cache.use_seen_filter INT 1</p>

<p>Should be the defaults in all ATS profiles.</p>

Author: Jan van Doorn
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-105">https://issues.apache.org/jira/browse/TC-105</a>

**Comment by knutsel** [comment]
Seeds don't include default profiles anymore.
