### ISSUE TITLE
[TC-309] No Cache-Control on images

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1097]
<p>From GH issue #962:</p>

<p>This was observed during 1.3.0RC6 testing. The headers are different in 1.1.6 (actually not cache-control headers).</p>

<p>Images didn't show up sometimes, high latency to display the Health-&gt;Table View.</p>

<p>Is this a byproduct of using localhost connection (through Vagrant) ?</p>

<p>But doesn't seems like this code changed along the way...</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
Request URL:https:<span class="code-comment">//127.0.0.1:4443/images/graph.png
</span>Request Method:GET
Status Code:200 OK

Remote Address:127.0.0.1:4443
Response Headers
view source
Accept-Ranges:bytes
Access-Control-Allow-Credentials:<span class="code-keyword">true</span>
Access-Control-Allow-Headers:Origin, X-Requested-With, Content-Type, Accept
Access-Control-Allow-Methods:POST,GET,OPTIONS,PUT,DELETE
Access-Control-Allow-Origin:http:<span class="code-comment">//localhost:8080
</span>Cache-Control:no-cache, no-store, max-age=0, must-revalidate
Connection:keep-alive
Content-Length:892
Content-Type:image/png
Date:Fri, 22 Jan 2016 15:03:36 GMT
Last-Modified:Fri, 22 Jan 2016 13:14:28 GMT
Server:Mojolicious (Perl)
</pre>
</div></div>

<p>Logs</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
10.0.2.2 - - [22/Jan/2016:15:11:55 +0000] <span class="code-quote">"GET /api/1.1/traffic_monitor/stats.json?data_type=json HTTP/1.1"</span> 200 73
10.0.2.2 - - [22/Jan/2016:15:11:55 +0000] <span class="code-quote">"GET /images/good.png HTTP/1.1"</span> 200 617
10.0.2.2 - - [22/Jan/2016:15:11:55 +0000] <span class="code-quote">"GET /images/graph.png HTTP/1.1"</span> 200 892
10.0.2.2 - - [22/Jan/2016:15:12:00 +0000] <span class="code-quote">"GET /api/1.1/traffic_monitor/stats.json?data_type=json HTTP/1.1"</span> 200 73
10.0.2.2 - - [22/Jan/2016:15:12:02 +0000] <span class="code-quote">"GET /api/1.1/traffic_monitor/stats.json?data_type=json HTTP/1.1"</span> 200 73
10.0.2.2 - - [22/Jan/2016:15:12:02 +0000] <span class="code-quote">"GET /images/good.png HTTP/1.1"</span> 200 617
10.0.2.2 - - [22/Jan/2016:15:12:02 +0000] <span class="code-quote">"GET /images/graph.png HTTP/1.1"</span> 200 892
</pre>
</div></div>

<p>By default, the cdn.conf contains an entry showing</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
  cors =&gt; {
    access_control_allow_origin =&gt; 'http:<span class="code-comment">//localhost:8080'
</span>  },
</pre>
</div></div>

<p>Comment those lines and this will disable the Cache-Control headers for all files. Use only if you are not going through a proxy. Enjoy the fast UI again.</p>

<p>The Cache Control should be changed for static files. These should probably be set to something like max-age=86400. When doing development, these should be disabled so one doesn't get frustrated not seeing updates made...</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
/opt/traffic_ops/app/<span class="code-keyword">public</span>/css
/opt/traffic_ops/app/<span class="code-keyword">public</span>/images
/opt/traffic_ops/app/<span class="code-keyword">public</span>/js
/opt/traffic_ops/app/<span class="code-keyword">public</span>/theme
</pre>
</div></div>

Author: Steve Malenfant
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-309">https://issues.apache.org/jira/browse/TC-309</a>

**Comment by ocket8888** [comment]
TO UI is deprecated in 2.2, disabled in 3.0, and removed entirely in the next major release (hopefully, but at the least this will happen eventually).
