### ISSUE TITLE
[TC-512] Default cdn.conf should have a traffic_ops_golang_port defined

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1098]
<p>Postinstall handles adding traffic_ops_golang_port to the cdn.conf, but there is no example in the default cdn.conf.</p>

<p>Almost documentation bug, but having some working defaults in cdn.conf is a good idea.</p>

Author: Steve Malenfant
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-512">https://issues.apache.org/jira/browse/TC-512</a>
Found Version: 2.1.0

**Comment by ocket8888** [comment]
This has been fixed @smalenfant , the current `cdn.conf` file has a `port` in its `traffic_ops_golang` section

**Comment by zrhoffman** [comment]
Fixed in 04669c1a9c.
