### ISSUE TITLE
[TC-292] Traffic Ops. Warn when a delivery service is not assigned

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1102]
<p>When pushing close on the delivery service screen a box should pop up when there have been no server assignments for the delivery service. This should only occur if the delivery service has been set to active.</p>

<p><a href="https://github.com/Comcast/traffic_control/issues/197" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/197</a></p>

Author: Eric Friedrich
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-292">https://issues.apache.org/jira/browse/TC-292</a>

**Comment by mitchell852** [comment]
TO UI is being deprecated so this is probably something to build into TP. I.e. on DS save if ds.servers.count <1 pop a message like "warning. 0 servers assigned"
