### ISSUE TITLE
[TC-196] API endpoint for Traffic Ops version

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1104]
<p>Traffic Ops UI has Help-&gt;About link to show what version is installed along with other info.    Wish there were an easy way to tell what version is installed for automated testing/monitoring.</p>

<p>Something like .../api/1.2/about could return a json struct with relevant info from that page.</p>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-196">https://issues.apache.org/jira/browse/TC-196</a>

**Comment by jhg03a** [comment]
I think this is done @dangogh

**Comment by mitchell852** [comment]
it is. search for `about` in routes.go

closing
