### ISSUE TITLE
ASN table should also allow entry of BGP community tags

### ISSUE THREAD

**Issue by knutsel** [apache/trafficcontrol#1106]
Many networks are just one ASN, and in that case the ASN table in its current form is a bit useless. 

Propose to add a "bgp_comm_tag" column to this table and associated APIs to allow networks to use BGP community tags to associate customer networks with cachegroups.

**Comment by mitchell852** [comment]
@jhg03a - any thoughts on this one?

**Comment by jhg03a** [comment]
Both ASN and BGP Community Tags are arbitrary mappings to locations.  So for some implementations it may make sense to use one over another.  They could be used as part of an implementation of a czf generator.  I'm not sure I'd just add it to the ASN table though as it would break the 1:1 mapping of cachegroup to ASN.  I think it would be easier/better for it to be a peer structured like the ASN table, then it can have its own 1:1 relationship of cachegroup to BGP Community Tag.  It's more flexible to have it, but it's not a huge priority for me personally.

**Comment by jhg03a** [comment]
Also for what it's worth, this request predates the implementation of deep_czf as an option which may be used similarly if the generator implementation chooses to use this information.

**Comment by mitchell852** [comment]
> Also for what it's worth, this request predates the implementation of deep_czf as an option which may be used similarly if the generator implementation chooses to use this information.

sounds like we have a workaround! i think i'll close. @knutsel please reopen if u feel strongly about this request.
