### ISSUE TITLE
Traffic Ops does not ignore active ANY_MAP Delivery Services when generating CRConfig

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#1121]
According to the documentation for Delivery Services:
> ANY_MAP is not known to Traffic Router. For this deliveryservice, the “Raw remap text” field in the input form will be used as the remap line on the cache.

However, Traffic Ops treats it similarly to an HTTP Delivery Service when generating CRConfig, and this is only avoided by setting the ANY_MAP Delivery Service to inactive. Rather, Traffic Ops should filter out ANY_MAP Delivery Services when generating the CRConfig so that Traffic Router doesn't treat them like an HTTP Delivery Service.

**Comment by mitchell852** [comment]
@rawlinp  - can you put a severity level label on this? trivial, minor, major, critical...or actually, since you can't attach labels, reach out to me and i'll attach it for you

**Comment by rawlinp** [comment]
@mitchell852 I'd say it's probably minor because setting it to inactive if it's causing problems is easy enough.

**Comment by rawlinp** [comment]
I fixed this in the Perl API , but it looks like it was overlooked in the Golang rewrite of the CRConfig endpoints and is now an issue again.
