### ISSUE TITLE
Traffic Ops "maintenance mode"

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#1124]
some situations require that traffic ops db not be modified for a period of time,  e.g. when upgrading to a newer version.  In-process items should be finished up,  but no new actions started.

Create a "maintenance mode" that can be set by an admin.   This should be shown somehow on the UI and any modification actions disallowed until changed back to the "normal mode".

**Comment by mitchell852** [comment]
without the protection this provides, you could corrupt TO which would have a very negative impact on traffic control.

**Comment by rawlinp** [comment]
Here's an idea:
- some kind of global "maintenance" flag in the DB
- some way to grant "maintenance" privileges to TO users

If a user does not have maintenance privileges, and TO is in maintenance mode, all their requests get 503'd.

**Comment by mitchell852** [comment]
> Here's an idea:
> 
> * some kind of global "maintenance" flag in the DB
> * some way to grant "maintenance" privileges to TO users
> 
> If a user does not have maintenance privileges, and TO is in maintenance mode, all their requests get 503'd.

would it make sense to use a couple new parameters that are part of the global profile? i.e. 

1. name=maintenance, config_file=global, value=true|false and 
2. name=maintenance.users, config_file=global, value=comma-separated list of usernames that can interact w/ TO when maintenance=true

or is that taking parameters too far?

**Comment by ocket8888** [comment]
I think that's "parameter abuse". Especially since `value =true|false` cannot be enforced.

**Comment by rawlinp** [comment]
Yeah, I'd lean more towards something like a new `maintenance_mode_users` table. If there are any rows, TO is in maintenance mode, and each row contains a user ID that is allowed to perform operations. But any admin can take us in or out of maintenance mode.

**Comment by mitchell852** [comment]
wondering if this is needed anymore since "cdn locks" was introduced. basically, you can apply an exclusive lock (aka hard lock) on one or all of the cdns which will prevent anyone except for you changing the state of the cdn.

**Comment by rawlinp** [comment]
I think cdn locks pretty much cover this use case.

**Comment by zrhoffman** [comment]
> I think cdn locks pretty much cover this use case.

Agreed. If anyone feels it doesn't, feel free to comment so we can reopen.
