### ISSUE TITLE
cache url expression configs do not get added to mid profiles

### ISSUE THREAD

**Issue by jpappa200** [apache/trafficcontrol#1125]
When we add a cache url expression to a delivery service in Traffic Ops the config files only get added to the edge profiles. We have to remember to manually add them to the mid profiles other wise ORT will have issues and the configs do not get put on the mids.

**Comment by mitchell852** [comment]
@jpappa200 - can you put a severity level label on this? trivial, minor, major, critical...

**Comment by mitchell852** [comment]
cache url expression was deprecated with ATS 6.x and will be removed altogether from ATC with PR #4644
