### ISSUE TITLE
ATS Config File Generation, add logging.config

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#1126]
ATS 7.1 requires logging.config to be configured instead of logs_xml.config. 

Need to add logging.config parameters with the same params as logs_xml.config.

**Comment by ezelkow1** [comment]
Added in https://github.com/apache/trafficcontrol/pull/1635

**Comment by limited** [comment]
@ezelkow1 Is this ready to be closed then?

**Comment by ezelkow1** [comment]
@limited yes it can be
