### ISSUE TITLE
Configurable Menu for Traffic Portal per Users' preference

### ISSUE THREAD

**Issue by thusai000** [apache/trafficcontrol#1161]
Traffic Portal's top level menus and navigation should be allowed to be configurable and persisted per user preference. Drag and drop capability will help structure the views to be more meaningful. Traffic Portal is used by clients of various job functions, an operator might want to lay out the UI differently than a tenant. Ability to group and structure relevant views/pages would be a strong feature enhancement.

Benefits:
1. Quickly locate frequently used views
1. Reduce number of click-throughs to perform job function by various organizations

**Comment by mitchell852** [comment]
Not sure I'll be able to pull off drag and drop but I should be able to make the menu order / groupings configurable using the traffic_portal_properties.json file.
