### ISSUE TITLE
CDN APIs: Routing

### ISSUE THREAD

**Issue by dewrich** [apache/trafficcontrol#1210]
- [ ] GET /cdns/routing

Implement feature parity with the same Traffic Ops Mojolicious endpoint

**Comment by mitchell852** [comment]
Note: This route is probably getting deprecated so you might not want to move it to Golang

**Comment by mitchell852** [comment]
sounds like this might actually be implemented in golang. please consult @elsloo

**Comment by smalenfant** [comment]
Hopefully this fixes #902 at the same time. Just adding for reference.

**Comment by mitchell852** [comment]
this endpoint is addressed in #2232
