### ISSUE TITLE
Config Files APIs

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#1234]
- [ ] get /api/$version/servers/:id/configfiles/ats
- [ ] get /api/$version/profiles/:id/configfiles/ats/#filename
- [ ] get /api/$version/servers/:id/configfiles/ats/#filename
- [ ] get /api/$version/cdns/:id/configfiles/ats/#filename

**Comment by dewrich** [comment]
See https://github.com/apache/incubator-trafficcontrol/pull/151 to see if it can support this task

**Comment by mitchell852** [comment]
these endpoints are addressed in #2232
