### ISSUE TITLE
Delivery Service APIs: CRUD

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#1236]
- [ ] get /api/$version/deliveryservices
- [ ] get /api/$version/deliveryservices/:id
- [ ] post /api/$version/deliveryservices
- [ ] put /api/$version/deliveryservices/:id
- [ ] delete /api/$version/deliveryservices/:id

**Comment by rob05c** [comment]
https://github.com/apache/incubator-trafficcontrol/pull/2124

**Comment by mitchell852** [comment]
this endpoint is addressed in #2232
