### ISSUE TITLE
ORT needs timeout to be configurable

### ISSUE THREAD

**Issue by DylanVolz** [apache/trafficcontrol#1248]
The ORT timeout is hardcoded to 30 seconds and should be set by a command line variable or similar.

**Comment by ocket8888** [comment]
This was implemented in ORT as the `--to_timeout_ms` argument and is maintained in T3C as `--traffic-ops-timeout-milliseconds`, so it seems this has been done.

Please re-open if the existing command line argument does not appear to work correctly, or if you meant some other timeout.
