### ISSUE TITLE
HWINFO APIs: CRUD

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#1306]
- [x] GET /api/1.2/hwinfo
- [ ] GET /api/1.2/hwinfo/:id
- [ ] GET /api/1.2/hwinfo/:name
- [ ] PUT /api/1.2/hwinfo/:id
- [ ] PUT /api/1.2/hwinfo/:name
- [ ] POST /api/1.2/hwinfo
- [ ] DELETE /api/1.2/hwinfo/:id
- [ ] DELETE /api/1.2/hwinfo/:name

**Comment by dewrich** [comment]
We'll have to tackle pagination (which we haven't yet, could follow the pattern of the query_builder) with this one because of the amount of data

**Comment by mitchell852** [comment]
this endpoint is addressed in #2232
