### ISSUE TITLE
rewrite ssl_multicert endpoint 

### ISSUE THREAD

**Issue by DylanVolz** [apache/trafficcontrol#1315]
the endpoint: api/1.2/cdns/title-vi/configfiles/ats/ssl_multicert.config
handled here: ApacheTrafficServer::ssl_multicert_dot_config
needs to be rewritten (into go) to not load every ds in the cdn twice.

This is a subtask of #1234

**Comment by mitchell852** [comment]
this endpoint is addressed in #2232
