### ISSUE TITLE
Add API endpoints to store and fetch cdn uri signing keys in traffic vault.

### ISSUE THREAD

**Issue by jrushford** [apache/trafficcontrol#1362]
A new Traffic server plugin is now available that implements the draft IETF CDNI URI signing.  In order to configure this plugin, it is required to retrieve JWK keysets , to put in the uri signing plugin's configuration file.   Endpoints to be added:

`
http GET /api/1.3/deliveryservices/{xml-id}/urisignkeys
`
`http POST /api/1.3/deliveryservices/{xml-id}/urisignkeys
`

**Comment by mitchell852** [comment]
"ds-id" is a little confusing. is this the ds database id or the ds xml-id? ideally, your routes would support both. which would probably mean you create 4 routes instead of 2.

http GET /api/version/deliveryservices/{:id}/urisignkeys
http POST /api/version/deliveryservices/{:id}/urisignkeys
http GET /api/version/deliveryservices/{:xml-id}/urisignkeys
http POST /api/version/deliveryservices/{:xml-id}/urisignkeys

where the first 2 key off an Int and the 2nd 2 key off a string.

**Comment by mitchell852** [comment]
also, i'm not sure this should be version 1.3. you should ask @dewrich

**Comment by rob05c** [comment]
It needs to be in something newer than 1.2, per Semantic Versioning. New features get new minor versions. Major versions should be reserved for breaking changes, so this itself doesn't need a major version.

This should not be put in 1.2, it will break people in confusing ways who have a newer client hitting an older server, with the "same" 1.2 version.

**Comment by rob05c** [comment]
> "ds-id" is a little confusing. is this the ds database id or the ds xml-id? ideally, your routes would support both.

-1 There should be one way to do things. Multiple ways to do the same thing are confusing and double the effort to learn and understand everything. Doing `xml-id` seems reasonable.

**Comment by jrushford** [comment]
What was I thinking :), I changed it to xml-id

**Comment by jrushford** [comment]
This new api is similar to the existing url_sig_keys endpoint.  Both are for delivery services tha use the uri_sig plugin and now for the new cdn_uri signing plugin.  I only need the xml-id endpoints for ort to generate the config file.  Unless I’m missing something, I don’t need the ds-id(int).

**Comment by mitchell852** [comment]
These apis exist - https://traffic-control-cdn.readthedocs.io/en/latest/api/v4/deliveryservices_xmlid_urisignkeys.html#deliveryservices-xml-id-urisignkeys
