### ISSUE TITLE
Status APIs: CRUD

### ISSUE THREAD

**Issue by dewrich** [apache/trafficcontrol#1377]
- [x] GET /api/$version/statuses
- [x] Get /api/$version/statuses/:id
- [x] PUT /api/$version/statuses/:id
- [x] POST /api/$version/statuses
- [x] DELETE /api/$version/statuses/:id

**Comment by dewrich** [comment]
First part completed by https://github.com/apache/incubator-trafficcontrol/pull/1393

**Comment by mitchell852** [comment]
this is done
