### ISSUE TITLE
Hash + encode xml_id to use as an option for a reverse proxy FQDN

### ISSUE THREAD

**Issue by mtorluemke** [apache/trafficcontrol#1476]
One suggestion is to use SipHash (2,4) + Base58 (for optimum human+computer readability). Thanks @PSUdaemon for the recommendation!

So, "edge.my-delivery-service-1.kabletown.net" becomes: "edge.EMJ59wJ1uoU.kabletown.net"

**Comment by zrhoffman** [comment]
I don't think we should build any features off of the assumption that we can make DNS records secret or difficult to guess.

@alficles if you see merit in this issue, comment and we can re-open.
