### ISSUE TITLE
GET /api/1.3/cdns/:name/snapshot/new fails if no caches assigned to cdn

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#1494]
GET /api/1.3/cdns/foo/snapshot/new returns an internal server error if no caches are assigned to a cdn. Instead, it should return a 400 Bad Request with a description of the problem.

**Comment by ZugNZwang** [comment]
I created a brand new CDN and immediately following that did a:
`GET /api/1.3/cdns/test/snapshot/new` and received the following response:
```http 
HTTP/1.1 200 OK 
Content-Type: application/json
{
    "response": {
      ...
    }
}
```

**Comment by rob05c** [comment]
This case was made before that route was moved to `traffic_ops_golang`. Guessing it was implicitly fixed then.

**Comment by mitchell852** [comment]
closing as appears to be fixed
