### ISSUE TITLE
deliveryservice.multi_site_origin_algorithm column isn't accessible via any UI

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#1546]
The question is is the deliveryservice.multi_site_origin_algorithm  even used anymore or was it abandoned when delivery service profiles were introduced? 

If it is fact used, it needs to be added to the TO UI and the TP UI. and i'm guessing it only pertains to DNS* and HTTP* delivery services.

If it is not used, the column should be deleted from the database in my opinion.

**Comment by dg4prez** [comment]
This is set in the DS profile now, so it doesn't need to have a column.

**Comment by mitchell852** [comment]
i _think_ the ds.multi_site_origin (boolean) is the only mso related field used currently. ds. multi_site_origin_algorithm has been completely abandoned and should be removed but additional research may be required before doing so.
