### ISSUE TITLE
Service Build - Copy an existing configuration with minimal inputs

### ISSUE THREAD

**Issue by ryandurfey** [apache/trafficcontrol#1563]
Create a new service by copying an existing service with only a few mandatory fields.  Mandatory fields might be: xmlid, origin.  Allow user to override other fields in copy by sending values as desired.  So if an edge header rewrite value is sent in the request, this would overwrite the copy value.

For example:
 
Mandatory:
Copy xmlid = x
new xmlid = y
origin = z

**Comment by mitchell852** [comment]
this is done. you can clone delivery services in TP. can I close this @ryandurfey ?
