### ISSUE TITLE
Managing federations on a CDN with no delivery services results in internal server error

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#1580]
For example, this would happen on a brand  new cdn.

I think the problem has to do with an empty IN statement

https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Federation.pm#L523

**Comment by srikailash** [comment]
Hi @mitchell852 , i am interested to work on this issue . can you tell me how to reproduce this issue ?

**Comment by moltzaum** [comment]
Not fixed in the perl directly, but rewritten in go.
