### ISSUE TITLE
Traffic Ops Golang Panics if Listen Config is Missing

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#1590]
Traffic Ops Golang should print or log an error if the config is invalid, rather than panicing.

Issue is here:
https://github.com/apache/incubator-trafficcontrol/blob/317a82a522ee75e870a22267e4c6bad6fabd9e27/traffic_ops/traffic_ops_golang/config.go#L214

**Comment by mitchell852** [comment]
@rob05c - can you put a severity level label on this? trivial, minor, major, critical...

**Comment by mitchell852** [comment]
@DylanVolz is working on this
