### ISSUE TITLE
TP -- Delivery Service DNS TTL field allows "e" and "."

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#1770]
the `Delivery Service DNS TTL` field in the traffic portal delivery service create page restricts input to numbers,  but still allows the letter `e` and `.`.   It really should only allow whole positive numbers.

**Comment by anna-k-1** [comment]
CDN-3163

**Comment by mitchell852** [comment]
this is fixed. not sure when but it was fixed.

![image](https://user-images.githubusercontent.com/251272/73495911-aca54100-4374-11ea-9c97-b97c670e2301.png)

![image](https://user-images.githubusercontent.com/251272/73495937-b62ea900-4374-11ea-8259-6c3023ce893e.png)
