### ISSUE TITLE
(RFE) TP: customizable table fields in the UI

### ISSUE THREAD

**Issue by guzzijason** [apache/trafficcontrol#1796]
As a Traffic Portal user, it would nice to be able to customize what fields are visible/searchable/sortable when viewing any table in the UI. For example, if I'm viewing the Delivery Services table, it might be useful to be able to add the initial dispersion field to my view (or any other arbitrary field that I might be interested in at the moment). The option to remove default field columns might be useful as well. I could see this being an individual user preference of some sort, so that changes made by one user don't affect other users' views.

**Comment by rob05c** [comment]
Putting this in 2.3 Milestone

@mitchell852 (or anyone else who might implement it) If this looks feasible for 2.2, feel free to move there.

**Comment by mitchell852** [comment]
functionality provided by PR #3760
