### ISSUE TITLE
ILO server field opens SSH instead of HTTPS link

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#1801]
In Traffic OPs, the link for ILO is https although looks like the new UI is now sending us to an SSH terminal screen.

Marked as regression due to change in functionality. This feature was added as part of #1399.

Would be nice if you we can have multiple choice on the click like "ssh, https, copy link". Context menu?

**Comment by jagooch** [comment]
+1 this feature. Implementation could be clickable icons near the IP address. 
- A computer terminal icon with an  SSH protocol link to the ILO. 
- A Web icon with an https link, properly formatted for ipv6 https connection to ILO. 


The feature could provide the auto-population of the ILO username/password fields using credentials stored in TODB . An access check would be necessary to control access to the credentials. 

The addition of credentials would enable 1-click login to the ILO Web interface.

**Comment by rawlinp** [comment]
ILO server field link is now https not ssh.
