### ISSUE TITLE
Traffic Monitor get stuck without configuration when launched while ops is down

### ISSUE THREAD

**Issue by nir-sopher** [apache/trafficcontrol#1846]
Whenever traffic-monitor is lunched and cannot bull the cr-config, it get stuck with the below messages in the log.
Only a monitor restart after ops is up resolve the issue.

ERROR: datareq.go:258: 2018-02-02T18:26:57.968237985Z: Request Error: /api/cache-count: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:57.968995775Z: Request Error: /api/cache-available-count: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:57.969861925Z: Request Error: /api/cache-down-count: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:57.970341475Z: Request Error: /api/cache-statuses: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:58.060326628Z: Request Error: /api/bandwidth-capacity-kbps: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:58.060482056Z: Request Error: /api/cache-count: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:58.060484512Z: Request Error: /publish/ConfigDoc: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:58.060531397Z: Request Error: /api/version: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:58.076461981Z: Request Error: /api/cache-available-count: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:58.308209146Z: Request Error: /publish/CrStates: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:58.467255395Z: Request Error: /publish/DsStats: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:59.22444596Z: Request Error: /api/bandwidth-kbps: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:59.224445942Z: Request Error: /api/traffic-ops-uri: service still starting, some caches unpolled: map[]
ERROR: datareq.go:258: 2018-02-02T18:26:59.224532243Z: Request Error: /publish/EventLog: service still starting, some caches unpolled: map[]^C^C

**Comment by nir-sopher** [comment]
@rob05c 
FYI,
Nir

**Comment by rawlinp** [comment]
I believe this issue has been fixed in #2921.
