### ISSUE TITLE
Traffic Portal - ORG servers should show what MSO DSs are using them

### ISSUE THREAD

**Issue by dg4prez** [apache/trafficcontrol#1863]
When you click on a server, it should show which delivery services have that origin server assigned.  This will reduce confusion as we can and do have multiple origin servers with the same hostnames.  It would also help if you could click on the server to modify the config when viewing the assigned servers list for a DS.

**Comment by mitchell852** [comment]
ok, so right now if you click on a server of type EDGE you’ll see

![image](https://user-images.githubusercontent.com/251272/35982292-ab72146c-0cac-11e8-90a8-f0dc89acac41.png)

you want the 'View Delivery Services' menu item to show for ORG servers, right?

**Comment by dg4prez** [comment]
Yes exactly.

**Comment by mitchell852** [comment]
and also, on the ds / server assignment page (https://localhost:8443/#!/delivery-services/:dsId/servers?type=DNS), you want the servers to be clickable, right? so you can quickly go to a server to edit the properties...

**Comment by mitchell852** [comment]
![image](https://user-images.githubusercontent.com/251272/61565076-3757cb80-aa35-11e9-8a7b-5e5fe1eec490.png)

it looks like in TP you can see the ds's associated with an ORG server

**Comment by mitchell852** [comment]
> and also, on the ds / server assignment page (https://localhost:8443/#!/delivery-services/:dsId/servers?type=DNS), you want the servers to be clickable, right? so you can quickly go to a server to edit the properties...

this appears to be done too. closing this issue. @dg4prez please reopen if things don't look right.
