### ISSUE TITLE
/api/1.2/cdns/my-cdn-name/configs/monitoring.json is not CDN/Profile specific

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#1903]
If you have multiple profiles on different CDN with different parameters, you'll end up with unwanted results.

For example, if I have 2 CDNs and enable `peers.polling.interval` on only a single RASCAL profile, it will show up on both CDNs Traffic Monitor.

**Comment by rob05c** [comment]
Looks like the bug is here https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/monitoring.go#L386

`monitoring.go` `getConfig` needs to take the CDN name, and add a `WHERE cdn.name = $1` to the query.
