### ISSUE TITLE
Deterministic Cachegroup failover

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#1907]
Currently, if all caches in a cache group are unavailable Traffic Router will route clients to the next closest cache group. This works great for some networks but could cause problems in others. Traffic Control should provide the ability to configure which cache group to fail over to if a given cache group is unavailable. Ideally, this will be able to be configured in Traffic Ops.

**Comment by limited** [comment]
We just completed work on a feature very similar to this based on this old email thread:
https://lists.apache.org/thread.html/7ebadacc6d1f8cf9fd230910faa1950638c7bdbb1ff7007a540446eb@%3Cdev.trafficcontrol.apache.org%3E

Our implementation places the backup policy in the CZF instead of the TO.

**Comment by mitchell852** [comment]
I think all the backend (API/database) has been done for this. Just need to hook it into TP.
