### ISSUE TITLE
Health and Stats delay different than Traffic Monitor Java

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#1923]
In previous version of Traffic Monitor (2.1, java). The "query_time" was an indication on how long the _astats took to download. 

In the Go version of Traffic Monitor, the Health and Stats is the delay to receive the header response since it is chunked.

We have cache servers that have bad NIC's which Traffic Monitor would detect even at idle speed. This doesn't show anymore.

The Health and Stats query time should include time finishing downloading the body.

**Comment by smalenfant** [comment]
@rob05c I tried to fix this although seems like I could not get the body transfer delay included in the Stat Time. You mind taking a look?

https://github.com/smalenfant/incubator-trafficcontrol/tree/sm-resp-time

**Comment by rob05c** [comment]
The Fetcher isn't actually reading the body, it's passing the `io.Reader` to the Handler. The Go runtime may choose not to read it from the socket, until it's actually read from the `io.Reader` in the Handler. 

The reqTime needs to be set right after we actually read the bytes, after this line: https://github.com/apache/incubator-trafficcontrol/blob/b3a20df3d1e6405ff530ab20b5698e700ee6da46/traffic_monitor/cache/cache.go#L308
