### ISSUE TITLE
riak_test fails without network connectivity

### ISSUE THREAD

**Issue by DylanVolz** [apache/trafficcontrol#1925]
--- FAIL: TestGetRiakCluster (0.00s)
	riak_test.go:309: expected no errors, actual: lookup www.devnull.com: no such host.
FAIL
exit status 1
FAIL	github.com/apache/incubator-trafficcontrol/traffic_ops/traffic_ops_golang	0.586s

tests probably shouldn't fail without network access.

**Comment by mitchell852** [comment]
any/all failing tests need to be fixed. no story required.
