### ISSUE TITLE
Additional textbox in DS request form

### ISSUE THREAD

**Issue by ashish-timilsina** [apache/trafficcontrol#1934]
Add a free textbox / notes field in DS request form to allow customers to input other info about their DS i.e origin server / security details (header to access the origin origin test file, etc) 
@mitchell852
@dangogh
@dewrich
@ryandurfey
@ashish-timilsina

**Comment by ashish-timilsina** [comment]
@mitchell852 yes that should work however, I can't seem to find the comment field. Is it "Long Description 2"?

**Comment by mitchell852** [comment]
I'm going to close this as longDesc2 can be used as your "additional notes" by specifying the label/description for longDesc2 in traffic_portal_properties.json
