### ISSUE TITLE
Traffic Portal ANY_MAP Delivery Service form contains Traffic Router configurations

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#1943]
ANY_MAP delivery services are unknown to the Traffic Router. There are some TR configuration options present in the form that should be removed:

- TR Request Headers
- TR DNS TTL
- Geo Limit fields (RGB, Geolimit Countries, Geolimit Redirect)

**Comment by mitchell852** [comment]
so sounds like all of these fields should be removed from the any_map ds form:

![image](https://user-images.githubusercontent.com/251272/70656832-0bbdc380-1c18-11ea-8542-8cfc06c51529.png)
