### ISSUE TITLE
GUI Reporting for `ADMIN_DOWN` Cache Server

### ISSUE THREAD

**Issue by hbeatty** [apache/trafficcontrol#1991]
Change Traffic Monitor to continue reporting on the status of a Cache Server when marked `ADMIN_DOWN` in TO.

Conversation from Slack:

Hank Beatty [11:02 AM]
We have an edge server that is marked `ADMIN_DOWN` in TO and is unreachable. In 2.2 of TM it is showing `ADMIN_DOWN` (orange) not `OFFLINE` (red). Apparently this is different from the behavior of TM 2.1 Java. Is this the planned new behavior or is this a bug?

Dave Neuman [11:04 AM]
you expect it to be OFFLINE because it is not reachable? (edited)

Hank Beatty [11:05 AM]
Steve does.
And apparently that was the behavior before.
with the Java version.

Matt Mills [11:54 AM]
It would likely turn red if you service trafficserver stop
I do not believe OFFLINE servers will show up in TM at all, since they’re removed from the CR Config
the “red” in TM is when TM marks it down
so (guessing) it likely turns red regardless of REPORTED or ADMIN_DOWN if it is unreachable

Dave Neuman [12:07 PM]
but Hank is saying that is not happening
he is saying that the server is admin_down so it's orange
but he is expecting Red
since it's unreachable

Matt Mills [12:11 PM]
https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_monitor/static/index.html#L292
GitHubGitHub
apache/incubator-trafficcontrol
incubator-trafficcontrol - Mirror of Apache Traffic Control (incubating)

Rob Butts [12:29 PM]
Right, the TM GUI displays ADMIN_DOWN caches as orange, regardless whether polling indicates they’re Available.
Whether it was planned or a bug is a matter of perspective. I planned it when I wrote it, not being aware of the old behavior. Feel free to make an Issue for it, if it’s something you find valuable
Doesn’t matter to me if it’s tagged Bug or Enhancement

Hank Beatty [1:16 PM]
@robert_butts We do find it valuable for maintenance reasons mainly. We like the fact that the Java version kept polling and reporting on the server even though it was `ADMIN_DOWN`. It can take a while for a cache server to drop all of its connections once it is put in an `ADMIN_DOWN` state. Having the continual updates was a nice feature.

Rob Butts [1:17 PM]
The new one does keep polling and reporting, it’s just not in the GUI. Shouldn’t be too hard to change. Just needs a bit more logic around L292 where Matt linked

Steve Malenfant [1:21 PM]
Here’s a few things I just noted from testing REPORTED vs ADMIN_DOWN. I would need to retest the Java version to see how it behaved, but I think these behaviors could be enhanced.
When a cache is in ADMIN_DOWN state and then becomes unavailable:- Status is not updated with “Unreachable”
- Should probably be colored “RED”
- UI is not updated: Health Time, Stat Time, Bandwidth and Connection Count and kept to latest values
- Caches count doesn’t include the server as being down (it does when in REPORTED State)

**Comment by zrhoffman** [comment]
> Hank Beatty [11:02 AM]
> We have an edge server that is marked `ADMIN_DOWN` in TO and is unreachable. In 2.2 of TM it is showing `ADMIN_DOWN` (orange) not `OFFLINE` (red). Apparently this is different from the behavior of TM 2.1 Java. Is this the planned new behavior or is this a bug?

An `ADMIN_DOWN` but unreachable how is still orange, but the interface that is unreachable shows up as red in the Traffic Monitor UI. Does this look okay to you @hbeatty?

![ADMIN_DOWN but unreachable mid-02](https://user-images.githubusercontent.com/11163823/116271733-7dc77780-a73d-11eb-8891-5faeeeabcb57.png)

**Comment by hbeatty** [comment]
This has been resolved to our satisfaction.
