### ISSUE TITLE
Limit Network Routing by Tenant by CZF and Country

### ISSUE THREAD

**Issue by ryandurfey** [apache/trafficcontrol#1994]
As we take on new tenants we often negotiate to protect our service by limiting them to on net (CZF) or in country traffic so as not to allow them to impact our peering or connections.  

We would like to be able to setup a tenant and specify whether they are limited to delivery by CZF or CZF plus country codes.  We would also like to tie in how to handle overflow traffic into these settings.

Tenant should not be able to override these settings.

**Comment by mtorluemke** [comment]
Already done.
