### ISSUE TITLE
Traffic Portal Snapshot Diff button to jump to next diff

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#2009]
Snapshot diffs are huge, and I have to scroll thru a huge amount of text, to find the single line that changed, e.g. when changing a server's status.

It'd be nice if there were a button (or some other UI component) to jump to the first change in the diff.

Ideally, there'd be something always visible to "jump to next", to quickly jump thru every change in the diff.

**Comment by rob05c** [comment]
@mitchell852

**Comment by mitchell852** [comment]
that sounds like a good idea. in the interim, you can search for ++ or --

but yes, the CRConfig.json can get very large and the diff is simply a diff (performed in the browser in TP) between the current CRConfig.json and what a new CRConfig.json will look like (after snapshotting). 

in fact, the CRconfig.json at comcast was so big, the browser could not handle it all so i created a setting in traffic_portal_properties.json called snapshot.diff.context that dictates how much context (in lines) is given around a change. for example, if you set that to 10, you'd get 10 lines before and after a change. however, it's hard to determine how much "context" is required to truly understand the change. 10 probably wouldn't do it. anyhow, that setting can help you limit the size of the diff in TP.

**Comment by mitchell852** [comment]
fixed with #3540
