### ISSUE TITLE
Clarify Docs for building, to indicate location of pkg script

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#2028]
https://traffic-control-cdn.readthedocs.io/en/latest/development/building.html says to use the "pkg script", but it doesn't say where it is. The docs should note it's in the root of the repo, and possibly include a link to Github or instructions to checkout and run it.

I know that might seem obvious, but I'm making this case because we actually had someone asking where to find it.

Relatedly, the docker-compose instructions on the same page have the same problem. Might be worth adding to the instructions, a section on how go get the code and navigate to it, i.e. 
```
mkdir -p $GOPATH/src/github.com/apache/
cd $GOPATH/src/github.com/apache/
git clone https://github.com/apache/incubator-trafficcontrol
cd incubator-trafficcontrol
```

**Comment by dneuman64** [comment]
Looks like the docker compose instructions have been updated.  I will submit a PR to add the pkg location.
