### ISSUE TITLE
TO API - profiles route no longer supports "includeParams" query param

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2059]
For example

GET /api/1.2/profiles/417?includeParams=true (perl) returns the parameters associated with the profile

whereas

GET /api/1.3/profiles/417?includeParams=true (golang) does not.

**Comment by mitchell852** [comment]
IMO just include the params with the GET /api/1.3/profiles/:id so the ?includeParams query param can be deprecated.

**Comment by dewrich** [comment]
Yes just ignore the `includeParams` because /api/1.2/profiles/417 will always return it.  Retrieving a Profile without it's parameters seems silly.
