### ISSUE TITLE
TO golang needs to be able to operate with no TLS

### ISSUE THREAD

**Issue by DylanVolz** [apache/trafficcontrol#2087]
currently there is no way to start up the golang side of the TO server without TLS certs, we need a config option to allow starting the server without certs and serving http.

**Comment by ocket8888** [comment]
HTTPS is fairly ubiquitous in the modern world, creating certificates is fairly simple, and CDN-in-a-Box will start up a Traffic Ops instance for you without needing any manual key generation steps. Which is to say, I can't really think of a good reason not to use secure communications except for testing, and testing with HTTPS is already so easy I'm not sure we need the capability to run Traffic Ops without it.

**Comment by rawlinp** [comment]
Closing this out as I was the one who suggested this to @DylanVolz way back when TLS was made a requirement, but times have changed. I agree w/ @ocket8888, we don't really need to add a non-TLS option for TO.
