### ISSUE TITLE
Download page should not use MD5 hashes; they are deprecated

### ISSUE THREAD

**Issue by sebbASF** [apache/trafficcontrol#2163]
The use of MD5 hashes on download pages was deprecated recently:

https://www.apache.org/dev/release-distribution#sigs-and-sums

MD5 hashes should no longer be generated or linked from the download page for new releases.

**Comment by sebbASF** [comment]
The latest release also has a SHA512 hash so the MD5 does not have to be replaced with a new hash; the links can just be dropped (and removed from its download dir)

However the verification instructions will have to be changed.

**Comment by sebbASF** [comment]
The previous release also has an SHA512 hash so its MD5 hash link could also be dropped from the page.
(Projects cannot remove files from archive.apache.org)

**Comment by rob05c** [comment]
@dangogh @sebbASF I removed them from the latest RC, didn't remove the previous versions. Should we remove the MD5s from the previous releases? (2.1, 2.0)?

**Comment by sebbASF** [comment]
Maybe the simplest is to tidy the page when you publish the next release.

**Comment by dangogh** [comment]
+1

**Comment by dangogh** [comment]
this happened with the 2.2 release -- no more MD5 hashes
