### ISSUE TITLE
When creating a header rewrite using traffic portal/api the "location" parameter isn't created

### ISSUE THREAD

**Issue by saoyag001** [apache/trafficcontrol#2176]
creating a mid header rewrite rule on a delivery service does not create a location parameter for the mid header rewrite resulting in a failed remap. This does work on the old traffic ops ui.

**Comment by jhg03a** [comment]
This also effects the edge header rewrite rule field as well.

**Comment by mitchell852** [comment]
Looking at this file:

https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm#L344-L372

It looks like 6 config files could be dynamically created based on the existence of certain values of a delivery service:

1. url_sig_*.config
2. uri_signing_*.config
3. cacheurl*.config
4. hdr_rw_*.config
5. regex_remap_*.config
6. set_dscp_*.config

therefore each of these files will need a location parameter so ORT knows where to put the config file.

This is the bug. When setting edge header rewrite or mid header rewrite values on a deliveryservice through the API

POST /api/deliveryservices
PUT /api/deliveryservices/:id

apparently the required location parameter is not being created as such:

name=location, 
value=/opt/trafficserver/etc/trafficserver
config_file=hdr_rw_xml-id.config

which causes ORT to fail as it has no idea where to put the hdr_rw_*.config file.

When fixing this bug, check that a location parameter is also being created for the other 4 files.

**Comment by rob05c** [comment]
Need to ensure this is implemented in https://github.com/apache/incubator-trafficcontrol/pull/2124

**Comment by mitchell852** [comment]
@dneuman64 - this can be closed, right? the location parameters are now created as expected?

**Comment by jhg03a** [comment]
#3970

**Comment by mitchell852** [comment]
> #3970

?

**Comment by jhg03a** [comment]
Independent

**Comment by mitchell852** [comment]
> Independent

@jhg03a - so why is this closed then?

**Comment by jhg03a** [comment]
I don't know why it was closed.  I'm not sure if this is still an issue given how far back of a release I've been on.  it would be worth investigating again just as a sanity check that edge & mid location params are working like they ought to be.

**Comment by mitchell852** [comment]
ok, i'll reopen.

**Comment by rob05c** [comment]
I believe this was fixed with the move to Go. See https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/deliveryservice/deliveryservices.go#L1476

But it's definitely fixed in the latest ORT, via https://github.com/apache/trafficcontrol/pull/4861
