### ISSUE TITLE
VOD delivery services are cached in RAM on Live-Only servers

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#2193]
For "Live only" server profiles (profiles w/o a Drive_Letter_Prefix), VOD Delivery Services can be assigned. These delivery services are silently (without warning the user) cached in RAM, rather than disk as would be expected. 

I would expect Traffic Ops validation to warn users or block this configuration when:
a) A VOD DS is assigned to a server profile without a disk storage volume 
 or 
b) The parameters defining a disk storage volume are deleted from a profile. 

@PeterRyder

**Comment by mitchell852** [comment]
this use case can be satisfied using the newly released server capabilities functionality @PeterRyder that introduced in TC 4.0. Closing. Please reopen if you disagree.
