### ISSUE TITLE
TO go - snapshot/new differences between Perl and Go implementations

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#2210]
Comparing the `/api/1.3/cdns/xxx/snapshot/new` endpoints between the Perl and Go versions revealed some differences.   The most obvious was that the Perl version has a top-level "response" object and the Go version does not:

```{ "response": ... }```

I saw other differences,  but none seemed to be structural.

**Comment by rob05c** [comment]
Same for `/api/1.3/cdns/over-the-top/snapshot` (but not the old `/CRConfig-Snapshots/title-vi/CRConfig.json`).
