### ISSUE TITLE
When fetching a user thru the API, capabilities should be added to the response

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2220]
when fetching a user object via one of these routes:

GET /api/$version/user/current
GET /api/$version/users
GET /api/$version/users/:id

the response should include the capabilities of the user in addition to the role. for example:

{
  role: 4,
  capabilities: [ 'asn-read', 'asn-write' ]
}

otherwise, 2 calls have to be made to fetch the capabilities of a user

GET /api/$version/user/current
GET /api/$version/roles/user.roleID from previous call

**Comment by mitchell852** [comment]
@moltzaum is working on this

**Comment by mitchell852** [comment]
added to roles and perms project

**Comment by mitchell852** [comment]
was this done with the roles/perms project @srijeet0406 @ocket8888 @shamrickus?

**Comment by ocket8888** [comment]
Yeah, this was closed with #6124
