### ISSUE TITLE
Portal Servers page is missing Traffic Monitor link

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#2230]
The old UI has a button on Traffic Monitor Server rows, that links to that monitor's FQDN (web GUI).

The Portal has no easy way to navigate to the monitor's webpage. I have to copy the host name, paste it somewhere, copy the domain, paste it in the same place, copy the entire FQDN, and paste it in the browser.

IMO it would be a good feature if the Portal had a link to the FQDN of every server. Or at the very least, displayed the full text that could be copied, which is two steps instead of like five. I frequently do the same with caches to see astats in the browser. And even if a server doesn't have a web UI (like Riak), you still need to copy the FQDN to paste into the command line, to hit the API.

Labelling bug, because it's in the old UI and not the new.

**Comment by mitchell852** [comment]
easy enough to make TP link to:

server.hostname + server.domainname

but which protocol? http? https?

**Comment by rob05c** [comment]
HTTP. The Monitor only serves HTTP, no HTTPS.

**Comment by mitchell852** [comment]
that's what i was thinking but thanks for the clarification

**Comment by mitchell852** [comment]
anyhow, looks like i already did this but forgot :)

just need to link the PR to this

**Comment by mitchell852** [comment]
fixed. see attached PR
