### ISSUE TITLE
ORT Routes need to point to the 1.3 TO APIs

### ISSUE THREAD

**Issue by dewrich** [apache/trafficcontrol#2239]
/api/1.3/*
- [ ] POST - /user/login
- [ ] GET - /servers/:id/configfiles/ats
- [ ] GET - /profiles/:id/configfiles/ats/:filename
- [ ] GET - /servers/:id/configfiles/ats/:filename
- [ ] GET - /cdns/name/:name/sslkeys
- [ ] GET - /deliveryservices/:xmlID/urisignkeys
- [x] POST - /servers/:hostname_short/update_status
- [ ] GET - /statuses
- [x] GET - /system/info

**Comment by rawlinp** [comment]
I noticed ORT still uses the `/login` endpoint to login (rather than a proper API route):
```
	my $url = $to_host . "/login";
	my $response = $lwp_conn->post( $url, [ 'u' => $u, 'p' => $p ], %headers );
```

**Comment by dg4prez** [comment]
https://github.com/apache/trafficcontrol/pull/2636

**Comment by rob05c** [comment]
With the `atstccfg` client-side config gen, this no longer applies. Config gen uses the TO Client, which uses the API login endpoint as well as the latest API version.
