### ISSUE TITLE
Traffic Vault sslkeys.xml schema name incorrect

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#2252]
Should this schema read "sslkeys" ?

https://github.com/apache/incubator-trafficcontrol/blob/ad102f35f046ab63fc84b61f8481f7e5e056777a/traffic_ops/app/conf/misc/riak_search/sslkeys.xml#L22

**Comment by anna-k-1** [comment]
@smalenfant is this issue causing any known bugs?

**Comment by mitchell852** [comment]
closing as riak is soon to be deprecated.
