### ISSUE TITLE
golang api should support ?orderby=x:DESC

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2261]
there has been some discussion about pushing orderby to the clients of the api rather than returning a default orderby on the server side. if we are going to do this, then ASC or DESC needs to be supported 

i.e.

/api/1.3/logs?orderby=lastUpdate <-- sort ascending
/api/1.3/logs?orderby=lastUpdate:DESC <-- sort descending

**Comment by ocket8888** [comment]
I believe this has been done (for all endpoints that support sorting)

**Comment by mitchell852** [comment]
> I believe this has been done (for all endpoints that support sorting)

with just ?orderby=name&sortOrder=desc ?

**Comment by ocket8888** [comment]
Yeah, exactly
