### ISSUE TITLE
Only create/update/modify DNSSEC keys for DS types that are routed on the CDN

### ISSUE THREAD

**Issue by elsloo** [apache/trafficcontrol#2272]
Create DNSSEC keys only for DS types that are routed on the CDN, such as any HTTP or DNS type. ANY_MAP, or other types that are not routed on the CDN should not have DNSSEC keys created for them.

**Comment by mitchell852** [comment]
Is this still true @rawlinp and would this just be wasted performance?

**Comment by rawlinp** [comment]
Yes, this does still appear to be true and is just wasted storage/bandwidth/performance.
