### ISSUE TITLE
CDNS API returns a 404 when there are no SSL Keys 

### ISSUE THREAD

**Issue by ajschmidt** [apache/trafficcontrol#2285]
The API method: /api/1.2/cdns/name/{cdn_name}/sslkeys.json returns a 404 if there are no SSL keys defined for the CDN. This should probably return an empty list or an error message. If the CDN does include 'https' delivery services then it should probably return an error.

**Comment by mitchell852** [comment]
a 404 implies "bad route" and i'd only expect to see that if you put in an invalid cdn_name

if the cdn_name is valid and there are no ssl keys, then an empty array would be expected.

**Comment by mitchell852** [comment]
may need to research if this is still applicable in API 2.x+

**Comment by ocket8888** [comment]
It does look as though there's no situation in which Traffic Ops would return a 404 from that endpoint; @ajschmidt can you confirm if this is still an issue?

**Comment by mitchell852** [comment]
i'll close. @ajschmidt can reopen if necessary. thanks for checking @ocket8888
