### ISSUE TITLE
Implement /api/1.1/cdns/metric_types

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#2309]
The route `/api/1.1/cdns/metric_types` is documented in API 1.x, but disappeared from Traffic Ops a long time ago.

This route should be implemented, as part of the 1.x API.

**Comment by rob05c** [comment]
Readers, be aware: this route is not currently a priority, and not scheduled to be implemented any time soon. If this route is an issue for you, please let us know, and we can discuss prioritizing it. We would also welcome a pull request implementing the route.

**Comment by ocket8888** [comment]
This route is deprecated; we won't be adding an implementation for it.
