### ISSUE TITLE
Provide the ability to fetch all children tenants for a specified tenant

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#2312]
Can you please add a new TO API endpoint /api/<ver>/tenants/children/:id which returns a list of all tenant ids that are children and requested id.  This simplifies TO API users needing to reconstruct the parent chains of all tenants.

**Comment by jhg03a** [comment]
My use case right now is trying to filter delivery services by tenant including children.  The TP UI currently uses /api/<ver>/deliveryservices?tenant=<id> for the UI path Tenants/<tenant name>/Delivery Services.  This does not recurse however.

**Comment by jhg03a** [comment]
Another option would be to add a new parameter ?tenentchildren=true or ?astenant=<name/id> to applicable endpoints ideally, but that may be more work.

**Comment by mitchell852** [comment]
I think the shortest path is this:

GET api/1.3/deliveryservices?tenant=60&recurse=true (or something like that) to fetch ALL delivery services associated with the specified tenant PLUS any delivery services associated with descendants of the specified tenant.

**Comment by mitchell852** [comment]
@jhg03a - as of api v2 there is a new query param called accessibleTo=tenantId that will fetch all delivery services "accessible to a particular tenant" which includes all children tenants? Does that work and if so, you want to close this?

https://traffic-control-cdn.readthedocs.io/en/latest/api/v2/deliveryservices.html#request-structure

**Comment by shamrickus** [comment]
Added `accessibleTo` in #4528

**Comment by jhg03a** [comment]
Sounds like that satisfies the main use case I had.
