### ISSUE TITLE
Correct Traffic Vault install documentation 

### ISSUE THREAD

**Issue by jgoochcmcast** [apache/trafficcontrol#2370]
Remove this section which does not apply to new installs of TV

> Riak Search (using Apache Solr) will now index all NEW records that are added to the “ssl” bucket. The cdn, deliveryservice, and hostname fields are indexed and when a search is performed riak will return the indexed fields along with the crt and key values for a ssl record. In order to add the indexed fields to current records and to get the current records added, a standalone script needs to be run. The following explains how to run the script.

Get script from github either by cloning the project and going to traffic_ops/app/script or from here
Run the script by performing the following command ./update_riak_for_search.pl -to_url=https://traffic-ops.kabletown.net -to_un=user -to_pw=password
Validate the search is working by querying against Riak directly: curl -kvs "https://admin:password@riakserver:8088/search/query/sslkeys?wt=json&q=cdn:mycdn"

Validation can also be done by querying Traffic Ops: curl -Lvs -H "Cookie: $COOKIE" https://traffic-ops.kabletown.net/api/1.2/cdns/name/mycdn/sslkeys.json

**Comment by mitchell852** [comment]
want to submit a PR for this @jgoochcmcast ?

**Comment by mitchell852** [comment]
closing as riak is soon to be deprecated.
