### ISSUE TITLE
Router hostname should be searchable in the servers page

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#2385]
Often times there are maintenances that affect a certain router, it would be nice if you could search the server page by router hostname to understand which caches/servers that maintenance will affect.

**Comment by mitchell852** [comment]
This could be done by simply adding routerHostName to the servers table...but then the table is getting pretty crowded...

another approach would be to add hidden columns which would be searchable. this is probably the best approach imo.

**Comment by mitchell852** [comment]
I will soon be creating a PR to allow the user to define which columns of the servers table they would like to see. similar to #3739

**Comment by mitchell852** [comment]
functionality provided in #3760
