### ISSUE TITLE
Global DNS TTL adjustment

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#2388]
As a SRE, I would like the ability to adjust all delivery service DNS TTLs to a lower temporary value.  This would allow for quicker turnaround time when performing Traffic Router maintenance that involves restarts.  This can be performed today with a direct SQL query, but that's a non-advised solution.

**Comment by mitchell852** [comment]
@jhg03a - severity level? minor, medium, major?

**Comment by jhg03a** [comment]
I stuck it as medium because directly touching TODB for mass editing is the current workaround and it's quite dangerous.

**Comment by mitchell852** [comment]
@jhg03a - what exactly does this sql query look like? update the ttl on all delivery services to X? if that was performed how would you revert that?

**Comment by jhg03a** [comment]
It probably wouldn't need to touch the actual ds, but rather just interpose itself as a higher priority value.

**Comment by jhg03a** [comment]
As a secondary thing, it would be really nice to know what the max TTL was prior to imposing the override somehow.  This is because when you first start to use this feature, you still have to wait for existing TTL to expire regardless.

**Comment by jhg03a** [comment]
And this override shouldn't impact DS who's TTL is already below the override TTL.

**Comment by awilson75** [comment]
> As a secondary thing, it would be really nice to know what the max TTL was prior to imposing the override somehow. This is because when you first start to use this feature, you still have to wait for existing TTL to expire regardless.

> And this override shouldn't impact DS who's TTL is already below the override TTL.

This needs to be created as a separate issue and shouldn't block the work we have ready to release.
