### ISSUE TITLE
Cloning Delivery Service doesn't carryover custom routing name

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#2389]
When cloning a delivery service I expect that custom routing names would be populated based on the source DS.  Instead they are populated with the default.

**Comment by anna-k-1** [comment]
CDN-3162

**Comment by mitchell852** [comment]
@jhg03a - this seems to work fine for me. maybe something got fixed?

**Comment by jhg03a** [comment]
Yep, verified against the head of master as of last night to be working.
