### ISSUE TITLE
TP - Improve profile diffing

### ISSUE THREAD

**Issue by ezelkow1** [apache/trafficcontrol#2391]
Currently a profile diff will just compare a sorted version of the json of 2 profiles and then display them side by side highlighting the differences.  I find the old TO diff much more useful where

1) Anything that is the same is stripped in the diff, showing only differences
2) The differences shown are just 'param name' - 'value' - 'value', so you can easily see the name of the param and the value differences between the 2 profiles
3) Doesnt show the full json, I dont think this is particularly useful anyway

**Comment by jhg03a** [comment]
I disagree on 2 & 3.  Being able to see the context and an unchanged sibling can provide better insight of it a projected change looks right or isn't yours.

Currently I just do a browser find for "++" and "--" to skip to the relevant pieces.  A UI improvement I'm not sure is possible would be to model the JSON as a collapsed tree, then expand elements with changes.

**Comment by ezelkow1** [comment]
I think you might be thinking of the snapshot diff.  That is something different and I would agree having the context there is useful.  This is in regards to the profile diff, which does not have the ++ -- differentiations, it has color highlights for each profile but leaves a lot of cruft in between that IMHO isnt really useful when comparing profiles

**Comment by jhg03a** [comment]
Ah, you're right.  I was mixing up Snapshot diff with Profile diff.  Statement withdrawn.

**Comment by mitchell852** [comment]
@ezelkow1 @jhg03a what about something like this?

![image](https://user-images.githubusercontent.com/251272/62552963-be75b380-b82b-11e9-98d7-516d7c90a1f9.png)

1. you can compare 2 or more profiles
2. it shows ALL params associated with ALL the profiles being compared (whether there is a diff or not). maybe highlight the rows where there is a diff?
3. it allows you to add or remove params from a profile easily
4. it allows you to edit params easily

keep in mind, 2 params of the same name/config file with different values can currently be created as seen in this example (foo)

**Comment by ocket8888** [comment]
What about parameters with the same config file and value but different names? or different `secure` settings?

**Comment by mitchell852** [comment]
>>> What about parameters with the same config file and value but different names?

Tom (hello.config); value:4 belongs to profile 1
Jerry (hello.config);value:4 belongs to profile 2

^^ that would show up perfectly in my above example. And as a user I could
a. leave it alone as it won't technically hurt anything or
b. remove Jerry from profile 2 and add Tom to profile 2 if i wanted to clean things up

>> or different secure settings?

this is not possible:
foo; hello.config; value:1, secure:false
foo; hello.config; value:1, secure:true

**Comment by ezelkow1** [comment]
I think these changes are pretty good. It might be nice if there was a way to have the params with actual diffs be propagated to the top, then everything non-diff below those. That way you get the best of both worlds with easy to see diffs but still able to see everything if you want

**Comment by jhg03a** [comment]
I like it.  Rather than forcing the UI to include/exclude non-changes, I'd recommend a checkbox to show unchanged values.  Normally I wouldn't expect it to be relevant, but it is handy to turn on to verify that all 3 in this case had a given parameter to begin with and not have to change UI pages (probably still leaning on [ctrl]+f here, unless there's a search of some kind).

The only piece that's going to look terrible is when a param value is huge, like a lua file.  If a parameter has more than X lines of text there might be a better way to display it.

**Comment by ocket8888** [comment]
If the parameter value includes newlines it could be displayed as a normal text block. Could even add syntax highlighting for configFile values that end with `.lua` (and aren't named `location`).

**Comment by mitchell852** [comment]
@jhg03a 

> Rather than forcing the UI to include/exclude non-changes, I'd recommend a checkbox to show unchanged values

Just so i'm clear. You want a way (a checkbox perhaps) to show/hide "equal" params across the profiles? in this example, a way to show/hide the `bar` parameter.

**Comment by mitchell852** [comment]
this is the same as the above design but a little cleaner/easier to work with imo

![image](https://user-images.githubusercontent.com/251272/64047289-9a0baf00-cb2b-11e9-9051-f0fe709e82a1.png)

and yes, i can think of the best way to show/hide params with no diff or vice versa as well.
