### ISSUE TITLE
TP - Bypass destination requires protocol

### ISSUE THREAD

**Issue by elsloo** [apache/trafficcontrol#2418]
The current implementation in the portal requires one to specify the protocol on a bypass destination for HTTP delivery services. Traffic Router is written to assume that it is not present, as the old Traffic Ops UI will reject any such configuration, and ensures the field contains FQDN only.

Also, while we are at it, we should determine whether this is correct. Perhaps a bypass destination should be allowed to specify HTTP or HTTPS and not rely on the redirection scheme configured on the DS. For sake of argument, consider a delivery service whose redirection scheme is HTTP to HTTPS. The protocol used in the 302 to the bypass destination will be HTTPS. It's entirely possible that we want to redirect to HTTPS on our edge, but keep the bypass over HTTP. There are many examples of these types of scenarios, as we have several redirection schemes. Typically security does not get downgraded from HTTPS to HTTP, so that should be yet another consideration.

A quick test of combinations of redirection schemes with a bypass destination shows that we have some room for improvement with Traffic Router. It seems we include the port we came in on, and redirect using HTTPS when configured to route HTTP->HTTPS. This results in a URL with HTTPS and a port of 80.

**Comment by anna-k-1** [comment]
CDN-3161

**Comment by mitchell852** [comment]
>>> The current implementation in the portal requires one to specify the protocol on a bypass destination for HTTP delivery services

**Comment by mitchell852** [comment]
Can this be closed as a bug @elsloo and maybe reopen another issue with the part about

> Perhaps a bypass destination should be allowed to specify HTTP or HTTPS and not rely on the redirection scheme configured on the DS.

**Comment by ocket8888** [comment]
We could just have one bypass destination field that's interpreted based on the DS type. FQDN -> HTTP bypass FQDN or DNS CNAME as appropriate, IP -> that one's simple enough. Then for STEERING* we only allow valid xml_id s of pre-existing Delivery Services. Idk if STEERING actually supports bypass at all, or if it's limited to DSes if it does, just spitballing here.

**Comment by dneuman64** [comment]
Traffic Portal no longer requires protocol, and forces user to create FQDN.  If we want to explore the other ideas brought up in this ticket we should do so either in another ticket or on-list.
