### ISSUE TITLE
Revalidate builds invalid regexes on ANY_MAP Delivery Services 

### ISSUE THREAD

**Issue by jhowar201** [apache/trafficcontrol#2426]
Revalidate via TP builds the URL regex based on origin on the delivery service and for ANY_MAP type there is no origin configured. The revalidation config files are placed on disk with no origin beginning with the / entered via TP. Attempting to enter the entire origin FQDN manually into the regex in TP will still require it to begin with a / for the URL so this cannot be avoided by manual intervention.

**Comment by anna-k-1** [comment]
CDN-3160

**Comment by mitchell852** [comment]
The API will no longer allow you to create an "invalidate content" request on a ds that has no origin defined. So you can try all day long and the api will just fail.

So, maybe the UI needs to be smart and remove the menu item if ds.origin=null
