### ISSUE TITLE
Autocreate self-signed SSL certificates

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#2429]
When creating a new Delivery service or modifying the type to support HTTPS, a default self-signed certificate should be created.  This could be triggered by a miss when looking up the DS in riak.  This specifically prevents situations where a CDN could be queued by a second user unaware of a DS change in flight.  This is not prevented by DS Requests since you must fulfill the DS before you could create SSL certs.  If this situation happens and ORT runs an update before SSL Keys are in place, a syncds will fail.

**Comment by jhg03a** [comment]
With the version of TR in the repo today, this can also cause TrafficRouter to also stop processing CRConfigs.

**Comment by dneuman64** [comment]
TR not processing the CrConfig due to missing certificates has been in TR since 1.7 when we added HTTPS support.

**Comment by mitchell852** [comment]
also, see #2159 to figure out if implementing Let's encrypt would nullify the need for this

**Comment by dneuman64** [comment]
I don't think this is the way to solve this problem.  We should be better with making changes more atomic.  Therefore, I don't think this is something we will plan on fixing.
