### ISSUE TITLE
Traffic Ops Riak handler should not have the Riak Port hard-coded

### ISSUE THREAD

**Issue by dewrich** [apache/trafficcontrol#2470]
The Riak Port is hard-coded to 8087 (https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/riaksvc/riak_services.go#L38), it should be configurable via the `/opt/traffic_ops/app/conf/production/riak.conf` file.

**Comment by rob05c** [comment]
Fixed in https://github.com/apache/trafficcontrol/pull/2896
