### ISSUE TITLE
simple migration test

### ISSUE THREAD

**Issue by DylanVolz** [apache/trafficcontrol#2471]
We need a simple test that is ran on PRs to ensure that if a migration file is added it is of a date later than all other migrations in the directory. This is a problem we run into a lot when branches age too long.

**Comment by ocket8888** [comment]
We have checks now that run on PRs to ensure that migrations

* Are properly named (_date_-_name_.sql)
* Have the right amount of date precision
* Do not use duplicate dates

but we don't have a check for this yet.
