### ISSUE TITLE
The tenant api needs to implement tenancy

### ISSUE THREAD

**Issue by DylanVolz** [apache/trafficcontrol#2474]
if the tenant tree looks like this

 -root
-- tenant a
--- tenant a.a
---- tenant a.a.a

and i have tenant a.a
then really the only tenants i’m aware of are a.a and a.a.a for a read or delete.
and if i want to create or modify a tenant, i can only give it a parent of a.a or a.a.a.

**Comment by mitchell852** [comment]
Just to add a bit of clarity

GET /api/tenants should return only tenants in your tenant tree
POST /api/tenants should check the value of the parent_id to ensure it's in your tenant tree
PUT /api/tenants/:id should make sure you're only updating a tenant in your tenant tree AND check the value of the parent_id to ensure it's in your tenant tree
DELETE /api/tenants/:id should make sure you're only deleting a tenant in your tenant tree
