### ISSUE TITLE
GET /api/1.3/deliveryservices/{{id}}/servers/eligible returns integers as strings

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2483]
Below is a screenshot of the request and response headers

![image](https://user-images.githubusercontent.com/6013378/42044597-a759f0de-7ab6-11e8-865f-9dd8f9868eef.png)

... and here's the payload response with one configured Delivery Service and one Edge-Tier cache
```JSON
{"response":[{"profileId":"10","profile":"ATS_EDGE_TIER_CACHE","statusId":"3","physLocation":"CDN_in_a_Box","cdnId":"2","cachegroup":"CDN_in_a_Box_Edge","interfaceName":"eth0","id":"2","tcpPort":"80","ipGateway":"172.13.239.1","httpsPort":null,"updPending":false,"ip6Address":null,"rack":null,"mgmtIpNetmask":null,"mgmtIpGateway":null,"type":"EDGE","domainName":"cdn.local","iloIpNetmask":null,"iloUsername":null,"status":"REPORTED","ipAddress":"172.13.239.6","ip6Gateway":null,"iloPassword":null,"guid":null,"physLocationId":"1","offlineReason":null,"routerPortName":null,"cachegroupId":"2","ipNetmask":"255.255.255.0","lastUpdated":"2018-06-28 15:01:48.240947+00","mgmtIpAddress":null,"typeId":"11","interfaceMtu":"1500","iloIpGateway":null,"cdnName":"CDN-in-a-Box","hostName":"edge","iloIpAddress":null,"profileDesc":"Edge Cache - Apache Traffic Server","routerHostName":null}]}
```

**Comment by rob05c** [comment]
The API defines that endpoint to return strings. See http://traffic-control-cdn.readthedocs.io/en//latest/api/v12/deliveryservice.html

I agree, it's a poor design (it's an artifact of Perl), but we can't change it and break the API promise now.

For what it's worth, we fully intend to make the next major version of the API properly typed.

**Comment by ocket8888** [comment]
well if the api defines those to be strings and we're not going to change that, then TP needs to do some logic with it to turn them into numbers, because `/api/1.2/deliveryserviceserver` expects integers. Unless @mitchell852  is right and they're ints. I'll try rebasing later.

**Comment by rob05c** [comment]
Yeah, I'm seeing ints too. I'd be interested to know how @ocket8888 saw strings. We shouldn't be changing the API, if the documentation is wrong, it needs fixed. Changing the API will break people.

**Comment by rob05c** [comment]
Git blame on the code shows the function hasn't changed since 11 months ago, so it should have been ints for at least that long. 

Maybe @ocket8888 your Perl has some global setting different, or something? I'm not a Perl wizard, but Perl converts strings to ints capriciously, especially in JSON.

**Comment by mitchell852** [comment]
@ocket8888 - can i close this? looks like it was just an environmental issue.

**Comment by ocket8888** [comment]
Oops, sorry, I got that notification while I was on vacation, and I forgot to do it :P
