### ISSUE TITLE
Add terminating newline to JSON API responses, so HTTP responses are POSIX text files

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2484]
[POSIX Standard 3.206 Line defines a line to be "A sequence of zero or more non- <newline> characters plus a terminating <newline> character."](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206) By this definition, all API responses produce zero lines of output. This causes problems operating on API responses using tools that DO implement and expect POSIX-compliance.

**Comment by dangogh** [comment]
examples, please?  both specific endpoints and the output you're seeing (any proprietary data changed or removed).   Do you see any that **are** compliant?

**Comment by ocket8888** [comment]
examples to come tomorrow, but no, I haven't seen any that are compliant

**Comment by rob05c** [comment]
The Traffic Ops API doesn't return POSIX files or lines. It serves JSON over HTTP. But neither of those standards are related to POSIX, operating systems, or filesystems of any kind. The API conforms to RFC2616 (, RFC7231, et al) for HTTP, and RFC7159 and RFC 4627 for JSON. 

If you're using the APIs in a POSIX context, for example piping `curl` results to POSIX utilities, you can use an intermediary tool like `jq` or `printf` to manipulate the output to be a POSIX-compliant file, e.g. `curl | xargs -I '{}' printf '{}\n'`.

I'm not sure why you expect an HTTP-JSON API to be POSIX compliant, as they're entirely unrelated standards. Can you point to an HTTP or JSON RFC requiring or recommending POSIX compliance?

**Comment by ocket8888** [comment]
No, I can't. It just seems like a good quality-of-life update. The newline won't, as you pointed out, affect the validity of the JSON), but _will_ allow it to represent a `*.json` file, and eliminate the need for intermediary tools.

**Comment by rob05c** [comment]
Eh, I guess I could support that. I'm not a fan of unnecessary space, but one character isn't going to make a practical difference. And RFC 4627 states "Insignificant whitespace is allowed before or after any of the six structural characters", so the terminating newline is explicitly still valid JSON.

But it's certainly a feature request, not a bug.

**Comment by ocket8888** [comment]
Hey, sounds good to me. By the way, I can't get into the vpn, slack or email, what's going on? I didn't even have github.com access until a second ago

**Comment by ocket8888** [comment]
Update: config files generated for ORT script endpoints are also missing newlines, which is a bigger deal somewhat because they _are_ explicitly meant to be real files

**Comment by ocket8888** [comment]
This has been fixed in the general case. Specific endpoints should have specific issues.
