### ISSUE TITLE
Trafficportal Profile exports (and likely others) don't work on Firefox

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2486]
Go to Configure -> Profile -> {{a profile}} -> More -> Export in Firefox v60-62
XHR request completes successfully and no (related) js errors in console, but no download occurs. Suggest changing from `ng-click` attribute to `<a href="/path/to/export/api/endpoint" download="">Export Profile</a>`, but other solutions likely exist.

**Comment by anna-k-1** [comment]
CDN-3159

**Comment by ocket8888** [comment]
What's that? A JIRA ticket?

**Comment by ocket8888** [comment]
So it looks like the issue is in `FileUtils.js` where an `href` is being set equal to a data url directly without first creating a `Blob` object to act as the "file". See: https://stackoverflow.com/questions/19327749/javascript-blob-filename-without-link

**Comment by ocket8888** [comment]
Fixed in #3921
