### ISSUE TITLE
Create a permission that can be used to retrieve secure parameter values

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2488]
GET /api/parameters can contain secure values.

currently if you are an admin (priv level=30), then the values for "secure" parameters will be returned. if you are not an admin, the value will be replaced with '**********'

as we move towards capability-based permissions (as opposed to priv_level based), we will need to key off of a capability (instead of a role) to determine whether to show or hide the value of secure parameters.

One suggestion was to create a capability called "secure-read" or something along those lines. The presence of this capability would allow you to see the value of "secure" parameters.

So for example,

to access GET /api/parameters and see value of secure and non-secure parameters you'd need the following capabilities:

params-read
secure-read

to access GET /api/parameters and see value of ONLY non-secure parameters you'd need the following capabilities:

params-read

**Comment by mitchell852** [comment]
related to #2037

**Comment by mitchell852** [comment]
assigning this to @rob05c to ensure he has this accounted for in his open roles/capabilities PR

**Comment by rob05c** [comment]
Yes, it is accounted for. E.g. https://github.com/apache/trafficcontrol/pull/2791/files#diff-aaa675dae4ffc0279136f6687d6c7f69R398

**Comment by mitchell852** [comment]
can this be closed @srijeet0406 @ocket8888 @shamrickus?

**Comment by ocket8888** [comment]
No. That's actually kind of an important detail we missed. With Permissions checking disabled, anyone with priv_level >= 30 can see "secure" Parameter Values. If you turn on Permissions checking, that doesn't change and there's no Permission you can take away from someone to hide them or give someone to show those Values. That should be fixed.

**Comment by srijeet0406** [comment]
@mitchell852 I can take this one
