### ISSUE TITLE
Multiple Go API endpoints don't return "joined" fields on PUT/POST

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#2494]
This is a regression from the Perl API, where keys like `parentCachegroupName` are returned with the name of the cachegroup rather than `null`. This requires following up `INSERT` or `UPDATE` SQL statements with a `SELECT` that returns the proper fields. This is essentially what the Perl API did through the DBIx ORM for these endpoints, but currently these APIs don't follow up with a `SELECT` to return the same data as the Perl API and return a `null` value in the response:

- POST, PUT /api/1.1/cachegroups
  - parentCachegroupName, secondaryParentCachegroupName, typeName
- POST, PUT /api/1.1/asns
  - cachegroup
- POST, PUT /api/1.3/deliveryservices
  - cdnName, profileName, profileDescription
- POST, PUT /api/1.1/regions
  - divisionName
- POST, PUT /api/1.1/phys_locations
  - region
- POST, PUT /api/1.1/servers
  - cachegroup, cdnName, physLocation, profile, profileDesc, status, type
- POST, PUT /api/1.1/tenants
  - parentName

Example PUT /cachegroups/{id} response from traffic_ops_golang:
```
{
    "alerts": [
        {
            "level": "success",
            "text": "cachegroup was updated."
        }
    ],
    "response": {
        "fallbackToClosest": null,
        "id": 531,
        "lastUpdated": "2018-07-02 17:07:59+00",
        "latitude": 39.739167,
        "longitude": -104.984722,
        "name": "rawl-cg",
        "parentCachegroupId": 3,
        "parentCachegroupName": null,
        "secondaryParentCachegroupId": null,
        "secondaryParentCachegroupName": null,
        "shortName": "rawl-cg",
        "typeId": 6,
        "typeName": null
    }
}
```
Example PUT /cachegroups/{id} response from Perl TO with the same request payload:
```
{
    "alerts": [
        {
            "level": "success",
            "text": "Cachegroup update was successful."
        }
    ],
    "response": {
        "fallbackToClosest": 1,
        "id": 532,
        "lastUpdated": "2018-07-02 21:42:40.062963+00",
        "latitude": 39.739167,
        "longitude": -104.984722,
        "name": "rawl-cg",
        "parentCachegroupId": 3,
        "parentCachegroupName": "mid-west",
        "secondaryParentCachegroupId": null,
        "secondaryParentCachegroupName": null,
        "shortName": "rawl-cg",
        "typeId": 6,
        "typeName": "EDGE_LOC"
    }
}
```
Notice how the Perl API returns all the `fooName` fields whereas the Go API returns `null`.

**Comment by mitchell852** [comment]
@DylanVolz is working on this

**Comment by moltzaum** [comment]
FYI The same issue exists for `profileparameters`
```
{
  "alerts": [
    {
      "text": "profileParameter was created.",
      "level": "success"
    }
  ],
  "response": {
    "lastUpdated": null,
    "profile": null,
    "profileId": 1,
    "parameter": null,
    "parameterId": 4
  }
}
```

**Comment by rob05c** [comment]
>The same issue exists for profileparameters

I believe this is a problem for all endpoints using the "CRUDer" framework and "Generic" funcs (and possibly more).

For the CRUDer/Generic endpoints, we should be able to fix it in all of them at once, by 
1. changing the Generic funcs to expect queries to return the whole object
2. using sqlx.StructScan to read the result of the insert/update
3. changing each endpoint's queries to return the values in a RETURNING clause.
  - for objects with values in other tables, RETURNING can only return columns in the inserted table - this can be worked around by wrapping the INSERT/UPDATE in a WITH statement.

**Comment by moltzaum** [comment]
> for objects with values in other tables, RETURNING can only return columns in the inserted table

In some cases you can also do a subquery.

Hm.. I'll try some stuff

**Comment by rawlinp** [comment]
Since this was a regression from TO API 1.x, and TO API 1.x no longer exists, I'm closing this out. Newer API versions that don't return "joined" fields on PUT/POST are now just how those versions work. However, I do think we should consider adhering to returning "joined" fields for PUT/POST requests as an API guideline.

**Comment by ocket8888** [comment]
fwiw, that is in [the API guideline](https://traffic-control-cdn.readthedocs.io/en/latest/development/api_guidelines.html#put), it's just not one that's actually followed in practice
