### ISSUE TITLE
error reporting different in traffic portal than in trafficops UI

### ISSUE THREAD

**Issue by jpappa200** [apache/trafficcontrol#2503]
When adding a new server in Traffic Portal I get "database access error" but in trafficops UI I get "create(): [57] the 61 profile is not in the over-the-top cdn" Traffic Portal error reporting should be a bit more descriptive.

**Comment by mitchell852** [comment]
This is probably an error in the TO (golang) API i'm guessing that can't seem to handle a server create where server.cdn != server.profile.cdn. The api should return a 400 Bad Request with a message and TP will then display the message.

This begs the question. Should TP prevent a server create where server.cdn != server.profile.cdn? probably. So 2 things:

1. validation in the API needs to be better
2. validation in TP needs to be better

**Comment by anna-k-1** [comment]
CDN-3158

**Comment by anna-k-1** [comment]
CDN-3158

**Comment by mitchell852** [comment]
fwiw in TP you cannot select a profile in a different cdn than the server's cdn. this safety check may have been added after this bug was filed. @jpappa200 want to verify?
