### ISSUE TITLE
TO Go API: deliveryservices boolean entries `null` instead of `false`

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#2524]
In current Perl API,  the `GET api/1.2/deliveryservices` endpoint returns `false` for the `ipv6RoutingEnabled` and `multiSiteOrigin` fields.  The Go API endpoint returns `null` for these fields.

In contrast,  the `active` field returns only `true` or `false` in both cases.

**Comment by dangogh** [comment]
see comments on the closed PR #2547

**Comment by mitchell852** [comment]
marking this as minor as this apparently is related to Kabletown data
