### ISSUE TITLE
RFE: New Calendar view for SSL Certificate Expiration

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#2526]
As a SRE I want to be able to click a link in traffic portal and see a calendar with a list of upcoming dates for which HTTPS enabled delivery services will have their certificates expire.  As a secondary goal, I would like to have a list or api endpoint that produces a list of expired SSL certificates.  As a third goal, I would also like the option to download this information in ics format for use in other tools such as gcal or outlook.  This would make staying on top of SSL certificate expirations much easier so manual records or 3rd party notifications would no longer be required and prevent expirations from occurring in production.

This data is all presently available in trafficvault and could be reconstituted via api+scripting, but I'd prefer to see it inside TP itself.

**Comment by mitchell852** [comment]
mind if i close @jhg03a ? probably not going to happen and there are probably better tools for this.

**Comment by jhg03a** [comment]
There actually isn't a better tool I can find.  Only TO knows what those cert expiration dates are without constant exporting and potential private key disclosure.

**Comment by jhg03a** [comment]
Unless you are 100% LE with no vanity DS url, you have this usability problem.

**Comment by rob05c** [comment]
> In the future, ssl certs will be a Permission, not admin-only, so that filtering will be exposed

Will we need 2 Permissions: certs-and-keys, and only-public-certs? In fact, I think an only-public-certs would be safe to let anyone read, that should probably be added to a "default" Permission set if such a thing exists.

**Comment by ocket8888** [comment]
Sounds like too much work for TPv1 IMO, could be a table in that version and then we revamp it later
