### ISSUE TITLE
TO Go API: deliveryservice_request missing fields from DeliveryServiceV13 struct

### ISSUE THREAD

**Issue by rivasj** [apache/trafficcontrol#2527]
When creating a Delivery Service Request in TP, the fields specific to the DeliveryServiceV13 struct are ignored and not included in the jsonb field 'deliveryservice' in the deliveryservice_request table (go fields: DeepCachingType, SigningAlgorithm, Tenant, TRResponseHeaders, TRRequestHeaders). 

Consequently, when opening a Delivery Service Request in TP, these fields are always null and either show an invalid diff, or don't retain changes.

To reproduce:
- Create Delivery Service Request on HTTP delivery service in TP
- Open Delivery Service Request and notice diff on required field 'Deep Caching', and other fields noted above

**Comment by dangogh** [comment]
guessing this is TO Go API issue and not really TP issue.

**Comment by mitchell852** [comment]
@rivasj is going to work on this
