### ISSUE TITLE
TO Go GET /server/{id}/deliveryservices endpoint missing fields from TO Perl version

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#2532]
Fields *missing* from TO Go version that are in the Perl version:
```
"anonymousBlockingEnabled"
"cdnName"
"deepCachingType"   <- value returned is null when it's really NEVER
"fqPacingRate"      <- value returned is null when it's really 0
"profileName"
"signed"
"tenant"
"type"
```
These fields need to be returned by the TO Go version to keep parity with the Perl version.

Also, the api/v12/server doc is missing "signingAlgorithm" and "anonymousBlockingEnabled" documentation for this endpoint. Also, the docs mention "multiSiteOriginAlgorithm", but this appears to have been removed from the Perl version after it was added, so the field should probably be removed from the TO Go version (as well as the documentation updated).

**Comment by mitchell852** [comment]
@DylanVolz is working on this

**Comment by rawlinp** [comment]
Closing this as it's since been duplicated by #2989
