### ISSUE TITLE
Tenant list returned from API empty for non-tenant assigned user (use_tenancy disabled)

### ISSUE THREAD

**Issue by JBevillC** [apache/trafficcontrol#2539]
__Problem Description__

Requesting a list of tenants (GET /api/1.3/tenants) results in an empty list for any user that doesn't have an associated tenant_id in the tm_user table.  This behavior occurs even when use_tenancy = 0 (disabled).

__Criteria to reproduce bug__
PARAM: use_tenancy = 0 (disabled)
tm_user table: authenticated user is not assigned a tenant_id (field is null)
SQL Query issued by golang trafic ops backend:
```
WITH RECURSIVE q AS (
        SELECT id, name, active, parent_id, last_updated FROM tenant WHERE id = -1
        UNION SELECT t.id, t.name, t.active, t.parent_id, t.last_updated FROM tenant t JOIN q ON q.id = t.parent_id)
        SELECT q.id AS id, q.name AS name, q.active AS active, q.parent_id AS parent_id, q.last_updated AS last_updated,
        p.name AS parent_name FROM q LEFT JOIN tenant p ON q.parent_id = p.id
```

**Comment by mitchell852** [comment]
I think @dangogh is working on this so i'm going to assign it to him
