### ISSUE TITLE
TO Go client should provide methods that take Nullable structs as input/output and return a ReqInf struct

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#2546]
Most of the client implementations for endpoints do not take a Nullable struct as input and don't return a Nullable struct as output. This means that a client is forced to provide a value for optional fields of the struct. If the input struct was Nullable, the client would be able to set optional fields to `nil` rather than setting an optional value they don't want/need. This would also make it possible to test passing `nil` values for optional fields in the Go API integration tests, which is a current limitation that greatly reduces possible test coverage.

Also, most of the client methods return `tc.Alerts` rather than the corresponding `Nullable` struct response for that endpoint, which means that the full JSON response returned via the API is not decoded. This means on a POST or PUT request that the client is forced to make a follow-up GET request in order the get the newly created/updated resource, which is very inefficient and also reduces our ability to test API responses in the Go API integration tests.

Additionally, some client methods don't return a `ReqInf` struct, but all the client methods should.

This issue was discussed on the mailing list: https://lists.apache.org/thread.html/20d64c419498b07a52f829e65b303f54bb1e535eb1ad0284b48a0729@%3Cdev.trafficcontrol.apache.org%3E

**Comment by rob05c** [comment]
Relatedly, new client functions need to return `ReqInf` data. This data is needed by the Monitor, and generally useful to API clients, especially for debugging connection issues.

>client methods return tc.Alerts rather than the corresponding Nullable struct response for that endpoint, which means that the full JSON response returned via the API is not decoded. This means on a POST or PUT request that the client is forced to make a follow-up GET request in order the get the newly created/updated resource

Is this theoretical, or have you had this issue in practice?

I haven't experienced this. On success, the created or updated resource should reflect the POST. When I've done API operations, I typically have the information I'm updating, by definition. I can't recall ever needing to go get the object I just created.

I would also argue testing doesn't count, and needs to do an additional GET anyway. Code should be designed for real usage; tests should be built around code, not the reverse. But regardless, no test should assume the data returned was created, without an additional independent GET. A great example of an error this would hide, is a transaction not being committed: if a transaction commit isn't called, the server could think it created and return everything as though it succeeded, while the data fails to actually be created.

Along those lines, I'd favor changing our API in a future version, to not unnecessarily return the data just posted; unless others have different experiences?

**Comment by rawlinp** [comment]
>>client methods return tc.Alerts rather than the corresponding Nullable struct response for that endpoint, which means that the full JSON response returned via the API is not decoded. This means on a POST or PUT request that the client is forced to make a follow-up GET request in order the get the newly created/updated resource

>Is this theoretical, or have you had this issue in practice?

In my experience, API clients typically decode the entire API response rather than just the equivalent "alert" section so that you have access to the entire PUT/POST response.

>I would also argue testing doesn't count, and needs to do an additional GET anyway. Code should be designed for real usage; tests should be built around code, not the reverse. But regardless, no test should assume the data returned was created, without an additional independent GET.

Agreed, the tests should not only check the JSON response from the PUT/POST but also do a GET to confirm that the resource was actually created/updated, but we need to be able to write tests that check the JSON response of PUT/POST requests. IMO the JSON response of the PUT/POST request should match the JSON response of a subsequent GET request (not the alerts section, but the actual resource), assuming the resource hasn't been modified between requests.

> Along those lines, I'd favor changing our API in a future version, to not unnecessarily return the data just posted; unless others have different experiences?

The API already returns the data just posted; it's just a matter of making the client decode those responses rather than just the "alerts". The typical deprecation best practices should be followed in order to not break software that uses the existing client methods.

**Comment by mitchell852** [comment]
@rawlinp - is this still applicable?

**Comment by rawlinp** [comment]
For the most part, this is probably no longer applicable since the TO API v4 client was greatly revamped. If we happen to find certain client methods that _should_ take nullable structs as input but don't, then we can open a new issue specifically for those methods.
