### ISSUE TITLE
TO Go: profileparameters endpoint has different JSON form Perl vs Go

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#2556]
the JSON output `api/1.1/profileparameters` is different from the Perl implementation to the Go implementation.   Arguably,  the new Go one is preferable,  but it's an API change that shouldn't be made without major API version change.

Perl version looks like this:
```
{
  "response": [
    {
      "parameter": 277,
      "profile": "MID",
      "lastUpdated": "2017-10-08 19:34:45+00"
    },
...
```
whereas the Go version looks like this:
```
{
  "response": [
    {
      "lastUpdated": "2017-10-08 19:34:45+00",
      "profile": "MID",
      "profileId": 5,
      "parameter": "location",
      "parameterId": 277
    },
```

**Comment by mitchell852** [comment]
I assigned this to @rob05c because I believe he rewrote this endpoint. If I am wrong, let me know. thanks!

**Comment by rob05c** [comment]
@mitchell852 I did not https://github.com/apache/trafficcontrol/commit/413e109742abab2af43e9bac6b9ca4df5a7d9da1
