### ISSUE TITLE
Traffic Portal not validating 'routerPortName' on the Server page

### ISSUE THREAD

**Issue by ajschmidt** [apache/trafficcontrol#2558]
When entering or updating the RouterPortName field for a Server, TP should validate the inputs and remove extra spaces, and/or hidden characters like tabs. In the output of the JSON api we are showing servers which have /t and spaces in the output for the RouterPortName.

**Comment by mitchell852** [comment]
@ajschmidt - any idea if this creates any downstream (or is it upstream) problems? I'm not sure where the value of server.router_port_name (the database column) is actually used. If it's actually used by other components of TC (as opposed to being purely informational) and whitespace or hidden characters can cause significant problems, then the severity of this issue will be raised.
