### ISSUE TITLE
TO Go cachegroups, DS regexes, and staticdnsentries don't validate their type

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#2560]
These TO Go endpoints do not validate that the requested `type` is actually a usable type for that endpoint. Right now you can create a cachegroup of type `A_RECORD`, a staticdnsentry of type `HOST_REGEXP`, and so on.

Since there are several different entities that use the `type` table, I'd propose handling this in the shared handlers alongside the call to `foo.Validate()`. We can create an interface like the following that the affected structs can implement:
```
type RequiredTyper interface {
    RequiredType() (*int, string)
}
```
with implementations that just return their *TypeID and string value of the `use_in_table` they expect of their type. If the type is missing, not found, or incorrect, the shared handler would return a `400 Bad Request`.

Entities that don't use the shared handlers could import the same code that the shared handler would use to do the validation.

EDIT: title originally said the servers endpoints were affected, but in fact they are not. However, they can benefit from a unified approach.

**Comment by DylanVolz** [comment]
+1, this strategy of enforcing the type validation with an interface and a helper function should be easy to implement and eases enforcing the use_in_table value of the type supplied for structs that require it.

**Comment by rob05c** [comment]
>this strategy of enforcing the type validation

How does this enforce it? It seems like a lot of structs won't have types, and for ones that do, someone could just omit the interfaces.

>Entities that don't use the shared handlers could import the same code that the shared handler would use to do the validation.

If you do this, please consider non-CRUD endpoints first. The way you phrase it suggests CRUD is a priority, and other functions an afterthought. CRUD is a minority, and most of the difficult endpoints aren't CRUD. It's been a major pain-point in the past, writing our many and unusual endpoints, when every utility function (tenancy, validate, etc) is written around the "shared_handlers" abstractions, and can't easily be used without major workarounds or refactoring.

Please expose simple functions, without interfaces/abstractions/typecasts/reflection, that are easy to use and don't require a steep learning curve. I've been the one rewriting most of the TO endpoints, and most of the difficult ones. Every time we add more rigid framework stuff, it makes my life harder :(

**Comment by DylanVolz** [comment]
Right, the interface is the strategy of enforcement in the CRUD framework, another option being having the code to check the use_in_table in the validate function. Either way the base helper would be of the form `func CheckTypeTable(type string, useInTable string, sqlx.Tx)` or similar and would need to be called in handlers validating a struct with a type in the type table.

**Comment by rawlinp** [comment]
Agreed, there will basically be a shared helper function that both CRUD and non-CRUD endpoints will use to validate the struct's type by checking the type table. The difference being that the CRUD framework will just check for the optional interface implementation and do the validation in the handler, whereas non-CRUD handlers would just call the shared function directly.

**Comment by rawlinp** [comment]
So I tried out the `RequiredTyper` interface idea, and it worked. But, I decided it is probably better to just call the helper method directly in the `Validate()` method of the structs in order to keep all validation logic contained there rather than splitting the validation into "type validation" and "other validation".
