### ISSUE TITLE
Legacy Naming Conventions (Rascal, RIAK, CCR et. al.)

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2564]
It's super confusing that Traffic Monitor is referred to in hundreds of places as "Rascal", Traffic Vault as "RIAK" and Traffic Router as CCR. We should change those.

That would also entail removing legacy constraints related to those names, e.g. Traffic Monitor profiles currently must start with a "RASCAL" prefix for no good reason I've ever heard. Database tables and columns ought to be renamed as well (if applicable, I'm not sure), but that probably would make production upgrades much more complicated.

**Comment by mitchell852** [comment]
"low effort" @ocket8888 ?
