### ISSUE TITLE
Traffic Ops API endpoint /cachegroups missing key requirement

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2566]
For certain operations (including snapshot generation) cache groups MUST have geomagnetic coordinates (latitude & longitude), which is enforced in the Traffic Portal UI but not by the backing Traffic Ops endpoint.

You really ought to have coordinates on a production CDN, as they can be very helpful.

Possible Solutions:

1. Enforce that new cache groups **must** have coordinates
2. Provide some default coordinates, either at cache group creation or at snapshot time.

**Comment by mitchell852** [comment]
I believe coordinateId is not required on POST/PUT of a cachegroup because adding a required field to the API would require the API to roll to the next major version. So, I think this can be fixed with API 2.x. right @rawlinp ?

**Comment by rawlinp** [comment]
Yes, however the Cachegroup API only creates a Coordinate under the hood from the lat/long in the request and sets cachegroup.coordinate to the ID of the created coordinate. In API 2.x we should make Cachegroups require a Coordinate, possibly making the Cachegroup API require a Coordinate ID rather than the lat/long.

**Comment by mitchell852** [comment]
TP should not require lat/long on a cg but provide a warning instead.

**Comment by mitchell852** [comment]
1.x will soon be removed. can this be closed @ocket8888 ?

**Comment by ocket8888** [comment]
No. In fact, I'm bumping this back up to "high impact". In combination with #6378 this causes a major problem under certain conditions. If servers in a cache group with null latitude and longitude are assigned to a Delivery Service (either directly or through a Topology), the CDN to which said Delivery Service belongs cannot be "snapshotted". Trying to do so will cause a segmentation fault and result in a 500 Internal Server Error response. Furthermore, because of #6378, the CDN will be stuck in this non-snapshot-able state until _direct database intervention_ occurs, because the missing coordinate cannot be fixed through the API.

**Comment by ocket8888** [comment]
This was solved by using option 2; a default coordinate set is now provided at Cache Group creation time, as of #6442 .
