### ISSUE TITLE
Provide the ability to apply table filtering via query params

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2568]
for example, following this link

https://tp.domain.net/#!/servers?search=OFFLINE 

would auto apply a filter to the servers table like

![image](https://user-images.githubusercontent.com/251272/43019750-3cfec87e-8c1b-11e8-985b-a4d22c3a6baa.png)

Essentially, this provides deep linking capabilities to TP that controls table filtering.

**Comment by ocket8888** [comment]
TPv2's generic tables already support this
