### ISSUE TITLE
Incorrect cachekey parameters for https origin servers

### ISSUE THREAD

**Issue by alficles** [apache/trafficcontrol#2589]
When a delivery service uses the parameter "ignore in cache key, and pass up" for the query string and an https delivery service at the same time, the resultant remap line will cause all requests to cache to the exact same key: an empty one.

This is the result of get_qstring_ignore_remap in DeliveryService.pm hardcoding `http://` in the regex. Since this doesn't match an https DS, it returns an empty string. ATS is fine with this, and happily serves the DS as though everything were the exact same content. This isn't great.

**Comment by mitchell852** [comment]
@alficles - is this bug only applicable in the TO UI or does it apply to TP/TO API as well?

**Comment by alficles** [comment]
Both. It's a bug in the perl that generates the config lines.

**Comment by mitchell852** [comment]
oh, i see

get_qstring_ignore_remap

is a function that is used by the following api routes:

	# -- CONFIG FILES
	$r->get("/api/$version/servers/#id/configfiles/ats")->over( authenticated => 1, not_ldap => 1 )->to ( 'ApacheTrafficServer#get_config_metadata', namespace => 'API::Configs' );
	$r->get("/api/$version/profiles/#id/configfiles/ats/#filename")->over( authenticated => 1, not_ldap => 1 )->to ( 'ApacheTrafficServer#get_profile_config', namespace => 'API::Configs' );
	$r->get("/api/$version/servers/#id/configfiles/ats/#filename")->over( authenticated => 1, not_ldap => 1 )->to ( 'ApacheTrafficServer#get_server_config', namespace => 'API::Configs' );
	$r->get("/api/$version/cdns/#id/configfiles/ats/#filename")->over( authenticated => 1, not_ldap => 1 )->to ( 'ApacheTrafficServer#get_cdn_config', namespace => 'API::Configs' );

**Comment by elsloo** [comment]
Resolved via #2590.
