### ISSUE TITLE
Golang cachegroup crud apis are missing data integrity rules implemented in Perl

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2597]
All of the rules found in Perl were not migrated to Go. For example, when trying to delete a cachegroup, the perl checks that no servers are attached to the cachegroup before deleting the cachegroup. The Go does not bother to do this check.

**Comment by moltzaum** [comment]
Working on this.

**Comment by rawlinp** [comment]
We should do this check in the API in order to give the user a useful error message, but also set the `server.cachegroup` FK to `ON DELETE RESTRICT` so that it's prohibited at the DB layer too.
