### ISSUE TITLE
TODO: Update Tenancy Check to Use Different Method

### ISSUE THREAD

**Issue by moltzaum** [apache/trafficcontrol#2602]
In `cdnfederations.go` I used `GetUserTenantIDListTx` instead of `IsResourceAuthorizedToUserTx` because the secondary method still used the `use_tenancy` variable. However, it would be more idomatic to use the secondary method, especially after `use_tenancy` is fully deprecated.

**Comment by ocket8888** [comment]
Fixed by #3311
