### ISSUE TITLE
Golang PUT/POST servers API missing port number validation

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#2603]
The Perl validation of `httpsPort` and `tcpPort` is just that the port is a non-negative integer. The  Go version will fail to marshal the JSON if the ports aren't integers, but in order to get parity with the Perl we have to validate that it's non-negative. However, there should be real validation that the ports are _actually_ in this range: [1, 65535].

EDIT: the original description said that the (IP, profile) uniqueness validation was missing, but this is actually taken care of by a DB constraint:
```
    "idx_140441_ip6_profile" UNIQUE, btree (ip6_address, profile)
    "idx_140441_ip_profile" UNIQUE, btree (ip_address, profile)
```

**Comment by mitchell852** [comment]
@DylanVolz - can you look at this?

**Comment by rawlinp** [comment]
Verified that the (ip, profile) validation is actually done by a DB constraint and returns a useful error message from the API.

The port number validation is all that's missing.
