### ISSUE TITLE
Add TR failover for TM CRConfig

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#2604]
In a scenario in which a TrafficMonitor in the ONLINE state reboots and is unable to contact TO, it is unable to retrieve its initial configuration and will not start fully.  Traffic Router currently trusts TO to inform it about what TMs it should be using regardless of the health of that TM.  As a result should one of these TMs get into a bad state and still be flagged as active in TO, TR will continue to try and use it without success.  For increased resiliency, a TR which receives an error from TM should round-robin through other ONLINE TMs instead of latching onto the failed server.

**Comment by elsloo** [comment]
In Traffic Router, we do not latch onto a failed server, and will continue trying to use the other servers that are available. We could potentially remove the unreachable server for some period of time before retrying. I'm not sure how much utility we would get out of that sort of work but it would slightly optimize things when we're in such a scenario.

As for TM, it needs to continue to trying to communicate with TO until it's available.

**Comment by rawlinp** [comment]
Per @elsloo's comment, this was a non-issue. Also:
> As for TM, it needs to continue to trying to communicate with TO until it's available.

TM may not have done this when this issue was created, but it does now. It also saves its crconfig and monitoring.json to disk now and will use that if it can't reach TO.
