### ISSUE TITLE
Go DS API needs helpful error message when creating a DS in a CDN without DNSSEC keys

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#2620]
If you have DNSSEC enabled on your CDN but the DNSSEC keys have not been generated for your CDN yet, it is impossible to create Delivery Services for that CDN. However, the error message returned when trying to create the Delivery Service is just "Internal Server Error".

In this case the error message returned to the user should state that the CDN has DNSSEC enabled but no DNSSEC keys yet, which prevents the creation of a new Delivery Service. IMO this should be a `400 Bad Request` rather than a `500 Internal Server Error`.

**Comment by mitchell852** [comment]
There appears to be a workaround for this so I've added the `minor` label. The workaround is to just make sure the CDN has DNSSEC keys right @rawlinp ?

**Comment by rawlinp** [comment]
I wouldn't really call it a workaround because there's no information given to the user to indicate that the issues is the CDN's DNSSEC keys, but I would agree it's minor.

**Comment by mitchell852** [comment]
@rawlinp - it's a super secret workaround :)

**Comment by rawlinp** [comment]
We now have a helpful error message for this issue.
