### ISSUE TITLE
properly handle db timeout errors

### ISSUE THREAD

**Issue by DylanVolz** [apache/trafficcontrol#2631]
Currently when a db query's context times out or is cancelled we do not catch this error and return a 500 internal server error. We should catch this case and return a 503.

**Comment by ocket8888** [comment]
This may not be a good idea. Current practices are to never expose underlying service state via API responses - from the [API Guidelines](https://traffic-control-cdn.readthedocs.io/en/latest/development/api_guidelines.html):

> ### 500 Internal Server Error
> When the Traffic Ops server encounters some error - through no fault of the client or their request - that renders it incapable of servicing the client’s request, it MUST return this status code if no other code is more appropriate. The response body in this case SHOULD indicate that an error occurred, but MUST NOT divulge details about what data was being processed, what (if any) other components are not functioning properly, or what process failed. Generally it is advisable that the resultant alerts array entry just say “Internal Server Error” and nothing else.

If you feel this is not a good practice, please bring it up to the mailing list.
