### ISSUE TITLE
The auth check method needs to return an error

### ISSUE THREAD

**Issue by DylanVolz** [apache/trafficcontrol#2633]
GetCurrentUserFromDB should be refactored to return an error. Currently there is no indication that it is a load problem when the query times out and the user receives a 403 or 401.

**Comment by mitchell852** [comment]
yes, a 401 implies either the user never authenticated or the user's cookie is invalid (expired)

a 403 implies that the user authenticated but is attempting to perform a forbidden action based on their permissions. so a 401 or 403 is definitely not the correct response when a query times out.

**Comment by zrhoffman** [comment]
Fixed by #2656
