### ISSUE TITLE
Initial state for new server objects should be PRE_PROD

### ISSUE THREAD

**Issue by guzzijason** [apache/trafficcontrol#2651]
Currently, default state for new servers is OFFLINE. Perhaps PRE_PROD is more appropriate?

**Comment by mitchell852** [comment]
I'm not sure what is appropriate. You want to start a discussion at dev@trafficcontrol.apache.org?

**Comment by mitchell852** [comment]
just for a little context

![image](https://user-images.githubusercontent.com/251272/43972365-57d05e02-9c91-11e8-9d28-d1b5a3cbabae.png)

**Comment by mitchell852** [comment]
^^ maybe that could be configurable. i.e. you can decide which state "new" servers are initially set to....or actually, maybe the easiest thing to do is just make that drop down enabled.

**Comment by guzzijason** [comment]
I'm +1 on enabling the drop down.
