### ISSUE TITLE
TO API: unable to write a null or blank value to IPv6

### ISSUE THREAD

**Issue by dg4prez** [apache/trafficcontrol#2657]
Created two servers with v6 addresses, then removed the address for one.  When removing the second's in traffic portal, an error tells me that i'm unable to edit the v6 address as it already exists for another host.

Making the same change via the API results in no error, but no change either.  This occurs when setting the address to both "" or NULL.

**Comment by mitchell852** [comment]
if my memory serves me correctly, ipv6 addresses must be unique per profile. for example

server 1 has profile A which has ipv6=2001:aaaa:bbbb:cccc::
server 2 has profile B which has ipv6=2001:aaaa:bbbb:cccc::

^^ this is fine but if 

server 3 has profile B which has ipv6=2001:aaaa:bbbb:cccc:: <-- that won't work. 

anyhow, my guess is that this constraint is kicking in on a null or blank value. i.e.

server 1 has profile A which has ipv6=null
server 2 has profile A which has ipv6=null <-- the system thinks that null is already taken so it's throwing the unique constraint error.
