### ISSUE TITLE
POST /api/version/roles results in internal server error

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2663]
`INFO: routing.go:226: 2018-08-13T10:30:06.037734942-06:00: POST /api/1.3/roles handling (reqid 26)
DEBUG: wrappers.go:153: 2018-08-13T10:30:06.049467415-06:00: &{ReqInfo:0xc42030af40 Role:{ID:<nil> Name:0xc4201db220 Description:0xc4201db2a0 PrivLevel:0xc4201db238 Capabilities:<nil>}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x151947b]

goroutine 193 [running]:
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/role.(*TORole).createRoleCapabilityAssociations(0xc420017a10, 0xc4200179e0, 0x16f96a9, 0x2, 0xc4213e0748)
	/Users/jmitch001c/code/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/role/roles.go:171 +0x28b
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/role.(*TORole).Create(0xc420017a10, 0x0, 0x0, 0x0)
	/Users/jmitch001c/code/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/role/roles.go:153 +0x871
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/api.CreateHandler.func1(0x1a2eb40, 0xc4200178c0, 0xc4204baf00)
	/Users/jmitch001c/code/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/api/shared_handlers.go:456 +0x2db
main.wrapHeaders.func1(0x1a2ee40, 0xc4213de780, 0xc4204baf00)
	/Users/jmitch001c/code/src/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/wrappers.go:153 +0x248
net/http.HandlerFunc.ServeHTTP(0xc4202e7f90, 0x1a2ee40, 0xc4213de780, 0xc4204baf00)
	/usr/local/Cellar/go@1.8/1.8.7/libexec/src/net/http/server.go:1942 +0x44
net/http.(*timeoutHandler).ServeHTTP.func1(0xc420017860, 0xc4213de780, 0xc4204baf00, 0xc4211efc80)
	/usr/local/Cellar/go@1.8/1.8.7/libexec/src/net/http/server.go:2967 +0x53
created by net/http.(*timeoutHandler).ServeHTTP
	/usr/local/Cellar/go@1.8/1.8.7/libexec/src/net/http/server.go:2969 +0x158`

**Comment by rob05c** [comment]
https://github.com/apache/trafficcontrol/blob/8fe0a128446c5303c2dba1f8787c4160ff3cb4b3/traffic_ops/traffic_ops_golang/role/roles.go#L171

**Comment by rob05c** [comment]
https://github.com/apache/trafficcontrol/blob/efbffa952f43f40aea70fd5a13b1aa64fb9ccb65/traffic_ops/traffic_ops_golang/role/roles.go#L147
in  `traffic_ops_golang/role/roles.go` `createRoleCapabilityAssociations`

**Comment by srijeet0406** [comment]
No internal server error in `api/3.0`
