### ISSUE TITLE
The use_tenancy global parameter from seeds.sql should be removed

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#2685]
This parameter is now unused and removed in patches.sql, which is run _after_ seeds.sql, so this seed should be cleaned up and removed from seeds.sql. Otherwise, DB upgrades will continue to add the parameter and remove the parameter every time.

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/db/seeds.sql#L39

**Comment by dangogh** [comment]
yes!    Thanks for catching that....

**Comment by dangogh** [comment]
This needs to wait until #2687 and #2695 are addressed.   The `use_tenancy` parameter must remain in the db (always set to "1") until the code is cleaned up.

**Comment by mitchell852** [comment]
agree. this needs to be removed if it's still lying around. tenancy has not been optional for quite some time.
