### ISSUE TITLE
Document POST servers/id/deliveryservices

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#2698]
This route needs documented.

It's new, and not in Perl or the docs. I almost deleted it, because I thought it was a mistake (it's not: https://github.com/apache/trafficcontrol/commit/209b65043a1da973cf9cc225844762f343e1ba55).

**Comment by ocket8888** [comment]
[Documentation for `/servers/{{ID}}/deliveryservices`](https://traffic-control-cdn.readthedocs.io/en/latest/api/v3/servers_id_deliveryservices.html) does exist.
