### ISSUE TITLE
Copy all Docs for API 1.2 into API 1.3

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#2699]
So far, we've been only putting new route docs into the 1.3 API docs. We need to copy all the old routes that haven't changed from 1.2. It's not reasonable to expect users to mentally diff docs, and go thru all the old minor versions to find the route they're looking for.

**Comment by ocket8888** [comment]
The new docs structure doesn't require that we make a full copy of each minor version anymore. So this is "done".

**Comment by rob05c** [comment]
Agreed
