### ISSUE TITLE
TO Go -- db access error if profile.cdn is null

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#2710]
hitting the `POST /api/1.3/servers` endpoint.   If the profile indicated has a null cdn, I get a db access error:
```
ERROR: servers.go:128: could not scan cdnID from profile: sql: Scan error on column index 0: converting driver.Value type <nil> ("<nil>") to a int: invalid syntax
```

The `POST .../profiles` endpoint doesn't allow a null cdn, but the profiles in `seeds.sql` create the initial set that way.   That needs to be fixed and a not null constraint placed on it,  or the servers endpoint needs to handle it appropriately.

**Comment by rob05c** [comment]
+1 on `not null`. 

Profiles apply to Servers and DSes, which should always be on one CDN, and using them for anything on a different CDN can cause all kinds of issues, and should never ever happen. Enforcing Profile CDNs with a foreign key and not-null will prevent those issues. Unless someone knows a scenario it's valid to have a cross-CDN profile?

**Comment by dangogh** [comment]
my thought as well.

global profiles are cross-CDN,  but should use the ALL cdn,  which is created in `seeds.sql`

**Comment by dangogh** [comment]
on the plus side,  it does detect if server cdn and profile cdn don't match
