### ISSUE TITLE
Change Portal CDN DNSSEC Generate input to a Calendar

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#2722]
Right now, the Traffic Portal `CDNs / over-the-top / DNSSEC / Keys / generate` `Effective Date (UTC) *` is a text input field. That field is a date, and always needs to be a valid timestamp in a particular format.

The input field should be changed to a calendar, so users can't typo it, and also just for ease of use.

**Comment by mitchell852** [comment]
UI assistance/validation is great but hopefully the API kicks out a date bad format. is that true @rob05c ?
