### ISSUE TITLE
TO Golang logging error not valuable and noisy

### ISSUE THREAD

**Issue by dewrich** [apache/trafficcontrol#2724]
```
ERROR: wrappers.go:157: 2018-08-21T11:08:30.070444-06:00: checking local user password: Algorithm defined is not SCRYPT
```
This `ERROR:` message is continually spewing in the logs.  Seems like this should be called when there is a true error

**Comment by moltzaum** [comment]
I haven't noticed this at all recently. @mitchell852 can you close this please?
