### ISSUE TITLE
Undocumented API Parameters

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2726]
I've noticed that many API endpoints support query parameters that are undocumented. For example, [the docs](https://traffic-control-cdn.readthedocs.io/en/latest/api/v12/user.html) mention that a possible parameter to pass to `GET /api/1.2/users HTTP/1.1` is `tenant` to filter by tenant, but that endpoint actually supports other parameters like e.g. `username` to filter by a specific username. Those parameters ought to be documented.

**Comment by moltzaum** [comment]
The page you are linking to doesn't exist. Was this fixed by #3078 ?

**Comment by ocket8888** [comment]
Unfortunately no. We still have entire endpoints that are undocumented.

**Comment by ocket8888** [comment]
I'm closing this not because it's fixed, but because it's too vague to be useful. If known parameters are undocumented, specific issues should be opened for those, so that it's easily verifiable when they are fixed.
