### ISSUE TITLE
Cannot add resolver to multiple federations

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#2738]
Using Traffic Portal, if you try to add the same resolver IP CIDR to multiple federations you will get an error saying that the CIDR is already in use.  Traffic Portal should allow a user to add the same resolver CIDR to multiple federations as this is the most common use case.

**Comment by mitchell852** [comment]
`to_development=# \d federation_resolver
                                        Table "public.federation_resolver"
    Column    |           Type           | Collation | Nullable |                     Default
--------------+--------------------------+-----------+----------+-------------------------------------------------
 id           | bigint                   |           | not null | nextval('federation_resolver_id_seq'::regclass)
 ip_address   | text                     |           | not null |
 type         | bigint                   |           | not null |
 last_updated | timestamp with time zone |           | not null | now()
Indexes:
    "idx_140291_primary" PRIMARY KEY, btree (id)
    "idx_140291_federation_resolver_ip_address" UNIQUE, btree (ip_address)`

so it looks like uniqueness was intentionally added on this column. so it sounds like the reqs changed. so i'll reclassify this as an enhancement and mark it as major.

**Comment by dneuman64** [comment]
I think this is an issue with the portal behavior. The only way I could tell to associate a resolver to a federation was to "add" a resolver.  In reality, I don't want to add the same resolver multiple times, but I want to be able to associate resolvers with multiple federations (using the federation_federation_resolvers table).  I think the portal needs to provide the ability to add new resolvers but to also associate resolvers with federations.

**Comment by mitchell852** [comment]
yes, i think when you "add" a resolver currently in TP it does 2 things:

1. creates a fed resolver
2. assigns that new fed resolver to the current federation

there is no way in TP currently to assign an existing fed resolver to a federation.
