### ISSUE TITLE
No traffic ops hostname yet

### ISSUE THREAD

**Issue by hotrovps** [apache/trafficcontrol#2745]
I build traffic router by this command "./pkg -v source traffic_router_build"
Next I installed the packet " traffic_router-2.2.0-7738.8f4d1ee2.el7.x86_64.rpm" on server.
Next "/etc/rc.d/init.d/tomcat start"

And then I got these error in /opt/traffic_router/var/log/traffic_router.log:

WARN  2018-08-24T10:41:10.457 [pool-1-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.util.AbstractResourceWatcher - [SteeringWatcher] Waiting for configuration to be processed, unable to download from 'https://${toHostname}/internal/api/1.2/steering.json'
ERROR 2018-08-24T10:41:10.517 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!

Any help would be appreciated !

**Comment by limited** [comment]
@hotrovps 

This issue tracker is not the best place for help configuring Traffic Control. Please send an email to users@trafficcontrol.apache.org and we can provide better advice there. 

As a quick suggestion,   you also need to edit the files before starting Traffic Router. 
   /opt/traffic_router/conf/traffic_monitor.properties - Fill in Traffic Monitor IPs
   /opt/traffic_router/conf/traffic_ops.properties   - Fill in Traffic Ops username/password

**Comment by hotrovps** [comment]
Thank @limited !

**Comment by amansingh14** [comment]
Hi @limited ,


Can you share me example for above how you n ips, traffic_monitor.properties. 

I am new traffic_control. Kindly help.

**Comment by limited** [comment]
Hi @amansingh14-

This issue tracker is not the best place for help configuring Traffic Control. Please send an email to users@trafficcontrol.apache.org and we can provide better advice there.

**Comment by amansingh14** [comment]
Hi @limited ,

  I tried to send mail on above mentioned mail ID but it failed.
