### ISSUE TITLE
API 1.3 users deliveryservices endpoint does not show all the deliveryservies assigned to a user

### ISSUE THREAD

**Issue by jrushford** [apache/trafficcontrol#2750]
The /api/1.3/users/${UID}/deliveryservices endpoint is not returning all the deliveryservices assigned to the user.

**Comment by mitchell852** [comment]
More specifically, it's not returning all the delivery services assigned to the tenant of the user (or the sub tenants)

**Comment by mitchell852** [comment]
closing as GET users/${UID}/deliveryservices has been deprecated in favor of GET /deliveryservices?accessibleTo=user.tenantId
