### ISSUE TITLE
Invalidation requests do not set the reval pending flag for edges

### ISSUE THREAD

**Issue by dg4prez** [apache/trafficcontrol#2763]
A bug was recently discovered in which the reval_pending flag in the database is not set for edges when an invalidation request is processed.  Mids are still flagged.  This should be considered a critical bug.

**Comment by mitchell852** [comment]
If I recall correctly a call to POST /api/1.3/user/current/jobs should 

1. create a job in the jobs table
2. figure out the cdn associated with the job's ds
3. set server.reval_pending=1 for all the caches in that cdn

**Comment by mitchell852** [comment]
@rivasj is looking at this
