### ISSUE TITLE
Traffic Ops needs to validate httpBypassFqdn for HTTP Delivery Services

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#2770]
The old Perl UI validated that httpBypassFqdn is a valid hostname. Traffic Portal form validation was just fixed to do this as well in #2769, but we still need to perform Delivery Service API-level validation within traffic_ops_golang as well.

**Comment by mitchell852** [comment]
what severity would you give this bug @rawlinp ? can you add the appropriate severity level?

**Comment by mitchell852** [comment]
this is still needed. reviewed in 8/17/21 working group.

**Comment by zrhoffman** [comment]
To be clear, Traffic Portal has this validation, but Traffic Ops does not.
