### ISSUE TITLE
Traffic Portal - DS Server Assignments

### ISSUE THREAD

**Issue by bnurcz000** [apache/trafficcontrol#2786]
The old UI had a DS assigning tool that seemed easier to view/use at a glance.
The servers were nested in a visual view that grouped all servers by profile and allowed batches to be checked and selected in groups.
This made it simple to compare one DS's server assignments to another.

![screen shot 2018-09-05 at 9 57 07 am](https://user-images.githubusercontent.com/16598638/45164015-2b657100-b1b7-11e8-9181-6ed9dd1de950.png)

Under the new portal, servers have to be selected individually
When comparing two DS's, we have to parse through an entire list.
It might be useful to have a visual representation on the new Portal similar to the old UI, or perhaps even a DIFF function to compare server assignments on two DS's.
I know we have a compare feature that performs a diff on top-level DS configs, but I don't believe it goes down to the server assignment level yet.

**Comment by mitchell852** [comment]
yeah, currently in TP if you want to select ALL servers for a certain profile, you'd have to filter the list by profile name and then hit the "select all" checkbox.

**Comment by smalenfant** [comment]
Would be nice if we could clone the "server assignments" from another delivery service then. The selecting PROFILE groups in Traffic Ops was really useful.

**Comment by mitchell852** [comment]
ds/server assignments will no longer be relevant going forward as topologies will be used instead. however, orgins still need direct assignment due to MSO.
