### ISSUE TITLE
Snapshot changes - Filtering

### ISSUE THREAD

**Issue by bnurcz000** [apache/trafficcontrol#2787]
The OLD UI only shows CHANGES when performing a snapshot.
![screen shot 2018-09-05 at 10 52 20 am](https://user-images.githubusercontent.com/16598638/45164077-4e902080-b1b7-11e8-82d0-fc0a0bdb95ae.png)

On the New Portal, it shows the status of EVERYTHING.
The Portal has a convenient change count of the top, but to see actual CHANGES, you have to manually scroll down until you see highlighted colors:
![screen shot 2018-09-05 at 10 53 13 am](https://user-images.githubusercontent.com/16598638/45164101-5bad0f80-b1b7-11e8-92cc-60e2bc434548.png)

A filter to show only things that are CHANGING would be a useful addition to the new Portal.

**Comment by mitchell852** [comment]
yeah, unfortunately at the moment, you have to search for `++`  or `--` to see what changed

**Comment by mitchell852** [comment]
resolved via #3540
