### ISSUE TITLE
cannot add / for v6 ip in servers field. Need to sort alphabetically on location

### ISSUE THREAD

**Issue by saoyag001** [apache/trafficcontrol#2790]
cannot add a / to v6 ip's on server add page. error is / is not allowed.
choosing site  on server add page is a random order, with over 50 sites, it's painful to navigate.

**Comment by rawlinp** [comment]
@saoyag001 this is really two separate issues, can you please separate them out? One is traffic_ops_golang not accepting IPv6 CIDRs anymore in the ip6Address field, and the other is that PhysLocations are not sorted in the server page.

**Comment by DylanVolz** [comment]
I am fixing the ipv6 field issue currently. I hadn't realized we used CIDRs in the ip6address field.
