### ISSUE TITLE
Make Traffic Ops "API Tests" use seeds.sql

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#2793]
Right now, The TO "API Tests" don't use seeds.sql, which has a number of issues:
1. The sql commands required by the tests have to be copy-pasted into the tests. For example, for capabilities, this is 200+ lines of duplicate code.
2. Changes to seeds.sql will break the tests, unless they're also copy-pasted in.
3. Changes to seeds.sql which change behavior could break an endpoint, but the "API Tests" will still pass because they're copy-pasted.
4. The seeds.sql is not being tested. Ideally, the TO tests should verify that the seeds.sql works correctly, as part of verifying TO works.

The "API Test" framework should be changed to use seed.sql, rather than copying its contents, to fix these issues, and improve test coverage in general.

**Comment by rawlinp** [comment]
There are some other DB-related issues with the TO API testing framework that I believe should be addressed along with this issue, which I've captured in https://github.com/apache/trafficcontrol/issues/3865. I captured your description for this issue in there as well.
