### ISSUE TITLE
order by name server location dropdown (physLocationService.getPhysLocations)

### ISSUE THREAD

**Issue by saoyag001** [apache/trafficcontrol#2794]
choosing site on server add page is a random order, with over 50 sites, it's painful to navigate.

in FormServerController.js
needs { orderby: 'name' }

**Comment by rawlinp** [comment]
We can add an `orderby: 'name'` parameter via Traffic Portal to solve the UI issue, but this is also a regression within traffic_ops_golang where the phys_locations index API endpoint doesn't have the same default `orderby=name` as the Perl version. If this was added to traffic_ops_golang the Traffic Portal change would be redundant.

**Comment by anna-k-1** [comment]
CDN-3154
