### ISSUE TITLE
Traffic Portal - The profile type for a grove profile is not shown.

### ISSUE THREAD

**Issue by jrushford** [apache/trafficcontrol#2804]
Recently a GROVE_PROFILE type was added to trafficcontrol.  A grove profile type has been added but in traffic portal when viewing the details of this profile, they 'type' is set to 'select'.  The drop down to change the type does not show a 'GROVE_PROFILE'.  In traffic ops, the grove profile is displayed properly.

**Comment by mitchell852** [comment]
you'll want to add that type to here:

https://github.com/apache/trafficcontrol/blob/master/traffic_portal/app/src/common/modules/form/profile/FormProfileController.js#L31

**Comment by dangogh** [comment]
interesting those aren't in the `types` table at all.....
