### ISSUE TITLE
No UI to configure Steering Delivery Service filters

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2811]
Currently, a filter must be added/modified via the Traffic Ops API. It'd be nice if there was a user-friendly Traffic Portal interface, especially since most other features (or all of them, as far as I know) are configurable from Traffic Portal.

**Comment by mitchell852** [comment]
Yeah, i think you can only do this via the API at the moment.

**Comment by ocket8888** [comment]
yep, everything I've hear, read or done points to this being an API-only operation

**Comment by mitchell852** [comment]
I can't even recall what a `filter` is tbh and what endpoint is used to manage these "filters"?

**Comment by rawlinp** [comment]
IIRC a filter is a DS regex of type `STEERING_REGEXP`, which, when assigned to _target_ delivery service, will cause that steering target to be preferred if the requested URL matches that regex.

**Comment by mitchell852** [comment]
> IIRC a filter is a DS regex of type `STEERING_REGEXP`, which, when assigned to _target_ delivery service, will cause that steering target to be preferred if the requested URL matches that regex.

thanks for the clarification! and it looks like you can already do that in TP :)

![image](https://user-images.githubusercontent.com/251272/96749106-9f5b3700-1387-11eb-8536-a9c7163a7ac6.png)

want to close this @ocket8888 ?

**Comment by ocket8888** [comment]
Yeah, that seems right.
