### ISSUE TITLE
TP changing Signing Algorithm to "None" does not work

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#2854]
In Traffic Portal,  I have a DeliveryService with Signing Algorithm set to "URL Signing Keys".   If I switch this to "None" and Update,  then look at that field again, it still is "URL Signing Keys".

Using the API,  if I change that field to `null` and `signed` to `false`,  a PUT properly changes it to `nil` and `false` in the database.   If I leave `signed` as `true` and set `signingAlgorithm` to `null`,  the result is `signed`: `true` and `signingAlgorithm`: `url_sig`.

TP and the TO API need to handle this better..

**Comment by rivasj** [comment]
Duplicate of https://github.com/apache/trafficcontrol/issues/2836 . I'm currently working this issue

**Comment by rivasj** [comment]
Closed by #2859
