### ISSUE TITLE
Some API Responses use wrong Content-Type

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2881]
The only concrete example with which I can come up is `/api/1.3/servers/<hostname>/configfiles/ats`, which responds with `Content-Type: text/plain;charset=UTF-8`, which is the correct character encoding, but the data is a JSON object so this header should be `Content-Type: application/json;charset=UTF-8`. However, I seriously doubt that out of all of TO's hundreds of API endpoints, this is the only one to suffer from this header issue.

**Comment by zrhoffman** [comment]
`/api/3.0/ping` still returns the wrong content type as of d4780c387e.
