### ISSUE TITLE
Add a identifier to a DS to allow for grouping similiar content.

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#2884]
When we build graphs using traffic stats we have the ability to filter data by server name, DS name, cache group, cdn, etc, but we don't have a good way to group by like content.  For example we could have 500 delivery services that all represent "linear video" and it would be nice to be able to group all of these together using something other than a regex (like a tag).

If we implemented this in Traffic Ops and then update Traffic Stats to add the tag to InfluxDB, we should have what we need to build some sweet dashboards.

**Comment by rob05c** [comment]
+1 for DS tags. I can think of tons of uses for them. Identifying, grouping, searching. And letting Tenants do all that themselves, for however they define groups of DSes. Seems extremely convenient and useful.

**Comment by rob05c** [comment]
>add the tag
To be clear, I vote DSes can have any number of arbitrary tags, not just one tag per DS. That's much more powerful and flexible.

The UI should show users existing tags, so they can easily add them without mis-typing, but also let them easily type in a new tag that doesn't exist. Just like Gmail, Github, etc.

**Comment by mitchell852** [comment]
one thing that already exists is ds grouping by tenant so i feel like at the very least there should be tags in Traffic Stats for each tenant.

**Comment by rawlinp** [comment]
> To be clear, I vote DSes can have any number of arbitrary tags, not just one tag per DS. That's much more powerful and flexible.

Should we put a limit on the number of tags associated with a single DS? Something like 100 just so there's an upper bound on user input but also a reasonable number of tags to work with. Also, what's a reasonable maximum for the tag text itself?

**Comment by rob05c** [comment]
>Should we put a limit on the number of tags associated with a single DS?

>what's a reasonable maximum for the tag text itself?

+1 to both. Seems like it should be configurable, too. Maybe a default of 100 tags and 50 characters per tag, or use a config in `cdn.conf` if it exists?

**Comment by mitchell852** [comment]
service categories feature was added by @jehunte in TC 5.0. i believe this achieves what you were looking for @dneuman64 . closing. please reopen if you disagree.
