### ISSUE TITLE
TP: add the ability to Regenerate KSK keys for a CDN

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2895]
In TP, you cannot regenerate KSK keys. Here is how it was done in the TO UI:

![image](https://user-images.githubusercontent.com/251272/46316792-58c2f600-c58e-11e8-8779-d803f934dd9c.png)

 ^^ Apparently, the "Regenerate KSK" button is only visible if defined($dnssec->{k_expiry} and when you click it you see the following dialog

![image](https://user-images.githubusercontent.com/251272/46316836-77c18800-c58e-11e8-8ff9-b7288d2cafd8.png)

This will require TP work as well as an API to support this functionality.

This API should be limited to the admin role.

**Comment by jhowar201** [comment]
The current process in TP also does not use the same digest settings as TO does on initial key generation. They should be selectable, or at least consistent with what we used in TO historically so we do not regenerate less secure keys.

It would also be helpful if after regenerating keys TP displayed the DS record information that needs to be added to DNS for that CDN as well. This currently needs to be retrieved from a Traffic Router log file after generating in TO.

**Comment by mitchell852** [comment]
@chadgilloth is looking at this
