### ISSUE TITLE
TO:Internal server error while using traffic_portal in production build

### ISSUE THREAD

**Issue by itsmesridhar** [apache/trafficcontrol#2905]
In my case production db was running in a separate container and traffic_ops&portal are running in same container. While access the api/1.3/user/current its getting internal server error response code from traffic_ops server. DB container connection also connected successfully.

**Comment by rawlinp** [comment]
@itsmesridhar can you provide the logs from Traffic Ops for the internal server error you're getting?

**Comment by itsmesridhar** [comment]
@rawlinp  Request was not forwarded to traffic_ops that's the problem here. Traffic_ops & portal are running in container with the ip: 172.17.0.2. While hit https request from host browser its asking for certificate exception permission and moving forward to load the static assets and its successful but it cannot able to access traffic_ops api. Traffic_portals logs are printed below.

configured portal base URL: http://localhost:8080/!#/

[root@c6974f816ccb /]# tail -f /var/log/traffic_portal/traffic_portal.log 
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
Error: connect ECONNREFUSED 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
`

**Comment by mitchell852** [comment]
you updated /opt/traffic_portal/conf/config.js appropriately?

**Comment by itsmesridhar** [comment]
Yes, I have updated  /opt/traffic_portal/conf/config.js with the traffic_ops baseURL. The problem which I have faced was resolved. Problem happens because traffic_ops go app not started properly in Centos7 container. Thanks for your help :-)

**Comment by azzarasw** [comment]
hello, i have a same problem with you, internal server error when traffic portal open, so i cant add the delivery services. by the way im using rocky linux to build all the components. do you have any solution about my problem? thank you before
