### ISSUE TITLE
Delivery Services Dashboard Widget CSS responsiveness is off when reducing screen size

### ISSUE THREAD

**Issue by chadgilloth** [apache/trafficcontrol#2906]
The delivery services table does not reclaim the empty space to the right when the table gets stacked on the chart as the screen size is reduced.

**Comment by mitchell852** [comment]
@chadgilloth - this can be closed, right?

**Comment by chadgilloth** [comment]
@mitchell852 Correct, it can be closed.

**Comment by mitchell852** [comment]
fixed in #2823
