### ISSUE TITLE
TO: investigate removing deliveryservice_tmuser table

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#2910]
From what I understand,  the `deliveryservice_tmuser` join table is no longer actively used,  but there is code that still uses it.    Issue #2750 describes getting DSes assigned to a user,  but it really should be DSes accessible to a user thru the tenants he/she has access to.

`git grep -i deliveryservicetmuser` shows a bunch of places where this is accessed.   These need to be investigated and removed.

**Comment by mitchell852** [comment]
if there are places that are checking the deliveryservice_tmuser table, it needs to be removed and replaced with the hasTenancy check.

**Comment by mitchell852** [comment]
this is potentially blocked by API 1.x removal but once removed please kill this unused table!
