### ISSUE TITLE
file list API response is not wrapped like the others in a response 

### ISSUE THREAD

**Issue by knutsel** [apache/trafficcontrol#2925]
/api/1.3/servers/atsec-chi-00/configfiles/ats 

![image](https://user-images.githubusercontent.com/3393745/46891366-d7d5eb00-ce26-11e8-9c3d-648fe7e0d64e.png)

should be 

![image](https://user-images.githubusercontent.com/3393745/46891383-e45a4380-ce26-11e8-9d37-7ca53fc25c5b.png)

**Comment by mitchell852** [comment]
config file generation in TO has been removed. closing.
