### ISSUE TITLE
TO go client: login broken

### ISSUE THREAD

**Issue by dangogh** [apache/trafficcontrol#2930]
`traffic_ops/client/endpoints.go` changed so the default apiBase is `api/1.4`,   but the `api/1.4/user/login` endpoint does not work.

Any client creating a session using the go client will fail to login.

**Comment by mitchell852** [comment]
login is overrated...

**Comment by dangogh** [comment]
unsure what happened that I ran into this,  but I no longer see it on a freshly-built traffic_ops
Closing..

**Comment by mitchell852** [comment]
In routes.go, I see

`{1.1, http.MethodPost, `user/login/?$`, login.LoginHandler(d.DB, d.Config), 0, NoAuth, nil},`

which to my understanding meant any of these should work fine

`POST api/1.1/user/login`
`POST api/1.2/user/login`
`POST api/1.3/user/login`
`POST api/1.4/user/login`

**Comment by jrushford** [comment]
I see this with grovetccfg still.  When I build grovetccfg from master and then use it agains staging which does not have the 1.4 api deployed, I get a 401 unauthorized:

2018-10-23T14:23:10.380331961Z Error connecting to Traffic Ops: logging in: requesting: 401 Unauthorized[401] - Error requesting Traffic Ops https://trafficops.kabletown.net/api/1.4/user/login {"alerts":[{"level":"error","text":"Unauthorized, please log in."}]}

**Comment by rob05c** [comment]
> In routes.go, I see
> 
> `{1.1, http.MethodPost, `user/login/?$`, login.LoginHandler(d.DB, d.Config), 0, NoAuth, nil},`
> 
> which to my understanding meant any of these should work fine:
> 
> `POST api/1.1/user/login`
> `POST api/1.2/user/login`
> `POST api/1.3/user/login`
> `POST api/1.4/user/login`
> `POST api/1.5/user/login`
> `POST api/1.6/user/login`
> `POST api/1.7/user/login`
> `POST api/1.8/user/login`
> `POST api/1.9/user/login`

It doesn't work that way. The `traffic_ops_golang` router will serve all minor endpoints at all newer versions _which exist_. That's important. If we served old endpoints at minors which didn't exist, a client (like now) which is newer than the server would hit an endpoint which had been modified in 1.4, say DeliveryServices had a new field added, and that field wouldn't exist in the server, and the client would return a struct with a nil or default value, and now the user thinks that value was nil or 0, when in fact they're hitting an old TO.

The level of errors and confusion that would cause would far exceed the frustration of having to downgrade the client.

**Comment by jrushford** [comment]
Why do I get a 401 when I hit api/1.4/user/login agains staging which does not yet have 1.4?  You would think that I would get a 404 or 400 bad request

**Comment by rob05c** [comment]
>staging which does not have the 1.4 api deployed
That's by design.

>I think this issue needs to be re-opened and looked at.

This isn't a bug. You can request a new feature. But it's currently working as-designed: the client is always the newest version in master, and older servers do not serve versions which don't exist.

We've had these discussions before, there's simply no great solution. Our options are essentially
1. A huge amount of duplicate client code and version maintenance, to maintain all minor version clients in master
2. Vendor the client within our own codebase, with the confusion and difficulty that entails.
3. Make the client only request new version numbers for API endpoints which are new or have changed. This only partially solves the problem, people trying to hit a changed endpoint, e.g. if a field is added to `/deliveryservices`, will still encounter the existing frustration
4. Require older clients to hit older Traffic Ops. If the user is running an old TO, they are required to use a client from a previous release.

I suspect 4 is unreasonably painful for people using Releases. It seems like it's only a pain point for people running off bleeding-edge master.

Either way, if someone wants to push for a change in how TO is versioned, it should probably be on the mailing list. There are significant downsides to all of the solutions (including the existing one).

**Comment by rob05c** [comment]
>Why do I get a 401 when I hit api/1.4/user/login agains staging which does not yet have 1.4? You would think that I would get a 404 or 400 bad request

@jrushford There wasn't a great deal of thought put into that response, but it's essentially a security decision: always return unauthorized when a user isn't authorized, regardless whether the endpoint they're trying to hit exists. I wouldn't be opposed to changing it.

**Comment by rob05c** [comment]
@jrushford @mitchell852 @dangogh How would you feel about this solution: what if we made hitting an API version that doesn't exist always return `501 Not Implemented`, and then further changed the TO client to always check for that code, and return it in the error from every client function?

It seems like that would mitigate a lot of the confusion around client/server versions, for people using `master` around the time a version change occurs.

**Comment by rawlinp** [comment]
@rob05c 
> It doesn't work that way. The traffic_ops_golang router will serve all minor endpoints at all newer versions which exist.

So /api/1.4/user/login _will_ work once TO is upgraded to serve at least one other 1.4 route?

**Comment by rob05c** [comment]
@rawlinp Correct. Which it is, in `master`.

**Comment by jrushford** [comment]
I'm +1 on changing it to return 501 Not Implemented.  This way, I wouldn't waste time trying to figure out if the login/password was recently changed.

**Comment by dangogh** [comment]
This sounds like a much better solution to me than switching back the api version used by the client. 
 501 really should be in place for ***all*** endpoints beyond the currently implemented version.   The 401 was totally confusing.

**Comment by mitchell852** [comment]
Obviously the 401 was not correct. I like the 501 suggestion

POST /api/1.9/user/login returns 501 because the 1.9 version has not been implemented in routes.go (i.e. a search of that file yields no hits for 1.9)
POST /api/1.4/user/logins (typo) returns 404 right?

**Comment by rob05c** [comment]
>Obviously the 401 was not correct

I don't agree that is obvious. There's a good argument to always return a 401 or 403, for security reasons, to avoid disclosing information to an attacker, that endpoints exist.

By returning a 400, 404, or 501, we are deliberately sacrificing security for convenience.

**Comment by dangogh** [comment]
that's a big stretch IMO,   but tired of arguing about it.

**Comment by jrushford** [comment]
+1 for 501 response
