### ISSUE TITLE
/api/1.x/cachegroups/{{ID}}/deliveryservices endpoint should have a more informative error message

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2932]
trying to assign a cachegroup with no cache servers to a deliveryservice via the `/api/1.x/cachegroups/{{ID}}/deliveryservices` endpoint returns a 500 response with the body:
```json
{
  "alerts": [
    {
      "text": "Internal Server Error",
      "level": "error"
    }
  ]
}
```
In the debug logs it explains that this is because there aren't any cache servers in the group, so it can't deliver content. However, "Internal Server Error" doesn't really tell you what went wrong.

**Comment by ocket8888** [comment]
Update: it appears to be doing string interpolation with an empty string to create the message; if you specify a CDN that actually doesn't exist in the request, you get back the message `"cdn {{CDN ID}} does not exist"`, which means there's a null/undefined value being coalesced to an empty string at some point.

**Comment by moltzaum** [comment]
```
{
  "alerts": [
    {
      "text": "no edge or origin servers found on cachegroup 473",
      "level": "error"
    }
  ]
}
```

@ocket8888 Is this the response you were hoping for?

**Comment by ocket8888** [comment]
That's much better - though it'd be best to tell me the Cache Group's name, not it's numeric identifier.
