### ISSUE TITLE
/api/1.x/cdns/configs doesn't appear to work properly

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2938]
This endpoint just outputs a list of cdns as name/id pairs like e.g.

```json
{
  "response": [
    {
      "name": "ALL",
      "id": 1
    },
    {
      "name": "CDN-in-a-Box",
      "id": 2
    },
    {
      "name": "foo",
      "id": 7
    }
  ]
}
```

Which, based on the name, doesn't seem like the desired behaviour. Even if it is, the `api/1.x/cdns` endpoint already provides the same information, so maybe we should just get rid of this instead of fixing it?

**Comment by mitchell852** [comment]
remove this route in api 2.x

**Comment by rawlinp** [comment]
closing this as it is deprecated and will no longer be an issue once 1.x is completely removed
