### ISSUE TITLE
/api/1.x/cdns/not_a_number_or_route Gives an Incorrect Error Message

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2939]
If you request that path on a Traffic Ops instance, the response will be

```json
{
	"alerts": [
		{
			"text": "id cannot parse to integer",
			"level": "error"
		}
	]
}
```
with response code 400. The proper response to requesting a route which does not exist is a 404 with the error message "The requested resource could not be found" or similar.

**Comment by mitchell852** [comment]
1.x is going bye bye soon. closing this.
