### ISSUE TITLE
Remove unused 'hack.ttl' parameter from monitoring config endpoint

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2942]
in the "config" object in the `/api/1.x/cdns/{{name}}/configs/monitoring` endpoint response, there's  a key named "hack.ttl" which nobody I've talked to believes has a use anymore. If that's the case, we should get rid of it

**Comment by mitchell852** [comment]
this is working as designed. all the params on a profile are arbitrarily listed in monitoring.json
