### ISSUE TITLE
When cloning DS assignments from one cache to another, target cache list is incomplete

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#2963]
https://tp.domain.net/#!/servers/:id/delivery-services under `More` provides the ability to clone ds assignments from one cache to another, however, the target cache list is incomplete as the dropdown in this view:

![image](https://user-images.githubusercontent.com/251272/47665142-0f9e9b80-db66-11e8-8bbe-e5b552769ee7.png)

is populated via this API call:

`GET api/1.3/servers?type=EDGE`

This is problematic because the system allow the addition of caches types such as:

`EDGE_FOO`

so currently, the targets list is limited to type=EDGE and you can't clone ds assignments from one EDGE_FOO cache to another EDGE_FOO cache.

**Comment by anna-knoll1** [comment]
CDN-3143
