### ISSUE TITLE
Broken endpoint: /api/1.x/deliveryservices/{{ID}}/unavailable_servers

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2973]
This always returns a list of all servers, regardless of assignment to the Delivery Service in question.
The expected behaviour is that it would return a set of servers that is utterly disjoint from what is returned by /api/1.x/deliveryservices/{{ID}}/servers .
Alternatively, we can deprecate the endpoint and label as "wontfix" because I really can't think of a use-case for this.

**Comment by mitchell852** [comment]
1.x is going bye bye soon. closing this.
