### ISSUE TITLE
Possible security issues with tenancy

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#2974]
Currently, we restrict a user who's tenant is not assigned to a Delivery Service (DS) from performing read operations on the configuration of said DS. However, there are no tenancy restrictions on read operations on servers, or their configuration files. Specifically the remap.config, parent.config and plugin.config are all configured on the server (parent.config, remap.config) or profile (plugin.config) level, and provide an unauthorized user with read access into certain properties of a Delivery Service, e.g. the FQDN it serves. It's true that any particular file can't immediately be associated with a particular Delivery Service, but with unrestricted access to all server config files, one could reasonably build up some limited understanding of supposed hidden architecture, albeit without niceties like the xml_id, database row and display name.

**Comment by rob05c** [comment]
Tenancy only applies to Delivery Services. Access to things like servers, parameters, config files, etc, is controlled exclusively by Roles & Capabilities. Capabilities are per-endpoint.

I agree, it's not a very powerful system, but it's what we have right now.

Right now, the solution is to only give Capabilities to those endpoints (servers, configfiles) to users and operators who need them.

**Comment by mitchell852** [comment]
question answered? yes, there was tenancy leakage when TO generated server config files but is that still true now that TO does not generate those config files @ocket8888 @rob05c ?

**Comment by ocket8888** [comment]
Yeah, the specific leakages through config file contents I was talking about are eliminated with the endpoints.

**Comment by mitchell852** [comment]
> Yeah, the specific leakages through config file contents I was talking about are eliminated with the endpoints.

so can u close this?

**Comment by ocket8888** [comment]
I was thinking I might leave it open because there are probably other leaks, but I don't know what they are. So I'd need to go find those and then edit this issue - but I could just as easily open a new issue.
