### ISSUE TITLE
Traffic Router use of obsolete breaks roll back

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#2994]
The following line of code prevent any rollback of traffic router version previous to 3.0.0.

https://github.com/apache/trafficcontrol/blob/ebd05c703c22ae634398838a011f6715b747838b/traffic_router/build/pom.xml#L228

I recommend removing the line as you can't install any previous RPMS by specifying the version number anymore unless you use special command line for yum.

**Comment by jhg03a** [comment]
Does `sudo yum --setopt=obsoletes=0 install traffic_router` help?
