### ISSUE TITLE
Deprecated TO GUI should include a link to associated TP

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3050]
We replaced the old TO GUI with a message that it's been deprecated and to use TP instead.  All our links on that notice refer to the ATC documentation.  We should help our users who are transitioning by providing a link to the new TP url they should use.  This will prevent support teams from being asked what the new URL is repeatedly.

**Comment by jhg03a** [comment]
Looks like originally this was slated to go in but got removed for some reason. #2665

**Comment by mitchell852** [comment]
As far as I recall, #2665 had a link to https://traffic-control-cdn.readthedocs.io/en/latest/overview/traffic_portal.html

which I didn't think was very valuable so it was removed. A link to the actual instance of TP would be useful. I agree.

**Comment by rawlinp** [comment]
Yeah, I wanted a configurable direct link to the associated TP instance in the deprecation header, but I think there was too much back-and-forth about naming the config variable or which one should be used (something along those lines). I would still prefer a configurable TP URL to include in the deprecation header.
