### ISSUE TITLE
Improve the DNSSEC keys refresh API

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#3054]
The current `/api/1.4/cdns/dnsseckeys/refresh` endpoint should be modified/enhanced:
- Return a `202 Accepted` to indicate that the request was received successfully but further processing is occurring in the background.
- The `202` response should also include a link to a separate API endpoint that shows the current status of the `refresh` job that was kicked off (this means also implementing that separate API endpoint)
- The `refresh` endpoint should also be changed to a `PUT` because mutation should not be done in a `GET`.

**Comment by mitchell852** [comment]
Added the major label because GETs that write are dangerous imo.

**Comment by rob05c** [comment]
> The refresh endpoint should also be changed to a POST because mutation should not be done in a GET.

> Added the major label because GETs that write are dangerous imo.

It's not just extremely dangerous and deceptive, it's a violation of the HTTP spec.
