### ISSUE TITLE
Create "Change password on first login" functionality in Traffic Portal

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#3057]
When creating local accounts in traffic portal, you have to create a password for a user.  This password is usually then shared with the user and they are asked to change it.  Traffic Portal should have the ability to force a user to change their password on login. This will make the user creation process more secure and also gives us a way to force users to change their password if need-be.

**Comment by mitchell852** [comment]
you can use the "Register User" function instead. If i recall correctly, you just define the user's email, role and tenant and then it sends an email to the new user with a link. When they follow the link, they can then define their username/password + other info about themselves.

**Comment by limited** [comment]
Beware requiring an email server for account creation. You would not believe the number of times it has been an issue to get access to a Service Provider’s email infrastructure.


—Eric

On Nov 27, 2018, at 4:30 PM, Jeremy Mitchell <notifications@github.com<mailto:notifications@github.com>> wrote:


you can use the "Register User" function instead. If i recall correctly, you just define the user's email, role and tenant and then it sends an email to the new user with a link. When they follow the link, they can then define their username/password + other info about themselves.

**Comment by dneuman64** [comment]
Closing this as abandoned.
