### ISSUE TITLE
Traffic Ops generates bad default parent.config

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3071]
The default parent.config lines generated by Traffic Ops for cache servers sets `round_robin=urlhash`, which isn't valid in Apache Trafficserver versions 4.2-9.0, and so has no conceivable purpose. The code in question ([lines 2604-2613 of ApacheTrafficServer.pm](https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm#L2604-L2613)):
```perl
if ( defined($parent_select_alg) && $parent_select_alg eq 'consistent_hash' ) {
	$default_dest_text .= "dest_domain=. ";
	$default_dest_text .= $parents . $secparents;
	$default_dest_text .= " round_robin=consistent_hash go_direct=false";
}
else {    # default to old situation.
	$default_dest_text .= "dest_domain=. ";
	$default_dest_text .= $parents;
	$default_dest_text .= " round_robin=urlhash go_direct=false";
}
```
this file generation should either be re-written in Go with a valid default (preferable, but risky and time-consuming), or patched with a valid default value (not preferable, but relatively safe).

**Comment by rob05c** [comment]
Related https://github.com/apache/trafficcontrol/issues/2725
