### ISSUE TITLE
TR can not call crState, crConfig endpoint if TM do not use port 80

### ISSUE THREAD

**Issue by jindov** [apache/trafficcontrol#3073]
Hi,
This is my case, I setup TM with another port, for example 82, and in the traffic_monitor.properties file of TR I declare `traffic_monitor.bootstrap.hosts=trafficmonitor.example.com:82`. Then start the TR, the `TrafficMonitorWatcher` show that it can call TM endpoint, but the `PeriodicResourceUpdater` always call the endpoint at port 80, I have to hard code in `/traffic_router/core/src/main/webapp/WEB-INF/applicationContext.xml`:
```
<property name="stateUrl" value="http://trafficmonitor.example.com:82/publish/CrStates" />
<property name="configUrl" value="http://trafficmonitor.example.com:82/publish/CrConfig?json" />
```
and rebuild the rpm.

**Comment by rawlinp** [comment]
What is the TCP Port of your Traffic Monitor servers in Traffic Ops? I think if they are set to 80 in Traffic Ops, your Traffic Router will pick up that 80 from Traffic Ops and use that rather than the `bootstrap` config (which should really just be for bootstrapping the Traffic Router anyways).
