### ISSUE TITLE
Federations page in Traffic Portal won't load for CDNs with no federations

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3076]
If you click on "Manage Federations" in the dropdown menu of a CDN that has no federated Delivery Services, the TO API will return
```http
HTTP/1.1 200 OK
...

{"response":null}\0
```
and visually nothing will happen. This should just show the regular federations page but with no federations currently listed.

**Comment by mitchell852** [comment]
this is due to a bug in the `GET /cdns/:id/federations` endpoint. it should not return null if 0 federations for the cdn. It should return [] instead.

@moltzaum @rob05c  - didn't this get fixed?

**Comment by rob05c** [comment]
https://github.com/apache/trafficcontrol/pull/2857

**Comment by moltzaum** [comment]
This is the PR that should have fixed it #2857
