### ISSUE TITLE
Blank fields incorrectly returns 200 OK when POSTing

### ISSUE THREAD

**Issue by moltzaum** [apache/trafficcontrol#3097]
curl -Lvsk --cookie $mc -XPOST https://localhost:6443/api/1.2/cdns -d @cdn.json
< HTTP/1.1 200 OK
{"alerts":[{"text":"'name' cannot be blank","level":"error"}]}

The same happens for profiles, and I presume other endpoints as well.

`shared_handlers.go:320` looks like it takes the validate errors and returns `http.StatusBadRequest`, which makes me a little confused. This bug causes the profiles api test to fail when it posts a "bad profile" (one without required fields).

**Comment by moltzaum** [comment]
I am on an updated master.
Whoever responds, please try to reproduce the error in case that removes something obvious.

**Comment by moltzaum** [comment]
I deleted the first bracket so that the json is malformed and posted and also got a 200.

**Comment by rawlinp** [comment]
This is possibly going to be fixed by #3098.

**Comment by moltzaum** [comment]
I'll checkout that PR to make sure.

**Comment by moltzaum** [comment]
Fixed by #3098
