### ISSUE TITLE
ATS config file content ordering

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3106]
The following ATS "config" files are generated from TO:

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/lib/API/Configs/ApacheTrafficServer.pm#L344

```
ip_allow.config (GET /api/$version/servers/#id/configfiles/ats/ip_allow.config)
parent.config (GET /api/$version/servers/#id/configfiles/ats/parent.config)
hosting.config (GET /api/$version/servers/#id/configfiles/ats/hosting.config)
remap.config (GET /api/$version/servers/#id/configfiles/ats/remap.config)
astats.config (GET /api/$version/profiles/#id/configfiles/ats/astats.config)
cache.config (GET /api/$version/servers/#id/configfiles/ats/cache.config)
drop_qstring.config (GET /api/$version/profiles/#id/configfiles/ats/drop_qstring.config)
logging.config (GET /api/$version/profiles/#id/configfiles/ats/logging.config)
plugin.config (GET /api/$version/profiles/#id/configfiles/ats/plugin.config)
records.config (GET /api/$version/profiles/#id/configfiles/ats/records.config)
storage.config (GET /api/$version/profiles/#id/configfiles/ats/storage.config)
url_sig_*.config (GET /api/$version/profiles/#id/configfiles/ats/url_sig_*.config)
uri_signing_*.config (GET /api/$version/profiles/#id/configfiles/ats/uri_signing_*.config)
volume.config (GET /api/$version/profiles/#id/configfiles/ats/volume.config)
bg_fetch.config (GET /api/$version/cdns/#id/configfiles/ats/bg_fetch.config)
hdr_rw_*.config (GET /api/$version/cdns/#id/configfiles/ats/hdr_rw_*.config)
regex_remap_*.config (GET /api/$version/cdns/#id/configfiles/ats/regex_remap_*.config)
regex_revalidate.config (GET /api/$version/cdns/#id/configfiles/ats/regex_revalidate.config)
set_dscp_*.config (GET /api/$version/cdns/#id/configfiles/ats/set_dscp_*.config)
ssl_multicert.config (GET /api/$version/cdns/#id/configfiles/ats/ssl_multicert.config)
to_ext_*.config (GET /api/$version/servers/#id/configfiles/ats/to_ext_*.config)
```

For some, the order of the file contents may be important. In this case it is important that multiple calls to the API endpoint that generates the config file returns a consistent content order.

For others, the order of the file contents may NOT be important, however, to utilize diff tools for testing purposes, a consistent content order will help eliminate false positives associated with diffs caused by ordering differences. 

The ask of this issue is to make the order of all of these ATS config files predictable and deterministic while still preserving the generated order if important.

**Comment by ocket8888** [comment]
The files which I believe have important ordering are:

* cache.config
* hosting.config
* ip_allow.config
* parent.config
* plugin.config
* remap.config
* logging.config

Any others should (probably) be sorted lexically. Plugin config files nonwithstanding, of course. Note that ordering in records.config is important if and only if conflicting definitions of the same configuration variable exist - which they should *not*. Also, logging.config being a Lua file should likely be kept the way it is for the moment.

**Comment by rob05c** [comment]
I'd like to request this, and all ATS config file changes, are done in Go, not Perl; unless they're critical bugs.

I've done a great deal of work rewriting the config files in Go, in #3075 and #2991. Every time the Perl changes, it invalidates the Go, and there's so much code—parent.config alone is 1500 lines in Go, and more than that in Perl—it's very difficult to find out what changed and change it appropriately in Go. 

This is the third time I've rewritten the ATS config files in Go. we're never going to get them in Go, if we keep not allocating the work to test and merge them, and keep changing Perl underneath them.

**Comment by ocket8888** [comment]
I wholeheartedly agree with @rob05c

**Comment by mitchell852** [comment]
ok @rob05c i can't argue with that. i opened this issue because i was really trying to satisfy a compare tool that we have that shows false diffs when ordering is different in a config file from one request to the next but i think the compare tool will simply be enhanced to ignore ordering diffs for certain files where ordering is really not important so i'm going to close this issue.

**Comment by rob05c** [comment]
To be clear, I'm not opposed to ordering, just asking to wait until Go.

FWIW I think there are pros and cons of ordering, of making the generation deterministic vs not doing unnecessary things. At the moment, I don't have a strong opinion either way.

>i think the compare tool will simply be enhanced to ignore ordering diffs
+1

**Comment by mitchell852** [comment]
ok, i'll reopen this and we can evaluate where deterministic ordering makes sense and where it does not with the go rewrite of the config file endpoints.

**Comment by mitchell852** [comment]
TO no longer creates config files. closing.
