### ISSUE TITLE
Python TO Client breaks with python 2.7

### ISSUE THREAD

**Issue by rivasj** [apache/trafficcontrol#3112]
The client is supposed to work with python 2.7 and 3.6, but I've come across this syntax error using 2.7:
```
...
from trafficops.tosession import *   File "/.../traffic_control/clients/python/trafficops/trafficops/tosession.py", line 211     raise
restapi.LoginError(msg) from e  
   ^ SyntaxError: invalid syntax
```

**Comment by ocket8888** [comment]
This bug was introduced by PR #3094 I believe. The issue is that `raise a from b` is Python3 syntax.

**Comment by ocket8888** [comment]
Update: it wasn't that PR. That PR is still open.
