### ISSUE TITLE
Read-Only users can create invalidation jobs

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3116]
The endpoint at `api/1.x/user/current/jobs` doesn't check roles if tenancy is enabled - thus any user to whom a Delivery Service is assigned and is also a member of the tenancy which owns said Delivery Service is permitted to create content invalidation jobs. This means that technically, Portal, Steering, Extension, and Monitor users may also create content invalidation jobs, though I think it's more distressing that the ability is given to a user permission group literally named "Read-Only".

**Comment by mitchell852** [comment]
there are many issues with the "read-only" role. pay no attention to it's  name :)

this is one reason I think we need to move to capability-based roles rather than priv level-based roles so it's more explicit what a role provides.
