### ISSUE TITLE
Bad regex for PUT method of /api/1.x/users endpoint

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3117]
Specifically, that endpoint cannot be reached for any API version. One *can* `PUT` to `/api/1.x/users/` or even `/api/1.x/users/.json`. The problem is that the regular expression being matched is `users/{id}?(\.json)?$` but should be `users(/{id})?(\.json)?$`.

**Comment by moltzaum** [comment]
`PUT /api/1.x/users` was never designated to be an endpoint. There is still an issue with the regex. It seems I wanted to write a single regex for the `MethodGet`, so I made the {id} optional. It is better to have two regexs, one where the id is not required and another where it is. The optional {id} should not apply to the PUT, or the delete if it were to be implemented.
```go
{1.4, http.MethodGet, `users/?(\.json)?$`},
{1.4, http.MethodGet, `users/{id}?(\.json)?$`},
{1.4, http.MethodPut, `users/{id}?(\.json)?$`},
{1.4, http.MethodPost, `users/?(\.json)?$`},
```

```go
{1.4, http.MethodGet, `users/?(\.json)?$`},
{1.4, http.MethodGet, `users/{id}$`},
{1.4, http.MethodPut, `users/{id}$`},
{1.4, http.MethodPost, `users/?(\.json)?$`,
```
I'll fix and update the documentation.

**Comment by ocket8888** [comment]
I disagree in the strongest possible terms. There's no reason to require a different endpoint for the method.

**Comment by mitchell852** [comment]
First of all, I think the`.json` is just silly because does our API support anything other than json? but that's another story i guess. 

But I'd say when in doubt just follow the examples already in routes.go so i guess:

```
		{1.4, http.MethodGet, `users/?(\.json)?$`
		{1.4, http.MethodGet, `users/{id}$`
		{1.4, http.MethodPut, `users/{id}$`
		{1.4, http.MethodPost, `users/?$`
```
Also, why is it 1.4? If these are simply rewrites of the Perl routes, it should be 1.1
