### ISSUE TITLE
PUT to /api/1.4/users/{{ID}} is broken

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3118]
There is no payload the endpoint will consider valid for an ID that matches the logged-in user; `role` cannot be blank, but a user cannot modify their own role. Thus, a user cannot modify itself in any way using the `1.4` endpoint.

**Comment by moltzaum** [comment]
Shouldn't you be able to update the role of a user that isn't yourself? That way it isn't blank and not yourself.

A user shouldn't be able to update their own role. If they did, they could accidentally remove their permissions without giving anyone else the power to actually do anything.

**Comment by mitchell852** [comment]
@ocket8888 - let's say i have the operations role and then PUT /api/1.4/users/my-user-id and leave the role as operations, will it work? can i update my own user as long as i don't try to change the role?

**Comment by moltzaum** [comment]
I see the problem now. A user should be able to update themselves as long as they don't change their role. I'll fix it

**Comment by mitchell852** [comment]
an api test to test this scenario would be awesome imo :)
