### ISSUE TITLE
CIAB Trafficmonitor shows a lot of "Request Error: ... service still starting, some caches unpolled"

### ISSUE THREAD

**Issue by Shihta** [apache/trafficcontrol#3138]
I use the latest master branch for building docker images of CDN in a Box.
After start all CIAB services, I can open Trafficmonitor webpage by access http://trafficmonitor.infra.ciab.test/.
The figure is shown as follows:
![2018-12-18 10 34 23](https://user-images.githubusercontent.com/5186176/50129151-b4aa3a80-02b2-11e9-91b6-f8dd2be62db6.png)

However, there are a lot of error messages in the docker log of Trafficmonitor.
I use "docker logs -f CONTAINER_ID" to get Trafficmonitor logs and the figure is shown as follows:
![2018-12-18 10 34 31](https://user-images.githubusercontent.com/5186176/50129158-bb38b200-02b2-11e9-8e81-89c0607f0707.png)

That might be the root cause that Trafficroter not work.
Any idea?

**Comment by Shihta** [comment]
@ezelkow1 
I didn't do any snapshot, so could you share with me some link to guide how to do the "snapshot"?
By the way, should this step be added in CIAB process?

**Comment by dangogh** [comment]
Hi @Shihta ..   this is something we are aware of and are working at.  Please be aware that CIAB is still unstable and is intended for demonstration and testing purposes only.   We ***really*** appreciate reports like this -- it'll help us improve its stability..

**Comment by ezelkow1** [comment]
?To make a snapshot hit the camera looking button at the top right of the UI in traffic portal. Then select your CDN-in-a-Box cdn. That will do the snapshot to store the start the CDN that the router and monitor depend on

________________________________

**Comment by Shihta** [comment]
@ezelkow1 Thanks! it work!

I sent a PR #3160 which some steps of taking snapshot.

**Comment by dangogh** [comment]
fixed by #3169
