### ISSUE TITLE
GET /api/tenants ordering changed from Perl to Go

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3159]
In perl the default ordering of the tenants response looked like this:

```
root
root.1
root.1.1
root.1.2
root.2
root.2.1
root.2.2
```

^^ it was ordered to represent the hierarchy starting with the root tenant

now it appears to be ordered like this:

```
root
root.1
root.2
root.1.1
root.1.2
root.2.1
root.2.2
```

**Comment by dangogh** [comment]
I don't think it is a bug.   The hierarchy is already represented in the structure by the parent of each tenant,  so the order shouldn't be relevant.    It may make it easier in TP to show them in the order they came, but that ordering should be done on the TP side,  not the API.

**Comment by mitchell852** [comment]
I can buy that @dangogh but as the default ordering of the api changes with the rewrite from Perl to Go, we will see "bugs" in TP...

**Comment by dangogh** [comment]
true -- so when endpoints are rewritten,  the affect on TP needs to be considered and perhaps updated to handle the difference.
