### ISSUE TITLE
Cannot update current user with curl

### ISSUE THREAD

**Issue by moltzaum** [apache/trafficcontrol#3168]
I am running into issues updating the current user with curl. The payload I am using has all the required fields, but errors are still returned. I was able to update the current user with traffic portal successfully. Traffic portal uses POST `/user/current/update` instead of PUT `/user/current`, but they work the same since the routes use the same subroutine.

Starting CIAB I used to get this:
> trafficops-perl_1  | + exec tail -f /var/log/traffic_ops/traffic_ops.log
> trafficops-perl_1  | [2018-12-27 20:46:01,718] [ERROR] Can't use an undefined value as a HASH reference at /opt/traffic_ops/app/lib/API/User.pm line 606.
> trafficops-perl_1  | [2018-12-27 20:46:01,730] [ERROR]  

I updated my rpm and no longer get this error but when I first ran into it, it seemed related.

This is what I'm seeing pretty much:
`curl -XPUT --cookie $mc -Lvsk https://localhost:6443/api/1.3/user/current -d @user.json`

```json
{
  "alerts": [
    {
      "level": "error",
      "text": "fullName is required"
    },
    {
      "level": "error",
      "text": "email is required"
    },
    {
      "level": "error",
      "text": "role is required"
    },
    {
      "level": "error",
      "text": "username is required"
    }
  ]
}
```

Since I do not get any errors with traffic portal, it seems the issue might be with my environment somehow.

**Comment by dangogh** [comment]
above you said TP uses `POST` with `user/current`,  but your curl uses `PUT`.  Could that be part of the problem?

**Comment by moltzaum** [comment]
I curled both endpoints. The one I have here is also just short enough to fit on a single line, which is why I chose it. Also, both endpoints use the same subroutine in perl so it isn't the problem.

**Comment by dangogh** [comment]
yes -- verified the problem in CIAB,  but also in another full test environment, so not limited to your environment.   These endpoints are still in Perl, so we should get them implemented in Go rather than trying to fix in Perl.

**Comment by moltzaum** [comment]
Interesting. Do you know what the issue might be, especially if it works with TP still?

**Comment by ocket8888** [comment]
Correct, the `/current` endpoint requires embedding, the others do not. For unknown reasons.

**Comment by ocket8888** [comment]
The Perl implementation of Traffic Ops has been removed, and in the latest API version the top-level "user" property has been eliminated.
