### ISSUE TITLE
Better error message would be nice when validation fails on an FQDN

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3200]
On the TP forms, any fields that validate FQDN format should provide an example when validation fails. I.e. this is a bit confusing

![image](https://user-images.githubusercontent.com/251272/50981963-5f300a80-14b9-11e9-9410-dc7a75a283a6.png)

Even though it might be obvious to some that FQDN doesn't include the protocol, it may not be for others so this message would probably be better:

`Must be a valid FQDN. Example: foo.bar.net`

**Comment by rob05c** [comment]
Could we also make the text box have a label before it, `http:// [____]` ? Seems like that would make the right answer more obvious to users.

**Comment by dneuman64** [comment]
This is resolved in the newest version of TP (4.0)
