### ISSUE TITLE
CIAB: edge server doesn't automatically update config

### ISSUE THREAD

**Issue by Shihta** [apache/trafficcontrol#3207]
Refer to [trafficcontrol/infrastructure/cdn-in-a-box/edge/run.sh](https://github.com/apache/trafficcontrol/blob/master/infrastructure/cdn-in-a-box/edge/run.sh#L76)

Since "crontab -r" removes the cron job, so edge no longer updates its config automatically.
Should this line be removed?
or are there other considerations?

**Comment by ocket8888** [comment]
I think that line was meant to to aid testing and somehow found its way into a commit. We should probably remove that line.

**Comment by ocket8888** [comment]
That was part of the issue, but apparently HTTPS connections need to be specifically enabled using a line in a configuration file specified in a profile parameter - creating a Delivery Service that uses HTTPS does _not_ in any way mean that HTTPS requests can actually be done, apparently.

**Comment by Shihta** [comment]
It has been fixed by #3252
