### ISSUE TITLE
Docker build error on mac 

### ISSUE THREAD

**Issue by felicks** [apache/trafficcontrol#3212]
I'm new to traffic controll and docker. I'm not able to run/build the image on mac. when running  docker-compose up I get the following error: 

`Felixs-MacBook-Pro-2:cdn-in-a-box felixneumann$ docker-compose up
Building trafficrouter
Step 1/11 : FROM centos:7
 ---> 1e1148e4cc2c
Step 2/11 : MAINTAINER Dan Kirkwood
 ---> Using cache
 ---> 56bda4f77237
Step 3/11 : ARG TRAFFIC_ROUTER_RPM=traffic_router/traffic_router.rpm
 ---> Using cache
 ---> b58d28ef2d3c
Step 4/11 : ARG TOMCAT_RPM=traffic_router/tomcat.rpm
 ---> Using cache
 ---> 9e807f8eb138
Step 5/11 : RUN yum -y install epel-release git rpm-build net-tools iproute nc wget tar unzip           perl-JSON perl-WWWCurl which make autoconf automake gcc gcc-c++ apr apr-devel           openssl openssl-devel bind-utils net-tools perl-JSON-PP gettext           java-1.8.0-openjdk-headless java-1.8.0-openjdk-devel &&     yum -y clean all &&     ln -sfv $(find /usr/lib/jvm -type d -name 'java-1.8.0*openjdk*') /opt/java
 ---> Using cache
 ---> 409ce9605b59
Step 6/11 : ADD $TRAFFIC_ROUTER_RPM /traffic_router.rpm
ERROR: Service 'trafficrouter' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder322366122/traffic_router/traffic_router.rpm: no such file or directory`

Did miss some setup steps? Do I need to install the traffic ops rpm?

**Comment by Shihta** [comment]
> traffic_router.rpm: no such file or directory

That means you didn't build the package.
Refer to [here](https://github.com/apache/trafficcontrol/blob/master/docs/source/admin/quick_howto/ciab.rst) for details.

**Comment by felicks** [comment]
thanks @Shihta 

I tried to run `make `
but I got the following error: 

`The build area has been initialized.
Building the rpm.
error: line 21: Tag takes single token only: Release:        Not in git repository and no BUILD_NUMBER present -- aborting!.el7
RPM BUILD FAILED: 1`

**Comment by ocket8888** [comment]
It seems you're running `make` from outside a git repository. Did you clone the repository or download a `.zip` file of the repository's current contents? Our packages are versioned using a git commit ID, so it will fail if run outside a repository (unless you manually specify a BUILD_NUMBER but I highly recommend you avoid that)

**Comment by mitchell852** [comment]
@felicks - can you move this discussion to https://traffic-control-cdn.slack.com. Probably the #general channel. thanks!

**Comment by Shihta** [comment]
@mitchell852 
The slack limits access to only these emails: `@clearcable.ca, @cable.comcast.com, @cisco.com, @ccur.com, @apache.org, @comcast.com, @rci.rogers.com, @videotron.com, @qwilt.com, @sjrb.ca, or @synamedia.com`
How to join it?
