### ISSUE TITLE
Delivery Service Request UI issue when fulfilling a "delete" request

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#3217]
In Traffic Portal, when you fulfill a `delete` Delivery Service Request, the UI takes you back to the `https://tp.example.com/#!/delivery-service-requests` view that shows the table of DSRs, containing the DSR you just fulfilled, except the DSR isn't updated in the table to show that it's been fulfilled. So you need to refresh the page in order for the DSR table to update your DSR to the `pending` status, allowing you to click `complete` in order to complete the DSR.

When you fulfill a `delete` DSR, Traffic Portal should take you back to the `https://tp.example.com/#!/delivery-service-requests` view but *also* refresh the data so that you can complete that DSR without refreshing the page manually.

**Comment by mitchell852** [comment]
@rawlinp - this must have fixed itself. i guess a lot can happen in a year :) You want to confirm and close?

**Comment by rawlinp** [comment]
I just tried in a recent build, and it still has the same issue. Maybe you tried fulfilling a `create` request? This is for `delete`.

**Comment by mitchell852** [comment]
yep, you're right. not sure what i tested earlier :)
