### ISSUE TITLE
Include carton stdout & stderr output in postinstall.log

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3229]
The postinstall perl script doesn't appear to be capturing carton's stdout or stderr in postinstall.log.  This would be immensely helpful when triaging missing perl modules once TO is installed, but only partially functional.

**Comment by mitchell852** [comment]
with the upcoming removal of perl - #5209 - can this be closed @jhg03a ?

**Comment by jhg03a** [comment]
Is postinstall perl gone along with TO perl?  If so, yes.

**Comment by ocket8888** [comment]
Not necessarily, but `carton` will be.

**Comment by jhg03a** [comment]
Sounds good.  Then it can be closed in favor of the perlectomy obsoleting the issue.

**Comment by mitchell852** [comment]
want to add a reference to this issue in #5208 @ocket8888 so it will autoclose this?

**Comment by ocket8888** [comment]
I already did
