### ISSUE TITLE
CIAB: Is there any plan to integrate Traffic Stats?

### ISSUE THREAD

**Issue by Shihta** [apache/trafficcontrol#3242]
Hi guys,
Is there any plan to integrate Traffic Stats into CIAB?
If not, would guys welcome this PR?

**Comment by dangogh** [comment]
YES!   I had planned on doing it and even started the work a while ago.  I'd planned on doing Traffic Stats, Grafana, and Influxdb together,  but other priorities took precedent.

We'd welcome any effort there.   You may want to create a PR with `WIP` (work-in-progress) in the title of the PR to get feedback as you're working on it..

**Comment by Shihta** [comment]
@dangogh 
Sorry that I haven't started anything yet but I think I can work on this part.
Do you think I should follow up your design?
If yes, where can I get them?

By the way, where can I find something like blueprint list?
That can help me to avoid some repetitive work.
Thanks!

**Comment by dangogh** [comment]
@Shihta I have the work I did previously here: https://github.com/dangogh/trafficcontrol/tree/box-stats -- a lot has changed since then,  so I'm sure it's not going to be close to working, but may give you a head-start.   Feel free to ask questions on Slack if you get stuck.

**Comment by dangogh** [comment]
http://trafficcontrol.apache.org/ -- there is a "Community" link at the top with info on Slack

**Comment by Shihta** [comment]
@dangogh After some effort, I have some question for you.

1. I can't create account for slack because it restricts email address. It only accepts `@clearcable.ca, @cable.comcast.com, @cisco.com, @ccur.com, @apache.org, @comcast.com, @rci.rogers.com, @videotron.com, @qwilt.com, @sjrb.ca, or @synamedia.com`. Could you help me to apply for an account?

2. There are some traffic graph in the portal and it need traffic stats to collect data. However, I can't find where is the portal config which can be supplied influxdb or trafficstats address.

3. I create influxdb databases by `create_ts_databases` and than connect traffic stats to influxdb. I found some error logs as follows, any idea?

```
[ERROR] 2019-01-22 08:51:16 Error parsing lastSummaryTime: parsing time "1970-01-01 00:00:00" as "2006-01-02 15:04:05-07": cannot parse "" as "-07"
[ERROR] 2019-01-22 08:51:30 could not unmarshall deliveryservice stats JSON - invalid character 'S' looking for beginning of value
[ERROR] 2019-01-22 08:51:30 could not unmarshall cache stats JSON - invalid character 'S' looking for beginning of value
[ERROR] 2019-01-22 08:51:40 could not unmarshall cache stats JSON - invalid character 'S' looking for beginning of value
[ERROR] 2019-01-22 08:51:40 could not unmarshall deliveryservice stats JSON - invalid character 'S' looking for beginning of value
```

4. Which cache group should traffic stats belong to? Please refer to these 2 lines:
[to-enroll](https://github.com/dangogh/trafficcontrol/commit/76b98946f6b4b5e250578aecd20e814d0f120f81#diff-d5eca03ef461b8122aa82bcf8ac34ff3R59)
[profiles/080-TRAFFIC_STATS.json](https://github.com/dangogh/trafficcontrol/commit/76b98946f6b4b5e250578aecd20e814d0f120f81#diff-e93b3d597e9d941083a60ddb29175038R2)
`to-enroll` set it to `$CDN` but the profile belongs to `ALL`. I'm not sure which one is correct.

Thanks!
