### ISSUE TITLE
Can I add openvpn to CIAB?

### ISSUE THREAD

**Issue by Shihta** [apache/trafficcontrol#3246]
Currently, there are 2 components that helping user to access CIAB network: socksproxy and vnc.
I think openvpn is one of good ways which helps users and developers.
Can I add this component?

**Comment by JBevillC** [comment]
Yeah, I feel openvpn would be useful as it provides an alternative to VNC/SocksProxy for access the private CIAB container network.  Just submit the PR as an `optional/` container.

**Comment by Shihta** [comment]
@JBevillC I have sent the PR (#3257)
Could you help me to review it?
or should I notify other admin?

**Comment by JBevillC** [comment]
@Shihta Yes, I can review the PR.  Apologies for the delay.
