### ISSUE TITLE
ERROR Database load_schema failed

### ISSUE THREAD

**Issue by huyvt5** [apache/trafficcontrol#3251]
I use command sudo /opt/traffic_ops/install/bin/postinstall to install traffic_ops but the following error
"Wed Jan 23 13:19:43 2019: INFO Setting up the database data
Wed Jan 23 13:19:43 2019: ERROR Database load_schema failed
"
I can't find any logs so I don't know where to handle them

**Comment by rivasj** [comment]
The postinstall script will fail in the load_schema phase if the traffic_ops database isn't created beforehand (see step 7 [https://traffic-control-cdn.readthedocs.io/en//latest/admin/traffic_ops/installation.html](url)). Any chance you skipped that step?

**Comment by rivasj** [comment]
Were you able to successfully run postinstall after you verified that your database has been created?

**Comment by huyvt5** [comment]
[root@localhost vagrant]# psql -h localhost -U traffic_ops
Password for user traffic_ops:
psql (9.6.11)
Type "help" for help.

traffic_ops=> \connect traffic_ops
You are now connected to database "traffic_ops" as user "traffic_ops".
traffic_ops=> \l
List of databases
Name | Owner | Encoding | Collate | Ctype | Access privileges
traffic_ops | traffic_ops | UTF8 | en_US.UTF-8 | en_US.UTF-8 |

**Comment by huyvt5** [comment]
up

**Comment by rivasj** [comment]
Hi @huyvt5 

You never answered my question so I wasn't sure how to proceed: 

> Were you able to successfully run postinstall after you verified that your database has been created?

Are you still running into the same issue?

**Comment by mitchell852** [comment]
closing as this should work fine in more recent versions of TC.
