### ISSUE TITLE
Hide ILO password in TP UI by default

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#3258]
Aside from the fact that Traffic Ops is not the best place to store secrets like ILO passwords (something akin to Ansible Vault would be better), we should at least hide the password in the UI by default until the user has checked a "show password" checkbox or something along those lines. This would help prevent passersby from learning the ILO password if an admin/ops user has a server open in TP.

The password is already redacted in the API response if the user is not admin/ops, but I'm not sure we should hide the response and display a "show password" checkbox for only admin/ops users. I think it would be fine to just do it across the board for everyone, even though certain roles will just see `*******` when they check the "show password" box anyways.

When creating/updating a server, the ILO password field should mask the characters as they're entered into the field. This might mean also adding a "confirm ILO password" field so that the user has to enter the password twice to confirm. That field might be unnecessary if we're ok with just allowing the user to select "show password" in order to confirm by reading it.

**Comment by ocket8888** [comment]
Fixed by #6981
