### ISSUE TITLE
Improve JSON diff viewing in Traffic Portal

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#3275]
We should consider using https://github.com/benjamine/jsondiffpatch in order to diff CRConfig snapshots in Traffic Portal. It is MIT-licensed and appears to be a pretty healthy, popular project, so it would seem to be a reasonable dependency for Traffic Portal. We should evaluate its ability to see if it can handle relatively large JSON diffs well.

Right now the CRConfig snapshot diff can be a a bit of a burden to parse through and verify changes in Traffic Portal, and I think integrating this project into the CRConfig snapshot diff would help make diffs much easier to read.

For a live demo: https://benjamine.github.io/jsondiffpatch/demo/index.html

**Comment by rob05c** [comment]
I tried to put a nontrivial CRConfig in their live demo, and it prints `InternalError: too much recursion`.

FWIW I while back, I benchmarked several JSON Patch libraries. The fastest I found was https://github.com/martindale/fast-json-patch

For a CRConfig that took 2358.051ms with our current library, fast-json-patch took 69.208ms.

Maybe we could write a tool to translate JSON Patch format to `jsondiffpatch`'s proprietary format, and then use `fast-json-patch` with their HTML formatter? https://github.com/benjamine/jsondiffpatch/blob/master/docs/formatters.md `jsondiffpatch.formatters.html.format(delta);`

**Comment by rawlinp** [comment]
I think that sounds like a reasonable idea. Maybe we could find a good golang json-patch library to do that server-side via the API then use the jsondiffpatch in Traffic Portal to format it since the json-patching seems like it might be a little heavy to do in javascript?

**Comment by ocket8888** [comment]
I'd like to put forth the suggestion that if the diffs get re-worked they use the HTML5 `<ins>` and `<del>` tags instead of classed `<span>`s.

**Comment by mitchell852** [comment]
I think this all sounds great but I also think one of our problems is the mammoth size of CRconfig.json. Seems like all the server/ds assignments and ds/server assignments is what makes it so huge and problematic.

**Comment by mitchell852** [comment]
fyi, fast-json-patch seems to do the job well/fast so I'm going to rework the snapshot diff to use that. It may result in a different UI experience however, but I think that will be fine.

**Comment by rawlinp** [comment]
That looks good to me and also has the benefit of keeping the diffing functionality in the client as opposed to requiring a new crconfig-diff API endpoint.
