### ISSUE TITLE
Golang endpoints should accept "string integers"

### ISSUE THREAD

**Issue by moltzaum** [apache/trafficcontrol#3304]
```json
{
        "name": "Manchester",
        "division": 1,
        "divisionName": "England"
}
```

The old perl API accepts both integers and strings since it is a dynamic language. In most go endpoints only an integer is accepted.

For instance, the regions endpoint documentation says that the POST supports strings: https://traffic-control-cdn.readthedocs.io/en/latest/api/regions.html
But actually POSTing an "integer string" yields an error message. 

The go endpoints should be able to accept either integer or "string integers" to reduce the likelihood of breaking things that were once supported.

**Comment by rob05c** [comment]
IMO this isn't a bad thing, following the Robustness Principle, but we shouldn't require it for Go endpoints. Perl accepts both because it's "dynamic," but if the API docs define it one way, and Perl returns that, I think it's sufficient to make Go to follow the docs.

It's also going to be a bit of a mess, if we make all Go endpoints accept these for every endpoint, to change every `int` to a custom `JSONIntStr`. Not only in the Server, but it'll make the structs we share with the client awkward, and client users will have to e.g. `int(cdn.ID)` to use them.

**Comment by moltzaum** [comment]
Do you think that it would be possible to avoid using `JSONIntStr` and instead replace `"[0-9]*"` with the number inside the quotes before decoding? Would that break anything?

Another potential solution is to replace `[0-9]` (excluding quotes) with the number now inside quotes. Then the json struct tag can be `",string"` for that field.

**Comment by jhg03a** [comment]
I'm generally an advocate for strong typing.  It prevents problems like the number `b`.  That said, API in my opinion are contracts.  Even if we adapt TP (which is really just a client) to use strong typing, I don't believe it's fair to require all 3rd parties to also adopt strong typing retroactively.  So I vote that we embrace strong typing on API versions and routes/methods where perl has never existed.  That said if we had a perl endpoint with weak types we should downgrade to weak types in Golang.  Also, this doesn't just stop at integers.  Perl used weak types for booleans and probably floats too.

**Comment by rawlinp** [comment]
I believe this was inadvertently closed automatically; this is still an issue with most of the TO Go API.

**Comment by zrhoffman** [comment]
API 1.x should have preserved backwards compatibility with Perl to ensure that any types accepted in Perl were accepted in the TO Go implementation, too, but in API 2.x and above, this behavior is explicitly no longer supporter, and API 1.x is deprecated, pending #5539 being merged.

Closing, feel free to reopen if you feel this warrants further discussion.
