### ISSUE TITLE
TO: Fix Delivery Service endpoint versioning (create V15)

### ISSUE THREAD

**Issue by rivasj** [apache/trafficcontrol#3327]
Need to create new struct DeliveryServiceNullableV13 and move field `ConsistentHashRegex` from that struct to DeliveryServiceNullable struct (V15).

View PR #3286 for discussion on semantic versioning and specifics on what needs to be done.

MUST be completed prior to next release for semantic versioning.

**Comment by mitchell852** [comment]
related to 1.x. closing.
