### ISSUE TITLE
Steering Target form doesn't display 'Steering Delivery Service' value

### ISSUE THREAD

**Issue by rivasj** [apache/trafficcontrol#3328]
Currently, this field is a disabled `select` field that is populated with the list of eligible targets, but given the value of the (parent) delivery service ID, so no value is displayed.

Because this field should always be disabled, it should just be `<input type="text"..>` field with the value of the steering delivery service xmlId.

**Comment by mitchell852** [comment]
so the select is disabled and shows nothing? weird, i'm pretty sure this used to work but yes, i guess, a text input probably makes more sense.

**Comment by rivasj** [comment]
@mitchell852 it looks like the page was designed to be able to assign a target to _any_ eligible steering DS, but since the form is tied directly to a _single_ steering DS, I think that it should be a disabled text input

**Comment by mitchell852** [comment]
since both of those fields are disabled

![image](https://user-images.githubusercontent.com/251272/52815567-3e307b80-305c-11e9-929d-a8bc255493e6.png)

can you change them both to a text input?

if you do that, i think that view would no longer need to make a call to fetch all delivery services.

**Comment by rivasj** [comment]
The "Steering Target" field is only disabled when editing an existing Target -- it is enabled when adding a new Target.

**Comment by mitchell852** [comment]
oh, i see. thanks.
