### ISSUE TITLE
Remove Goose

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3342]
Traffic Ops uses Goose for database migration. Goose is unmaintained, and has been for years. We need to move to a maintained db migration tool. For security, bug fixes, ease of use, etc.

The most difficult part of this will be removing the 1 Go migration we have, which won't be supported by a generic SQL migration tool. It will need to be converted to real SQL. Alternatively, if we "squash" the migrations into the default seeds in a release, including that migration, that may solve the problem (or it may be equally difficult to squash).

**Comment by rawlinp** [comment]
The migrations were recently squashed, so the one Go migration we had is now gone.

**Comment by rawlinp** [comment]
Note: as of https://github.com/apache/trafficcontrol/pull/5699, we are using a maintained fork of `goose`. However, it doesn't seem to be a very popular fork, so we'd probably still prefer to move off of `goose` altogether for something more popular.
