### ISSUE TITLE
Add Traffic Ops API Testing Riak Support

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3348]
Currently, the TO API Tests don't support Riak. This makes it impossible to write integration tests for Riak endpoints. 

We need to add Riak support, so we can test the Riak endpoints.

This may be as simple as adding a few fixtures and configs, or it may be rather difficult. To begin with, someone needs to investigate or prototype it, to find out how much work it's going to be.

**Comment by rob05c** [comment]
See also https://github.com/apache/trafficcontrol/issues/3924

**Comment by rawlinp** [comment]
Closing as we do now have support for this via the `includeSystemTests` option for running the TO API tests. Currently, you can test against the CIAB Riak instance.
