### ISSUE TITLE
Document Traffic Router API Fully

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3352]
The TR API has docs: https://traffic-control-cdn.readthedocs.io/en/latest/development/traffic_monitor/traffic_monitor_api.html

But they're incomplete, and not in a very visible place.

We should add explanations and examples of what they return.

We should also probably put the Router API docs in a more visible place. Maybe create a unified root "APIs" doc page, with links to the APIs of every component?

**Comment by mitchell852** [comment]
@rob05c - the issue title says TR but the link in description is to TM docs. can you fix?

**Comment by rob05c** [comment]
The Traffic Router API has documentation now, and I've been told it's complete:
https://traffic-control-cdn.readthedocs.io/en/latest/development/traffic_router/traffic_router_api.html#tr-api
