### ISSUE TITLE
Update PostgresQL Version

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3362]
Currently TrafficOps uses PostgreSQL 9.6.  Right now, the current major release is PostgreSQL 11.  The final update for PostgreSQL 9.6 will be [November 11, 2021](https://www.postgresql.org/support/versioning/) under the current versioning plan.

**Comment by jhg03a** [comment]
As an update the current major release of PostgreSQL is 12.

**Comment by rawlinp** [comment]
PostgreSQL has been updated to 13 as of https://github.com/apache/trafficcontrol/pull/5630.
