### ISSUE TITLE
Document Static DNS Entries Example

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3374]
We should create a Static DNS Entries page in the How To Guides, explaining how to create and use them.

Example:

In Traffic Portal
1. Navigate to the Delivery Service’s page.
2. Click the “More” button, in the top-right.
3. In the More dropdown, Click “View Static DNS Entries”
4. On the Static DNS Entries page, click the “+” button in the top-right
5. You should now be at the Static DNS Entries creation form, with the following fields:

**Host** the sub-domain to be served at that Delivery Service’s domain. For the CiaB DS, this is `video.demo1.mycdn.ciab.test`. For example, a host of `foo` will create the DNS record `foo.video.demo1.mycdn.ciab.test`.
**Type** the DNS Record type - A, AAAA, CNAME, and TXT are supported.
**TTL** the TTL of the DNS Record.
**Address** the value of the DNS record to serve.

6. After filling out the form and clicking “Create”, Snapshot the CDN.
7. Once the Snapshot propagates to the Router, from within a container on the CiaB Docker Network, you should be able to request the record you created. For example:
```
$ docker exec cdn-in-a-box_trafficvault_1 dig foo.video.demo1.mycdn.ciab.test

;; ANSWER SECTION:
foo.video.demo1.mycdn.ciab.test. 30 IN      A   192.0.2.1.
```

**Comment by ocket8888** [comment]
> _"For example, a host of `foo` will create the DNS record `foo.video.demo1.mycdn.ciab.test`"_

Unless I'm missing something, I don't think that's actually right. I think it'll make a record for `foo.demo1.mycdn.ciab.test`.

**Comment by rob05c** [comment]
You might be right. I was having trouble getting Traffic Stats to build, to make a CiaB to test. We should definitely test before merging.

**Comment by ocket8888** [comment]
I had initially just copied your `dig`, but the new example is something I actually ran, so the output can be trusted.

**Comment by rob05c** [comment]
Excellent. Yeah, my Slack dig was a lie, I couldn't get the CiaB to work so I did a real dig and changed the values >_>
