### ISSUE TITLE
Unable to create multiple delivery service requests

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3378]
1. Set dsRequest.enabled=true in traffic_portal_properties.json
2. Update an existing DS in TP
3. fulfill/complete the ds request
4. update the same DS a 2nd time

doing No. 4 will attempt to create another DS request and will make a call to:

POST api/1.5/deliveryservice_requests

which returns this error:

`{"alerts":[{"text":"'status' complete request cannot be changed","level":"error"}]}`

in fact, even if  your 2nd ds change is another ds change you get the same error.

it seems like "creating a ds request" is somehow invoking the "update a ds request" logic...

**Comment by mitchell852** [comment]
I believe this bug is related to #2886

**Comment by mitchell852** [comment]
If i create 2 ds requests in a row, i've noticed on this line

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/deliveryservice/request/validate.go#L38

the first ds request has req.ID=nil as i would expect as it's a new ds request and should have  no ID
the 2nd ds request has req.ID=something which is unexpected making me think it's a pointer problem

**Comment by moltzaum** [comment]
When I POST to `deliveryservice_requests` I get an internal server error.

```
ERROR: api.go:115: 2019-03-08T18:16:03.3468112Z: 192.168.32.1:57530 panic: (err: runtime error: invalid memory address or nil pointer dereference) stacktrace:
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/routing.stacktrace(0x1256aacc, 0x54dcc0, 0x9150d0)
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/routing.wrapPanicRecover.func1.1(0x663d98, 0x10ea23c0, 0x11474a80)
panic(0x54dcc0, 0x9150d0)
github.com/apache/trafficcontrol/lib/go-tc.(*DeliveryServiceNullable).Sanitize(0x0)
github.com/apache/trafficcontrol/lib/go-tc.(*DeliveryServiceNullable).Validate(0x0, 0x11476aa0, 0x3, 0x4)
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/deliveryservice/request.(*TODeliveryServiceRequest).Validate(0x10c82600, 0x5a8b78, 0x10c82600)
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/api.decodeAndValidateRequestBody(0x11474a80, 0xf66742b0, 0x10c82600, 0x0, 0x0)
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/api.CreateHandler.func1(0x663d98, 0x10ea23c0, 0x11474a80)
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/routing.AuthBase.GetWrapper.func1.1(0x663d98, 0x10ea23c0, 0x11474a80)
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/routing.wrapPanicRecover.func1(0x663d98, 0x10ea23c0, 0x11474a80)
github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/routing.wrapHeaders.func1(0x664db8, 0x10d3d490, 0x11474a80)
net/http.HandlerFunc.ServeHTTP(0x10e8a7e8, 0x664db8, 0x10d3d490, 0x11474a80)
net/http.(*timeoutHandler).ServeHTTP.func1(0x11400980, 0x10ec9fc0, 0x10d3d490, 0x11474a80, 0x116b0980)
created by net/http.(*timeoutHandler).ServeHTTP
```

Inside `deliveryservice/request/validate.go` I can verify that `req.DeliveryService` is nil and return an error to prevent a panic. It appears the decode is not working while not returning errors, but only for the delivery service requests.

I found a TODO in `deliveryservice/request/request_test.go` from 2018-01-22 that says "this section panics when deliveryservice.Validate() tries to get the type name", which isn't quite the same issue, but it is related.

**Comment by moltzaum** [comment]
Meanwhile, it also seems that the Decode is not working for the TODeliveryServiceRequest struct, but it is working for simpler ones like TOCDN. I'm not sure if other structs also have the issue.
