### ISSUE TITLE
Portal: Cannot use "0" as a TTL value for Static DNS entries

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#3400]
This was possible with Traffic Ops although "0" now reports `'ttl' cannot be blank`. TTL of 0 is valid number.

**Comment by rawlinp** [comment]
This seems to be an API validation issue in traffic_ops_golang, rather than form validation in TP. TP allows `0` in the form, but the API returns an error. @smalenfant do you think this should be a backport candidate for 3.0.1?
