### ISSUE TITLE
Cloning a Steering DS from an non-steering DS copies origin URL 

### ISSUE THREAD

**Issue by hbeatty** [apache/trafficcontrol#3403]
Steps followed:

* Open a DS of type HTTP_LIVE_NATNL
* Click ‘More’ button in upper right corner, then select ‘Clone Delivery Service’
* Select ‘Steering’, then ‘Submit’
* Under ‘Content Routing Type’ select ‘CLIENT_STEERING’
* Update the ‘Key(XML ID)’ and ‘Display Name’
* Click ‘Clone’ in the bottom right corner

The result appears to copy the origin URL from the original DS that was cloned, even though a Client Steering DS has no origin URL. This can be seen from the view of all Delivery Services in TP.

I marked this as minor because I'm pretty sure this doesn't cause a break in functionality

**Comment by mitchell852** [comment]
because different types of ds's (HTTP*, DNS*, STEERING*, ANY_MAP) utilize different attributes, maybe it makes more sense to limit cloning where source type = target type.

for example, you can clone a DNS ds to a DNS_LIVE but not a DNS to a STEERING.

**Comment by mitchell852** [comment]
> because different types of ds's (HTTP*, DNS*, STEERING*, ANY_MAP) utilize different attributes, maybe it makes more sense to limit cloning where source type* = target type*.
> 
> for example, you can clone a DNS ds to a DNS_LIVE but not a DNS to a STEERING.

@hbeatty - what do you think of that solution?

**Comment by hbeatty** [comment]
I agree with that. Limiting cloning of type = type makes perfect sense to me.
