### ISSUE TITLE
Anonymous blocking option not available for steering delivery services in portal

### ISSUE THREAD

**Issue by dg4prez** [apache/trafficcontrol#3405]
When anonymous blocking is enabled, all DS types should have the option to be set to block anonymous connections.  It has been observed that steering delivery services do not.

**Comment by mitchell852** [comment]
> When anonymous blocking is enabled

How is it enabled? Is it via a global parameter or something?

**Comment by mitchell852** [comment]
@dg4prez - Currently in TP, you can set the value of anonymousBlockingEnabled for HTTP* delivery services but not for DNS, ANY_MAP or STEERING.

I can add it to STEERING but do you think it needs to be added to DNS as well?

**Comment by mitchell852** [comment]
This will require a TR enhancement to support anonymous blocking on steering* delivery services. It is currently only support in TR for HTTP* delivery services.

**Comment by ocket8888** [comment]
It'll never work for ANY_MAP Delivery Services, and I'm not even sure it'll ever make much sense on DNS Delivery Services either. The IP that makes DNS requests will nearly always be a downstream LDNS server used by the client, and not the client itself. You likely would never see an IP that corresponds to a known proxy or TOR exit node etc. even if that's what the client actually is behind the scenes.

This could possibly be accomplished as an extension to ATS or the configuration file generation process, but it's pretty involved.

AFAIK, though, STEERING is routed via HTTP, so it should be totally possible to implement within Traffic Router.

**Comment by dneuman64** [comment]
This can be closed as fixed.  I added the code in portal and TR to allow Anonymous proxy blocking to be set and enforced for Steering DSs. 

As for DNS DSs, I can see an argument that if you have eDNS0 client subnet extension support enabled then you would know the client IP and can therefore geo block them.  I don't think that we should go through the trouble of adding that support until we have a real use case for it.

**Comment by mitchell852** [comment]
@dneuman64 - do you know which PR added this for steering ds's?
