### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8444

### ISSUE THREAD

**Issue by thanhkm12** [apache/trafficcontrol#3412]
Hello everyone,
Curently, I tried install Traffic Portal 3.0  on Centos7 but failed.
Please help me resolve  above problem.
Thanks!

**Comment by mitchell852** [comment]
You can join our slack channel for questions about installation problems: https://traffic-control-cdn.slack.com/

In that slack instance, you'll find a #dev channel. thanks!
