### ISSUE TITLE
DS deletion in TP doesn't remove certs, keys and csrs from Traffic Vault

### ISSUE THREAD

**Issue by traeak** [apache/trafficcontrol#3434]
When a delivery service is deleted via traffic portal certs, keys and csrs are not removed from traffic vault.  This allows stale data to pile up in traffic vault.

**Comment by rob05c** [comment]
Duplicate of https://github.com/apache/trafficcontrol/issues/882

This is fixed in https://github.com/apache/trafficcontrol/pull/3333

Specifically, it needs to be on Snapshot, because the deleted DS is still being served until the next Snapshot.
