### ISSUE TITLE
After creating a new parameter in Traffic Portal, redirect to the "link profiles" page

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#3453]
What I want to do:
- create a profile parameter and assign it to some existing profiles

What this currently requires in TP:
1. create the profile parameter (page is then redirected to the parameters table)
3. search for parameter that I just created
4. click on parameter that I just created
5. click "View Profiles"
6. click "link profiles to parameter"
7. select profiles that I want to link to

What I think TP should require instead instead:
1. create the profile parameter (page is then redirected to the "link profiles to parameter" view)
2. select profiles that I want to link the new parameter to

This would really streamline the process of creating a parameter and assigning it to one or more profiles, which I think is the most common use case of creating a new parameter.

**Comment by mitchell852** [comment]
done per #3737
