### ISSUE TITLE
Missing fields in TP DS Assignment

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3461]
Looks like Delivery Service fields which use IDs are missing from the UI

Reproduce steps:
1. In Traffic Portal, go to the servers configuration page and select an edge.
2. Under the more section, select "View Delivery Services"

Expected:
I should be able to see the name of the tenant, type, cdn, and maybe signing algorithm.

Actual:
The columns are blank

**Comment by ocket8888** [comment]
any errors in the dev console?

**Comment by jhg03a** [comment]
Not relevant ones.

**Comment by ocket8888** [comment]
Cannot reproduce in master, but issue seems to exist in some v3.0.0-based releases.

**Comment by mitchell852** [comment]
looks like this got fixed somewhere along the line because all ds tables have those columns with values in it.
