### ISSUE TITLE
TO Client: Return status codes for all client functions

### ISSUE THREAD

**Issue by moltzaum** [apache/trafficcontrol#3469]
It would be a good idea to return status codes from client functions to better test the trafficops api. A common use case would be to test for 404s while using `PUT` or `DELETE`.

A part of the underlying argument is that the client should be more versatile.
Related: #3447

There are some instances where we have already returned status codes:
```
client/role.go
33:func (to *Session) CreateRole(region tc.Role) (tc.Alerts, ReqInf, int, error) {
54:func (to *Session) UpdateRoleByID(id int, region tc.Role) (tc.Alerts, ReqInf, int, error) {
76:func (to *Session) GetRoles() ([]tc.Role, ReqInf, int, error) {
92:func (to *Session) GetRoleByID(id int) ([]tc.Role, ReqInf, int, error) {
109:func (to *Session) GetRoleByName(name string) ([]tc.Role, ReqInf, int, error) {
126:func (to *Session) DeleteRoleByID(id int) (tc.Alerts, ReqInf, int, error) {

client/staticdnsentry.go
90:func (to *Session) UpdateStaticDNSEntryByID(id int, sdns tc.StaticDNSEntry) (tc.Alerts, ReqInf, int, error) {
```

**Comment by rob05c** [comment]
We should put the status code in the `ReqInf` object.

**Comment by ocket8888** [comment]
Is this still an issue? I believe

> We should put the status code in the `ReqInf` object. 

has been done

**Comment by rawlinp** [comment]
Yes, this was done by https://github.com/apache/trafficcontrol/pull/5334.
