### ISSUE TITLE
Missing variable declaration in JS files

### ISSUE THREAD

**Issue by MatheusRV** [apache/trafficcontrol#3504]
If a variable is not declared as a local variable, it becomes a global variable by default, which may be unintentional and could lead to unexpected behavior.

In JavaScript, if a variable is used in a function but not declared as a local variable, it becomes a global variable by default. This can have unintended consequences: unlike local variables, global variables can be read and modified by all functions. If different functions use the same global variable, they may end up overwriting each others values, leading to subtle and difficult to diagnose bugs.

Recommendation
Check whether the variable in question was meant to be local; if so, declare it by means of a var declaration. If the variable is really meant to be global, it is best to document this fact by inserting a global var declaration at the beginning of the source file.

[More Info About Issue](https://lgtm.com/projects/g/apache/trafficcontrol/alerts/?mode=tree&ruleFocus=3970086)

**Comment by ocket8888** [comment]
IMO block-scoped variables should always use `let` or `const` as appropriate.

**Comment by mitchell852** [comment]
any examples of where this is occurring?

**Comment by MatheusRV** [comment]
> any examples of where this is occurring?

https://github.com/apache/trafficcontrol/blob/21e50eedf1b824f11869d678fd9439a3d4a73d3c/traffic_monitor/static/index.html#L248
root/traffic_monitor/static/sorttable.js - 32 times

More in https://lgtm.com/projects/g/apache/trafficcontrol/alerts/?mode=tree&ruleFocus=3970086

**Comment by ocket8888** [comment]
I've been meaning to take a run at that sorting script.

By the way, `traffic_monitor`/static/sorttable.js` isn't actually served iirc, and could probably be deleted. I think the `<script>` tag that includes it is commented out.
