### ISSUE TITLE
Order of operations issue with DS Requests

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3512]
I believe there is an order of operations issue in DS Requests.

Perform the following sequence of steps:
1. User A creates a DS request to change LongDesc2
2. Before the DS request is fullfilled, User B updates LongDesc3 and fulfills immediately
3. User B sees an error as well as their change
4. User A sees that their DS Request now includes changes they didn't ask for
5. User B fulfills DS Request from User A
6. User B now sees that their change from 2 is now gone

I believe the correct action is to check for an existing DSR before updating the DS.  The current behavior could lead to accidental deployment/reversion of changes.

**Comment by mitchell852** [comment]
This was fixed with PR #3727 and i confirmed that you cannot create a 2nd ds request when one is currently open.
