### ISSUE TITLE
Fixing user privilege order in Traffic Portal

### ISSUE THREAD

**Issue by tyagian** [apache/trafficcontrol#3519]
When we add a new user to the traffic_portal, there is a Role (privilege level) * field which should have order either from low to high privilege level or high to low. Can we fix it in the future release?

**Comment by ocket8888** [comment]
I think the idea is to move away from roles as just names for an integer describing privilege level and toward true capability separation. 'Course you could still order by e.g. number of granted capabilities.

**Comment by rawlinp** [comment]
@ocket8888 I believe you're right about that, but in the meantime it would probably make sense to order the Role field in Traffic Portal by privilege level. Right now it's all jumbled and not even sorted alphabetically.

**Comment by tyagian** [comment]
Right. I was trying to figure out if anyway it is sorting it. 
I think 
`traffic_portal/app/src/common/modules/form/user/FormUserController.js` and the HTML that calls it is in that same /form/user directory
it does have this `roleService.getRoles({ orderby: 'priv_level DESC' })`
but that isn't working.

**Comment by rawlinp** [comment]
Ah, in that case, I believe the sorting is another case of sorting regressions introduced in the rewrite from Perl to Go. We lost that in a lot of different endpoints, and it appears that the `roles` endpoint has regressed as well.
