### ISSUE TITLE
Traffic Portal build system uses local dependencies

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3527]
Because of how the build system recursively copies the `traffic_portal/` directory, existing `node_modules` and `bower_components` dependencies directories in the locally-copied repo will be pulled into the build environment. This means that conflicting dependency versions can exist - which can cause the build to fail cryptically. Problem is easily fixed by deleting the local resources, but developers might be annoyed by that, so a better solution would be to just either destroy the dependency directories in the build system before running `bower install`/`npm install` or just not copying them in the first place.

**Comment by zrhoffman** [comment]
This was fixed in #4758, which added `git clean -fdX` (force, recursive, remove only gitignored files) to [`clean_build.sh`](https://github.com/apache/trafficcontrol/blob/45dd3c84fb/build/clean_build.sh#L58-L59).
