### ISSUE TITLE
Fix Traffic Ops monitoring.json missing DeliveryServices

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3528]
Traffic Ops `monitoring.json` is missing DeliveryServices. This is mostly ok, because the Monitor is smart enough to copy them in from the CRConfig. But, the CRConfig doesn't have thresholds. So, Delivery Service thresholds are broken, until this is fixed.

It looks like the bug is that the endpoint is only using DS Profiles which are also a Router Profile. See https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/monitoring/monitoring.go#L350

It may be as simple as removing that line, and the join above it.

**Comment by mitchell852** [comment]
severity? minor, medium, major? @rob05c

**Comment by rob05c** [comment]
Eh, it'd be major if it were a regression. But it hasn't worked in ages, if ever. Medium?
