### ISSUE TITLE
TP: Can add an empty cache group fallback

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3533]
When creating or updating a cachegroup, you can add fallback cachegroups, however, if you select "Add failover cachegroup", then you end up with an "empty" cg fallback.

![image](https://user-images.githubusercontent.com/251272/56916096-5b7ac080-6a75-11e9-8ea8-12c2235d10aa.png)

![image](https://user-images.githubusercontent.com/251272/56916118-6a617300-6a75-11e9-87a1-461aada575f5.png)

**Comment by mitchell852** [comment]
I think @mattjackson220 is going to look at this

**Comment by lbathina** [comment]
issue is fixed however, the ```Add Failover cache group...``` should be the default option and blank shouldn't be displayed.

**Comment by mitchell852** [comment]
> issue is fixed however, the `Add Failover cache group...` should be the default option and blank shouldn't be displayed.

@lbathina - i fixed that in this PR #4178
