### ISSUE TITLE
TO: WIll not recognize RIAK servers as available when server state set to REPORTED instead of ONLINE

### ISSUE THREAD

**Issue by jhowell-comcast** [apache/trafficcontrol#3536]
in: 
// GetRiakServers returns the riak servers from the database. The riakPort may be nil, in which case the default port is returned.
func GetRiakServers(tx *sql.Tx, riakPort *uint) ([]ServerAddr, error) {
	rows, err := tx.Query(`
SELECT CONCAT(s.host_name, '.', s.domain_name) FROM server s
JOIN type t ON s.type = t.id
JOIN status st ON s.status = st.id
WHERE t.name = 'RIAK' AND st.name = 'ONLINE'
`)

If the RIAK server is set to REPORTED, TO will treat it as offline. If there's only a single RIAK node in the setup, this will cause all keystore activities to fail with a nil server set returned.

**Comment by rob05c** [comment]
Bug is here:
https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/riaksvc/riak_services.go#L230

Needs to be `(st.name = 'ONLINE' OR st.name = 'REPORTED')`

**Comment by jhg03a** [comment]
Two things that could be done here are:
1. Improve error logging when there are no eligible TO Riak servers, versus all TO Riak servers are legitimately unavailable.
2. Treat REPORTED equivalently to ONLINE and all other statuses equivalent to OFFLINE

**Comment by mitchell852** [comment]
> 2\. Treat REPORTED equivalently to ONLINE and all other statuses equivalent to OFFLINE

@jhg03a - isn't REPORTED a status that only applies to caches? Our infrastructure servers really need to be OFFLINE or ONLINE I think. Unfortunately, we don't really distinguish between cache servers and infrastructure servers.

**Comment by dneuman64** [comment]
Unfortunately our system is build with an ASSUMPTION that REPORTED is for caches and ONLINE for infra servers.  I am closing this since we should just be setting these hosts to ONLINE
