### ISSUE TITLE
TO API can only support up to API minor version ".9"

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#3543]
Because the API version is treated as a float under the hood, I believe we will run into issues once we reach API minor version 1.10, because `1.1 == 1.10`. The underlying implementation should model API versions as a struct of two unsigned integers: 
```
type APIVersion struct {
    Major uint
    Minor uint
}
```

This would have to be refactored before we could possibly support TO API minor version 1.10. We are currently at 1.4, so I believe we have about 5 releases until this will need to be addressed.

**Comment by rawlinp** [comment]
This is a bug, but I've also labelled it as tech debt because the bug will only come back to bite us in the future, assuming we make it to minor version 1.10.

**Comment by mitchell852** [comment]
done
