### ISSUE TITLE
TP: remove Restangular dependency

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3571]
At one point, I added Restangular (https://github.com/mgonto/restangular) to help simplify the TP services (traffic_portal/app/src/common/api), however, many of the services use Restangular and others do not. It might make sense to just remove the dependency on Restangular altogether so the service code can be consistent and one less dependency.

**Comment by ocket8888** [comment]
I could roll this into a branch I was working on where I was stripping out underscore.js - turns out restangular needs underscore.js (actually lodash, but apparently they're nearly the same thing) so that'd be perfect.
