### ISSUE TITLE
Audit, complete and improve TO change log

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3575]
We have X api routes written in Go: https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/routing/routes.go

We have Y api routes written in Perl (that have yet to be rewritten in Go): https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/lib/TrafficOpsRoutes.pm#L394

1. Ensure that all the api routes that modify data (for example, create, update or delete), generate a TO change log (which gets stored in the log table).

2. Ensure that all the change log entries are comprehensive and readable. For example, `Server updates queued for cdn 2` could be better.

(one could argue that we should not touch the Perl routes but i believe this is a pretty easy change to them that will add value. especially, if we find any perl routes that don't create a change log at all. and also, the completion of the perl->go rewrite is still a ways off)

**Comment by Daisykh** [comment]
Taking this one on as far as auditing. Would the wider goal be to aim for all api routes being held to the apache API guidelines? https://cwiki.apache.org/confluence/display/TC/API+Guidelines

**Comment by mitchell852** [comment]
holding all the api routes to the API guidelines would require changing existing routes which would break the contract of the existing API. unfortunately, if api routes were introduced in 1.x that violate the guidelines, they are here to stay for 1.x...unless they were introduced between open source releases...
