### ISSUE TITLE
pkg should return non-zero exit code on failure

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3576]
Currently if any component fails to compile with `pkg -v`, this is treated as silent success.  Instead if any build inside pkg fails pkg should exit with a non-zero exit code.

**Comment by ocket8888** [comment]
What component specifically does this? If I replace Traffic Portal's `build_rpm.sh` script with just `exit 1` then `pkg` exits with code `1` when I try to build it.

**Comment by jhg03a** [comment]
I ran across it while testing a modification in TR that didn't compile.  I ended up with every other RPM in the directory, but the code I have to check the pkg exit code didn't trip with a non-zero response.

**Comment by ocket8888** [comment]
hm. When maven fails to build for me, it exits with a non-zero exit code - might be specific to the 'rpm' maven project. That or maybe the TR build script/container is swallowing errors.

**Comment by jhg03a** [comment]
Can't get this to reproduce
