### ISSUE TITLE
Max DNS Entries should not be included as option for HTTP/Steering Delivery Services

### ISSUE THREAD

**Issue by dsouza93** [apache/trafficcontrol#3648]
Max DNS entries only apply to DNS routed delivery services. Altering this field in traffic portal does not change anything in CRconfig generation for HTTP routed/steering delivery services. Max DNS entries should be removed from the form for HTTP routed delivery services and steering delivery services.

**Comment by mitchell852** [comment]
double-checked. max_dns_answers is only on the DNS delivery service form.
