### ISSUE TITLE
Traffic Stats profile name such as TRAFFIC_STATS_TEST will cause a failure.

### ISSUE THREAD

**Issue by ylev22** [apache/trafficcontrol#3660]
In 
https://traffic-control-cdn.readthedocs.io/en/latest/glossary.html?highlight=TRAFFIC_STATS
there is a recommendation about the name of the Traffic Stats profile, that should/(could) begin with TRAFFIC_STATS.
However, using a name such as TRAFFIC_STATS_TEST will lead to a failure of the relevant component => no stats are collected.

**Comment by mitchell852** [comment]
sounds like documentation needs to be fixed. instead of saying 

`For legacy reasons, the names of Profiles of this type must begin with TRAFFIC_STATS`

should say

`For legacy reasons, the names of Profiles of this type must be TRAFFIC_STATS `
