### ISSUE TITLE
Wrong header rewrite rules with shared origin

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3663]
This is related to #3537 

Steps to reproduce:
1. Configure 2 delivery services with the same base origin url
2. Add a mid header rewrite rule to each that is different
3. Observe the generate remap.config file

Expected:
An error of some kind

Actual:
The the `@pparam=` field only points to the last evaluated delivery service header rewrite file.  No warning or error is provided.

**Comment by jhg03a** [comment]
I'm not sure there can be anything but an error returned here since you can't have multiple remap.config entries for the same parent.

**Comment by mitchell852** [comment]
so if/when #3537 is resolved, this issue goes bye bye?

**Comment by jhg03a** [comment]
Probably

**Comment by mitchell852** [comment]
@jhg03a can we close this as duplicate #3537
