### ISSUE TITLE
Inconsistent parent.config with shared origin

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#3664]
This is related to #3537

Steps to reproduce:
1. Configure 2 delivery services with the same base origin url
2. Set any parameter on the DSs that would be reflected in parent.config differently.  For example qstring or even worse routing type (HTTP/HTTP_LIVE).
3. Observe the generate parent.config file several times over the course of several minutes

Expected:
An error of some kind or consistently wrong behavior in one of the two cases.

Actual:
Depending on how the perl ORM sorts delivery services internally, you will see inconsistent parent.config values between runs.

**Comment by mitchell852** [comment]
so if/when #3537 is resolved, this issue goes bye bye?

**Comment by jhg03a** [comment]
Closing as duplicate of #3537 per @mitchell852
