### ISSUE TITLE
GET api/1.4/users?tenant=1 is returning an empty response

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3679]
https://tp.domain.net/#!/tenants/1/users makes a call to GET api/1.4/users?tenant=1 but the response is empty although tenant 1 (root tenant) has plenty of users assigned to it.

**Comment by mitchell852** [comment]
it appears that the api call needs to look like this

GET api/1.4/users?tenant=root

**Comment by ocket8888** [comment]
This is also a docs problem, since the docs indicate that the `tenant` query parameter takes an integral, unique identifier.

**Comment by dangogh** [comment]
is that a regression from the Perl TO?

**Comment by ocket8888** [comment]
No, the Perl appears to only care about the `tenantId` query param - the `tenant` param is new (I'd bet anything the "CRUDer" gave it for free)
