### ISSUE TITLE
ORT.Py doesn't seem to reload plugin.config correctly

### ISSUE THREAD

**Issue by Shihta** [apache/trafficcontrol#3684]
My test step is as folllows:
1. Start CIAB
2. update edge profile (added remap_stats.so in plugin.config of edge server)
3. after cron triggers ort.py, `/etc/trafficserver/plugin.config` is updated correctly
4. send some request to demo1
5. check astats by `curl "http://edge.infra.ciab.test/_astats?application=&inf.name=eth0"`, there is no `plugin.remap_stats` related information

The plugin.config changes will take effect after manually execute `traffic_ctl server restart` in edge container.

**Comment by ocket8888** [comment]
No, that's proper. The run modes that are used in the CRON jobs are not allowed to restart the server. Applying new plugin changes requires a `BADASS`.

**Comment by Shihta** [comment]
I'm not quite familiar with it. Could you give me more tips?

Take cache container as an example, CRON triggers each job with root permission.
I could add `traffic_ctl server restart --manager` in CRON and it works correctly.
So I guess ORT.py can restart it.
Did I miss anything?

**Comment by ocket8888** [comment]
The ORT run-modes in the CRON file are SYNCDS and REVALIDATE, and those run-modes don't restart ATS. The only run-mode that does that is BADASS. The reason for that is that if you restart ATS every time there's a config update, you'll interrupt any clients who happen to be in the middle of fetching content from them.

The [docs](https://traffic-control-cdn.readthedocs.io/en/latest/development/ort/traffic_ops_ort.html#cmdoption-traffic-ops-ort-arg-mode) have an explanation of the different ORT run-modes.

**Comment by Shihta** [comment]
Thanks for your instructions 👍
