### ISSUE TITLE
Ignoring ADMIN_DOWN/PRE_PROD Cache Servers while setting parent_pending flag

### ISSUE THREAD

**Issue by Vijay-1** [apache/trafficcontrol#3687]
**Test setup:**
Edge Group - one edge(EDGE-1) and its parent group has two Mids (MID-1 and MID-2)
Assign this EDGE-1 to a delivery service DS-1.

**Test Case:** 
ADMIN-DOWN (or PRE_PROD) one of the MIDs (MID-1); Execute ORT in EDGE-1
ORT run fails complaining that its parent is pending.
 
**Reason:**
During ORT run, EDGE-1 uses "/api/1.3/servers/<host-name>/update_status" to deduce whether its parent has executed ORT successfully (upd_pending -> false).This API (traffic_ops_golang's getServerUpdateStatus function in servers_update_status.go) uses a DB query which ignores only the OFFLINE Mids and not the ADMIN_DOWN Mids and hence ORT run in Edge fails saying 
 
Fix:
Rewrite the db query to ignore ADMIN_DOWN MIDS.

**Comment by ocket8888** [comment]
Should it also ignore PRE_PROD servers?

**Comment by Vijay-1** [comment]
I am not very sure about ignoring PRE_PROD. I have never used that state in my set up.  I believe OFFLINE/ONLINE and ADMIN_DOWN are the most frequently used states and that is why we should ignore ADMIN_DOWN. 
Also, i believe, we dont try ORT runs on a PRE_PROD server. Thoughts?

**Comment by ocket8888** [comment]
When `reval_pending` is set when you create a content invalidation job, it ignores cache servers that have specifically the `OFFLINE` or `PRE_PROD`. It should probably ignore `ADMIN_DOWN` too.

I was just thinking it'd be nice for `upd_pending`, `reval_pending` and `parent_pending` to all have the same rules regarding status. TBH, I don't really know what "`PRE_PROD`" means either. But at least some people run ORT on them if `reval_pending` has that rule.

**Comment by mitchell852** [comment]
So this looks like a regression bug that was introduced when this endpoint was rewritten from Perl to Go? GET api/servers/{host_name}/update_status

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/routing/routes.go#L344

**Comment by mitchell852** [comment]
@Vijay-1 - want to submit a PR to add admin_down and/or pre_prod to this sql query? assuming that's the correct fix.

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/server/servers_update_status.go#L52

**Comment by mitchell852** [comment]
nevermind @Vijay-1 - @rob05c beat you to it :)

**Comment by traeak** [comment]
Maybe don't allow any parent proxy to be changed to REPORTED unless the revalidate state is good ?

**Comment by ocket8888** [comment]
There's no rate limit on submitting new invalidation jobs - so it'd be possible for a server to never be put back into `REPORTED` state.

**Comment by traeak** [comment]
If the system is being spammed by invalidation jobs then there are much bigger problems.

**Comment by ocket8888** [comment]
Sure, but that doesn't mean we should compound them. I think that'd wind up just another quirk of the system that nobody really understands or remembers why it exists, but everyone's afraid to change it. We need a better definition of the connection between all these `*_pending` "flags" and a server status.

**Comment by jhg03a** [comment]
So what is the intended behavior in the following scenario:

1 edge + 2 mids (both reported):
1. User requests content A/B which hashes to across both mids
2. Mid 2 is set to ADMIN_DOWN
3. DS Owner submits broad `/.*` invalidation job
4. User re-requests content A/B which this time is hashed across only Mid 1
5. Mid 2 is set back to REPORTED
6. User re-requests content A/B which rehashes back to where it was in step 1

I'm assuming that means the pending flag on Mid 2 is set at this point which means there is a race condition between syncds and revalidate.  I'm also wondering if this ought to trigger a retroactive parent_pending flag on the edges as well, just to prevent this.

**Comment by mitchell852** [comment]
Potentially solved or mitigated with #5117

**Comment by rawlinp** [comment]
Currently, we check `ONLINE/REPORTED/ADMIN_DOWN` caches specifically and ignore all other statuses. I think including `ADMIN_DOWN` is by design, because `ADMIN_DOWN` caches should probably still be able to run ORT. If the cache can't run ORT, it is more likely `OFFLINE` than `ADMIN_DOWN`. If there are "stuck" `ADMIN_DOWN` caches causing revalidations to not propagate, then they should likely be `OFFLINE` instead.
