### ISSUE TITLE
TP: conditionally show 'config files' dropdown item on server page

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3712]
![image](https://user-images.githubusercontent.com/251272/60605868-89cb9380-9d77-11e9-90a7-990746f41381.png)

Currently, config files are only relevant for servers with a profile that has a profile_type of ATS_PROFILE, so it might make sense to hide that menu item otherwise.

**Comment by mitchell852** [comment]
another option would be to simply change the API to return an empty array as it does now but also include an "alert" with level=info or something that says something like "Only servers with a profile of type ATS_PROFILE have config files"

**Comment by ocket8888** [comment]
That sort of depends what you mean by "config file", any Parameter will have that value, and in fact Traffic Ops will happily generate configuration files for servers of any type - even if they're ATS config files (though I think some like parent.config explicitly check for edge vs mid and would therefore break)

**Comment by mitchell852** [comment]
you can't view config files anymore via the TP and the TO API. closing.
