### ISSUE TITLE
Cache groups on dashboard is broken

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3720]
Component: TP - dashboard
Version: 3.0.0-10156.528dd745.el7
Build Date: 2019-07-12 04:25:00OURCE

The list of cache group on dashboard is empty while there are 13 CGs 

(image removed)

**Comment by rawlinp** [comment]
This seems specific to the environment. 2/3 of the environments I checked properly display the cachegroups dashboard. The 3rd environment is returning no cachegroups from the `api/1.2/cdns/health` endpoint, which I believe is the issue in that specific environment.
