### ISSUE TITLE
Traffic ops Api - doesn't handle the invalid values for fallbackId gracefully.

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3724]
Api version: 1.4 
component: Traffic OPS
**Scenario1:** 
Request: 
/api/1.4/cachegroup_fallbacks?cacheGroupId=<<valid cache group id >> &fallbackId=!131
expected: invalid value - list accepted value type
Actual: refer to the screen shot
<img width="1332" alt="Screen Shot 2019-07-15 at 1 52 47 PM" src="https://user-images.githubusercontent.com/26607771/61244609-dd3ec980-a707-11e9-9fc5-1295a4e58972.png">

**Scenario2:** 
/api/1.4/cachegroup_fallbacks?fallbackId=`<<valid id>>`
Expected: all the cachegroup that has fallback id associated with it ?!
actual: 
```
{"alerts":[{"level":"error","text":"Invalid cachegroup id, should be an integer"}]}
```
as per the definition here -> https://traffic-control-cdn.readthedocs.io/en/latest/api/cachegroup_fallbacks.html#id3 the request expects atleast one of the two params.

**Comment by ocket8888** [comment]
fwiw that's not unique to `cachegroup_fallbacks` afaik. Any API endpoint that's still in Perl and calls into UI code (and there are a few of them) has the potential to do this.

**Comment by rawlinp** [comment]
This endpoint should be considered deprecated anyways in favor of the cachegroups API which supports fallbacks now.

**Comment by lbathina** [comment]
I learnt from Jeremy that we are not using this endpoint. If its deprecated, may be we should update the documentation

**Comment by ocket8888** [comment]
well I think to "officially" deprecate something is a mailing list decision - can't leave it up to just the people that happen to see this issue.

**Comment by lbathina** [comment]
while I understand that its a mailing decision, I think this ticket could be the trigger to initiate the process. If not, please do not hesitate to take next necessary steps.

**Comment by ocket8888** [comment]
The only next necessary step is just to send the email, I believe. [Which has been done](https://lists.apache.org/thread.html/77d4793eed8ed0143ac33554278b0b41dc23f15de18f854120fe2b92@%3Cdev.trafficcontrol.apache.org%3E)

**Comment by lbathina** [comment]
thanks!
