### ISSUE TITLE
Creating types dynamically through the API should be limited to type where useintable=server

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3728]
The types table currently has types associated with

- cache groups
- delivery services
- federations
- regexes
- servers
- static dns entries
- steering targets
- TO extensions

as far as i know, only one type of type can be added dynamically - server types. The other types are "static" and would require supporting code changes if new types are introduced.

For example, you can create an EDGE_FOO or MID_FOO type and the system will treat those servers as edges and mids respectively because they start with EDGE or MID.  no code changes required.

however, if you create a DNS_FOO delivery service type, the system can't handle that without code changes.

Therefore, I think the CRUD apis for types should only work if useintable=server. otherwise, you should get back a 400 Bad Request.

**Comment by ocket8888** [comment]
Maybe `server_type` should just be its own thing? Then "Type"s could just be made totally immutable (or done away with entirely).
