### ISSUE TITLE
UI usability: topology->Cachegroup->Parameters - table gets extended beyond the page.

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3734]
topology->Cachegroup->view Parameters 
List of parameters associated with cachegroup gets displayed. The table gets extended beyond the page when the value field is too long. It's annoying from usability perspective. 

![Screen Shot 2019-07-17 at 8 56 54 AM](https://user-images.githubusercontent.com/26607771/61386768-198e3900-a872-11e9-8303-d0f59a5107b3.png)

**Comment by mitchell852** [comment]
@lbathina - this was fixed by PR #3919 - can you confirm and close this issue if fixed?

**Comment by lbathina** [comment]
fixed.
