### ISSUE TITLE
Clone DS Assignment for servers works across CDNs

### ISSUE THREAD

**Issue by dsouza93** [apache/trafficcontrol#3756]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When cloning Delivery Service Assignments from one server to another, the portal allows the user to clone assignments from a server from one CDN, to a server in a different CDN. This is not caught anywhere in the stack and will eventually misconfigure the caches.
## Expected / new behavior:

The servers available for cloning to should only include servers in the same CDN. There should also be checks upstream in TO to not allow servers from one CDN to be assigned to Delivery Services from another CDN

## Minimal reproduction of the problem with instructions:

Simply navigate to a servers configuration page and click on Delivery Services, then click on clone delivery services and select a server from a separate CDN.

**Comment by mitchell852** [comment]
do you plan to write an api test that attempts to clone ds assignments from server in cdn1 to a server in cdn2 and watch it fail or something?
