### ISSUE TITLE
deliveryservice_stats should be accessible to readonly users

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3759]
## I'm submitting a ...
- [ ] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Currently, the `/deliveryservice_stats` endpoint requires permissions of at least the "operator" role. The endpoint is only capable of reading back data, and should thusly be available to all users at the "readonly" level or above (presuming tenancy is satisfied).

(*Currently* the endpoint actually only considers role if the delivery service is not accessible to the tenant - behavior will be changed pending merge of #3758 to no longer override role when tenancy is correct)

## Expected / new behavior:
Simply change the check to look for at least "readonly" privileges.

**Comment by mitchell852** [comment]
> Currently, the /deliveryservice_stats endpoint requires permissions of at least the "operator" role.

Actually, I don't think that's true. It currently requires that either:

a. the ds is assigned to the user or
b. you have the ops or above role

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/API/DeliveryServiceStats.pm#L38

so really, if the ds is assigned to the user, no role is required. 

however, when tenancy was introduced, the ds to user assignment thing was deprecated so really it should have been changed to:

a. the ds is accessible to the user via tenancy
b. you have the ops or above role

also, we used to let your role overrule everything. see `b`. that's no longer true. 2 things should always be checked.

1. do you have the proper role to perform this action? in this case R/O sounds perfect as brennan said
2. do you have access to this ds via tenancy?

**Comment by ocket8888** [comment]
Once it's rewritten to Go tenancy won't override Role - but I suppose that isn't "current" behavior. Bit cocky of me :stuck_out_tongue:

**Comment by mitchell852** [comment]
yeah, role and tenancy are now mutually exclusive. you need to pass BOTH tests when retrieving or performing actions on "tenantable" resources. I believe there are only 4 tenantable resources currently: delivery services, users, origins and tenants.
