### ISSUE TITLE
Specify TLS version support in Traffic Router server.xml

### ISSUE THREAD

**Issue by hbeatty** [apache/trafficcontrol#3764]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When trying to specify one or multiple TLS versions for Traffic Router to allow it is ignored. Currently all TLS versions are used regardless of the configuration in server.xml.

## Expected / new behavior:

The expected behavior would be to allow one to specify which TLS versions should be allowed as referenced in the Tomcat documentation here: https://tomcat.apache.org/tomcat-8.5-doc/ssl-howto.html, https://tomcat.apache.org/tomcat-8.5-doc/config/http.html#SSL_Support and https://support.comodo.com/index.php?/Knowledgebase/Article/View/659/17/how-to----disable-weak-ciphers-in-tomcat-7--8 - Thanks @elsloo 

None of which work. I believe the problem lies here: https://github.com/apache/trafficcontrol/blob/2e6a6797d55ca28310d0c5eb1be5ec592dcc595f/traffic_router/connector/src/main/java/com/comcast/cdn/traffic_control/traffic_router/protocol/RouterNioEndpoint.java#L45 and here: https://github.com/apache/trafficcontrol/blob/2e6a6797d55ca28310d0c5eb1be5ec592dcc595f/traffic_router/connector/src/main/java/com/comcast/cdn/traffic_control/traffic_router/protocol/RouterNioEndpoint.java#L68 To me it looks like the SSL that Tomcat establishes is destroyed and then recreated with the "all" TLS protocols.

## Minimal reproduction of the problem with instructions:

It is possible to test which TLS protocols are availbe by using the command:

```
docker run -it drwetter/testssl.sh:latest -p <delivery_service_url>
```

**Comment by hbeatty** [comment]
We changed this:

https://github.com/apache/trafficcontrol/blob/2e6a6797d55ca28310d0c5eb1be5ec592dcc595f/traffic_router/connector/src/main/java/com/comcast/cdn/traffic_control/traffic_router/protocol/RouterNioEndpoint.java#L68

to:

`sslHostConfig.setProtocols("TLSv1.2");`

Then using the docker statement above we verified that only TLSv1.2 was offered:

```
 Testing protocols via sockets except NPN+ALPN 

 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    offered (OK)
 TLS 1.3    not offered
 NPN/SPDY   not offered
 ALPN/HTTP2 not offered
```

We need to find a way to access the enabled protocols that have to be in a variable already from server.xml

**Comment by smalenfant** [comment]
We were able to change TLS protocols in Traffic Router 2.2 and below.
