### ISSUE TITLE
Rewrite /cdns/{name}/configs/routing to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3782]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/cdns/{{name}}/configs/routing` is handled by Perl

## Expected / new behavior:
`/cdns/{{name}}/configs/routing` should be handled by Go

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

## Anything Else

PR in progress: #2450

**Comment by zrhoffman** [comment]
I am working on this.
