### ISSUE TITLE
Rewrite /servers/{{server}}/configfiles/ats/{{configFile}} to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3783]
## I'm submitting a ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/servers/{{server}}/configfiles/ats/{{configFile}}` is handled by Perl

## Expected / new behavior:
`/servers/{{server}}/configfiles/ats/{{configFile}}` should be handled by Go. This includes behavior for when `server` is an id as well as a hostname, and should encompass all possible files - not just the generic case.

The files that need special handlers are:

- [ ] files matching `to_ext_.*\.config`
- [ ] cache.config
- [ ] chkconfig
- [ ] ip_allow.config
- [ ] hosting.config
- [ ] packages
- [x] parent.config (PR #3075)
- [ ] remap.config

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mhoppa** [comment]
This was done

**Comment by rob05c** [comment]
Yep
