### ISSUE TITLE
Rewrite /divisions/name/{{name}} to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3789]
## I'm submitting a ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/divisions/name/{{name}}` is handled by Perl

## Expected / new behavior:
`/divisions/name/{{name}}` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `DELETE`
- [x] `GET` (#2341)

## Minimal reproduction of the problem with instructions:
N/A

**Comment by rawlinp** [comment]
@ocket8888 for `DELETE`?

**Comment by ocket8888** [comment]
Oh, not for DELETE. But it could easily be added.

**Comment by mitchell852** [comment]
i really like that our "collection" endpoints seem to be supporting both id and name (assuming name is unique). for example:

/divisions?id=27
/divisions?name=foo

not sure why we didn't do that in the first place. :)

**Comment by ocket8888** [comment]
something I'd also like to support is `/divisions?division=1` and `/divisions?division=foo`. But things with numeric names break that with collisions. There's an issue about it.
