### ISSUE TITLE
Rewrite /federations/{{id}}/users/{{userID}} to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3792]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/federations/{{id}}/users/{{userID}}` is handled by Perl

## Expected / new behavior:
`/federations/{{id}}/users/{{userID}}` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `DELETE`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mhoppa** [comment]
This is done via https://github.com/apache/trafficcontrol/pull/4014 can someone please close
