### ISSUE TITLE
Rewrite /hwinfo to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3798]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/hwinfo` is handled by Perl

## Expected / new behavior:
`/hwinfo` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

## Anything Else
A route named `/hwinfo-wip` seems to exist. Progress to completion is unknown.

**Comment by mitchell852** [comment]
take the `-wip` off and it should work :)

**Comment by mhoppa** [comment]
Should we deprecate this?

**Comment by ocket8888** [comment]
Maybe, that's a question for the mailing list. I'd be heavily in favor.
