### ISSUE TITLE
Rewrite /hwinfo/dtdata to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3799]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/hwinfo/dtdata` is handled by Perl

## Expected / new behavior:
`/hwinfo/dtdata` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

## Anything Else
A route named `/hwinfo-wip` seems to exist. Progress to completion is unknown.

**Comment by rawlinp** [comment]
This one seems like a candidate for deprecation/removal (do not rewrite to Go). I think this endpoint was only used by the old Perl UI, but I might be wrong about that.

**Comment by ocket8888** [comment]
I think `hwinfo` in general isn't used, actually. And I'm fine with deprecating it, but "no re-write" is a separate discussion.

**Comment by mitchell852** [comment]
the dtdata makes me think it was used by the old TO UI so `/hwinfo/dtdata` should be deprecated imo (not rewritten to Go and a deprecation notice added to the perl response)
