### ISSUE TITLE
Rewrite /isos to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3801]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/isos` is handled by Perl

## Expected / new behavior:
`/isos` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `POST`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by awilliams** [comment]
Related: #892
