### ISSUE TITLE
Rewrite /jobs/{{id}} to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3803]
## I'm submitting a ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/jobs/{{id}}` is handled by Perl

## Expected / new behavior:
`/jobs/{{id}}` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
deprecate as the new GET job endpoint supports ?id=
