### ISSUE TITLE
Rewrite /user/current/jobs to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3804]
## I'm submitting a ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/user/current/jobs` is handled by Perl

## Expected / new behavior:
`/user/current/jobs` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`
- [ ] `POST`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) because I thought the new jobs endpoints could handle all of this but i could be wrong.
