### ISSUE TITLE
Rewrite /parameters/validate to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3805]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/parameters/validate` is handled by Perl

## Expected / new behavior:
`/parameters/validate` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `POST`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
not sure if this is even used so imo this should be deprecated (not rewritten to Go and a deprecation notice added to the response)
