### ISSUE TITLE
Rewrite /cachegroups/{{parameterID}}/parameter/available to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3811]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/cachegroups/{{parameterID}}/parameter/available` is handled by Perl

## Expected / new behavior:
`/cachegroups/{{parameterID}}/parameter/available` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `GET`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) because not sure it's used anywhere nor do cachegroup params have any effect.
