### ISSUE TITLE
Rewrite /regions/{{region}}/phys_locations to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3812]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/regions/{{region}}/phys_locations` is handled by Perl

## Expected / new behavior:
`/regions/{{region}}/phys_locations` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `POST`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) because GET /phys_locations?regionId=x should get you what you need (need to check that the regionId query param is supported)

**Comment by rawlinp** [comment]
+1 on deprecation
