### ISSUE TITLE
Rewrite /parameters/{{id}}/profiles

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3816]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/parameters/{{id}}/profiles` is handled by Perl

## Expected / new behavior:
`/parameters/{{id}}/profiles` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `GET`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) as you should be able to get this info with GET /profiles?paramId=x (need to check that the paramId works however on the profiles endpoint)

**Comment by rawlinp** [comment]
+1 on deprecation if query param works
