### ISSUE TITLE
Rewrite /parameters/{{id}}/unassigned_profiles to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3817]
## I'm submitting a ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/parameters/{{id}}/unassigned_profiles` is handled by Perl

## Expected / new behavior:
`/parameters/{{id}}/unassigned_profiles` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `GET`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) as:
a) not sure it's used
b) you can get this information in other ways

**Comment by rawlinp** [comment]
agree, +1 on deprecation

**Comment by mhoppa** [comment]
This was addressed in the PR #4337 @rawlinp @ocket8888 @mitchell852  can one of you do the honors of closing this

**Comment by ocket8888** [comment]
Closed by #4337.

FYI when closing multiple issue, they *all* need to be prefixed with a "closing verb". So "fixes #3816 and fixes #3817", not "fixes #3816 and #3817"

**Comment by mhoppa** [comment]
we have had that discussion before havent we 🤦‍♂ probably wont be the last either :P thanks!

**Comment by ocket8888** [comment]
Have we? I remember telling someone, don't remember who. Anyway, no problem.
