### ISSUE TITLE
Rewrite /divisions/{{division}}/regions to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3818]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/divisions/{{division}}/regions` is handled by Perl

## Expected / new behavior:
`/divisions/{{division}}/regions` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `POST`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) as you should be fetching the regions for a division like GET /regions?divisionId=x (but may need to check that the divisionId query param is available on the regions endpoint)

**Comment by rawlinp** [comment]
+1 on deprecation as long as the query param works
