### ISSUE TITLE
Rewrite /regions/name/{{name}} to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3819]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/regions/name/{{name}}` is handled by Perl

## Expected / new behavior:
`/regions/name/{{name}}` should be handled by Go.

### Minimum API Versions
1.1

### Request Methods
- [x] `GET` (#2353)
- [ ] `DELETE`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) as you can do the same thing with GET /regions/{id}

**Comment by zrhoffman** [comment]
Agreed that we don't need to be able to delete by name, but being able to get a region by name could be nice when you don't know its ID.

Both GET and DELETE are undocumented HTTP methods for this route listed in #4290, so both need to be documented before this issue is closed.

**Comment by ocket8888** [comment]
Getting a region by name can be done - I believe - by using the `name` parameter of a request to `/regions`.

**Comment by zrhoffman** [comment]
Right you are. I'm on board to deprecate both `GET` and `DELETE` `/regions/name/{{name}}`.
