### ISSUE TITLE
Rewrite /servercheck/aadata to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3831]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/servercheck/aadata` is handled by Perl

## Expected / new behavior:
`/servercheck/aadata` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
`aadata` is something used by the old TO UI. i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response).

**Comment by ocket8888** [comment]
the decision to either deprecate and/or rewrite the endpoint can't be made here, but once the decision is made this issue can be closed (if appropriate)

**Comment by rawlinp** [comment]
+1 on deprecation
