### ISSUE TITLE
Rewrite /stats_summary/create to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3833]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/stats_summary/create` is handled by Perl

## Expected / new behavior:
`/stats_summary/create` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `POST`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should not rewritten to Go as-is. Instead rewrite it as POST /stats_summary and add a deprecation notice to POST /stats_summary/create

also, find all usages of POST /stats_summary/create in the codebase and change to POST /stats_summary

**Comment by ocket8888** [comment]
the decision to either deprecate and/or rewrite the endpoint can't be made here, but once the decision is made this issue can be closed (if appropriate)

**Comment by rawlinp** [comment]
+1 to the deprecation/rewrite idea
