### ISSUE TITLE
Rewrite /types/trimmed to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3834]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/types/trimmed` is handled by Perl

## Expected / new behavior:
`/types/trimmed` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `GET`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) because:
a. it's weird
b. you can GET /types instead and deal with the extra fields which are few

**Comment by ocket8888** [comment]
the decision to either deprecate and/or rewrite the endpoint can't be made here, but once the decision is made this issue can be closed (if appropriate)

**Comment by rawlinp** [comment]
+1 on deprecation. Specialized endpoints that only return subsets of data from other endpoints are an API smell IMO.
