### ISSUE TITLE
Rewrite /deliveryservice_user to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3836]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/deliveryservice_user` is handled by Perl

## Expected / new behavior:
`/deliveryservice_user` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `POST`

## Minimal reproduction of the problem with instructions:
N/A

## Anything Else
PR in progress: #2457 . Progress to completion is unknown

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) as assigning delivery services to a user has no effect in our current system due to the introduction of tenancy.

**Comment by ocket8888** [comment]
the decision to either deprecate and/or rewrite the endpoint can't be made here, but once the decision is made this issue can be closed (if appropriate)

**Comment by rawlinp** [comment]
+1 on deprecation. If it even does have an affect anywhere, the code should be fixed to where tenant is used over delivery service users.
