### ISSUE TITLE
Rewrite /deliveryservice_user/{{DSID}}/{{userID}} to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3837]
## I'm submitting a ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/deliveryservice_user/{{DSID}}/{{userID}}` is handled by Perl

## Expected / new behavior:
`/deliveryservice_user/{{DSID}}/{{userID}}` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `DELETE`

## Minimal reproduction of the problem with instructions:
N/A

## Anything Else
PR in progress: #2456 . Progress to completion is unknown

**Comment by Daisykh** [comment]
I'm rebasing PR [https://github.com/apache/trafficcontrol/pull/2456](#2456 ) and [https://github.com/apache/trafficcontrol/pull/2457](#2457 )

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to Go and a deprecation notice added to the response) as assigning delivery services to a user has no effect in our current system due to the introduction of tenancy.

**Comment by ocket8888** [comment]
the decision to either deprecate and/or rewrite the endpoint can't be made here, but once the decision is made this issue can be closed (if appropriate)

**Comment by rawlinp** [comment]
+1 on deprecation
