### ISSUE TITLE
Rewrite /user/current/update to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3839]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/user/current/update` is handled by Perl

## Expected / new behavior:
`/user/current/update` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `POST`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
i think this should be deprecated (not rewritten to perl and a deprecation notice added to the response) as this is currently handled by PUT /user/current

**Comment by ocket8888** [comment]
the decision to either deprecate and/or rewrite the endpoint can't be made here, but once the decision is made this issue can be closed (if appropriate)

**Comment by rawlinp** [comment]
+1 on deprecation as long as `PUT /user/current` already does the same thing

**Comment by mhoppa** [comment]
https://github.com/apache/trafficcontrol/pull/3954 already accomplished this. @ocket8888  @mitchell852 @rawlinp  can one of you guys close

**Comment by ocket8888** [comment]
Closed by #3954
