### ISSUE TITLE
Rewrite /to_extensions/{{id}}/delete to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3845]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/to_extensions/{{id}}/delete` is handled by Perl

## Expected / new behavior:
`/to_extensions/{{id}}/delete` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `POST` (yeesh...)

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
for obvious reasons, i don't believe this should be rewritten to Go as-is. maybe create a `DELETE /to_extensions/{{id}}` instead and add a deprecation message to the existing perl api to use the other one.

**Comment by ocket8888** [comment]
the decision to either deprecate and/or rewrite the endpoint can't be made here, but once the decision is made this issue can be closed (if appropriate)

**Comment by rawlinp** [comment]
+1 to not rewriting as-is
