### ISSUE TITLE
Rewrite /cachegroup_fallbacks to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3848]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/cachegroup_fallbacks` is handled by Perl

## Expected / new behavior:
`/cachegroup_fallbacks` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [ ] `GET`
- [ ] `PUT`
- [ ] `POST`
- [ ] `DELETE`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
I think this should be deprecated (not rewritten to perl and a deprecation message added to the response). This can all be handled using the normal cache group CRUD apis.

**Comment by ocket8888** [comment]
the decision to either deprecate and/or rewrite the endpoint can't be made here, but once the decision is made this issue can be closed (if appropriate)

**Comment by rawlinp** [comment]
+1, definitely shouldn't be rewritten. Go cachegroups API supersedes this.

**Comment by mhoppa** [comment]
https://github.com/apache/trafficcontrol/pull/3766 accomplished this @ocket8888 @mitchell852 @ocket8888  can you close this?

**Comment by ocket8888** [comment]
Closed by #3766 - strangely, because that PR was merged before this issue was opened.
