### ISSUE TITLE
Rewrite /cdns/usage/overview to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3850]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/cdns/usage/overview` is handled by Perl

## Expected / new behavior:
`/cdns/usage/overview` should be handled by Go.

### Minimum API Version
1.2

### Request Methods
- [ ] `GET`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by mitchell852** [comment]
I think this should be deprecated (not rewritten). Not sure anyone uses it or if it even works.

**Comment by ocket8888** [comment]
the decision to either deprecate and/or rewrite the endpoint can't be made here, but once it is made this issue can be closed (if appropriate)

**Comment by mitchell852** [comment]
understood. just adding my thoughts.
