### ISSUE TITLE
Rewrite /riak/stats to Go

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#3859]
## I'm submitting an ...
improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Documentation (possibly)
- Traffic Ops

## Current behavior:
`/riak/stats` is handled by Perl

## Expected / new behavior:
`/riak/stats` should be handled by Go.

### Minimum API Version
1.1

### Request Methods
- [x] `GET`

## Minimal reproduction of the problem with instructions:
N/A

**Comment by rawlinp** [comment]
This particular endpoint should be deprecated and not rewritten IMO. I believe this endpoint was primarily for informational/debug purposes during the initial integration of Riak and doesn't really provide much benefit to Traffic Control currently.

**Comment by ocket8888** [comment]
I mean, that's fine by _me_ but I think the general sentiment is we need to re-write **all** of `/api/1.x` before we can remove things.

**Comment by rawlinp** [comment]
I'm not saying to remove it, I'm saying it should be marked deprecated and not rewritten into Go. It will be removed when the rest of the Perl is removed.
