### ISSUE TITLE
TP: Login controls are not shown when 'Unauthorized, please log in.'

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3861]
<img width="1277" alt="Screen Shot 2019-08-09 at 11 21 19 AM" src="https://user-images.githubusercontent.com/26607771/62797041-f1bc7a80-ba97-11e9-8865-480a9e7b79cb.png">

## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

on accessing nightly, Unauthorized, please log in. screen appeared without the login controls.

## Expected / new behavior:

It should show up the login controls to login again.

## Minimal reproduction of the problem with instructions:

 launch of tp

**Comment by mitchell852** [comment]
my guess is there was an incompatible traffic_portal_properties.json that was deployed in your "nightly" environment and probably had something to do with the addition of the oauth property to traffic_portal_properties.json.

**Comment by mitchell852** [comment]
closing as this was an environment problem. the environment where this was tested did not have a compatible traffic_portal_properties.json file with the running version of TP.
