### ISSUE TITLE
TP: table header in CDN Snapshot diff page is screwed up

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3863]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

<img width="1173" alt="Screen Shot 2019-08-12 at 2 33 26 PM" src="https://user-images.githubusercontent.com/26607771/62896449-52ed8380-bd0e-11e9-9ddc-6231678fc737.png">
Appears correct only on General COnfig tab. All other tabs have same issue. 

## Expected / new behavior:

<img width="1137" alt="Screen Shot 2019-08-12 at 2 35 00 PM" src="https://user-images.githubusercontent.com/26607771/62896483-63056300-bd0e-11e9-85e2-fd0a46c72868.png">

## Minimal reproduction of the problem with instructions:

login to TP
click on camera icon on the top right of TP page. 
enter the CDN and submit

## Anything else:

chrome browser v 75.0.3770.100

**Comment by ocket8888** [comment]
What's your browser? And what version thereof?

**Comment by lbathina** [comment]
chrome browser v 75.0.3770.100
