### ISSUE TITLE
TO API ?limit=-1 is not supported

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#3867]
## I'm submitting a ...
- [ ] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Pagination was added to the TO api for some endpoints which allows the user to specify these query params:

- limit
- offset (starts at 1. imo should start at 0 but is what it is)
- page

however, a limit of -1 is not supported. if you want no limit, you can simply leave off the `limit` param but it makes it harder to do programatically. 

GET api/1.4/asns?offset=1&limit=-1 <-- returns an error

## Expected / new behavior:
GET api/1.4/asns?offset=1&limit=-1 <-- should NOT return an error and should return everything.

## Minimal reproduction of the problem with instructions:
GET api/1.4/asns?offset=10&limit=-1 returns an error

**Comment by rawlinp** [comment]
These tests will need to be updated when this issue is fixed, otherwise they will fail since they expect offset=0 to fail: https://github.com/apache/trafficcontrol/pull/3866
