### ISSUE TITLE
Monitoring.json doesn't list the delivery services

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3874]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [X] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

DS list returned in the response of monitoring.json is empty.

## Expected / new behavior:

should return a json with DS list same as the DS list in /api/1.2/cdns/<cdn>/snapshot

## Minimal reproduction of the problem with instructions:

request for /api/1.2/cdns/<cdn>/configs/monitoring.json
compare the DS field with DS field in the response of  endpoint /api/1.2/cdns/<cdn>/snapshot

**Comment by mitchell852** [comment]
i'm a bit confused, does monitoring.json need the `ds` field or not?

**Comment by ocket8888** [comment]
Fixed by #5184
