### ISSUE TITLE
Add the ability to route to a cache using only IPv6

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#3882]
## I'm submitting a ...

- [ ] bug report
- [x] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [x] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Currently you can configure a Delivery Service to allow IPv6 routing, but that is for all caches with an IPv6 address.  We don't have the ability to route using only IPv6 to specific caches.
## Expected / new behavior:

We would be able to configure certain caches to only be routed to using IPv6.  As we deploy more and more caches, we need to sometimes deploy caches that support IPv6 only, so we need to be able to route to them as such.

## Anything else:

We probably also need to take a look at getting #1627 merged in order to support this feature.

**Comment by ocket8888** [comment]
It seems that currently you could just assign your cache servers only IPv6 addresses to accomplish this. Does this problem still exist?

**Comment by rawlinp** [comment]
I'm pretty sure we support routing to IPv6-only caches today, but @dneuman64 please correct me and reopen this if I'm wrong.
