### ISSUE TITLE
TO: Steering endpoint is Not accessible with user that has access privilege greater than steering user

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3885]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Login as a user with no steering role. In my case - I have operations role
access the endpoint   
1. ```/api/1.4/steering/{{id}}```
response got: 404 Not found 
{"alerts":[{"level":"error","text":"Resource not found."}]}

2. However, when accessing the endpoint ```/api/1.4/steering/{{id}}/targets and /api/1.4/steering/{{id}}/targets/{{id}}```
response got: 200 OK 

## Expected / new behavior:

The response for 1 & 2 should have been 200 for user with operations role

**Comment by ocket8888** [comment]
Steering is a permissions role, and Operations is higher than Steering. According to the permissions system we have today, you should be able to access all of those.

**Comment by lbathina** [comment]
can I get list of roles ordered by access?

**Comment by lbathina** [comment]
previledge level greater than steering should have access ? can I assume that?

**Comment by mitchell852** [comment]
![image](https://user-images.githubusercontent.com/251272/63459769-64bbde80-c412-11e9-9ad5-f2ed1f8e76ce.png)

Highest to lowest. A higher role can do everything a lower role can do plus more.

**Comment by mitchell852** [comment]
there is no such route as

`/api/1.4/steering/{{id}}`

the 404 means 1 of 2 things:
1. there is no route that matches that pattern or
2. there is no resource that matches that id

in this case it is the first one. when in doubt, check routes.go (the Go routes) and trafficopsroutes.pm (the perl routes).

**Comment by ocket8888** [comment]
> _"previledge level greater than steering should have access ? can I assume that?"_

Yeah, that's how Roles work today.

**Comment by lbathina** [comment]
my Bad. This can be closed. Not a bug

**Comment by mitchell852** [comment]
> my Bad. This can be closed. Not a bug

no problem.  one would assume if this route exists:

`/api/1.4/steering/{{id}}/targets/{{id}}`

then this one would exist:

``/api/1.4/steering/{{id}}``

but this api likes to make things "interesting". :)
