### ISSUE TITLE
Add a database constraint preventing assigning Servers from one CDN to a DeliveryService on a different CDN.

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3893]
Add a database constraint preventing assigning Servers from one CDN to a DeliveryService on a different CDN.

This is really close to being a bug. It's a data bug for it to happen.

## I'm submitting a ...

- [ ] bug report
- [x] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
You can assign Servers to DSes on different CDNs.

## Expected / new behavior:
Trying to assign a Server to a DS of a different CDN should error. Should be validated at the Database level at the very least, if not also the API and Portal.

## Minimal reproduction of the problem with instructions:
Add a Server on one CDN to a DS on another.

**Comment by ocket8888** [comment]
This is technically a breaking change, right? I think the exact phrase I've heard is "[we] shouldn't hold an upgrade hostage over database state". So I think this needs to go to the mailing list for the whole deprecation process.

**Comment by rawlinp** [comment]
If adding a DB constraint means existing DB violations would make the DB migration fail, then yeah I don't think we can just add a DB constraint. We can however prevent _new_ DB violations via the API. That wouldn't hold the upgrade hostage over the DB state. Or, we in the migration we could just delete the _invalid_ assignments before adding the DB constraint. Either way, I agree it should be discussed on the mailing list.

**Comment by rob05c** [comment]
> "[we] shouldn't hold an upgrade hostage over database state"

Yeah, you're right. We do need to start marking things like this deprecated, so we can add DB constraints 2 major versions later, though.

> via the API

+1

> Deleting data, even invalid data

Er, I'm not suggesting we delete any data. Adding a constraint is good, but yes, we should never delete user data, without explicit explanation and approval.

> it should be discussed on the mailing list

If you all feel the need, sure. I wouldn't think an API constraint would need a discussion, I can't imagine anyone legitimately assigning DS–Servers cross-CDN. It's certainly never worked, ATS and Router config gen will fail with that in all kinds of ways. But I'm not trying to avoid a discussion, if people feel it's necessary.

**Comment by ocket8888** [comment]
> _" I wouldn't think an API constraint would need a discussion"_

It doesn't, necessarily. But I think a DB constraint does merit it.

**Comment by rawlinp** [comment]
+1 on adding an API constraint against invalid input not requiring a mailing list discussion.

**Comment by rawlinp** [comment]
This was added as an API constraint.
