### ISSUE TITLE
Add ability to export server data from Traffic Portal

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#3895]
## I'm submitting a ...
- [ ] bug report
- [x] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Currently the only way to export server data is to copy/paste it out of the portal or to use the API.  Copy/pasting does not give you the ability to control which fields you are exporting, and using the API requires some basic knowledge on scripting/writing code.  Neither of these options are great, we should provide the ability to let a user export server data.  
## Expected / new behavior:

User can export server data to csv.  Traffic Portal would allow them to choose servers from a specific CDN, Cache group, etc as well as letting the user choose which fields they want to export.  This would be useful for external groups that use the Traffic Ops data for other purposes (e.g. network monitoring)

**Comment by ocket8888** [comment]
Does "server data" include associated Profile/Parameters and/or Delivery Service assignments?

**Comment by dneuman64** [comment]
Not as part of this issue, this is more focused on the actual server object

**Comment by mitchell852** [comment]
it's easier to just do this globally for all tables fyi.
