### ISSUE TITLE
fields in DS-> SSL-keys-> generate accept invalid state and city info

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3898]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

DS-> SSL-keys-> generate 
Select United States , enter any junk value for state and city. 
fill all fields and click Generate Keys

keys gets generated
## Expected / new behavior:

State and city should be valid, should be validated.

**Comment by ocket8888** [comment]
New cities are incorporated every day, and "state" should be "state/province/territory" (e.g. Puerto Rico is in the US but isn't a state). I don't think building a database of every territory and city in every country in the world is within the scope of Traffic Control, nor do I think we can - or even want to - maintain such a thing. This behavior is also in line with the behavior of things like user information and physical locations, which do not validate input city/state/province/territory or even country, I believe.

**Comment by mitchell852** [comment]
closing
