### ISSUE TITLE
STEERING location response not listing all targets

### ISSUE THREAD

**Issue by jhowar201** [apache/trafficcontrol#3934]
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

STEERING delivery services are only returning one target from the TR response in location even when configured with multiple targets with equal/differing weight/order.
```{"locations":["https://edge1.origin1.cdn.example.com/?trred=false"]}```

## Expected / new behavior:

Expected that all targets would be listed in the locations response and order is based on target metric as previous versions:
```{"locations":["https://edge1.origin1.cdn.example.com/?trred=false","https://edge1.origin2.cdn.example.com/?trred=false"]}```

## Minimal reproduction of the problem with instructions:

Attempted to change STEERING target weights to various values such as 0, -1 or 50/50 and while the response service in the location changed, it only ever responds with a single service for redirect even when configured for 50/50 weight on 2 targets. 
Confirmed the TR is getting the weights as it sees the changes in the json and picks up the correct values for all targets in its logs. 
Issue occurs when using any target sorting mechanism (WEIGHT vs ORDER etc), response may change but only 1 target is ever listed in location field.
TP/TR Version: 3.0.0-10043.861616b3

## Anything else:

This looks similar to https://github.com/apache/trafficcontrol/issues/3476 but I have confirmed RGB is off on the steering DS as well as its 2 target services when testing.

**Comment by ocket8888** [comment]
Isn't that intentional? I thought you only get a list of locations from CLIENT_STEERING

**Comment by jhowar201** [comment]
Very correct. This is a non-issue as the customer requested the wrong type and I had not noticed it till you pointed it out. Closing to avoid confusion.
