### ISSUE TITLE
Internal Server Error  on create DS with CDN that has DNSSECENABLEd true 

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3937]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

create a CDN with DNSSec Enabled set to true
Create Any type of DS with CDN to be the CDN created in previous step
click on create 

Internal Server Error occurs

## Expected / new behavior:

DS should be created successfully.

**Comment by ocket8888** [comment]
Isn't this a symptom of operation in an environment that doesn't support DNSSEC?

**Comment by lbathina** [comment]
got that info after it was raised.
