### ISSUE TITLE
Add Traffic Monitor gbps calculated stat, for thresholds.

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#3981]
Right now, for bandwidth thresholds, the Monitor has `availableBandwidthInKbps` and `kbps`. For multi-gigabit servers, the Parameters end up being like `60000000`. Hard to keep track of all those zeros. 

It'd be super-easy to add another calculated stat to the Monitor, `gbps`, so you could use a parameter `health.threshold.gbps 4`, which is much easier for Ops to visually verify is correct.

## I'm submitting a ...
- [ ] bug report
- [x] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [x] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Bandwidth thresholds are `kbps` , which has tons of zeros, hard for Ops to manage and verify correct.

## Expected / new behavior:

`gbps` Calculated Stat exists in the Monitor, so operators can use `health.threshold.gbps` as a Threshold.

## Minimal reproduction of the problem with instructions:

Setting `health.threshold.gbps` Parameter in TO works as a TM threshold.

## Anything else:
Not really.

**Comment by rob05c** [comment]
Should be 2 lines, right here: https://github.com/apache/trafficcontrol/blob/49df3d40f76fc5b8d1ed038bb637010d02a41387/traffic_monitor/cache/cache.go#L154

**Comment by vincentalfred** [comment]
I would like to try this issue
Thanks
