### ISSUE TITLE
Ciab Register user returns 500 Internal server error

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#3984]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [X] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [X] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When we try to register a user from CIAB, 500 internal server error is returned
## Expected / new behavior:

User registration should be successful. 

## Minimal reproduction of the problem with instructions:

User Admin-> Users ->Register User-> enter required details-> click send registration

**Comment by ocket8888** [comment]
Underlying problem is no email server is available in CiaB - I'm not sure we want that, either.

**Comment by jhg03a** [comment]
#3997

**Comment by mitchell852** [comment]
@lbathina - please retest this once #3997 is complete
