### ISSUE TITLE
Go client/API integration tests are a bit too verbose

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#4017]
## I'm submitting a ...
- improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- Traffic Control Client (Go)
- Traffic Ops

## Current behavior:
Tests like `CreateTestType` are outputting verbose debug logging by default, using `github.com/apache/trafficcontrol/lib/go-log.Debugln`, which clutters output.

## Expected / new behavior:
Tests should use [`testing.T.Logf`](https://godoc.org/testing#T.Logf) to output verbose debug output, so that it can be turned on and off with the `-v` flag of `go test`.

**Comment by Sacules** [comment]
Hi, I'd like to give this issue a try :)
