### ISSUE TITLE
TP: Compare profiles - should not allow to compare a profile to itself.

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4019]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

The compare profile dropdown displays the profile name selected in one dropdown in other as well. Which allows to compare the profile to itself and update it. 

The update could be introducing issues. The best is to remove the item selected in first dropdown from the other so they are not allowed to compare to itself. 

## Expected / new behavior:

Profiles should not be allowed to compare to itself and update.

**Comment by mitchell852** [comment]
> I think you'll need to add a form validation that disables pressing the "Submit" ("Compare"?) button while the two selected profiles are the same.

That's probably the best solution imo because it's simple.

**Comment by lbathina** [comment]
Goal is not to allow comparison of profile with itself. I agree with oclet8888. That is best and simple solution. Message should be “Choose different profiles to compare” ??

**Comment by lbathina** [comment]
has there been any fix for this? I see that when same profile is choosen we now get profiles are identical messgae

**Comment by mitchell852** [comment]
no, no fix yet. if you select the same profile then it makes sense that you get the "profiles are identical" message because you are comparing a profile to itself.

**Comment by zrhoffman** [comment]
Is #4019 fixed?

**Comment by mitchell852** [comment]
this is really a non-issue. if you don't want to compare a profile to itself then don't. :)
