### ISSUE TITLE
deliveryservice_server_capabilities Doc requires to be fixed with endpoint info 

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4022]
## I'm submitting a ...
- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [X] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
[The documentation](https://traffic-control-cdn.readthedocs.io/en/latest/api/deliveryservice_server_capabilities.html) refers to `deliveryservices_required_capabilities` as deliveryservice_server_capabilities

## Expected / new behavior:

deliveryservice_server_capabilities should be `deliveryservices_required_capabilities`

## Anything else:

Response Type for Delete is  undefined. Should it be object?

**Comment by ocket8888** [comment]
> _"Response Type for Delete is undefined. Should it be object?"_

Assuming the response example is accurate (and I think it is), no. There is no defined `response` object.

**Comment by lbathina** [comment]
may be the doc needs an update. I understand that alerts were included later. first version was just response object and saying response type undefined in that context was right. now the response for the api is one object with has two other objects alerts and response - in this case , it is not undefined.

**Comment by ocket8888** [comment]
No, that's not how the docs work. You should read [the "How to Read this Documentation" section of the API docs](https://traffic-control-cdn.readthedocs.io/en/latest/api/index.html#how-to-read-this-documentation)

**Comment by lbathina** [comment]
thanks. got it. one other the request structure is a table in one section of this doc and is listed in other sec of same doc. will be nice to have it uniform

**Comment by ocket8888** [comment]
No, query parameters go in a table, request bodies are documented as field lists. It is consistent, just looks odd because one method takes only query params and another has none but does have a request body.
