### ISSUE TITLE
Missing DELETE servers in documentation

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4032]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [X] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [X] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

 Missing documentation. DELETE endpoint for servers exists but is not documented.
## Expected / new behavior:

The `DELETE` handler of `servers` endpoint should be documented.
## Minimal reproduction of the problem with instructions:

Link to servers endpoint documentation: https://traffic-control-cdn.readthedocs.io/en/latest/api/servers.html

**Comment by ocket8888** [comment]
Related: #2726 and #3443

**Comment by ZugNZwang** [comment]
Looks like this route was removed. Documentation is no longer necessary.

**Comment by ocket8888** [comment]
... was it though?

**Comment by ZugNZwang** [comment]
I tried making a `DELETE` request to `/servers` and  I got a 404 and `resource not found`
