### ISSUE TITLE
TP, TO: server capabilities are allowed to be assigned to any servers which are not mid or edge

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4038]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Server Capabilities is assignable to any server (like origin)
## Expected / new behavior:

Server Capabilities should be assignable only to edge or mid type servers 
## Minimal reproduction of the problem with instructions:

create server capabilities 
assign it to any server of type other than mid or edge

**Comment by ocket8888** [comment]
That's a good idea, but harder. Because people can create their own types, checking for a cache server typically means checking not for a specific type (or set of types), but for types matching a glob pattern (`*MID*` or `*EDGE*`). It can probably be done, I just don't know offhand if column constraints are allowed to contain subqueries.

**Comment by rob05c** [comment]
Eh, you're right. Postgres check constraints can't reference other tables (the pattern is easy, they do support regexes, it's the other table that's hard).

It's possible with a trigger. But I'm on the fence whether the ugliness and pain of a trigger/function is worth it.

**Comment by mhoppa** [comment]
I can do this issue. I can't assign myself so wanted to post so we dont have duplicate effort.

**Comment by mitchell852** [comment]
@mhoppa - you want to do both the TP and TO API parts? If you do the TP part search for `serverUtils.isCache` that's how i test if a server is a cache or not.

**Comment by mhoppa** [comment]
sure!
