### ISSUE TITLE
There should be a way to correlate logs on the request made. 

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4048]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [X] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

currently we have logs that has timestamps.
However, it wasn't easy and clear to track down the error logs corresponding to a request.

## Expected / new behavior:

We should have some form of correlation between logs to easily and legitimately identify logs corresponding to a specific request. something like trace id or request id or session id
 this can be applicable to all logs of all components.

**Comment by ocket8888** [comment]
requests do have unique identifiers already. Just aren't exposed in logs.

**Comment by rawlinp** [comment]
They're exposed in the info logs, not the access logs (see `reqid`):
```
INFO: routing.go:196: 2019-10-30T12:18:26.893542-06:00: DELETE /api/1.3/cdns/353? handling (reqid 61443)
DEBUG: plugin.go:178: 2019-10-30T12:18:26.893553-06:00: DEBUG plugins.OnRequest calling 0 plugins
DEBUG: shared_handlers.go:295: 2019-10-30T12:18:26.894426-06:00: changelog for delete on object
[::1]:49701 - admin [30/Oct/2019:12:18:26 -0600] "DELETE /api/1.3/cdns/353? HTTP/1.1" 200 81 1 "to-api-v14-client-tests"
INFO: routing.go:199: 2019-10-30T12:18:26.895136-06:00: DELETE /api/1.3/cdns/353? handled (reqid 61443) in 1.583052ms
INFO: routing.go:196: 2019-10-30T12:18:26.8954-06:00: GET /api/1.3/cdns?name=cdn4 handling (reqid 61444)
```
Although, I'm not sure if the `ERROR` log line includes the `reqid`. We could probably prepend it to the error log line if not already. It's fairly easy to trace which requests caused errors if there are no concurrent requests, since the error should be logged between the `handling` and `handled` lines, but that goes out the window if TO-Go is handling concurrent requests.

**Comment by lbathina** [comment]
error and access doesn't have them exposed.

**Comment by srijeet0406** [comment]
Fixed in https://github.com/apache/trafficcontrol/pull/4696
