### ISSUE TITLE
cache_stats endpoint orderby=value returns Internal Server Error

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4054]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [X] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a GET Request to the cache_stats endpoint with `orderby=value` results in an 500: Internal Server Error.
## Expected / new behavior:

Response should have correct ordered values.
## Minimal reproduction of the problem with instructions:

GET
https://{{TO_BASE_URL}}/api/{{api_version}}/cache_stats?cdnName=Kabletown2.0&endDate=2019-10-31T10:44:00-06:00&metricType=bandwidth&startDate=2019-10-30T10:44:00-06:00&orderby=value

**Comment by mitchell852** [comment]
@ZugNZwang - looks like orderby was never supported for this endpoint:

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/app/lib/Extensions/TrafficStats/API/CacheStats.pm#L32-L62

however, it's use before would not return a 500 so i guess this is a regression.
