### ISSUE TITLE
tenant users returned is not filtered list of users belong to the tenant

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4056]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [x] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

https://{{TO_BASE_URL}}/api/{{api_version}}/users?tenantId=5
returns all users without filter on tenant

## Expected / new behavior:

should return only users that are specific to requested tenant

**Comment by ocket8888** [comment]
Alternatively, if that actually never worked and was documented improperly, then just remove it from the list of query parameters. The `tenant` query parameter works fine, and uses names instead of IDs which is much more user-friendly IMO.
