### ISSUE TITLE
Delivery Services ID result return null when doing GET Request for Federations Users

### ISSUE THREAD

**Issue by dandypham** [apache/trafficcontrol#4065]
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
First create a Federation with a Delivery Service on TP. If using TO please do this:
Create a federation POST Request: 
`https://{{TO_BASE_URL}}/api/{{api_version}}/cdns/999/federations`
With this json payload:
```json
{
        "cname": "test.quest.",
        "ttl": 48,
        "description": "A test federation"
}
```
Add Delivery Services to Federations. POST Request:
`https://{{TO_BASE_URL}}/api/{{api_version}}/federations/{{federationsID}}/deliveryservices`
With this json payload:
```json
{
        "dsIds": [1],
        "replace": true
}
```
So now we have a Federations with a Delivery Service. Check again with GET Request:
`https://{{TO_BASE_URL}}/api/{{api_version}}/federations/{{fedID}}/deliveryservices` It will display the CDN connecting to that Delivery Service.
Now add a Users that already connected to a Delivery Services to Federations. POST Request:
`https://{{TO_BASE_URL}}/api/{{api_version}}/federations/{{fedID}}//users`
And now is the error, when return the users information with GET Request:
`https://{{TO_BASE_URL}}/api/{{api_version}}/federations/{{fedID}}//users`
The dsIds will be null.
```json
{
    "response": [
        {
            "dsIds": null,
            "email": null,
            "fullName": null,
            "id": 2,
            "role": "admin",
            "username": "admin"
        }
    ]
}
```
## Expected / new behavior:
When do a GET Request for the users should return format like this:
`https://{{TO_BASE_URL}}/api/{{api_version}}/federations/{{fedID}}//users`
```json
{ "response": [
        {
                "fullName": null,
                "email": null,
                "id": 2,
                "role": "admin",
                "company": null,
                "username": "admin"
        }
]}
```

**Comment by mhoppa** [comment]
Talked to @dandypham on the rewrite the wrong json tag was used for company https://github.com/apache/trafficcontrol/blob/master/lib/go-tc/federation.go#L171.

Needs to be fixed to company. PR coming soon
