### ISSUE TITLE
TP: DS-> Manage Required Capabilities is displayed as Manage Required Server Capabilities

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4069]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

DS-> Manage Required Capabilities is displayed as Manage Required Server Capabilities

in menu as well as the page header

<img width="971" alt="Screen Shot 2019-11-01 at 3 06 30 PM" src="https://user-images.githubusercontent.com/26607771/68056710-6a0e9280-fcb9-11e9-9b36-ba7d8472cb53.png">

## Expected / new behavior:

it should be `Manage Required Capabilities` in context menu and Required Capabilities in bread crumb/header

**Comment by ocket8888** [comment]
Is that really a problem? This page shows the server capabilities required by this Delivery Service on the servers which service it (tongue-twister). So it seems like a fine title, and consistent in the two places it's shown, as you've noted.

**Comment by mitchell852** [comment]
Yeah, I was just trying to be as clear as possible.

`Manage Required Server Capabilities` is more accurate and clear than `Manage Required Capabilities` in the context of a delivery service in my opinion. I would suggest closing this issue if nobody has issue with the added clarity that `Manage Required Server Capabilities` provides.

**Comment by mitchell852** [comment]
@lbathina - can you close unless you have strong feelings about this change.
