### ISSUE TITLE
TO: Server Server capability is not allowed to be removed from a server when its not associated with any DS

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4070]
## I'm submitting a ...
- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
A server which has the Capabilities cap1, cap2, cap3 assigned to Delivery Service that requires Capabilities cap1 and cap2 cannot be dissociated with  cap3:
```http
HTTP/1.1 400 Bad Request
Content-Type: application/json

{ "alerts": [{
    "text": "cannot delete server_capability because it is being used by a server_server_capability",
    "level": "error"
}]}
```
## Expected / new behavior:

deleting cap3 should be allowed as its not a requirement of the only ds that the server is assigned to
response code should be 200

**Comment by mhoppa** [comment]
As talked about this is working as expected and not a bug. Issue should be closed.

The cap is able to be removed from the server just not delete entirely

**Comment by mitchell852** [comment]
yeah, i don't see any reason why in this sceneario cap3 cannot be removed (disassociated) from the server. however, cap3 cannot be deleted entirely as it is in use by the server.

**Comment by mitchell852** [comment]
@lbathina can you close?

**Comment by lbathina** [comment]
Yep. I got mixed up with delete server capabilities. My mistake.
