### ISSUE TITLE
TO: replace is dummy in POST federations/{{ID}}/users 

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4086]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

POST on end point federations/{{ID}}/users
with body 
```json
{
        "userIds": [6],
        "replaces": true
}
```
returns:
```json
{
    "alerts": [
        {
            "text": "1 user(s) were assigned to the TEST. federation",
            "level": "success"
        }
    ],
    "response": {
        "userIds": [
            6
        ],
        "replace": null
    }
}
```
try to post the same again:
it returns following 
```json
{
    "alerts": [
        {
            "text": "federation_tmuser federation, tm_user '1, 6' already exists.",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

on first post replace is null in the return 
on second post either it should respect replace and return same result as first or if we expect the endpoint to behave like this. the parameter replace should be removed. coz it is just dummy.

**Comment by ocket8888** [comment]
I think based on that return that the issue is the handler not properly reading the `replace` field of the input. If that was fixed I'd guess that the rest of the endpoint would work as expected; i.e. respect the `replace` parameter.

**Comment by mhoppa** [comment]
https://traffic-control-cdn.readthedocs.io/en/latest/api/federations_id_users.html#id1 you are using `replaces` in the request body it needs to be `replace`.

**Comment by mhoppa** [comment]
that is why it is not being followed

**Comment by lbathina** [comment]
:( again my mistake.
