### ISSUE TITLE
GET Request TO: /federations success when Federations doesn't exist

### ISSUE THREAD

**Issue by dandypham** [apache/trafficcontrol#4089]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Do not create Federation or Federation Resolver
GET Request : `https://{{TO_BASE_URL}}/api/{{api_version}}/federations`
It will return Status 200 OK 
```
{
    "response": []
}
```
## Expected / new behavior:

Conflict 409 Error

**Comment by ocket8888** [comment]
That's again a question of URI existence versus filtering. If the current user has no assigned federations cannot have any federation resolver delivery service mappings. I don't think an empty array is wrong, per se.

**Comment by mitchell852** [comment]
yes, i think this gets the "as designed" label. If the user calling `GET /federations` has no federations assigned to themselves, the correct response is `200 "response": []`

**Comment by mitchell852** [comment]
i'm going to close this as it's working the way it is supposed to work. please reopen if you don't agree @dandypham
