### ISSUE TITLE
GET Requests: /federations/1231/users success when Federation doesn't exist

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4091]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Do not create Federation. 
GET Request : `https://{{TO_BASE_URL}}/api/{{api_version}}/federations/1231/users`
It will return 200 OK 
```json
{
    "response": []
}
```
## Expected / new behavior:

Should return 404 Not Found

**Comment by ocket8888** [comment]
Shouldn't this be a `404 Not Found` since the requested URI doesn't exist?

**Comment by mhoppa** [comment]
Agreed FWIW PERL endpoint has the same behavior
