### ISSUE TITLE
Delivery Service Required Capability assignment should be restricted to sensible DS types

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4101]
## I'm submitting a ...
- [X] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Delivery Service Capabilities can be assigned to Delivery Services of arbitrary type - although that causes an incorrect error.

## Expected / new behavior
As STEERING, CLIENT_STEERING Delivery Services cannot be assigned servers, and ANY_MAP Delivery Services are not routed by ATC, it makes little sense to require capabilities on them. In particular, this could be confusing on STEERING and CLIENT_STEERING Delivery Services because the capability restriction isn't actually enforced, since it may or may not exist on targets.

Instead, it should only be possible to assign required capabilities to Delivery Services of the types:
- DNS
- DNS_LIVE
- DNS_LIVE_NATNL
- HTTP
- HTTP_LIVE
- HTTP_LIVE_NATNL
- HTTP_NO_CACHE

## Minimal reproduction of the problem with instructions:
1. Choose or create a CLIENT_STEERING Delivery Service
1. Choose or create a capability
1. Assign the capability to the Delivery Service as a Required Capability
1. Observe that the error says that there are servers assigned without this capability, which is nonsensical. This error should not be displayed as there is no way to link server to CLIENT_STEERING DS other than the targets which we have removed. so basically there are no servers associated yet it gives error as if it has something associated.

**Comment by mitchell852** [comment]
are you 100% sure there are not servers assigned to the CLIENT_STEERING DS? Try this:

GET /deliveryservices/{id}/servers where id=CLIENT_STEERING DS's id

**Comment by lbathina** [comment]
although we cannot assign server to a CLIENT_STEERING target from TP, it seems that we could do it via TO. which shouldn't be the case.

**Comment by lbathina** [comment]
thanks jeremy. I am posting our chat in here.
following should be fixed. 

1. should not be able to assign servers to "steering" ds's
2. should not be able to assign DSRC's to "steering" ds's (need to be a discussion how we want DSRC to work for each DS type - this was never defined in first place. requirement gap)

**Comment by mitchell852** [comment]
@lbathina - do you want to just close this issue and create 2 more for those 2 items?

**Comment by lbathina** [comment]
This can be one issue - 2 PR could be submitted against it if its going to be in different PR.

**Comment by mitchell852** [comment]
ok, then i think you need to come up with a new title and description for this issue if you're going to keep it because it's not accurate.

**Comment by lbathina** [comment]
updated the title based on the discussion. We do not want to allow users to assign DSRC to any delivery services other than HTTP* or DNS*

**Comment by mitchell852** [comment]
you might want to clarify what DSRC means for anyone reading this issue that was not involved in the project.

**Comment by lbathina** [comment]
DSRC - delivery service required capabilities

**Comment by ocket8888** [comment]
ANY_MAP s still have assigned servers though, right? Should they be allowed?

**Comment by lbathina** [comment]
As per the discussion, we expect ANY_MAP and STEERING ds not have DSRC assignments. If that's not the case for ANY_MAP, then we need a clear justification - what is the purpose of the DS, what is the expected behaviour of that DS type, what is allowed currently and what is not allowed , why not allowed, what needs to be changed , if cannot be changed why...

**Comment by ocket8888** [comment]
right that's what I'm asking

**Comment by mitchell852** [comment]
I addressed the TP portion for any map in #4202
