### ISSUE TITLE
TP: Delivery Service URLs section shouldn't be displayed for ANY_MAP DS type

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4102]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [X] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

DS page of ANY_MAP type shows the delivery service urls sections 
## Expected / new behavior:

 delivery service urls sections  shoudn't be displayed for ANY_MAP DS type as it has no effect.

**Comment by ocket8888** [comment]
IDK what difference this makes, but those URLs are generated by the API, so technically TP is faithfully portraying what it has received. They still shouldn't be shown; my point is that maybe the API shouldn't generate them.
