### ISSUE TITLE
DS domain can't accessed. DNS wont update.

### ISSUE THREAD

**Issue by riupie** [apache/trafficcontrol#4111]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [x] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

So, I deploy CIAB in a VM for testing its features and how to use it. Lets say I have a website called ucup.infra.ciab.test and I want to create DS so I can access it from http://cdn.ucup.mycdn.ciab.test. What I did, I create Origin via Traffic Portal Configure-->Origins then create DS via Services-->Delivery Services. I can access  the origin server but not with DS.
## Expected / new behavior:

I can access my website via DS.
## Minimal reproduction of the problem with instructions:

This is the log from traffic router:
```1573656929.898 qtype=HTTP chi=172.24.0.8 rhi=- url="http://video.demo1.mycdn.ciab.test/" cqhm=GET cqhv=HTTP/1.1 rtype=GEO rloc="38.89,-77.03" rdtl=- rerr="-" rgb="-" pssc=302 ttms=1.797 rurl="http://edge.demo1.mycdn.ciab.test/" rurls="-" rh="-"
1573656933.294 qtype=HTTP chi=172.24.0.8 rhi=- url="http://video.demo1.mycdn.ciab.test/" cqhm=GET cqhv=HTTP/1.1 rtype=GEO rloc="38.89,-77.03" rdtl=- rerr="-" rgb="-" pssc=302 ttms=0.782 rurl="http://edge.demo1.mycdn.ciab.test/" rurls="-" rh="-"
1573657009.273 qtype=DNS chi=172.24.0.2 rhi=- ttms=0.889 xn=26602 fqdn=cdn.ucup.mycdn.ciab.test. type=A class=IN rcode=NXDOMAIN rtype=- rloc="-" rdtl=- rerr="-" ttl="-" ans="-"
1573657009.279 qtype=DNS chi=172.24.0.2 rhi=- ttms=0.418 xn=50451 fqdn=cdn.ucup.mycdn.ciab.test. type=AAAA class=IN rcode=NXDOMAIN rtype=- rloc="-" rdtl=- rerr="-" ttl="-" ans="-"
1573657721.259 qtype=DNS chi=172.24.0.2 rhi=- ttms=1.081 xn=4228 fqdn=cdn.ucup.mycdn.ciab.test. type=A class=IN rcode=NXDOMAIN rtype=- rloc="-" rdtl=- rerr="-" ttl="-" ans="-"
```

It is like the DNS didnt update the DS domain.

**Comment by ocket8888** [comment]
What are the Delivery Service's XMLID and Display Name? Did you take a CDN Snapshot and then wait about a minute for the Snapshot to propagate?

**Comment by riupie** [comment]
> What are the Delivery Service's XMLID and Display Name? Did you take a CDN Snapshot and then wait about a minute for the Snapshot to propagate?
I did Perform Snapshot from here.
![image](https://user-images.githubusercontent.com/29999878/68817909-c7411580-06b5-11ea-94c7-bb9b328e8899.png)

And this my DS configuration.
![image](https://user-images.githubusercontent.com/29999878/68817847-92cd5980-06b5-11ea-99e1-68e8ffb9e0e7.png)

**Comment by ocket8888** [comment]
Sorry, I asked for the Display Name, but what I meant was the Routing Name. My bad; need that to help figure this out.

**Comment by riupie** [comment]
> Sorry, I asked for the Display Name, but what I meant was the Routing Name. My bad; need that to help figure this out.


Okay, np. This is the routing name.
![image](https://user-images.githubusercontent.com/29999878/68827081-704a3900-06d3-11ea-8a0c-3bc2d19974c2.png)

**Comment by ocket8888** [comment]
Alright, that all looks proper. I'll give it a try myself tomorrow.

**Comment by riupie** [comment]
> Alright, that all looks proper. I'll give it a try myself tomorrow.

okay, I'll wait.

**Comment by ocket8888** [comment]
So I think maybe I see what's going on here: you have it set to serve "HTTP and HTTPS" protocols, but did you generate SSL Keys for it? Because if you snap before making those SSL keys then Traffic Router won't serve it (even over HTTP) and in fact I've seen that actually crash Traffic Router in CDN-in-a-Box.

So restart your CiaB stack and then either

a) try again but this time generate some ssl certificates *before* taking a CDN snapshot or
b) set the protocol to simply "HTTP"

and then try again

**Comment by riupie** [comment]
> So I think maybe I see what's going on here: you have it set to serve "HTTP and HTTPS" protocols, but did you generate SSL Keys for it? Because if you snap before making those SSL keys then Traffic Router won't serve it (even over HTTP) and in fact I've seen that actually crash Traffic Router in CDN-in-a-Box.
> 
> So restart your CiaB stack and then either
> 
> a) try again but this time generate some ssl certificates _before_ taking a CDN snapshot or
> b) set the protocol to simply "HTTP"
> 
> and then try again

Ahh, I see.
Btw, besides add DS I have to add the DS to the edge server manually, right? Since when I only add DS i wont serve and error 503.
![image](https://user-images.githubusercontent.com/29999878/68906448-ddfb7100-0776-11ea-8232-822f9539a00f.png)

Then, how did you find out this crash on Traffic Router, because when I just saw log on access.log I only saw access about traffic.

**Comment by ocket8888** [comment]
yeah, you have to do the server assignment as well. And you have to queue server updates or the caches won't actually serve the traffic once you're routed to them. I found the crash by looking at the TR container logs, not by `exec`-ing into it and reading any certain file. But it doesn't always happen, sometimes the new config just won't load but TR doesn't crash. Haven't nailed down the difference yet.

Anyway, if your issue is solved, feel free to close this.

**Comment by riupie** [comment]
Ok, thank you!

**Comment by phusinh** [comment]
how can i request by qtype dns to the router traffic please reply and give an example thanks

> Ok, thank you!
