### ISSUE TITLE
TO: Error response conflict in deliveryservices_required_capabilities

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4112]
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
When making a `POST` to `/deliveryservices_required_capabilities` with a `requiredCapability` that does not exist and with no servers linked to the same delivery service the error response is:
```http
HTTP/1.1 404 Not Found
Content-Type: application/json

{
    "alerts": [
        {
            "text": "server_capability not found",
            "level": "error"
        }
    ]
}
```
When making a `POST` to `/deliveryservices_required_capabilities` with a `requiredCapability` that does not exist and servers are linked to the same delivery service the error response is:
```http
HTTP/1.1 400 Bad Request
Content-Type: application/json

{
    "alerts": [
        {
            "text": "capability TEST_DISK1 cannot be made required on the delivery service 2 as it has the associated servers 14 that do not have the capability assigned",
            "level": "error"
        }
    ]
}
```
Even though the server capability does not exist.
## Expected / new behavior:
Should return a `404` and same response message.

**Comment by ocket8888** [comment]
Technically, what's it's saying isn't wrong, though I would expect a non-existent capability to be the problem taking precedence.

**Comment by mhoppa** [comment]
yeah agreed not really a bug - more of an improvement.
