### ISSUE TITLE
TO: Can Update a Server's Type after its been assigned to Delivery Service

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4113]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Delivery Service Required Capability is created before any Servers are assigned to a Delivery Service. 
Making a  `POST` Request to `https://{{TO_BASE_URL}}/api/{{api_version}}/deliveryserviceserver` with a server of  type other than `EDGE` is allowed in the API.
Updating that same server: `PUT` `https://{{TO_BASE_URL}}/api/{{api_version}}/servers/{id}/` to Type `EDGE` is allowed. Even though that server does not have the required capability associated to it.
## Expected / new behavior:

1. Should not be allowed to link a server of ANY type to a delivery service, ONLY Edge and Origin
2. Should not be allowed to update a server's type when linked to a delivery service.

**Comment by ocket8888** [comment]
Probably shouldn't ~expose types as a type~ be able to manipulate the Type of a server at all...

**Comment by mitchell852** [comment]
> Probably shouldn't ~expose types as a type~ be able to manipulate the Type of a server at all...

possibly. or at the very least when trying to change the "type" of a server, if the server is assigned to 1 or more delivery services, reject the request.

**Comment by mhoppa** [comment]
I like @mitchell852 request lets start with that and then if we run into other situations where it is causing issues then we can make it more strict.

Ill take this ticket and fix it today

**Comment by rob05c** [comment]
>possibly. or at the very least when trying to change the "type" of a server, if the server is assigned to 1 or more delivery services, reject the request.

+1

We've had cases where we want to repurpose a server, like a Mid to an Edge or vice versa. A Monitor to a Router also makes sense, they have similar hardware requirements. It'd be a pain to have to recreate the whole thing just to change that field.
