### ISSUE TITLE
TO: Deleting a Delivery Service Required Capability that does not exist returns incorrect error

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4115]
## I'm submitting a ...
- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
A `DELETE` Request to `https://{{TO_BASE_URL}}/api/{{api_version}}/deliveryservices_required_capabilities` with a valid `deliveryServiceID` and with a `requiredCapability` value that does not exist returns:
```http
HTTP/1.1 403 Forbidden
Content-Type: application/json

{
    "alerts": [
        {
            "text": "not authorized on this tenant",
            "level": "error"
        }
    ]
}
```
Applies to Admin and Operator Role with the same tenancy as the delivery service or with the parent tenancy of the delivery service.
## Expected / new behavior:
Should Return:
```http
HTTP/1.1 404 Not Found
Content-Type: application/json

{
    "alerts": [
        {
            "text": "no deliveryservice.RequiredCapability with that key found error",
            "level": "error"
        }
    ]
}
```

**Comment by ocket8888** [comment]
I can't replicate this. I have no Server Capabilities created in my CDN-in-a-Box and I got this:
```http
DELETE /api/1.4/deliveryservices_required_capabilities?deliveryServiceID=1&requiredCapability=any HTTP/1.1
User-Agent: python-requests/2.22.0
Accept-Encoding: gzip, deflate
Accept: */*
Connection: keep-alive
Cookie: mojolicious=...
Content-Length: 0
```
which gets this as a response:
```http
HTTP/1.1 404 Not Found
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Set-Cookie, Cookie
Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Content-Type: application/json
Set-Cookie: mojolicious=...; Path=/; HttpOnly
X-Server-Name: traffic_ops_golang/
Date: Thu, 14 Nov 2019 22:53:15 GMT
Content-Length: 112

{
	"alerts": [
		{
			"text": "no deliveryservice.RequiredCapability with that key found",
			"level": "error"
		}
	]
}
```
So what I have to ask is: are you sure your tenant has permissions to access that Delivery Service?

**Comment by ZugNZwang** [comment]
Sorry. I just did some more testing. This only happens when using a `deliveryServiceId` that the  user's tenancy does not have access to. So the message is correct. It ignores the `requiredCapability` parameter since it cannot access the `deliveryServiceId`.

**Comment by ocket8888** [comment]
:+1: got it
