### ISSUE TITLE
TO: Can link Edge Server, w/o Required Capabilities, to Delivery Service

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4123]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `POST` Request to `https://{{TO_BASE_URL}}/api/{{api_version}}/deliveryservices/{{xml_id}}/servers` 
Where the associated delivery service has a required capability assigned,
and Edge Server has no server capabilities. It is allowed and returns no errors
```http
HTTP/1.1 200 OK
Content-Type: application/json

{
    "response": {
        "serverNames": [
            "testEdgeServer"
        ],
        "xmlId": "test"
    }
}
```

## Expected / new behavior:

Should not allow Edge Server missing required capabilities to be assigned to delivery service
```http
HTTP/1.1 400 Bad Request
Content-Type: application/json

{
    "alerts": [
        {
            "text": "Caching server cannot be assigned to this delivery service without having the required delivery service capabilities: [[FOO]] for server testEdgeServer",
            "level": "error"
        }
    ]
}
```

**Comment by mhoppa** [comment]
Looking at this ^

**Comment by mitchell852** [comment]
I changed this to medium. Assigning unqualified servers to a DS could have bad side effects.
