### ISSUE TITLE
TO: Internal Server Error when filename in the request path param doesn't exist

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4128]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

```http
GET /api/{{api_version}}/cdns/Kabletown2.0/configfiles/ats/hdr_rw_.*.config HTTP/1.1
Content-Length: 0
```
returns
```http
HTTP/1.1 500 Internal Server Error
Content-Type: application/json

{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```

## Expected / new behavior:

404 if the file doesn't exist

**Comment by ocket8888** [comment]
Probably catching a SQL error somewhere and returning this. Checking for `database/sql.ErrNoRows` might be the simple fix.

**Comment by mitchell852** [comment]
closing as this endpoint has been deprecated
