### ISSUE TITLE
/cdns/{{cdn}}/configfiles/ats/{{filename}} - returns 200 for file that doesn't exist with in requested cdn

### ISSUE THREAD

**Issue by lbathina** [apache/trafficcontrol#4129]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Minimal reproduction of the problem with instructions:

Create a new cdn - test 
HTTP GET https://{{TO_BASE_URL}}/api/{{api_version}}/cdns/test/configfiles/ats/hdr_rw_{{ds xmi id that exists in another cdn}}.config

## Current behavior:

returns 200 
no alerts displayed
## Expected / new behavior:

expected code: ? not defined in the documetation
alert should be as described in here https://traffic-control-cdn.readthedocs.io/en/latest/api/cdns_cdn_configfiles_ats_filename.html

**Comment by ocket8888** [comment]
That's how it worked in Perl, unfortunately. I'd suggest that the return code be a `409 Conflict` to reflect the conflicting DS-to-CDN relationship. As far as alerts, though, none can be displayed as the entire response body is considered the verbatim contents of the file.

We may also never do this within TO itself, though, what with the advent of cache-side configuration generation.

**Comment by mitchell852** [comment]
these endpoints are now gone. closing.
