### ISSUE TITLE
Copy DS Assignments allows copy from empty server

### ISSUE THREAD

**Issue by alficles** [apache/trafficcontrol#4131]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When you use the "Copy DS Assignments to..." feature, you can copy DS assignments from a server with no assignments to a server that is configured with many assignments, thereby removing those assignments.

## Expected / new behavior:

Traffic Ops and Traffic Portal should reject attempts to copy DS assignments from a server that has no assignments. It's already possible to delete all assignments if that's what genuinely desired.

It's not possible to protect the user from all errors, but getting the copy backward is a fairly common mistake. (There are other opportunities to improve the UI as well to reduce that.) Since copying DS assignments is often used on new servers being added to a CDN, this would serve as a safety check to reduce the chance that the user has made a mistake.

**Comment by mitchell852** [comment]
I can see how this could be confusing:

![image](https://user-images.githubusercontent.com/251272/69205535-70996880-0b07-11ea-9ba4-edeab732fffa.png)

A warning message exists however to provide clarification but who reads, right?

![image](https://user-images.githubusercontent.com/251272/69205645-cd951e80-0b07-11ea-86cb-117aa9377b28.png)

Anyhow, IMO this scenario could be avoided by "fixing" TP and removing the "clone delivery service assignments" if the server has none.
