### ISSUE TITLE
Unable to unassign a delivery service request

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#4151]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
In TP, you can no longer "unassign" a delivery service request because the following TO API endpoint now returns an internal server error:

```
PUT https://trafficops.domain.net/api/1.4/deliveryservice_requests/4/assign

{id: 4, assigneeId: null}
```

## Expected / new behavior:
The following TO API endpoint should successfully unassign the ds request by putting NULL in the deliveryservice_request table for that ds request.

```
PUT https://trafficops.domain.net/api/1.4/deliveryservice_requests/4/assign

{id: 4, assigneeId: null}
```

## Minimal reproduction of the problem with instructions:
Via TP:
1. enable ds requests for TP in traffic_portal_properties.json
2. update a delivery service (which will create a ds request)
3. assign the ds request to yourself
4. attempt to unassign it. this will fail.

Via TO API:
1. ensure a ds request exists. note the id.
2. `curl -k -v -H "Accept: application/json" --cookie cookie.txt -X PUT --data '{"id": 4, "assigneeId": null}' https://trafficops.domain.net/api/1.4/deliveryservice_requests/4/assign`

**Comment by ocket8888** [comment]
Possibly a routing issue?

**Comment by mhoppa** [comment]
Looks like postgres issue on the query -> 
```ERROR: api.go:136: 2019-12-03T19:36:14.6387349Z: 172.21.0.1:51184 pq: invalid input syntax for integer: "null"
DEBUG: api.go:148: 2019-12-03T19:36:14.6388209Z: Internal Server Error```

**Comment by ocket8888** [comment]
Looks like the problem is in here:
```go
v := null
if req.AssigneeID != nil {
	v = strconv.Itoa(*req.AssigneeID)
}
if _, err = req.APIInfo().Tx.Tx.Exec(`UPDATE deliveryservice_request SET assignee_id = $1 WHERE id = $2`, v, *req.ID); err != nil {
	return api.ParseDBError(err)
}
```
Why are we converting this thing to text instead of just inserting `req.AssigneeID` as the `$1` value?

**Comment by mhoppa** [comment]
Putting up a fix now 👍
