### ISSUE TITLE
Missing docs for deliveryservice_requests endpoint

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4165]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [X] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [X] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

No documentation exists for the `deliveryservice_requests` endpoint

**Comment by ocket8888** [comment]
FWIW there are quite a few undocumented routes and methods of routes that haven't been catalogued anywhere AFAIK. In case you were looking for a project

**Comment by ZugNZwang** [comment]
This is fixed by this PR: https://github.com/apache/trafficcontrol/pull/4444
