### ISSUE TITLE
The default Traffic Monitor profile does not contain the "RASCAL" prefix

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#4206]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [x] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

TM config cannot be created until a profile beginning with "RASCAL" is associated with the TM server

## Expected / new behavior:

Correct contents of the default TM profile to include the proper name

**Comment by ocket8888** [comment]
Is this a bug within the actual code base, or the "default profiles" hosted on the ATC website?

**Comment by limited** [comment]
Certainly an issue with the default profile on the website. 

I would also argue that the requirement that all TM profiles start with RASCAL is at worst a bug in the code base and at best an undocumented configuration requirement. I think the best solution here would be to remove the RASCAL prefix requirement from TO.

**Comment by ocket8888** [comment]
It's documented in the _Profiles and Parameters_ overview section, but I agree it's a silly requirement and getting rid of it is on the roadmap. But the requirement is assumed in the logic of several components, so it's not trivial to remove.

**Comment by limited** [comment]
Fair enough, I hadn't seen that section of docs before.

I'll change my comment to "undocumented in the installation guide" :-)

**Comment by dneuman64** [comment]
@limited what version of the default profile were you using?  I looked at the 3.1.0 release and the default profile is named RASCAL_TRAFFIC_MONITOR.
http://trafficcontrol.apache.org/downloads/profiles/3.0.x/

**Comment by limited** [comment]
I was looking at the 3.0 default profile as well. The filename is
"RASCAL_TRAFFIC_MONITOR" but the profile itself contains the name:

```
"profile": {

    "description": "Traffic Monitor",
    "name": "TRAFFIC_MONITOR",
    "type": "TM_PROFILE"
  }

```

**Comment by dneuman64** [comment]
Oh, you mean I am supposed to actually read that :)
I just fixed it.

**Comment by dneuman64** [comment]
I am closing this as fixed since I updated the default profile.  please re-open if there's an issue
