### ISSUE TITLE
deliveryservices/request endpoint has Internal Server Error issues

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4215]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `POST` request to `/deliveryservices/request` and the body is missing certain keys, the response returned is:
```
HTTP/1.1 500 Internal Server Error
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
The known keys affected are:
`deepCachingType`
`deliveryProtocol`
`routingType`
`originHeaders`
`details`

## Expected / new behavior:

```
HTTP/1.1 400 Bad Request
{
    "alerts": [
        {
            "text": "<key name>: cannot be blank.",
            "level": "error"
        }
    ]
}
```

**Comment by ocket8888** [comment]
Is SMTP enabled and working on the test TO server? Can you post the relevant TO logs?

**Comment by ZugNZwang** [comment]
SMTP is enabled and working AFAIK but I can't seem to find any relevant logs of an email sent.

**Comment by ocket8888** [comment]
Sure but can you find the error occurring in the logs so I can see the expanded explanation of what caused the error? With any possibly sensitive information censored, of course.
