### ISSUE TITLE
Internal Server Error when updating user's password using /user/current endpoint

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4241]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `PUT` request to `/user/current` with the following request body:
```
{
    "user": {
        "localPasswd": "newPassword"
    }
}
```
The response returned is:
```
HTTP/1.1 500 Internal Server Error
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

Should either allow to change password or block the request.
## Anything else:

Error log: 
`Updating user: resetting password: pq: syntax error at or near "WHERE"`

**Comment by mitchell852** [comment]
Pretty sure the PUT requires the entire user object as it is a "replace" and not a "modify" in which case the api should required 400 bad request with a list of missing required fields.

However, maybe this is our one PUT that acts like a PATCH. @ocket8888 would know I believe.

**Comment by ZugNZwang** [comment]
I was able to update multiple fields without having the entire user object in the request.

**Comment by mitchell852** [comment]
> I was able to update multiple fields without having the entire user object in the request.

yep, that's because PUT /user/current is the one PUT (i think) that really acts like a PATCH.

**Comment by mitchell852** [comment]
for some reason i think to update a password you have to send a) localPasswd and b) confirmLocalPasswd (which is odd) but regardless a 500 internal server error would not be the proper response obviously.

**Comment by ocket8888** [comment]
You shouldn't need to send a `confirmLocalPasswd` I believe, I think that'd be a regression. But yes, this is the PATCH-y PUT.
