### ISSUE TITLE
Internal Server Error when making GET request to api_capabiltities endpoint

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4242]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `GET` request to `/api_capabilities?httpMethod=DOESNTEXIST` the response returned is:
```
HTTP/1.1 500 Internal Server Error
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
This only occurs when using the optional `httpMethod` parameter with a value that does not exist.
## Expected / new behavior:

Should return an empty response:
```
HTTP/1.1 200 OK
{
    "response": null
}
```

**Comment by ocket8888** [comment]
I'd say the `response` in this case should be an empty array (`[]`), not `null`.

**Comment by ocket8888** [comment]
I'm also not sure how Perl handled it. It possibly returned a 4XX error saying that you didn't give it a proper HTTP request method. Need to look into that.

**Comment by ocket8888** [comment]
It seems the Perl version of the handler actually didn't support that query parameter at all and it's currently undocumented, so its handling is pretty much whatever we want at this point. Because of that I'm gonna label this an improvement.
