### ISSUE TITLE
GET /api/1.x/api_capabilities returns `route` instead of `httpRoute`

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#4244]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
GET /api/1.x/api_capabilities returns `route` instead of `httpRoute`

## Expected / new behavior:
GET /api/1.x/api_capabilities should return `httpRoute`

## Minimal reproduction of the problem with instructions:
GET /api/1.x/api_capabilities against the Perl API and notice that `httpRoute` is returned.
GET /api/1.x/api_capabilities against the Go API and notice that `route` is returned.

This bug manifests itself in TP as well at https://tp.domain/#!/endpoints

**Comment by lbathina** [comment]
good catch
