### ISSUE TITLE
Get request to api_capabilities using query values that don't exist return null

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4257]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `GET` request to `api_capabilities` with any of the following query parameters with values that do not exist:

- `?capability=DOESNTEXIST`
- `?route=DOESNTEXIST`
- `?id=100000000`

Will return a null response:
```
HTTP\1.1 200 OK
{
    "response": null
}
```

## Expected / new behavior:

Should return an empty array.
```
HTTP\1.1 200 OK
{
    "response": []
}
```

## Anything else:

The `capability` query parameter is the only parameter that perl handled, and it would return an empty array. These other query parameters, should either be removed or should also return an empty array.

**Comment by mhoppa** [comment]
this was fixed in https://github.com/apache/trafficcontrol/pull/4321 @mitchell852 @rawlinp  @ocket8888  can you close
