### ISSUE TITLE
Undocumented Traffic Ops Golang routes

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#4290]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [x] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

The following routes are defined in `routes.go` but do not have a page in our Traffic Ops API documentation:

| HTTP Method(s) | Route | Resolution
|---|---|---|
|  <ul><li>- [ ] `PUT`</li><li>- [ ] `DELETE`</li></ul> | [`asns`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/traffic_ops/traffic_ops_golang/routing/routes.go#L148-L149) |
|  <ul><li>- [ ] `GET`</li></ul> | [`about`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L356) |
| <ul><li>- [ ] `POST`</li></ul> | [`cdns/dnsseckeys/generate`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L190) |
| <ul><li>- [x] `GET`</li></ul> | [~`deliveryservice_matches`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L303) | Deprecated (skipping)
| <ul><li>- [ ] `GET`</li><li>- [ ] `POST`</li><li>- [ ] `PUT`</li><li>- [ ] `DELETE`</li></ul> | [`deliveryservice_request_comments`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L389-L393) |
| <ul><li>- [ ] `GET`</li><li>- [ ] `POST`</li><li>- [ ] `PUT`</li><li>- [ ] `DELETE`</li></ul> | [`deliveryservice_requests`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L378-L383) |
| <ul><li>- [ ] `PUT`</li></ul> | [`deliveryservice_requests/{{ID}}/assign`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L386) |
| <ul><li>- [ ] `PUT`</li></ul> | [`deliveryservice_requests/{{ID}}/status`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L387) |
| <ul><li>- [ ] `GET`</li></ul> | [`deliveryservices/{{ID}}/urlkeys`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L556) |
| <ul><li>- [x] `GET`</li></ul> | [~`divisions/name/{{name}}`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L209) | Deprecated (skipping)
| <ul><li>- [x] `DELETE`</li></ul> | [~`divisions/{{ID}}`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L208) | Deprecated (skipping)
| <ul><li>- [ ] `GET`</li></ul> | [`federations/all`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L514) |
| <ul><li>- [x] `GET`</li></ul> | [~`keys/ping`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L266) | Deprecated (skipping)
| <ul><li>- [ ] `GET`</li></ul> | [`ping`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L264) |
| <ul><li>- [x] `GET`</li><li>- [x] `DELETE`</li></ul> | [~`regions/name/{{name}}`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L286) | Deprecated (skipping)
| <ul><li>- [x] `DELETE`</li></ul> | [~`regions/{{ID}}`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L289) | Deprecated (skipping)
| <ul><li>- [x] `GET`</li></ul> | [~`riak/bucket/{{bucket}}/key/{{key}}/values`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L557) | Documented in #4464
| <ul><li>- [x] `GET`</li></ul> | [~`riak/ping`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L265) | Documented in #4446
| <ul><li>- [x] `GET`</li></ul> | [~`servers/checks`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L310) | Documented in #4325
| <ul><li>- [x] `GET`</li></ul> | [~`servers/details`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L314) | Documented in #4512
| <ul><li>- [ ] `POST`</li></ul> | [`servers/{{ID}}/deliveryservices`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/traffic_ops/traffic_ops_golang/routing/routes.go#L437) |
| <ul><li>- [ ] `GET`</li></ul> | [`steering`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L568) |
| <ul><li>- [x] `POST`</li></ul> | [~`types`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L352) | Documented in #4406
| <ul><li>- [x] `PUT`</li><li>- [x] `DELETE`</li></ul> | [~`types/{ID}`~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/traffic_ops/traffic_ops_golang/routing/routes.go#L351-L353) | Deprecated (skipping)

- [x] [~/api/deliveryservices_dnsseckeys_generate.rst~](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/docs/source/api/deliveryservices_dnsseckeys_generate.rst) refers to an endpoint that does not exist (`deliveryservices/dnsseckeys/generate`) (Update: renamed to cdns/dnsseckeys/generate).

## Expected / new behavior:

- All routes defined in `routes.go` should be documented in the Traffic Ops API documentation.
- Nonexistent routes should be undocumented.

## Minimal reproduction of the problem with instructions:

These reStructuredText files do not yet exist in the repo:
* [`api/v2/about.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/about.rst)
* [`api/v2/cdns_dnsseckeys_generate.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/cdns_dnsseckeys_generate.rst)
* [~`api/v2/deliveryservice_matches.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/deliveryservice_matches.rst)
* [`api/v2/deliveryservice_request_comments.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/deliveryservice_request_comments.rst)
* [`api/v2/deliveryservice_requests.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/deliveryservice_requests.rst)
* [`api/v2/deliveryservice_requests_id_assign.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/deliveryservice_requests_id_assign.rst)
* [`api/v2/deliveryservice_requests_id_status.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/deliveryservice_requests_id_status.rst)
* [`api/v2/deliveryservices_id_urlkeys.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/deliveryservices_id_urlkeys.rst)
* [~`api/v2/divisions_name_name.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/divisions_name_name.rst)
* [`api/v2/federations_all.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/federations_all.rst)
* [~`api/v2/keys_ping.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/keys_ping.rst)
* [`api/v2/ping.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/ping.rst)
* [~`api/v2/regions_name_name.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/regions_name_name.rst)
* [~`api/v2/riak_bucket_bucket_key_key_values.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/riak_bucket_bucket_key_key_values.rst)
* [~`api/v2/riak_ping.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/riak_ping.rst)
* [~`api/v2/servers_checks.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/servers_checks.rst)
* [~`api/v2/servers_details.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/servers_details.rst)
* [`api/v2/steering.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/steering.rst)

These reStructuredText files are incomplete:
* [`api/v2/asns.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/asns.rst)
* [~`api/v2/divisions_id.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/divisions_id.rst)
* [~`api/v2/regions_id.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/regions_id.rst)
* [`api/v2/servers_id_deliveryservices.rst`](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/servers_id_deliveryservices.rst)
* [~`api/v2/types.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/types.rst)
* [~`api/v2/types_id.rst`~](https://github.com/apache/trafficcontrol/blob/df7a3a3d1c/docs/source/api/v2/types_id.rst)

Start CDN-in-a-Box and try to hit the `deliveryservices/dnsseckeys/generatedeliv` endpoint to see that it does not exist:

```shell script
docker-compose exec mid sh -c 'topost --insecure --to-user=$TO_ADMIN_USER --to-password=$TO_ADMIN_PASSWORD --to-url=https://$TO_HOST deliveryservices/dnsseckeys/generate'
```

**Comment by ocket8888** [comment]
Does this list overlap with #3443?

**Comment by zrhoffman** [comment]
The following routes are also mentioned in #3443:

* GET `steering`
* GET/POST/PUT/DELETE `deliveryservice_requests `

**Comment by ocket8888** [comment]
Are the others in that issue no longer undocumented, then?

**Comment by zrhoffman** [comment]
These endpoints are documented:
* POST `roles`
* PUT `roles`
* DELETE `roles`

These endpoints from that issue are listed in this one (and are still undocumented):
* GET `steering`
* GET/POST/PUT/DELETE `deliveryservice_requests`

These endpoints are still undocumented yet unmentioned in this issue:
* DELETE `divisions/{{ID}}`
* DELETE `regions/{{ID}}`

@ocket8888 Should I add those endpoints to this issue so we have a list of undocumented ones in one place?

Not sure which exact endpoints that issue is referring to:
* POST type
* PUT type
* DELETE type

---

Also, I have edited this issue to specify which HTTP methods the mentioned endpoints are defined for.

**Comment by ocket8888** [comment]
yes, please do. I think that's probably referring to `/types`

**Comment by zrhoffman** [comment]
Added them.

Also, that issue also mentions incomplete documentation for [POST `deliveryservices/dnsseckeys/generate`](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC0/docs/source/api/deliveryservices_dnsseckeys_generate.rst). I have been unsuccessful finding any history of references to that route in the project (including TO Perl) except [in the Python TO client](https://github.com/apache/trafficcontrol/blob/RELEASE-4.0.0-RC1/traffic_control/clients/python/trafficops/tosession.py#L754) and in our documentation. The route itself 404s. Can we just remove that page?

**Comment by ocket8888** [comment]
Based on the routes that _do_ exist and the response example on the `/deliveryservices/dnsseckeys/generate` page:
```json
{
        "response": "Successfully created dnssec keys for cdn1"
}
```
I think maybe there was a typo somewhere and that was meant to be `/cdns/dnsseckeys/generate`. So the docs page can get removed, and it looks like you already captured the *actual* undocumented route.

By the way, can you turn your list in the Issue into a checklist, so that items can be checked off as they're done? That way we don't need to make an issue out of each one in order to keep track of what needs to be done.

Also, looks like your bottom list has `/types/{{ID}}` in it twice.

**Comment by zrhoffman** [comment]
> [...] [T]he `/deliveryservices/dnsseckeys/generate` [...] docs page can get removed [...].

Now the issue mentions removing the `deliveryservices/dnsseckeys/generate` page.

> By the way, can you turn your list in the Issue into a checklist, so that items can be checked off as they're done?

Updated.

> Also, looks like your bottom list has /types/{{ID}} in it twice.

Thanks, fixed. In a draft, they were links to the different sections of ATC Read the Docs site.

**Comment by ocket8888** [comment]
> _"Updated"_
err, that's not exactly what I meant. I've edited it so things can be checked off

**Comment by zrhoffman** [comment]
Oops, my update didn't save. It should be good now.

**Comment by ocket8888** [comment]
`divisions/name/{{name}}` is deprecated, so it doesn't need docs

**Comment by ZugNZwang** [comment]
`servers/{{ID}}/deliveryservices` is also missing the documentation for the `POST` method
