### ISSUE TITLE
Traffic Ops Golang isn't looking for influxdb.conf in the right place

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#4292]
## I'm submitting a ...
- bug report

## Traffic Control components affected ...
- Documentation
- Traffic Ops

## Current behavior:
Traffic Ops (Go implementation) looks for `influxdb.conf` by default in the same directory as `cdn.conf`.

## Expected / new behavior:
The Perl behavior was to look in `conf/$MOJO_MODE/` in the working directory. Traffic Ops should match the legacy behavior (for now).

## Minimal reproduction of the problem with instructions:
Put your influxdb.conf file in the usual location, start Traffic Ops, try to request an endpoint that will connect to an Influx server

**Comment by smalenfant** [comment]
The documentation is not accurate as well. 

The setting documented is incorrect: `influx_db_conf_path`
The path is not documented which seems to be `/opt/traffic_ops/app/conf/influxdb.conf` (in this bug report)

**Comment by smalenfant** [comment]
The RPM should install influxdb.conf in the proper location

**Comment by ocket8888** [comment]
> The path is not documented which seems to be `/opt/traffic_ops/app/conf/influxdb.conf` (in this bug report)

The path is configurable by `influxdb_conf_path`, and so should not be documented, except possibly to mention it as the location to which the RPM installs the configuration file by default.
