### ISSUE TITLE
Line breaks in DS raw remap text will result in a malformed remap.config file 

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#4298]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
When creating or editing a delivery service of type HTTP*, DNS* or ANY_MAP, a line break in the `remapText` field will result in a malformed remap.config file being deployed to all of the edge caches assigned to the delivery service which can have a negative impact across multiple delivery services (if multiple delivery services are assigned to the cache).

When remapText = foo[line break]bar, the applicable line in remap.config will look like this:

```
map	http://edge.demo1.mycdn.ciab.test/     http://origin.infra.ciab.test/  foo
bar
map	http://edge.demo2.mycdn.ciab.test/     http://origin2.infra.ciab.test/
```

## Expected / new behavior:
On API DS create/update, any line breaks in the `remapText` field need to be removed.

## Minimal reproduction of the problem with instructions:
1. In TP, create or edit an HTTP*, DNS* or ANY_MAP delivery service and enter a line break in the `Raw Remap Text` field. Note: a textarea has been provided for readability of the `Raw Remap Text` field, however, it has the downside of allowing line breaks.
2. Navigate to the assigned servers for DS. Pick one.
3. View config files for the server.
4. View the contents of remap.config file and notice the line that doesn't start with `map`

**Comment by rawlinp** [comment]
Can we also add form validation to TP to prohibit line breaks in the raw remap field?

**Comment by ocket8888** [comment]
Wasn't this a feature? I thought the ability to put in line breaks was added specifically so that you could add multiple lines to `remap.config`? Because people used to have to use `__RETURN__` to make the line breaks.

**Comment by rawlinp** [comment]
Yes, but it seems like for fields like raw_remap we should prevent newlines, since I'm pretty sure that field is only ever meant to be _the one line_ that goes in remap.config (for ANYMAP DSes), or _appended to the one line_ for other DS types. I think regex_remap might be the same case. Seems like maybe only edge/mid header rewrite fields are _allowed_ to contain newlines, right?

**Comment by mitchell852** [comment]
edge header rewrite values create a hdr_rw_xml-id.config file and you can put multiple lines in the file.

mid header rewrite values create a hdr_rw_mid_xml-id.config file and you can put multiple lines in the file.

regex remap values create a regex_remap_xml-id.config file and you can put multiple lines in the file.

raw remap text is intended to (like @rawlinp said) add one line for any map and append to the existing line for other ds types.

**Comment by mitchell852** [comment]
> Can we also add form validation to TP to prohibit line breaks in the raw remap field?

yeah, the fix should probably be in the api AND in TP.
