### ISSUE TITLE
Fix ORT to atomically place files.

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#4311]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [x] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
ORT does not atomically place new files. It uses `cp`, which is not atomic. 

This means if somethings fails – Perl crashes, the OS crashes, the syscall fails for some reason – the file will be half-written, causing ATS reloading to fail.

## Expected / new behavior:
The proper procedure is to make a new temporary file, and then call `mv`, which is guaranteed to be atomic, and either succeed or fail.

Code is here:

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/ort/traffic_ops_ort.pl#L1575

## Minimal reproduction of the problem with instructions:

Difficult to reproduce. You'd have to run ORT and kill the Perl when it was in the middle of a file write. But it would definitely happen. And then your ATS reload or restart would fail.

**Comment by rob05c** [comment]
Also: it's common practice to run the OS temp directory on a different filesystem for security reasons, which will cause `mv` to be non-atomic as it then has to actually copy bytes.

Therefore, the temporary file should be in the same directory as the real file, to ensure it's on the same filesystem.

**Comment by mitchell852** [comment]
removing GFI label. hope that's ok @rob05c

**Comment by rob05c** [comment]
Why? This should be pretty straightforward for a new developer.
It's really just a matter of replacing the `cp` with code to make a new file with a temporary name and `mv` it to the correct location.

**Comment by ocket8888** [comment]
Because it's Perl?

Which, maybe new _developers_ won't be learning from their universities, but new _contributors_ might know. So I think it's a fine GFI.

**Comment by mitchell852** [comment]
added it back :)

**Comment by mitchell852** [comment]
@rob05c can this be closed?

**Comment by rob05c** [comment]
Yes, t3c currently atomically places new files: https://github.com/apache/trafficcontrol/blob/master/cache-config/t3c-apply/torequest/torequest.go#L499
