### ISSUE TITLE
Bad Request when creating a Delivery Service with missing ecsEnabled field

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4322]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `POST` request to `/deliveryservices` with the `ecsEnabled` field not included in the request body the response returned is:
```json
HTTP\1.1 400 Bad Request
{
    "alerts": [
        {
            "text": "ecsEnabled is a required field",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

Should return:
```json
HTTP\1.1 200 OK
{
    "alerts":[
        {
            "text":"Deliveryservice creation was successful.",
            "level":"success"
        }
    ],
    "response":[{...}]
}
```

**Comment by lbathina** [comment]
@ZugNZwang can you provide the request body that produced this output.

**Comment by ZugNZwang** [comment]
Issue no longer exists. Could have been issue with the environment build.
