### ISSUE TITLE
Improve Steering Target UI

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#4373]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [X] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Currently you have to start at the client steering delivery service, then view targets on that page.  There isn't a way to go the other direction and know what steering ds an arbitrary DS may or may not belong to.

## Anything else:
My present solution to this problem involves a direct TODB query:
```sql
SELECT d1.xml_id AS parent_ds,
       d2.xml_id AS target_ds,
       t1.value AS value,
       ty.name AS target_type
FROM steering_target t1
LEFT JOIN deliveryservice d1 ON d1.id = t1.deliveryservice
LEFT JOIN deliveryservice d2 ON d2.id = t1.target
LEFT JOIN type ty ON ty.id = t1.type
WHERE t1.deliveryservice IN (
	SELECT t.deliveryservice
	FROM steering_target t
	WHERE t.target IN (
		SELECT id
		FROM deliveryservice
	)
)
ORDER BY d1.xml_id,d2.xml_id;
```

**Comment by mitchell852** [comment]
this would probably require some api work so adding the TO label.

**Comment by mitchell852** [comment]
similar to #2101?

**Comment by jhg03a** [comment]
Yep, looks like I made a duplicate.  The SQL query though is still valid.
