### ISSUE TITLE
Bug in /cdns/dnsseckeys/refresh 

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#4381]
## I'm submitting a ...
- bug report

## Traffic Control components affected ...
- Traffic Ops

## Current behavior:
When calling the `/cdns/dnsseckeys/refresh` endpoint an error in an SQL statement causes this error to appear:
```
refreshing DNSSEC Keys: getting cdn parameters: getting cdn dnssec key refresh parameters: pq: column "c.domain_name" must appear in the GROUP BY clause or be used in an aggregate function
```
## Expected / new behavior:
The endpoint should work. I _think_ this is probably a "regression", because the undocumented `/internal/api/{{version}}/cdns/dnsseckeys/refresh` route used the Perl DBIx package to abstract its queries, and that means they weren't likely to be syntactically invalid.

## Minimal reproduction of the problem with instructions:
Make a POST request to `/cdns/dnsseckeys/refresh`.

**Comment by rawlinp** [comment]
Wow, nice catch. I'm guessing minor due to the availability of `/internal/api/{{version}}/cdns/dnsseckeys/refresh` still?

**Comment by ocket8888** [comment]
Yeah. The reason it was related to `plugin` though, was because the ToDnssecRefresh.pl extension uses the `/api/1.4/`-based route, specifically. So that extension as-is doesn't work and there's no way to tell it to fall back on a different endpoint like the `/internal/api/`-based one (without changing the script, obviously). If you instead configured it to look at Perl - either through perlBypass or setting the TO URL parameter differently - then it would just get 404 responses.

**Comment by rawlinp** [comment]
Ok, I don't really think it's a check extension plugin even though it's in the same directory as the other "check extensions". It doesn't update the servercheck table; it's literally just used in a cron job to periodically call that API endpoint.

We'll definitely need this fixed before we can delete TO-Perl, so I'll add this as a Go rewrite milestone issue.
