### ISSUE TITLE
No traffic ops hostname yet

### ISSUE THREAD

**Issue by amansingh14** [apache/trafficcontrol#4405]
## I'm submitting a ...
- [ ] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [x] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

Hi I am getting below error after starting traffic_router service

ERROR 2020-02-15T17:53:11.922 [pool-2-thread-1] com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - No traffic ops hostname yet!

# My traffic_monitor.properties file configuration: 
traffic_monitor.bootstrap.hosts=192.168.0.160:443
traffic_monitor.bootstrap.local = false
traffic_monitor.properties=file:/opt/traffic_router/conf/traffic_monitor.properties

traffic_monitor.properties.reload.period=60000

Thanks in advance ...

**Comment by rawlinp** [comment]
Verify that you can `curl https://<insert your TM hostname and port here>/publish/CrConfig` from your TR host. If TR cannot receive the CrConfig snapshot from TM, it will continue logging `No traffic ops hostname yet!` because the CrConfig provides the TO hostname.

**Comment by rawlinp** [comment]
Closing this as we normally don't take support questions in our GitHub issues. Please reach out in our slack instance at traffic-control-cdn.slack.com.
