### ISSUE TITLE
parameters POST request with no request body returns Internal Server Error

### ISSUE THREAD

**Issue by ericholguin** [apache/trafficcontrol#4427]
## I'm submitting a ...
- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Making a `POST` request to `/parameters` with no body in the request returns:
```http
HTTP/1.1 500 Internal Server Error
Content-Type: application/json

{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:
Most endpoints return:
```http
HTTP/1.1 400 Bad Request 
Content-Type: application/json

{
    "alerts": [
        {
            "text": "EOF",
            "level": "error"
        }
    ]
}
```

**Comment by ZugNZwang** [comment]
Perl returned:
```json
HTTP/1.1 400 Bad Request
{
    "alerts": [
        {
            "level": "error",
            "text": "parameters must be in JSON format,  please check!"
        }
    ]
}
```

**Comment by Rohith-Raju** [comment]
Hey @ocket8888 @mitchell852, Is this issue still relavent?

**Comment by ocket8888** [comment]
Doesn't look like this issue still exists;
```bash
topost -kp parameters
```
results in
```http
HTTP/1.1 400 Bad Request
Content-Type: application/json

{
	"alerts": [
		{
			"text": "no request body supplied",
			"level": "error"
		}
	]
}
```
