### ISSUE TITLE
ORT uses non-standard API route /ort/{{host name}}/packages

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#4436]
## I'm submitting a ...
- improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- CDN-in-a-Box (because of ORT.py)
- Traffic Ops ORT (and also the Python version used by CDN-in-a-Box)

## Current behavior:
To fetch the packages necessary for install on cache servers, ORT calls the `/ort/{{host name}}/packages` endpoint, which is not grounded in an API version nor documented anywhere, nor handled in Go.

## Expected / new behavior:
ORT should use only real, documented, supported, versioned, API endpoints. I'm not personally very particular how that's done, though I prefer the bottom-most option (unrealistic though that may be).

• The call could be forwarded to ATSTCCFG which could be updated to support generating the output from standard API calls
• ORT itself could be changed to request the necessary information from the standard API
• The endpoint could be rewritten in Go and added to the 2.0 API.
• The ability to install packages could be removed from ORT entirely, and be left to the orchestration or administration system of choice for the organization managing the server - which probably does it better anyway.

## Minimal reproduction of the problem with instructions:
Run ORT, observe the call to an unsupported, non-standard API

**Comment by rob05c** [comment]
This endpoint is just Parameters, easily gotten from the existing API.
I'm planning to make the `atstccfg` do that, and make ORT call `atstccfg` to get this data.

**Comment by rob05c** [comment]
Fixed by https://github.com/apache/trafficcontrol/pull/4493
