### ISSUE TITLE
ORT uses non-standard API endpoint /update/{{host name}}

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#4438]
## I'm submitting a ...
- improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
- CDN-in-a-Box (because of ORT.py)
- Traffic Ops ORT (and also the Python version used by CDN-in-a-Box)

## Current behavior:
To report that updates and/or revalidations were successfully applied on cache servers, ORT calls the `/update/{{host name}}` endpoint, which is not grounded in an API version nor documented anywhere, nor handled in Go.

## Expected / new behavior:
ORT should use only real, documented, supported, versioned, API endpoints. I'm not personally very particular how that's done, though I prefer the bottom-most option (unrealistic though that may be).

• The call could be forwarded to ATSTCCFG which could be updated to it using standard API calls
• ORT itself could be changed to make the request using the standard API
• The endpoint could be rewritten in Go and added to the 2.0 API.

## Minimal reproduction of the problem with instructions:
Run ORT, observe the call to an unsupported, non-standard API

**Comment by rob05c** [comment]
This doesn't have an alternative within the API.
We need a way to set the `upd_pending` and `reval_pending` flags, without POSTing anything else on the Server (which could overwrite data that changed underneath us).

So, I think we should move this to the API.

**Comment by rob05c** [comment]
https://github.com/apache/trafficcontrol/pull/4599 adds the necessary endpoint.
Still need to make a PR changing ORT to actually use it.
