### ISSUE TITLE
Internal Server Error for PUT Request on cachegroups/{{ID}} endpoint

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4442]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When user do a PUT Request to cachegroups/id endpoint with the `name` of another cachegroup, It will return 500 Internal Error.

Login to TO. Do a PUT Request `https://{{TO_BASE_URL}}/api/2.0/cachegroups/08` With this replacement json payload: 
```json
{
        "latitude": 0.0,
        "longitude": 0.0,
        "name": "test",
        "fallbacks": [],
        "fallbackToClosest": true,
        "shortName": "test",
        "typeId": 23,
        "localizationMethods": ["GEO"]
}
```

It will return status 500 Internal Server Error 
```json
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

It should return bad request.

**Comment by ocket8888** [comment]
what did Perl do?

**Comment by dmohan001c** [comment]
update cache group with the already existing cache group name:
PUT: https://localhost/api/3.0/cachegroups/1
{
    "name": "CDN_in_a_Box_Origin",
    "shortName": "ciabMid-01",
    "latitude": 38.897663,
    "longitude": -77.036574,
    "fallbackToClosest": true,
    "typeName": "MID_LOC",
    "typeId": 24,
    "fallbacks": []
}
Response
{
    "alerts": [
        {
            "text": "updating coordinate for cachegroup 'CDN_in_a_Box_Origin': pq: duplicate key value violates unique constraint \"coordinate_name_key\"",
            "level": "error"
        }
    ]
}
Status Code: 400 Bad Request
