### ISSUE TITLE
Missing deprecation notices in certain v1 endpoint documentation

### ISSUE THREAD

**Issue by ericholguin** [apache/trafficcontrol#4450]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [X] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

The following endpoints are deprecated and not supported in v2. They are missing deprecation notices in their documentation pages:

- cdns/{{cdn}}/configfiles/ats/{{filename}}
- profiles/{{profile}}/configfiles/ats/{{filename}}
- servers/{{server}}/configfiles/ats
- servers/{{server}}/configfiles/ats/{{filename}}

## Expected / new behavior:

They should have deprecation notices like other deprecated endpoints
## Anything else:

https://traffic-control-cdn.readthedocs.io/en/latest/api/v1/cdns_cdn_configfiles_ats_filename.html

https://traffic-control-cdn.readthedocs.io/en/latest/api/v1/profiles_profile_configfiles_ats_filename.html

https://traffic-control-cdn.readthedocs.io/en/latest/api/v1/servers_server_configfiles_ats.html

https://traffic-control-cdn.readthedocs.io/en/latest/api/v1/servers_server_configfiles_ats_filename.html

**Comment by ocket8888** [comment]
Are you talking about in the documentation? Because only `/servers/{{host name}}/configfiles/ats` could possibly have a deprecation notice in the alerts.

**Comment by ZugNZwang** [comment]
Yes documentation, adding that now.

**Comment by mitchell852** [comment]
assigned to @ocket8888 so he can close when api 1.x is removed.

**Comment by ocket8888** [comment]
The endpoints in question have already been removed from the documentation; those links 404
