### ISSUE TITLE
API 1.x endpoint calls need to be updated to 2.0 

### ISSUE THREAD

**Issue by ericholguin** [apache/trafficcontrol#4461]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [X] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [X] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

The following code needs to be updated to use 2.0:

https://github.com/apache/trafficcontrol/blob/4b3d01d7855b72762eda171bb2a7335a0d155d55/test/router/server/server.go#L59
https://github.com/apache/trafficcontrol/blob/4b3d01d7855b72762eda171bb2a7335a0d155d55/test/router/server/server.go#L67
https://github.com/apache/trafficcontrol/blob/4b3d01d7855b72762eda171bb2a7335a0d155d55/traffic_ops/install/bin/copy-pgdata.sh#L59
https://github.com/apache/trafficcontrol/blob/4b3d01d7855b72762eda171bb2a7335a0d155d55/traffic_ops/install/bin/copy-pgdata.sh#L82
https://github.com/apache/trafficcontrol/blob/4b3d01d7855b72762eda171bb2a7335a0d155d55/traffic_ops/install/bin/copy-pgdata.sh#L208
https://github.com/apache/trafficcontrol/blob/4b3d01d7855b72762eda171bb2a7335a0d155d55/traffic_ops/app/bin/checks/ToAutorenewCerts.pl#L83
https://github.com/apache/trafficcontrol/blob/4b3d01d7855b72762eda171bb2a7335a0d155d55/traffic_ops/traffic_ops_golang/trafficstats/util_test.go#L54
https://github.com/apache/trafficcontrol/blob/4b3d01d7855b72762eda171bb2a7335a0d155d55/traffic_ops/traffic_ops_golang/invalidationjobs/invalidationjobs.go#L365
https://github.com/apache/trafficcontrol/blob/4b3d01d7855b72762eda171bb2a7335a0d155d55/traffic_ops/traffic_ops_golang/invalidationjobs/userinvalidationjobs.go#L137

**Comment by neelkamath** [comment]
I'll try fixing it

**Comment by ocket8888** [comment]
Can we just get rid of `copy-pgdata.sh`? Isn't that a tool designed to help migrate from MySQL to PostgresQL?

**Comment by ocket8888** [comment]
The only of these not already fixed by #5539 are those in `test/router` - which doesn't work.

**Comment by zrhoffman** [comment]
> The only of these not already fixed by #5539 are those in `test/router` - which doesn't work.

Grove API v1 references also need to be updated, and since Swagger contains API v1 references and we don't use it, we should just remove it.

**Comment by ocket8888** [comment]
Sure, but those aren't listed here. Are you going to add those to the issue? Because I was about to open a PR to update test/router references that would close this issue if that was all that was left.

**Comment by zrhoffman** [comment]
Oh neat, I'll add them to a new issue, then.
