### ISSUE TITLE
Regional geo blocking alternate for null zipcode using bgp asn/cachegroup 

### ISSUE THREAD

**Issue by tyagian** [apache/trafficcontrol#4471]
## I'm submitting a ...
- [ ] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Expected / new behavior:

As I understand, RGB blocks IP request which has a null value in zipcode. As a workaround, If we can use BGP ASN which uses cache group and physical location. Physical location already has zipcode so it will map subnets in BGP communities to their respective zip code. This way allows IPs that are not found in the local geolocation database, for instance in MaxMind.

**Comment by dneuman64** [comment]
By BGP/ASN I am assuming you are referring to a specific implmentation you have on your CDN for the coverage zone file. 
Would what's in #4372 solve your issue?

**Comment by tyagian** [comment]
Yes, We can fix it using [#4372](https://github.com/apache/trafficcontrol/issues/4372)  issue. That should be a more acceptable approach. I am closing this issue considering it as duplicate.
