### ISSUE TITLE
No message display after delete a cache group

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4522]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Create a Cache Group on TP, then delete it. There isn't any message display after that.
## Expected / new behavior:

Return a message for user like `cachegroup was deleted.`

**Comment by ocket8888** [comment]
Is the API endpoint not returning `alerts` or is the page just not properly displaying them? Because this could be fixed without using `alerts`, but the best solution would be to use them.

**Comment by dpham692** [comment]
The TP page just not display them at all. I test the API endpoint and it's returning message fine.
```
{
    "alerts": [
        {
            "text": "cachegroup was deleted.",
            "level": "success"
        }
    ]
}
```

**Comment by ocket8888** [comment]
That should be a very quick fix, then.
