### ISSUE TITLE
Can change any type's useInTable value to be server

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4548]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `PUT` request to `/types/{id}`, where `id` identifies a type that **does not** belong in the servers table. The API allows that type to be changed from the table it was using. For example one can update a type using  the deliveryservice table to use the server table.

```http
HTTP/1.1 200 OK
Content-Type: application/json
{
    "alerts": [
        {
            "text": "type was updated.",
            "level": "success"
        }
    ],
    "response": {
        "id": 1,
        "lastUpdated": "2020-03-26 20:49:44+00",
        "name": "HTTP",
        "description": "HTTP Content Routing",
        "useInTable": "server"
    }
}
```
## Expected / new behavior:

Should not be allowed and return:
```http
HTTP/1.1 400 Bad Request
Content-Type: application/json
{
    "alerts": [
        {
            "text": "can not update type",
            "level": "error"
        }
    ]
}
```

**Comment by mitchell852** [comment]
Yeah, I think you should only be able to:

a. create a type with useintable=server (any other values for useintable should be rejected)
b. update a type where useintable=server but can't change the useintable value to something else.
c. delete a type where useintable=server

imo this should all be enforced at the api level. UI level is a bonus maybe but not really necessary.

fyi, the useintable thing is very strange...

**Comment by rawlinp** [comment]
Fixed by https://github.com/apache/trafficcontrol/pull/4600
