### ISSUE TITLE
Deleting a type that doesn't exist returns Internal Server Error

### ISSUE THREAD

**Issue by ericholguin** [apache/trafficcontrol#4549]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a `DELETE` request to `types/{id}` where the id doesn't belong to any existing type the response returned is:
```http
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```

## Expected / new behavior:

Should return:
```http
HTTP/1.1 404 Not Found
Content-Type: application/json
{
    "alerts": [
        {
            "text": "no type found with this id",
            "level": "error"
        }
    ]
}
```
## Anything else:

Error logs show:

```ERROR: api.go:180: .... sql: no rows in result set```

**Comment by dmohan001c** [comment]
Fixed the Internal server error in delete types by invalid id.
DELETE: https://localhost/api/4.0/types/42222
Response: 
{
    "alerts": [
        {
            "text": "no type with that key found",
            "level": "error"
        }
    ]
}
Status Code: 404 Status Not Found
