### ISSUE TITLE
Traffic Portal fails to perform a CDN snapshot

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4552]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

In Traffic Portal when clicking the `Perform Snapshot` button in the`/cdns/{id}/config/changes` page, there is an alert message shown:

![Screen Shot 2020-03-27 at 10 13 18 AM](https://user-images.githubusercontent.com/14004132/77776413-997cbd80-7013-11ea-86e9-9df53db4b958.png)

## Expected / new behavior:

Should display the alert message `Snapshot performed`
## Anything else:

This is due to the query parameters not being correctly passed into the request:
https://github.com/apache/trafficcontrol/blob/c0af35f0c82d3cb22e168a63372d3730e2af1670/traffic_portal/app/src/common/api/CDNService.js#L179

**Comment by ocket8888** [comment]
That looks correct to me... can you see in the "Network" tab of the dev tools what was passed in the request?

**Comment by ZugNZwang** [comment]
In the Request Payload I see: 
![Screen Shot 2020-03-27 at 10 37 04 AM](https://user-images.githubusercontent.com/14004132/77778641-ed3cd600-7016-11ea-8e24-a8e3ace975e8.png)

**Comment by ocket8888** [comment]
I think I see the problem
