### ISSUE TITLE
TP: Provide the ability to view all servers utilized by a topology

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#4559]
## I'm submitting a ...

- [x] new feature / enhancement request

## Description

In Traffic Portal, users should be able to view all servers utilized by a topology.

## Traffic Control components affected ...

- [x] Traffic Portal

## Acceptance Criteria

- the topology servers view is accessible via a button on the edit topology page.
- the topology servers view is accessible via a deep link (i.e. tp.domain.com/!#/topologies/name/servers).
- the topology servers view shows all servers utilized by the topology in a tabular format.
- the topology servers view provides a method to edit an existing server.

See the Flexible Topologies PR for specifics: apache/trafficcontrol#4537

**Comment by mitchell852** [comment]
this is not done afaik. reopening.

**Comment by zrhoffman** [comment]
Fixed in 5056
