### ISSUE TITLE
Adjust cachegroup parentage and deliveryservice-server assignment endpoints for Topologies

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#4572]
## I'm submitting a ...

- [x] new feature / enhancement request

## Description

API endpoints that are affected by cachegroup parentage or deliveryservice-server assignment need to be updated to take Topology-based Delivery Service assignment and parentage into account.

## Traffic Control components affected ...

- [x] Documentation
- [x] Traffic Ops

## Acceptance Criteria

- Assign a Delivery Service to a server (or vice versa). It should be prohibited to assign an `EDGE` server to a Delivery Service (or vice versa) that has a Topology assigned already.
- perform an operation on "child" cachegroups -- like queueing updates on "child" caches when changing the status of a "parent" cache. Child caches via both Topologies and legacy Cachegroup parentage would all need to be updated in that case.The line

See the Flexible Topologies PR for specifics: apache/trafficcontrol#4537

**Comment by rawlinp** [comment]
@zrhoffman this is pretty much done, right? Can this be closed?

**Comment by zrhoffman** [comment]
Yep looks done!
