### ISSUE TITLE
traffic_ops installation error due to cpan installation and _postinstall script execution

### ISSUE THREAD

**Issue by DungeonMasterAkshay** [apache/trafficcontrol#4577]
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other

## Which component(s) is/are affected?
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Anything else:
```console
[root@localhost]# ./postinstall
Carton is up to date. (v1.0.34)
Installing modules using /opt/traffic_ops/app/cpanfile
! Installing WWW::Curl::Easy failed. See /root/.cpanm/work/1585676395.76616/build.log for details. Retry with --force to force install it.
! Installing Net::Pcap failed. See /root/.cpanm/work/1585676395.76616/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Net::Pcap' is not installed
! Bailing out the installation for Net-PcapUtils-0.01.
! Installing the dependencies failed: Module 'Net::PcapUtils' is not installed, Module 'Net::Pcap' is not installed
! Bailing out the installation for /opt/traffic_ops/app/.
Installing modules failed
Now installing goose
Successfully installed goose to /opt/traffic_ops/go/bin/goose
Experimental keys on scalar is now forbidden at /opt/traffic_ops/install/bin/_postinstall line 84.
Type of arg 1 to keys must be hash or array (not private variable) at /opt/traffic_ops/install/bin/_postinstall line 84, near "$var ) "
Experimental keys on scalar is now forbidden at /opt/traffic_ops/install/bin/_postinstall line 324.
Type of arg 1 to keys must be hash or array (not private variable) at /opt/traffic_ops/install/bin/_postinstall line 324, near "$defaultInputs ) "
Experimental keys on scalar is now forbidden at /opt/traffic_ops/install/bin/_postinstall line 346.
Type of arg 1 to keys must be hash or array (not private variable) at /opt/traffic_ops/install/bin/_postinstall line 346, near "$defaultInputs ) "
Experimental push on scalar is now forbidden at /opt/traffic_ops/install/bin/_postinstall line 396, near "%temp;"
Bareword "main" not allowed while "strict subs" in use at /opt/traffic_ops/install/bin/_postinstall line 946.
Execution of /opt/traffic_ops/install/bin/_postinstall aborted due to compilation errors.
```

**Comment by ocket8888** [comment]
Looks like you're getting carton installation errors. What's your Perl version? What happens if you manually try installing the cpan dependencies?

**Comment by DungeonMasterAkshay** [comment]
PERL :  perl 5, version 26, subversion 3 (v5.26.3) 
carton v1.0.34

Manual Installation(depenedencies) :
[root@oops_api app]# carton install cpanfile
Installing modules using /opt/traffic_ops/app/cpanfile
! Installing Net::Pcap failed. See /root/.cpanm/work/1585683091.80510/build.log for details. Retry with --force to force install it.
! Installing WWW::Curl::Easy failed. See /root/.cpanm/work/1585683091.80510/build.log for details. Retry with --force to force install it.
! Installing the dependencies failed: Module 'Net::Pcap' is not installed
! Bailing out the installation for Net-PcapUtils-0.01.
! Installing the dependencies failed: Module 'Net::Pcap' is not installed, Module 'Net::PcapUtils' is not installed
! Bailing out the installation for /opt/traffic_ops/app/.
Installing modules failed

**Comment by ocket8888** [comment]
what does the log file they're pointing you to say?

**Comment by DungeonMasterAkshay** [comment]
These are logs for Net::Pcap module which is perl module.
I have tried to install with cpanfile .
I have tried to install with this command : carton install Net::Pcap/Net::PcapUtils and cpan Net::Pcap/Net::PcapUtils.


**These are following log error of _postinstall script execution** 

Experimental keys on scalar is now forbidden at /opt/traffic_ops/install/bin/_postinstall line 84.
Type of arg 1 to keys must be hash or array (not private variable) at /opt/traffic_ops/install/bin/_postinstall line 84, near "$var ) "
Experimental keys on scalar is now forbidden at /opt/traffic_ops/install/bin/_postinstall line 324.
Type of arg 1 to keys must be hash or array (not private variable) at /opt/traffic_ops/install/bin/_postinstall line 324, near "$defaultInputs ) "
Experimental keys on scalar is now forbidden at /opt/traffic_ops/install/bin/_postinstall line 346.
Type of arg 1 to keys must be hash or array (not private variable) at /opt/traffic_ops/install/bin/_postinstall line 346, near "$defaultInputs ) "
Experimental push on scalar is now forbidden at /opt/traffic_ops/install/bin/_postinstall line 396, near "%temp;"
Bareword "main" not allowed while "strict subs" in use at /opt/traffic_ops/install/bin/_postinstall line 946.
Execution of /opt/traffic_ops/install/bin/_postinstall aborted due to compilation errors.

**Comment by ocket8888** [comment]
Are you installing on CentOS8? I'm told that's what happens when you try to install on CentOS 8. You should try installing on CentOS 7 if that's the case.

**Comment by DungeonMasterAkshay** [comment]
Actualy I am using RHEL 8 OS 
gcc (GCC) 8.3.1 20190507 (Red Hat 8.3.1-4) 
perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi

**Comment by zrhoffman** [comment]
If you have RHEL 7, you can use that. Otherwise, use CentOS 7 as @ocket8888 suggested. The two operating systems are built to be functionally identical.

**Comment by zrhoffman** [comment]
#4587 fixes the errors in `_postinstall` related to "Experimental keys on scalar is now forbidden". Building `WWW::Curl::Easy` and `Net::Pcap` fails due to upstream issues related to the newer versions of libraries that CentOS 8 has, and without patches, they fail to build. Neither module is required for the `_postinstall` script though, so the PR should be a complete fix for this issue.
