### ISSUE TITLE
POST request to users/register returns Internal Server Error

### ISSUE THREAD

**Issue by ZugNZwang** [apache/trafficcontrol#4583]
## I'm submitting a ...

- [X] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [X] Traffic Ops
- [ ] Traffic Ops ORT
- [X] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

When making a valid `POST` request to `/users/register` the response returned is:
```http
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

Should return:
```http
HTTP/1.1 200 OK
Content-Type: application/json
{
    "alerts": [
        {
            "text": "Sent user registration to {{<email>}} with the following permissions [ role: admin | tenant: root ]",
            "level": "success"
        }
    ]
}
```
## Anything else:

Error Log:
```ERROR: api.go:180: ... Checking for existing user with email {{ <email>}}: missing destination name rolename in *tc.User```

**Comment by ZugNZwang** [comment]
Possibly has to do with this line:

https://github.com/apache/trafficcontrol/blob/7d1b23ed6ba72136cb88f7313a5cca11d3fb9f00/lib/go-tc/users.go#L102

**Comment by ocket8888** [comment]
Did you have an SMTP server running and configured?

**Comment by ZugNZwang** [comment]
SMTP was enabled and working.

**Comment by ocket8888** [comment]
Was it configured in the TO configuration file? Could you hit other email-based endpoints e.g. `/user/reset_password` and `/deliveryservices/request` ?

**Comment by ZugNZwang** [comment]
Yes. `/deliveryservices/request` works correctly. I did not test `/user/reset_password`. I don't think it has any issue with SMTP or email. As i mentioned the error log shows:
```ERROR: api.go:180: ... Checking for existing user with email {{ <email>}}: missing destination name rolename in *tc.User```

**Comment by ocket8888** [comment]
right, right. Just checking
