### ISSUE TITLE
/GET jobs Request Query Parameters not working

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4646]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Create multiple jobs in TO with `/api/2.0/jobs`. Then try to perform a /GET with Request Query Parameters come with it. For example: (id, assetUrl, createdBy ...)
None of the Query Para will work and it will return all the jobs has been created.
## Expected / new behavior:

Each Query Param in /GET jobs API return jobs match with their condition.

**Comment by rawlinp** [comment]
I think this API is suffering from the same issue we had with the deliveryservicesregexes API caused by: https://github.com/apache/trafficcontrol/pull/4527/files#diff-2101fb96dfbf3889d34ca24458176f9eR223

I believe that line should be `if len(where) > 0` instead.
