### ISSUE TITLE
Internal Server Error for incorrect startdate query param in /GET deliveryservice_stats

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4655]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Perform a /GET deliveryservice_stats with incorrect startDate param input.

For example: `api/2.0/deliveryservice_stats?deliveryServiceName=client-steering-geoordered-mkga&deliveryService=9999999&startDate=1&endDate=2020-07-22T17:56:00.000Z&metricType=tps_total`

It will return a 500 Internal Server Error
## Expected / new behavior:

Should return 400 Bad Request

**Comment by ocket8888** [comment]
Do you see anything in the logs?

**Comment by dpham692** [comment]
No there is none.

**Comment by ocket8888** [comment]
I actually think I know what this is. And I think it's unavoidable. Details to follow.

**Comment by ocket8888** [comment]
This was most likely caused by a timeout. Your startDate parameter is not invalid, so 400 would be incorrect in any case (except perhaps that you've provided two differing identities for a DS). When trying to reproduce this error, I found this in the logs:
```
ERROR: api.go:180: 2020-04-25T02:26:03.780490149Z: 172.21.0.1:33552 Getting summary response from Influx: unable to decode json: received status code 200 err: context deadline exceeded (Client.Timeout or context cancellation while reading body)
```
Which is pretty much what I expected. When there's a problem communicating with Influx the only proper response is a 500 error with no details.

**Comment by mitchell852** [comment]
so can this be closed?

**Comment by ocket8888** [comment]
I'd say so; it's been 11 days so I think if there was anything to say in response it would've been said by now. But I'll follow up with him in dms.
