### ISSUE TITLE
Internal Server Error for /jobs API with userId parameter query

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4658]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Perform a /GET Request for jobs API with invalid userId parameter. For example: `api/2.0/jobs?userId=WRONG`
It will return a 500 Internal Server Error

## Expected / new behavior:

Should return 400 Bad Request

**Comment by ocket8888** [comment]
Do the logs say anything about what went wrong?
