### ISSUE TITLE
Traffic Router does not set Content-Type on auth call to Traffic Ops

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#4680]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [x] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Traffic Router POSTs JSON to the Traffic Ops Authentication API endpoint, but the Content-Type in the request is incorrectly marked as `application/x-www-form-urlencoded`

## Expected / new behavior:

When POSTing JSON, the API call should contain the header `Content-Type: application/json`

## Anything else:

Simple fix likely belongs in `ProtectedFetcher::getConnection()` near the call to get the auth cookie. 

A more extensive/safer fix might be to overload `ProtectedFetcher's` constructor and `getConnection()` to take in a `JSONNode` which correctly sets the `Content-Type` header

**Comment by ocket8888** [comment]
This doesn't cause the API call to fail, does it?

**Comment by limited** [comment]
No impact to Traffic Ops, just general hygiene
