### ISSUE TITLE
Add ?parent= query param to GET /tenants to view all tenants that share a parent tenant

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#4706]
## I'm submitting a ...

- [ ] bug report
- [x] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
All tenantable resources (ds, dsr, origin and user) except for tenants (which is also a tenantable resource) can be filtered based on their direct tenancy assignment. i.e. 

```
GET /api/deliveryservices?tenant= <-- gives you all the ds's directly assigned to the tenant
GET /api/deliveryservice_requests?tenant= <-- gives you all the dsr's directly assigned to the tenant
GET /api/origins?tenant= <-- gives you all the origins directly assigned to the tenant
GET /api/users?tenant= <-- gives you all the users directly assigned to the tenant
```
## Expected / new behavior:
Add the ability to filter tenants based on their direct tenancy assignment. i.e. 

```
GET /api/tenants?parent= <-- gives you all the tenants directly assigned to the (parent) tenant
```

**Comment by ocket8888** [comment]
This differs from `accessibleTo` in that it returns only those Tenants that are the _direct_ child of the parent with the specified identifier? That is in a tree like: root -> A ->B if I request `GET /tenants?parent={{whatever the ID of root is}}` I'll get back a response containing _only_ A?

**Comment by mitchell852** [comment]
> That is in a tree like: root -> A ->B if I request `GET /tenants?parent={{whatever the ID of root is}}` I'll get back a response containing _only_ A?

yes, but i can't remember for the life of me why i suggested this so i guess i'll close.
