### ISSUE TITLE
Cloning a server profile only links a subset of header_rewrite parameters.

### ISSUE THREAD

**Issue by traeak** [apache/trafficcontrol#4712]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
When creating a new server profile via cloning some location parameters some of the header_rewrite parameters are not carried along and have to be manually linked.  Update: this also includes regex_remap parameters as well.

## Expected / new behavior:
All linked parameters should clone, not just a subset.

## Minimal reproduction of the problem with instructions:
Internally this is easy to reproduce.

**Comment by mitchell852** [comment]
yet another bug related to "location parameters".

**Comment by rob05c** [comment]
The better fix for this is to change the Config Gen to check DS fields, and create config files as necessary. And get rid of DS-field location params entirely.

**Comment by rob05c** [comment]
Fixed by https://github.com/apache/trafficcontrol/pull/4861
