### ISSUE TITLE
GET /deliveryservice_stats limits metric types

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#4740]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
The Go version of GET /deliveryservice_stats limits the metric types to the following:

```
dsMetricTypes = map[string]interface{}{
	"kbps":      struct{}{},
	"tps_total": struct{}{},
	"tps_2xx":   struct{}{},
	"tps_3xx":   struct{}{},
	"tps_4xx":   struct{}{},
	"tps_5xx":   struct{}{},
}
```

Therefore making it impossible to fetch `metricType=foo` for example. The Perl version did not restrict the metric types but rather it simply added whatever metric type to the influx query.

I would suggest fixing this in 1.x and 2.x (which is already part of TC 4.1) and potentially redesigning the entire endpoint for 3.x (which is part of TC 5.0). I'll created a separate issue for that - #4741 

## Expected / new behavior:
GET /api/deliveryservice_stats does not limit metric types to a predefined set.

## Minimal reproduction of the problem with instructions:
GET /api/1.4/deliveryservice_stats?metricType=foo will return a 400 bad request.

**Comment by ocket8888** [comment]
This was intentional. The Perl version allowed for arbitrary input without restriction, which let a read-only user destroy the entire stats database. I'd suggest that instead if there's a new type of stat you want, we just add support for that instead.
