### ISSUE TITLE
Fix bugs for POST /api/x/cachegroups/:id/deliveryservices

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4762]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

1. Bug when user assigns all of the servers within a Cache Group to non exist Delivery Services. 
For example by using this payload:
```{"deliveryServices": [999]}```
API will return Status code 500 Internal Server Error
```
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
2.Bug when user assigns all of the servers within a Cache Group to empty Delivery Services. 
For example by using this payload:
```{"deliveryServices": []}```
API will return Status Code 200 Success
```
{
    "alerts": [
        {
            "text": "Delivery services successfully assigned to all the servers of cache group 4.",
            "level": "success"
        }
    ],
    "response": {
        "id": 4,
        "serverNames": [
        ],
        "deliveryServices": []
    }
}
```
3. Bug when user assigns all of the servers within a Cache Group to Delivery Services from different CDN. 
For example: create new cdn and new delivery services from that cdn just created. Now use this API to assign.
API will return 500 Internal Server Error
```
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```

## Expected / new behavior:

1. Should return 404 Not Found. Delivery Services Not Found
2. Should return 400 Bad Request. 
3. Should return 409 Conflict. Delivery Services is not in the same CDN as Servers.

**Comment by ocket8888** [comment]
Idk about 2, that's asking it to do a no-op and it technically does that successfully.

**Comment by dpham692** [comment]
Confirm 2 is not a bug.

**Comment by mitchell852** [comment]
1.x will soon be removed. closing.

**Comment by ocket8888** [comment]
This doesn't look specific to 1.x

**Comment by mitchell852** [comment]
> This doesn't look specific to 1.x

so needs to be reopened?

**Comment by ocket8888** [comment]
looks that way to me, but @dpham692 would know for sure.
