### ISSUE TITLE
TM unexpected error - MonitorConfig.Config["peers.polling.interval"] missing

### ISSUE THREAD

**Issue by cheluskin** [apache/trafficcontrol#4793]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [x] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Error in TM log: 
**ERROR: monitorconfig.go:113: 2020-06-15T09:46:52.650722482+02:00: MonitorConfigPoller: getting monitor config map: MonitorConfig.Config["peers.polling.interval"] missing, peers.polling.interval parameter required
 <nil>**

## Expected / new behavior:
No unexpected errors in log

## Minimal reproduction of the problem with instructions:
TM 4.1.x
OPS 4.1.x

## Anything else:
traffic_monitor return "Service Unavailable" via http 

/cdns/mycdn/configs/monitoring response wit empty config node
```json
{
    "response": {
        "trafficServers": [
            {
                "profile": "Cache",
                "status": "ONLINE",
                "ip": "51.14.2.204",
                "ip6": "",
                "port": 80,
                "cachegroup": "DEFAULT",
                "hostname": "am1",
                "fqdn": "am1.myawesomecdn",
                "interfacename": "eth0",
                "type": "EDGE",
                "hashid": "AMS-2120465"
            },
            {
                "profile": "Cache",
                "status": "ONLINE",
                "ip": "166.179.47.244",
                "ip6": "",
                "port": 80,
                "cachegroup": "DEFAULT",
                "hostname": "par1",
                "fqdn": "par1.myawesomecdn",
                "interfacename": "eth0",
                "type": "EDGE",
                "hashid": "PAR-212047"
            }
        ],
        "trafficMonitors": [
            {
                "profile": "TM",
                "status": "ONLINE",
                "ip": "55.210.105.137",
                "ip6": "",
                "port": 80,
                "cachegroup": "DEFAULT",
                "hostname": "tm",
                "fqdn": "tm.myawesomecdn"
            }
        ],
        "cacheGroups": [
            {
                "name": "DEFAULT",
                "coordinates": {
                    "latitude": 46.8534,
                    "longitude": 4.3488
                }
            }
        ],
        "profiles": [
            {
                "name": "ccr-TR",
                "type": "CCR",
                "parameters": null
            },
            {
                "name": "Cache",
                "type": "EDGE",
                "parameters": null
            }
        ],
        "deliveryServices": [],
        "config": {}
    }
}
```

**Comment by cheluskin** [comment]
Unfortunately, due to this error, it is impossible to start traffic monitor, and for some reason traffic router depends on its config. This makes the entire 4.0 release unusable. And which version is worth using?

**Comment by dneuman64** [comment]
Hi @cheluskin, sorry for the trouble. 
4.0 is our latest stable release and is your best bet for using Traffic Control.  4.1 is out for release consideration now. 
According to the error you are seeing, it looks like you need to add a peers.polling.interval param to Traffic Ops and assign it to your Traffic Router profile.  You also will need to make sure that your Traffic Monitor Profile begins with the name "Rascal".
![image](https://user-images.githubusercontent.com/5092346/84785396-af61a500-afa8-11ea-91f0-889c54eecb9b.png)

**Comment by mitchell852** [comment]
looks like this is resolved. also, to get quicker feedback try https://traffic-control-cdn.slack.com
