### ISSUE TITLE
Fix query parameter for servers API

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4795]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

1. When user perform a /GET `https://{{TO_BASE_URL}}/api/3.0/servers?type=MID` with any type like MID,EDGE ...
The API will return 500 Internal Server Error.
```
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
2. When user perform a /GET `https://{{TO_BASE_URL}}/api/3.0/servers?status=ONLINE` with any valid or invalid status
The API will return 500 Internal Server Error
```
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
3. When user perform a /GET `https://{{TO_BASE_URL}}/api/3.0/servers?parentCachegroup=1` with valid or invalid parentCachegroup number.
The API will return 500 Internal Server Error
```
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Expected / new behavior:

Should return the servers with correct match

**Comment by ocket8888** [comment]
I believe this is duplicated by #4789, can that one be closed?

**Comment by ocket8888** [comment]
actually, I take that back. The dsId issue has a different root cause.

**Comment by dpham692** [comment]
@ocket8888 sure
