### ISSUE TITLE
Fix ip and ip6 address problem from /POST and /GET servers API

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4804]
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
1. User can create a servers with empty IP address and can mark it as service. For example using this payload:
```json
{				
"cachegroupId":   3,
"cachegroup":     "infrastructure",
"cdnId":          2,
"cdnName":       "testCDN", 
"domainName":     "test.net", 
"hostName":       "testingServer", 
"interfaceMtu":   1500,
"interfaceName":  "eth0",
"ipAddress":      "",
"ipGateway":      "0.0.0.2",
"ipNetmask":      "255.255.255.0",
"ip6Address":     "0:0:0:0:0:0:0:1",
"ip6Gateway":     "::1",
"physLocationId": 1,
"physLocation":   "Augusta-ME", 
"profileId":      34,
"profile":         "ATS_Edge_MKGA",
"statusId":       2,
"typeId":         11,
"updPending":     false,
"ipIsService":    true,
"ip6IsService":   false
						
}
```
The server will return 200 OK
2. User can try to create a normal server. After that perform a /GET, ip6address and ipaddress will still be null. For example create a server with this payload:
```json
{				
"cachegroupId":   3,
"cachegroup":     "infrastructure",
"cdnId":          2,
"cdnName":       "testCDN", 
"domainName":     "test.net", 
"hostName":       "testingServer", 
"interfaceMtu":   1500,
"interfaceName":  "eth0",
"ipAddress":      "0.0.0.1",
"ipGateway":      "0.0.0.2",
"ipNetmask":      "255.255.255.0",
"ip6Address":     "0:0:0:0:0:0:0:1",
"ip6Gateway":     "::1",
"physLocationId": 1,
"physLocation":   "Augusta-ME", 
"profileId":      34,
"profile":         "ATS_Edge_MKGA",
"statusId":       2,
"typeId":         11,
"updPending":     false,
"ipIsService":    true,
"ip6IsService":   false				
}
```
Then perform a GET `https://{{TO_BASE_URL}}/api/2.0/servers?id=NUMBER` . The API will return the null for ip and ip6 address
## Expected / new behavior:
1. Should return 400 with message like "an empty IP or IPv6 address cannot be marked as a service address"
2. Should return correct server info

**Comment by ocket8888** [comment]
There's also another problem with that. You said it returns 200 OK, but ignoring the fact that you made an empty IP a service address, it also, therefore, doesn't have any service addresses. It should have at least rejected it on that basis.

**Comment by dpham692** [comment]
@ocket8888 Yeah, you right about that. I just check and server still create without ip and ip6

**Comment by dpham692** [comment]
@ocket8888 Also even if user input the ipv6 and ip address in. The TP still clean out ip of the servers.
