### ISSUE TITLE
User can create a Topologies with EDGE_LOC cachegroup is a parent of MID_LOC cachegroup

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4806]
## I'm submitting a ...
- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...
- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
Using  POST `/api/3.0/topologies`, user can create a Topology where an EDGE_LOC cachegroup is a parent of a MID_LOC cachegroup just by using 3 layer cachegroup.
For example:
Do a `POST /api/3.0/topologies` with this payload:
```json
{
    "name":"test",
    "description":"test",
    "nodes":
        [
            {
                "cachegroup":"albany-ny-usa",
                "parent":{"type":"ROOT"},
                "secParent": {"name":"","type":""},
                "parents":[]
            },
            {
                "cachegroup":"mid-east",
                "parent":{"name":"albany-ny-usa","type":"MID_LOC"},
                "secParent":{"name":"","type":""},
                "parents":[0]
            },
            {
                "cachegroup":"sacramento-ca-usa",
                "parent":{"name":"mid-east","type":"EDGE_LOC"},
                "secParent":{"name":"","type":""},
                "parents":[1]
            }
        ]
}
```
API will return 200 OK. Then, upon logging in to TP, user will see this Topology with an EDGE_LOC cachegroup as a parent of a MID_LOC cachegroup.
## Expected / new behavior:
EDGE_LOC cachegroup should only have EDGE_LOC cachegroup(s) as a child(ren).

**Comment by mitchell852** [comment]
@dpham692 - what "type" is albany-ny-usa? i'm guessing it's an EDGE_LOC?

**Comment by dpham692** [comment]
@dpham692 Yes, it's EDGE_LOC.  You can also work around this bug to add 3 layer like EDGE_LOC -> ORG_LOC ->  EDGE_LOC or even 4 layer like EDGE_LOC -> ORG_LOC -> MID_LOC -> EDGE_LOC
