### ISSUE TITLE
TP: Servers table - clicking on empty cell does not trigger row click

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#4838]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:
![image](https://user-images.githubusercontent.com/251272/86137317-66cae100-baaa-11ea-826d-4ae0ba34c85f.png)

clicking on empty cell does not trigger row click ^^

## Expected / new behavior:
clicking on empty cell SHOULD trigger row click 

## Minimal reproduction of the problem with instructions:
in the servers table, find a row with an empty column, click on it.

**Comment by ocket8888** [comment]
oh, I think this is actually specific to ILO IP Address and other IP-type things. In the old table, the text included was an SSH link for those IPs, but in the new table I just made the entire cell click handle like that. So maybe this is a suggestion after all :P

**Comment by mitchell852** [comment]
yeah, i suppose if params.value is null or empty, then somehow `SSHCellRenderer` should not be used.

**Comment by mitchell852** [comment]
also wonder if #1801 should be addressed while fixing this as well.

**Comment by ocket8888** [comment]
Yeah. I didn't do it at the time, because I just wanted to replicate the current tables' behavior, but fixing both of those at once should be fine.

**Comment by mitchell852** [comment]
this issue is no longer relevant. the behavior has been changed to require a double-click to ensure that grid values can be copied w/o triggering a row click.
