### ISSUE TITLE
/cdns/capacity returns 500 error: capacity was zero

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#4848]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Visiting `/api/3.0/cdns/capacity` returns a 500 error:

```json
{
	"alerts": [
		{
			"text": "Internal Server Error",
			"level": "error"
		}
	]
}
```

## Expected / new behavior:

Should return a response like

```json
{
	"response": {
		"availablePercent": 89.0939840205533,
		"unavailablePercent": 0,
		"utilizedPercent": 10.9060020300395,
		"maintenancePercent": 1.39494071146245e-05
	}
}
```

## Minimal reproduction of the problem with instructions:

1. Start CDN-in-a-Box
2. Log into Traffic Ops
3. Visit https://trafficops.infra.ciab.test/api/3.0/cdns/capacity

## Anything else:

From the error log:
```json
ERROR: api.go:201: 2020-07-01T17:32:06.388024754Z: 192.168.48.10:55050 capacity was zero!
```

**Comment by ocket8888** [comment]
I think the reason it does that currently is to avoid dividing by zero. I don't remember the specifics of how it works, but it might be permissible to instead return zero values in that case.

**Comment by zrhoffman** [comment]
Do all of the structs in [traffic_ops/traffic_ops_golang/cdn/capacity.go](https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/cdn/capacity.go) (last modified in February in c3c313f6cf) accommodate the new interface-specific structure coming from TM? If it's not unmarshalling correctly, there won't be any data there.

**Comment by ocket8888** [comment]
Hm. Not sure. That'll need some looking-into.
