### ISSUE TITLE
Add id column in /POST cachegroups response structure and xmlid query parameter for /GET cachegroup

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4850]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [x] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

So after user create a cache group, it doesn't display any id in the response but then the rest of the cache group method are using id to navigate like `cachegroups/{{ID}}/deliveryservices` , `cachegroups/{{ID}}/parameters`. 
Right now, the only way to get the id is go to Traffic Portal and look at the URL of that cache group because you cannot /GET cachegroup with topologies or type; there will be a lot of cache group display in the result.

## Expected / new behavior:

I suggest we add id in the response of the POST `cachegroups` API and add xmlid query parameter in  /GET `cachegroups` so that if TP failed user can able to use the TO API.

**Comment by mitchell852** [comment]
@dpham692 - i'm confused by the term `xmlid` in the title. xmlid is a delivery service property.

**Comment by shamrickus** [comment]
When I create a new cache group with, it returns the id for me:
```topost -k cachegroups cachegroup.txt
{"alerts":[{"text":"cachegroup was created.","level":"success"}],
"response":{"id":112,
...}}
```

**Comment by dpham692** [comment]
@shamrickus Confirm it's display the id.
