### ISSUE TITLE
Port 443 on traffic_ops is not listen

### ISSUE THREAD

**Issue by Samirarahiqi** [apache/trafficcontrol#4852]
Hello every body. I run Traffic control components such as traffic_ops and traffic_server now I have a valid certificate on traffic_ops, when I started to use  Certificate from Certificate Authority , the port=443 is not listen on traffic_ops machine . And I suppose to have valid certificate to have a connection between ops and traffic_server . (note: at the beginning of installation before using certificate authority the port=443 was listened). Can you please help me? If you need more information for guidance, please let me know.Also I used the latest version of trafficcontrol ( V4.2.0)

**Comment by ocket8888** [comment]
Please post your entire `cdn.conf` file, if you can.

**Comment by mitchell852** [comment]
asking this question on our slack channel will get you a faster response - https://traffic-control-cdn.slack.com/
