### ISSUE TITLE
Internal Server Error when generate iso

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4874]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

Go to TP, Tools -> Generate ISO. Fill out the form and click Generate ISO.
The UI will return 500 Internal Server Error.

TO
Do a POST `https://{{TO_BASE_URL}}/api/3.0/isos` with this payload:
```
{
	"dhcp":"no",
	"interfaceMtu":9000,
	"osversionDir":"centos72",
	"hostName":"ds17-cdn-fo-oshob-03",
	"domainName":"cdn.domain.example",
	"ipAddress":"127.0.2.10",
	"ipNetmask":"255.255.255.0",
	"ipGateway":"127.0.0.0",
	"disk":"sda",
	"rootPass":"password",
	"confirmRootPass":"password",
	"interfaceName":"eth0",
	"ip6Address":null,
	"ip6Gateway":null,
	"mgmtIpAddress":null,
	"mgmtIpNetmask":null,
	"mgmtIpGateway":null
}
```
API will return a 500 Internal Server Error also.
## Expected / new behavior:

Should return 200 Success or 404 Bad Request depend on the payload.

**Comment by ocket8888** [comment]
This could be because the TO server doesn't have the right configuration or utilities to support generating ISOs. What do the logs say?

**Comment by jhg03a** [comment]
Correct.  The place where that test was run is not setup to do this test.
