### ISSUE TITLE
cache stats JSON

### ISSUE THREAD

**Issue by Samirarahiqi** [apache/trafficcontrol#4875]
## I'm submitting a ...

- [ ] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [x] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [ ] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [x] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

**Comment by Samirarahiqi** [comment]
Hello everyone , I create influxdb databases by create_ts_databases and than connect traffic stats to influxdb. I found some error logs as follows, any idea?                                           
```
[ERROR] 2020-07-12 10:05:20 could not unmarshall cache stats JSON - invalid character 'S' looking for beginning of value
[ERROR] 2020-07-12 10:05:20 could not unmarshall deliveryservice stats JSON - invalid character 'S' looking for beginning of
``` value

**Comment by ocket8888** [comment]
You'll have better luck asking support questions in our Slack channel

**Comment by dneuman64** [comment]
Hi @Samirarahiqi this error happens your Traffic Monitor is not running correctly so when Traffic Stats calls the DSStats and CacheStats API it gets a "Service Unavailable".  Can you check your TM logs and fix any errors you might see in there?

**Comment by mitchell852** [comment]
> You'll have better luck asking support questions in our Slack channel

https://traffic-control-cdn.slack.com/
