### ISSUE TITLE
Can create multiple Servers using the same profile with the same ip address for their service address

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4888]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [x] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

So right now, user can create multiple server with same profile with same ip address for their service address.
## Expected / new behavior:

It should not allow user to create the second server with same ip address for the same profile.

**Comment by mitchell852** [comment]
@bdgranger - i do believe the change in #4907 will prevent the use case you described.....but #4940 (once implemented) will then re-enable your ability to do what you want to do :)

**Comment by bdgranger** [comment]
@mitchell852 It does appear that that is the case.  Thanks!
