### ISSUE TITLE
non-standard httpsPort not appended to domain name in remap.config line

### ISSUE THREAD

**Issue by bdgranger** [apache/trafficcontrol#4894]
## I'm submitting a ...

- [x] bug report
- [ ] new feature / enhancement request
- [ ] improvement request (usability, performance, tech debt, etc.)
- [ ] other 

## Traffic Control components affected ...

- [ ] CDN in a Box
- [ ] Documentation
- [ ] Grove
- [ ] Traffic Control Client
- [ ] Traffic Monitor
- [x] Traffic Ops
- [ ] Traffic Ops ORT
- [ ] Traffic Portal
- [ ] Traffic Router
- [ ] Traffic Stats
- [ ] Traffic Vault
- [ ] unknown

## Current behavior:

ATC version 3.1.0, running on Centos7.7.

I am running multiple ATS caches on a single server in docker containers, so need to assign each container cache different tcpPort and httpsPort in order to avoid conflicts (e.g. instance 1: docker -p 10000:80 -p 11000:443; instance 2: docker -p 10002:80 -p 11002:443). I can create multiple servers through traffic ops using the same IP address but different ports.  When generating the remap.config lines for a "http and https" delivery service, traffic ops appends the tcpPort to the domain of the http line, but does not append the httpsPort to the domain in the https line.  Sample remap.config output:

**# DO NOT EDIT - Generated for bg-vedge by Traffic Ops (https://bg-cdn-to.bg-cdn.com) on Fri Jun 26 15:49:20 UTC 2020
map     http://bg-vedge.bgvirt.content.bg-cdn.com:10000/     http://www.google.com/ @plugin=header_rewrite.so @pparam=dscp/set_dscp_0.config
map     https://bg-vedge.bgvirt.content.bg-cdn.com/     http://www.google.com/ @plugin=header_rewrite.so @pparam=dscp/set_dscp_0.config**

The result is that if I attempt to fetch content through the https URL using the non-standard port, I get a "not found on server" response since no line in remap.config matches "https://bg-vedge.bgvirt.content.bg-cdn.com:11000", which is the URL I have to use to connect to that edge cache container.

## Expected / new behavior:

I would expect the https remap line to have the non-standard httpsPort appended to the domain, in the same way that the http line has the non-standard tcpPort appended.

## Minimal reproduction of the problem with instructions:

No actual caches needed to reproduce this issue, it can all be seen using only the traffic ops UI.
* Create a new edge server in the traffic ops UI, using non-standard tcpPort and httpsPort (e.g. 10000, 11000)
* Create an "http and https" delivery service and assign the newly-created server to it
* Under the servers tab, select "edit" for the newly-created server, then select "Get Config Files"
* Look under remap.config and see that the http line includes the tcpPort but the https line does not include the httpsPort

**Comment by zrhoffman** [comment]
@bdgranger Is this still an issue in ATC 7.0.1 or ATC 6.1.0?

**Comment by bdgranger** [comment]
@zrhoffman it appears this has been addressed in more recent releases. Closing this issue.  Thanks!
