### ISSUE TITLE
Can update Delivery Service to use Topology when it's already assign to a Server.

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4915]
## I'm submitting a ...

- [x]  bug report

## Traffic Control components affected ...

- [ ]  CDN in a Box
- [ ]  Documentation
- [ ]  Grove
- [ ]  Traffic Control Client
- [ ]  Traffic Monitor
- [x]  Traffic Ops
- [ ]  Traffic Ops ORT
- [x]  Traffic Portal
- [ ]  Traffic Router
- [ ]  Traffic Stats
- [ ]  Traffic Vault
- [ ]  unknown

## Current behavior:

Right now, user can update Delivery Service to use Topology when it's currently assign to a Servers.
Step to generate error on TP:
1. Create a Delivery Service, Server and Topology. Do not assign Topology to Delivery Service.
2. Link Delivery Services to Server.
3. Now, user can update Delivery Service to assign a Topology in the same CDN.

## Expected / new behavior:

 TP shouldn't let user update Delivery Service to assign a Topology when it's currently link to a Server.

**Comment by mitchell852** [comment]
This is fine actually @dpham692. We decided not to require the user to remove all assigned servers from a DS before assigning a topology. However, if a DS has BOTH a topology AND assigned servers, the topology will be used and the assigned servers will be ignored. 

This approach allows a smoother transition to topologies.

However, will all that said, the opposite is not allowed: a user cannot assign servers to a DS that has a topology assigned.
