### ISSUE TITLE
Internal Server Error when perform snapshot

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4924]
## I'm submitting a ...

- [x] bug report
-  new feature / enhancement request
-  improvement request (usability, performance, tech debt, etc.)
-  other 

## Traffic Control components affected ...

-  CDN in a Box
-  Documentation
-  Grove
-  Traffic Control Client
-  Traffic Monitor
- [x]  Traffic Ops
-  Traffic Ops ORT
- [x] Traffic Portal
-  Traffic Router
-  Traffic Stats
-  Traffic Vault
-  unknown

## Current behavior:

Snapshot failed when perform.
```
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```
## Minimal reproduction of the problem with instructions:

Should return 200 OK

**Comment by zrhoffman** [comment]
There are several references to `server.ip_address`, which was removed in #4730.

In: [/traffic_ops/traffic_ops_golang/monitoring/monitoring.go](https://github.com/apache/trafficcontrol/blob/7691d16c89/traffic_ops/traffic_ops_golang/monitoring/monitoring.go#L190):

```sql
	me.ip_address as ip,
```
In [/traffic_ops/traffic_ops_golang/server/detail.go](https://github.com/apache/trafficcontrol/blob/7691d16c89/traffic_ops/traffic_ops_golang/server/detail.go#L160):

```json
		"ip_address":       "server.ip_address",
```

In [/traffic_ops/traffic_ops_golang/cachesstats/cachesstats.go](https://github.com/apache/trafficcontrol/blob/7691d16c89/traffic_ops/traffic_ops_golang/cachesstats/cachesstats.go#L217):

```sql
  s.ip_address
```
