### ISSUE TITLE
Cannot delete Service Categories on TP

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4950]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Documentation
-  Traffic Ops

## Current behavior:

1. Create a Service Categories.
2. Try to delete it and TP will display `no serviceCategory with that key found`

Also there is no documentation to delete the service_categories
## Expected / new behavior:

User can delete the service_categories. Update delete document for service_categories on API page.

**Comment by mitchell852** [comment]
@jehunte to fix this:

https://github.com/apache/trafficcontrol/blob/master/traffic_portal/app/src/common/modules/form/serviceCategory/edit/FormEditServiceCategoryController.js#L63

`deleteServiceCategory()` is expecting the object, not the name...
