### ISSUE TITLE
TP: Provide the ability to view all servers utilized by a ds that is assigned to a topology

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#4965]
## I'm submitting a ...

-  new feature / enhancement request
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

-  Traffic Portal

## Current behavior:

Right now, a user cannot view the servers employed by a delivery services that utilizes a topology.

## Expected / new behavior:

In TP, for a delivery service that is assigned to a topology, the user should be able to see the servers that are being used for that delivery service. The user should not be able to directly assign servers to the delivery service as it is the topology itself that dictates which servers to use for the delivery service.

**Comment by zrhoffman** [comment]
Duplicate of #4559

**Comment by mitchell852** [comment]
reopening as this will be closed when #4966 is merged.
