### ISSUE TITLE
Internal Server Error when create Server without profileId

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4979]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
The `POST` handler of the `/servers` endpoint returns a `500 Internal Server Error` response when the request payload did not specify a `profileId`.

## Expected / new behavior:
It used to return 400 with a message to the effect that `profileId` is required.

## Minimal reproduction of the problem with instructions:
Create a Server using `https://{{TO_BASE_URL}}/api/3.0/servers` without `profileId`. API will return Internal Server Error.
```json
{
    "alerts": [
        {
            "text": "Internal Server Error",
            "level": "error"
        }
    ]
}
```

**Comment by rimashah25** [comment]
@mitchell852: The answer is no. Profile is a required field in TP.
