### ISSUE TITLE
User can create routing regular expression without pattern param input

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#4981]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

The POST handler of the `deliveryservices/{{ID}}/regexes` endpoint let user create routing regular expression for a Delivery Service when the request payload have a blank pattern.
## Expected / new behavior:

It should not let user create regexes and return 400 Bad Request with response message like 
```
{
    "alerts": [
        {
            "text": "malformed JSON",
            "level": "error"
        }
    ]
}
```
## Minimal reproduction of the problem with instructions:

Do a POST `https://{{TO_BASE_URL}}/api/3.0/deliveryservices/1/regexes` with this payload:
```
{
    "pattern": "",
    "type": 33,
    "setNumber": 20
}
```
Pattern input is empty and user can still create a regrexes.

**Comment by rimashah25** [comment]
@mitchell852: No, TP has it as a required field.
