### ISSUE TITLE
Unable to clone delivery services in TP

### ISSUE THREAD

**Issue by shamrickus** [apache/trafficcontrol#4992]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Portal

## Current behavior:
When cloning a delivery service, an injector error is returned by angular.

## Expected / new behavior:
No errors on cloning

## Minimal reproduction of the problem with instructions:
Clone a delivery service

## Anything else:
https://code.angularjs.org/1.8.0/docs/error/$injector/unpr?p0=topologiesProvider%20%3C-%20topologies%20%3C-%20FormNewDeliveryServiceController

**Comment by mitchell852** [comment]
good catch @shamrickus
