### ISSUE TITLE
Traffic Monitor API Change Makes Upgrading ATC Impossible

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#5001]
https://github.com/apache/trafficcontrol/commit/f2a6b5ba360f181450bc85a1c7a5d58832361037#diff-19d5dde3706497c19da9a59a2ccb15c5R165
```
type Stats struct {
	srvhttp.CommonAPIData
-	Caches map[tc.CacheName]map[string][]ResultStatVal `json:"caches"`
+	Caches map[tc.CacheName]map[string]map[string][]ResultStatVal `json:"caches"`
}
```

This struct is used in the Monitor API, `/publish/CacheStats`, which is used by clients, including Traffic Ops `/deliveryservices/{{id}}/capacity`, and possibly Traffic Router.

```
ERROR: api.go:209: 2020-09-01T17:08:30.9960088Z: 172.18.0.1:54310 getting delivery service capacity: getting CacheStats for delivery service 'my-ds' monitor 'my-monitor.my-cdn.example.net:80': decoding CacheStats from monitor 'my-monitor.my-cdn.example.net:80': json: cannot unmarshal array into Go struct field Stats.caches of type map[string][]cache.ResultStatVal
```

This makes it impossible to upgrade. Whether you upgrade TM or other things first, you break the others. But as a project, ATC supports upgrading in any order.

I see several solutions:
1. We could start versioning the Monitor API
2. we could make a new endpoint, and change things that need the new endpoint (TO. TR? Other clients) to call the new, and fall back to the old
3. We could fix all clients to try decoding both. But then we'd have to release that, before making another major release with Multi-Interface

I don't have a strong opinion. Though I would vote for 2. 
3 is pretty limiting and expensive, in terms of our release schedule.
1 is pretty expensive long-term for development. The Monitor API changes so infrequently, we've never felt the need before.
To me at least, 2 seems like the easiest solution.

## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Monitor

## Current behavior:
Monitor API has changed, breaking existing clients (TO, possibly TR or other clients).

## Expected / new behavior:
Monitor API from previous version still exists, so it's possible to upgrade the Monitor before other components. Other components also need to fall back to the existing endpoint, so they can be upgraded before the Monitor.

## Minimal reproduction of the problem with instructions:
Upgrade Traffic Ops with existing Monitors, request `/deliveryservices/{{id}}/capacity`, observe error.
Upgrade Traffic Monitor before Traffic Ops, request `/deliveryservices/{{id}}/capacity`, observe error.

**Comment by mitchell852** [comment]
@rob05c - this would probably warrant our seldom used "critical" label, no?

**Comment by rob05c** [comment]
We had a discussion about this, and realized none of the Monitor clients of that endpoint actually need interface-specific data.

So, the easiest solution is to just keep the old endpoint unchanged, and not add a new endpoint. We can always add a new endpoint in the future, if we find we need it.

We should be able to just make the monitor sum the stats for each interface, turning

`map[tc.CacheName]map[string]map[string][]ResultStatVal`

into

`map[tc.CacheName]map[string][]ResultStatVal`

**Comment by shamrickus** [comment]
This also affects Traffic Stats, on master TS will spit out a bunch of errors:
```
[ERROR] 2020-09-09 16:43:40 could not unmarshall cache stats JSON - json: cannot unmarshal object into Go struct field CacheStatsJSON.caches of type []struct { Index uint64 "json:\"index\""; Time int "json:\"time\""; Value string "json:\"value\""; Span uint64 "json:\"span\"" }
```
