### ISSUE TITLE
Traffic Control 4.0 Upgrade Fails Without Snapshot

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#5006]
Upgrading to 4.0 will bring the CDN down, until a Snapshot is done.

We usually recommend snapshotting after upgrade, but it shouldn't be required and it shouldn't bring the CDN down. Especially since it takes time for the Snapshot to propagate.

This is because 4.0 adds monitoring.json to the Snapshot (which fixes other bugs), and it's empty on upgrade.

The solution is to make the monitoring.json endpoint in Traffic Ops serve a dynamically-built monitoring.json if the database snapshot is `{}`.

This should be fixed in `master` and backported to 4.1.x, and a new 4.1.1 Release made.

I recommend coordinating with https://github.com/apache/trafficcontrol/issues/5005 to fix both in the same release.

## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
Upgrading to >4.0 breaks the CDN until a Snapshot is done, because no monitoring.json snapshot exists.

## Expected / new behavior:
Upgrading to >4.0 does not break the CDN, and a dynamically-built monitoring.json is served to Traffic Monitor until a Snapshot is performed.

## Minimal reproduction of the problem with instructions:
Upgrade to 4.x without doing a Snapshot, observe your CDN failing.

## Anything else:

**Comment by rawlinp** [comment]
Fixed in 4.1.x via https://github.com/apache/trafficcontrol/pull/5141
