### ISSUE TITLE
Reference urls for Cache Config in TP are invalid

### ISSUE THREAD

**Issue by shamrickus** [apache/trafficcontrol#5010]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Documentation
-  Traffic Portal

## Current behavior:
Currently for the Edge/Mid/First/Inner/Last Header Rewrite rules, regex remap expression, raw remap text fields on a delivery service, when hovering over the field to get a description, the hyperlink leads to a 404 page.

## Expected / new behavior:
Should not goto a 404 page, should end up on a page explaining header rewrite

## Minimal reproduction of the problem with instructions:
Look at any DS in TP and follow the reference urls.

**Comment by mitchell852** [comment]
closed with #5027
