### ISSUE TITLE
Bug that let user create two ASNs with same number in the same cachegroup

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#5020]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

1. Go to Traffic Portal
2. Click on Topology -> ASNs.
3. Create a ASNs with valid number.
4. Create another ASNs with same number in the same cache group like step 3. Notice that TP let user create it.
## Expected / new behavior:

TO and TP should not let user create 2 ASNs with same number in the same cachegroup

**Comment by jhg03a** [comment]
ASN may only belong to a single cachegroup
