### ISSUE TITLE
Traffic Portal warning when user enters unusually large CIDR

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#5038]
## I'm submitting a ...

-  new feature / enhancement request

## Traffic Control components affected ...

-  Documentation
-  Traffic Portal

## Current behavior:

Currently, a user can add an IP for a server with an unreasonable CIDR.  This is specifically true for IPv6 where CIDRs are commonly included with the IP Address. We would usually expect a /64 with an IP but a user can enter something like a /12.  This leads to issues with the way ip_allow.config is generated on caches which can result in requests being incorrectly denied.

## Expected / new behavior:

If a user enters less than a /64 for IPv6 and less than a /27 for Ipv4, Traffic Portal should show the user a warning and make sure they really want to enter a CIDR that large.

## Minimal reproduction of the problem with instructions:

Create a new server, add an IPv6 with a /30 and a IPv4 with a /24.

**Comment by mitchell852** [comment]
Not sure if this should be done in TP (before save) or in the TO API (after save)....or both. TO API probably has better IP parsing tools...

**Comment by ocket8888** [comment]
CIDR parsing is trivial to extract, though. We already have regular expressions that can match IPv4 and IPv6, and after that's known you can just extract the CIDR with a simple `parseInt(/.+\/(\d+)/.exec(ip).groups[1], 10)`.

**Comment by mitchell852** [comment]
something like this @dneuman64 ?

![image](https://user-images.githubusercontent.com/251272/93647172-040c2600-f9c5-11ea-8e2a-856c2c364150.png)
