### ISSUE TITLE
TP: allow side bar color to be configured on the server side

### ISSUE THREAD

**Issue by traeak** [apache/trafficcontrol#5050]
## I'm submitting a ...

-  new feature / enhancement request
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

-  Traffic Portal

## Expected / new behavior:

We run multiple instances of TC in addition to prod.  It would be nice to have each TP instance use different side bar color to be able to more easily differentiate between what instance a user may have open at any one time to help them not accidentally apply changes to the wrong instance.

**Comment by mitchell852** [comment]
@traeak - this can be done currently using the custom.css file that comes with TP where the color schema for each instance of TP can be overridden by writing custom styles. However, I do think it would be nice to flag an instance of TP as "production" to trigger a different style or display a "PRODUCTION" banner. How does that sound?

**Comment by traeak** [comment]
I think it's fine to do this.  The color per TP instance type is "handy" if working in more than 2 instances of TP (for us prod, staging, nightly, etc...) but real damage can only be done on prod.
