### ISSUE TITLE
Github actions Go Unit tests fail sometimes (TestGetImportProfileParameters)

### ISSUE THREAD

**Issue by srijeet0406** [apache/trafficcontrol#5060]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Control Client
-  Traffic Monitor
-  Traffic Ops

## Current behavior:

When you make a commit or create a PR, Github actions will run a set of tests on your code. The `Golang unit tests` task sometimes fails due to a couple of known culprits. Look here: https://github.com/srijeet0406/trafficcontrol/runs/1150200903
I haven't been able to reproduce this locally, but maybe if you run the test multiple times, it will eventually fail (because it seems like a race condition atm).
## Expected / new behavior:

All github action tasks pass consistently.
## Minimal reproduction of the problem with instructions:

This happens intermittently. This is one example: https://github.com/srijeet0406/trafficcontrol/runs/1150200903
## Anything else:

The failing test is:
`=== RUN   TestGetImportProfileParameters/Fail:_Storage_error_selecting_param
    TestGetImportProfileParameters/Fail:_Storage_error_selecting_param: profile_import_test.go:292: Starting test scenario:  Fail: Storage error selecting param`

**Comment by zrhoffman** [comment]
Since these are 2 separate failing tests, would you please open a separate issue for one of them?

**Comment by ocket8888** [comment]
Is this still happening? I don't see it occurring in the actions but maybe they're just circumventing it?

**Comment by zrhoffman** [comment]
It succeeds 1000 out of 1000 times for me when testing locally.

```shell
cd traffic_ops/traffic_ops_golang/profile
go test -c
failures=0
for ((i = 0; i < 1000; i++)); do
  ./profile.test test.run TestGetImportProfileParameters || (( ++failures ))
done;
echo "Failed ${failures} times out of ${i}"
```

**Comment by srijeet0406** [comment]
I haven't seen it in a long time now, closing this for now, will reopen if the issue reappears.
