### ISSUE TITLE
Github actions Go Unit tests fail sometimes (TestGetStats)

### ISSUE THREAD

**Issue by srijeet0406** [apache/trafficcontrol#5061]
## I'm submitting a ...

-  bug report
 

## Traffic Control components affected ...

-  Traffic Control Client
-  Traffic Monitor
-  Traffic Ops

## Current behavior:

When you make a commit or create a PR, Github actions will run a set of tests on your code. The Golang unit tests task sometimes fails due to a couple of known culprits. Look here: https://github.com/srijeet0406/trafficcontrol/runs/1150200903
I haven't been able to reproduce this locally, but maybe if you run the test multiple times, it will eventually fail (because it seems like a race condition atm).

## Expected / new behavior:

All github action tasks pass consistently.

## Minimal reproduction of the problem with instructions:

This happens intermittently. This is one example: https://github.com/srijeet0406/trafficcontrol/runs/1150200903

## Anything else:

The failing test is:
=== RUN TestGetStats TestGetStats: datareq_test.go:248: expected getStats TotalMemoryMB > 0, actual: '0' --- FAIL: TestGetStats (0.01s)

**Comment by ocket8888** [comment]
The line where that's failing is checking the actual memory of the machine running the test using `runtime`, so for small virtual machines dedicated to running Go unit tests and nothing else it's not unreasonable that they'd be using less than a megabyte of memory. So I think that particular expectation of the test should be removed.

**Comment by mitchell852** [comment]
> So I think that particular expectation of the test should be removed.

what do u think @srijeet0406 ?

**Comment by srijeet0406** [comment]
I agree, that test expectation can be unreasonable at times. Also, I haven't seen this issue happen for a while now, not sure if anything changed from our side.

**Comment by mitchell852** [comment]
I'm going to close. please reopen if we see this again.
