### ISSUE TITLE
Getting delivery service servers returns empty array for non-topology based delivery services

### ISSUE THREAD

**Issue by srijeet0406** [apache/trafficcontrol#5079]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  CDN in a Box
-  Traffic Ops

## Current behavior:

For a non topology based DS that has servers assigned, a call to `GET api/3.0/servers?dsId=<your ds ID>` returns an empty response.

## Expected behavior:
We should be able to see the servers associated with the delivery service in the response.

## Minimal reproduction of the problem with instructions:

Run TO (and TP) locally.
Create a non-topology based delivery service.
Assign a server to this ds.
Now try to make a call to `GET api/3.0/servers?dsId=<your ds ID>`
Notice how the response has an empty array

**Comment by rawlinp** [comment]
I think this might've been introduced in https://github.com/apache/trafficcontrol/pull/5054
