### ISSUE TITLE
ORT 4.1 not compatible with Traffic Ops 3.0.1

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#5105]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops ORT

## Current behavior:
The 1.4 API route is used and only 1.3 API is available in Traffic Ops 3.0.1

## Expected behavior:
ORT to be able to log in to our Traffic Ops

## Minimal reproduction of the problem with instructions:
- Traffic Ops 3.x
- Traffic Ops ORT 4.1

**Comment by rob05c** [comment]
Yeah, looks like the wrong client got vendored. Whatever we vendored has `apiBase = 1.4`, needs to be 1.3 for 3.0.x

**Comment by rob05c** [comment]
Fixed by https://github.com/apache/trafficcontrol/pull/5113
