### ISSUE TITLE
Traffic Stats -- Support Kafka as an output

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#5118]
## I'm submitting a ...

-  new feature / enhancement request

## Traffic Control components affected ...

-  Traffic Stats

## Current behavior:

Currently, Traffic Stats can only be configured to send TS data to InfluxDB.

## New behavior:

Traffic Stats can be configured to send data to InfluxDB, Kafka, or Both. 
The configuration will support all information needed to send to Kafka, including TLS support.

**Comment by smalenfant** [comment]
@dneuman64 We accomplished this goal by sending to telegraf and using the Kafka output. This was mostly to bridge the data to Elasticsearch. Although a direct implementation would be more robust. We used the influx_relay output to telegraf. 

```
[[inputs.influxdb_listener]]
  service_address = ":8186"
  read_timeout = "10s"
  max_body_size = 0
  database_tag = "database"

[[outputs.kafka]]
  ## URLs of kafka brokers
  brokers = ["kafka:9092"]
  topic = "telegraf"
  data_format = "json"
  
  [outputs.kafka.tagpass]
    database = ["deliveryservice_stats"]
```
