### ISSUE TITLE
Error while running github feature from .asf.yaml in trafficcontrol

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5123]
Sent to commits@trafficcontrol.apache.org (https://mail-archives.apache.org/mod_mbox/trafficcontrol-commits/202010.mbox/browser):

> An error occurred while running github feature in .asf.yaml!:
> .asf.yaml: Invalid GitHub label 'CDN' - must be lowercase alphanumerical and <= 35 characters!

Related to #5120

**Comment by rawlinp** [comment]
Interesting...I didn't realize they had to be lowercase. I'll try again.
