### ISSUE TITLE
Traffic Monitor Null Pointer Crash

### ISSUE THREAD

**Issue by rob05c** [apache/trafficcontrol#5125]
Traffic Monitor is accessing `ReqInf.RemoteAddr` without checking for `nil` here:
https://github.com/apache/trafficcontrol/blob/2609e6fc59d98ae1985f0424f28956c6970b585d/traffic_monitor/towrap/towrap.go#L346
https://github.com/apache/trafficcontrol/blob/2609e6fc59d98ae1985f0424f28956c6970b585d/traffic_monitor/towrap/towrap.go#L355

The `traffic_ops/*client*` returned `ReqInf.RemoteAddr` is guaranteed non-nil if `err==nil`, but if `err != nil`, it may be nil, depending how far the client got before it errored. It must be checked for nil before accessing. 

This causes panics and applications crashes when certain types of errors happen.

## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Monitor

## Current behavior:
Traffic Monitor crashes on certain Traffic Ops request errors.

## Expected behavior:
Traffic Monitor does not crash.

## Minimal reproduction of the problem with instructions:
Induce particular types of Traffic Ops connection errors. This was observed after downgrading a Traffic Ops from 4.1 to 3.0. But that may or may not be consistently reproducible, and is certainly not the only case which will cause a crash.

## Anything else:

**Comment by mitchell852** [comment]
seems serious. @rob05c want to apply a severity label?

**Comment by mitchell852** [comment]
> Traffic Monitor crashes on certain Traffic Ops request errors.

I added the 'need more info' label because I'm not sure this is enough to work from @rob05c

**Comment by rob05c** [comment]
Er, what more info do you need? I linked the exact lines of code causing the crash. They need nil checks.

If `GetCRConfig` returns an error, typically because of an error requesting TO, those 2 lines will panic and TM will crash. I have observed this crash, it's not just theoretical.

The fix is to change
```
remoteAddr = reqInf.RemoteAddr.String() 
```
to
```
remoteAddr := ""
if reqInf.RemoteAddr != nil {
  remoteAddr = reqInf.RemoteAddr.String()
}
```
In those 2 places.

**Comment by mitchell852** [comment]
haha. maybe i should read the _whole_ issue :)

**Comment by srijeet0406** [comment]
I'm working on this one.
