### ISSUE TITLE
TM fails to return 404

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#5129]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Monitor

## Current behavior:

TM responds to any URI path it doesn't know about with a broken http page and a 200 response code.

## Expected behavior:

TM should return a 404 for anything it doesn't handle

## Minimal reproduction of the problem with instructions:

curl -vs http://trafficmonitor-01.cdn.kabletown.invalid/something/that/doesnt/exist.foo

**Comment by mitchell852** [comment]
can u apply a severity level @jhg03a
