### ISSUE TITLE
Bug - TO right click menu on servers tab is sometimes cut off if you have reached end of list

### ISSUE THREAD

**Issue by saoyag001** [apache/trafficcontrol#5153]
## I am submitting a...

-  bug report

-  Traffic Portal Version: 4.1.0-10702.c5c3723f.el7

## Current behavior:
When reaching the end of a server list, and right clicking on the host for quick options, the popup menu gets cut off 

## Expected behavior:
menu should display above where there is room to display all options

## Minimal reproduction of the problem with instructions:
<img width="477" alt="image" src="https://user-images.githubusercontent.com/1561313/96029946-f493c780-0e20-11eb-9799-11884b788501.png">
if you notice in this image, i have both the table scrolled to the bottom and the outer page. instead of cutting off the pop up menu, it woudl be nice for it to move to the top instead of cuttign off as there is no way around it.
Test in Latest Firefox and Safari

**Comment by shamrickus** [comment]
I got this

**Comment by saoyag001** [comment]
testing in my lab works, popupa doesnt extend past the boundaries of hte window.
Thanks!
