### ISSUE TITLE
CiaB produces invalid configuration/required parameter is undocumented

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5159]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  CDN in a Box
-  Documentation
-  Traffic Ops ORT

## Current behavior:
CDN-in-a-Box's cache server Profiles are missing the required Parameter:
```json
{
	"name": "trafficserver",
	"config_file": "package",
	"value": "{{version}}-{{patch}}.{{commit hash}}.{{Enterprise Linux release}}.{{distro}}.{{CPU arch}}"
}
```

Which is also not present anywhere in documentation. If this Parameter is not present, `atstccfg` will assume that the server is using the unsupported ATS version 5.0, and will generate its configuration appropriately. This means that it will possibly generate configuration that the cache servers can't actually understand.

## Expected behavior:
`atstccfg` should be aware of the actual ATS version installed on the CiaB cache servers.

## Minimal reproduction of the problem with instructions:
Check the ORT logs for CiaB cache servers, notice that they note the ATS version as 5

**Comment by ocket8888** [comment]
These exist now, but have Values that are just `(unchanged)`. If that's handled specially, I think it's undocumented. If it isn't, then a reasonable feature request would be that it isn't required (which is covered by #6205) or that the Value be valid and correct somehow.

**Comment by zrhoffman** [comment]
> These exist now, but have Values that are just `(unchanged)`. If that's handled specially, I think it's undocumented.

CDN in a Box changes it to a valid value:
https://github.com/apache/trafficcontrol/blob/497b885614729a8eba8a2019b0cc23a9c9ef0f09/infrastructure/cdn-in-a-box/cache/run.sh#L45

https://github.com/apache/trafficcontrol/blob/497b885614729a8eba8a2019b0cc23a9c9ef0f09/infrastructure/cdn-in-a-box/cache/run.sh#L52

But yeah, we should document it. Note that our site's [downloadable](https://trafficcontrol.apache.org/downloads/profiles/6.0.x/) profiles
[already have it](https://github.com/apache/trafficcontrol-website/blob/6e76b763781f8e5caaf2e8a839319e4920302830/downloads/profiles/6.0.x/EDGE_ATS_811_CENTOS_84.traffic_ops#L2268-L2272):

```json
    {
      "configFile": "package",
      "name": "trafficserver",
      "value": "8.1.1-59.673d979d0.el8.centos.x86_64"
    },
```

**Comment by mitchell852** [comment]
can this be closed @ocket8888 @zrhoffman

**Comment by ocket8888** [comment]
No, the parameter is still undocumented

**Comment by zrhoffman** [comment]
This is it, right?

https://github.com/apache/trafficcontrol/blob/743f1d49c0047458b95e6c047363863e8120ec39/docs/source/overview/profiles_and_parameters.rst#L465-L469

It could still use an example IMO

**Comment by ocket8888** [comment]
Huh, yeah, I guess it is.
