### ISSUE TITLE
TP and TO API are validating topology name differently

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#5161]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

Right now, user can create topologies with special characters like hyphen via Topologies API below.
`https://{{TO_BASE_URL}}/api/3.0/topologies`
## Expected behavior:

TO should not let user create Topologies with special characters like hyphen
## Minimal reproduction of the problem with instructions:

Do a POST `https://{{TO_BASE_URL}}/api/3.0/topologies` with this payload:
```
{
    "name":"name_hyphen_wrong",
    "description":"test",
    "nodes":
    [{
        "cachegroup":"albany-ny-usa",
        "parent":{"type":"ROOT"},
        "secParent":{"name":"","type":""},
        "parents":[]
    }]
}
```

**Comment by ocket8888** [comment]
Or should TP's restrictions be relaxed?

**Comment by rawlinp** [comment]
I agree w/ @ocket8888 -- TP restrictions should be relaxed instead.
