### ISSUE TITLE
Global Max Mbps and Tps is not send to TM

### ISSUE THREAD

**Issue by hmahdiany** [apache/trafficcontrol#5180]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Monitor
-  Traffic Ops
-  Traffic Portal

## Current behavior:

When a value for Global Max Mbps or Global Max Tps is defined through TP these values is not sent to TM and can not be seen at "api/monitor-config", consequently when the amount of traffic which is being delivered for DS reaches those values extra traffic won't be redirected to HTTP or DNS bypass FQDN or IP.
## Expected behavior:

Values which are defined for Global Max Mbps or Global Max should be sent to TM. As a result when current DS traffic reaches those values TM is supposed to mark that DS unavailable and sent extra traffic to HTTP or DNS bypass FQDN or IP.

**Comment by ocket8888** [comment]
Anyone know if this is a regression?

**Comment by dneuman64** [comment]
It is definitely in 4.0 or 4.1, whatever he is using.  
IMO we should get this into 5.0.

**Comment by mitchell852** [comment]
severity? minor, medium, major?
