### ISSUE TITLE
TP: error message doesn't display properly when fulfilling an invalid DSR immediately

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#5188]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Portal

## Current behavior:

The error message does not display after user assign a Topology to a DS that has Required Capabilities.

## Expected behavior:

The error message should display so user know the DS is updated or not.
## Minimal reproduction of the problem with instructions:

Create a new server capability (and do not assign it to any servers), add it as a required capability to a non-topology-based DS, then try to assign a topology to that DS. The update should be prohibited but the error message does not display.

**Comment by rawlinp** [comment]
![image](https://user-images.githubusercontent.com/6724053/97060645-3cb59700-1551-11eb-8065-7a97d8d5fcd4.png)

Verified: that is what I see in the chrome dev tools view, so the TO API is properly returning a 400. However, TP is not displaying this error message at the top of the page like it should.

**Comment by mitchell852** [comment]
This should not be closed yet as a DSR is incorrectly created/completed when the update to the DS fails API validation. reopening.
