### ISSUE TITLE
TO logs warnings when generating snapshots for topology-based delivery services

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5192]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
Traffic Ops logs a warning when generating snapshots for topology-based delivery services:
```
WARNING: servers.go:364: 2020-10-26T13:35:43.892585-06:00: Creating CRConfig: deliveryservice rawl-http has no regexes, skipping
``` 

## Expected behavior:
Traffic Ops should not log this warning when generating snapshots for topology-based delivery services.

## Minimal reproduction of the problem with instructions:
Create a topology. Assign it to a delivery service. Snapshot the delivery service's CDN.

**Comment by rimashah25** [comment]
I can take this one.

**Comment by rimashah25** [comment]
Should there be any other expected behavior besides removing the warning log?

**Comment by zrhoffman** [comment]
> Should there be any other expected behavior besides removing the warning log?

Nope. Topologies work as expected, so removing the warning is sufficient.

**Comment by ocket8888** [comment]
Topologies work as expected, but would we still want to log the warning for DSes that don't use them?

**Comment by zrhoffman** [comment]
Yep

**Comment by rawlinp** [comment]
This was not fixed. I'm still seeing this in 5.1:
```
WARNING: servers.go:365: 2021-03-18T12:38:27.051636584Z: Creating CRConfig: deliveryservice testqa has no regexes, skipping
```
Yet the `testqa` DS has a topology assigned.
