### ISSUE TITLE
TP: Allow users to assign topology-based DS to ORG servers

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5197]
## I'm submitting a ...

-  new feature / enhancement request

## Traffic Control components affected ...

-  Traffic Portal

## Current behavior:

Traffic Portal prevents users from creating deliveryservice server assignments for topology-based delivery services by going to Server -> Manager Delivery Services.

## New behavior:

To support Multi-Site Origin, Delivery Services must must always be directly assignable to `ORG` servers in Traffic Portal regardless of whether or not the Delivery Service employs a topology.

## Minimal reproduction of the problem with instructions:

In Traffic Portal:
1. Create a topology
2. Create a delivery service with the topology
3. Create a server of type `ORG`
4. Try to assign the delivery service to the `ORG` server from Server -> Manage Delivery Services

**Comment by zrhoffman** [comment]
Note that this does *not* block 5.0

**Comment by mitchell852** [comment]
@zrhoffman - didn't i already to this? i forget :)

**Comment by zrhoffman** [comment]
You added TP support for assigning ORG servers to a DS in #5164. This issue is for assigning DSes to an ORG server from the Server -> Manage Delivery Services page.

**Comment by mitchell852** [comment]
> You added TP support for assigning ORG servers to a DS in #5164. This issue is for assigning DSes to an ORG server from the Server -> Manage Delivery Services page.

oh the other way around, gotcha
