### ISSUE TITLE
TP has "Link delivery services to server" button as well as under the "More" menu

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5216]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Portal

## Current behavior:
TP has two buttons that both link delivery services to a server in the `/#!/servers/id/delivery-services` page:
![image](https://user-images.githubusercontent.com/6724053/97480699-6556db80-1919-11eb-9750-339432a0c92a.png)

## Expected behavior:
The `More` menu item for linking delivery services to the server should be removed.

## Minimal reproduction of the problem with instructions:
In your TP, go to `/#!/servers/<your-server-ID>/delivery-services`.

**Comment by mitchell852** [comment]
yeah, seems redundant but is it a bug? or did I do this on purpose? :) maybe it's an "improvement" instead?

**Comment by rawlinp** [comment]
Yeah, probably an improvement rather than a bug. I almost didn't open this because it seems so trivial 😄
