### ISSUE TITLE
Generate ISO broken with IPv6 addresses

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#5237]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

When trying to use the /isos 3.0 interface with both an IPv4 and IPv6 IP specified, TO returns an error message back to TP indicating the IPv6 address is invalid when a CIDR netmask is included like normal.  Looks like at some point we accidentally made the form validation in TO no longer support IPv6 addresses with CIDR netmask.

## Expected behavior:

TO API should supply the generate script with all the necessary information

## Minimal reproduction of the problem with instructions:

Try to create an iso with a /64 netmask at the end of an IPv6 address like normal.

## Anything else:

```
alerts	[ {…} ]
0	Object { text: "decoding: invalid IP address: ffff:3333:fe2e:b::2/64", level: "error" }
text	"decoding: invalid IP address: ffff:3333:fe2e:b::2/64"
level	"error"
```

**Comment by ocket8888** [comment]
Is it working in API 2.0 and/or 1.x?

**Comment by jhg03a** [comment]
I tested with 2.x and the same results.

**Comment by ocket8888** [comment]
Should IPv6 Gateways also be allowed to have CIDR prefixes?

**Comment by jhg03a** [comment]
No
