### ISSUE TITLE
TO Go Plugin dependencies are not fetched

### ISSUE THREAD

**Issue by shamrickus** [apache/trafficcontrol#5245]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  CDN in a Box
-  Traffic Ops

## Current behavior:
If a TO Go plugin uses a dependency that needs to be fetched via `go get`, `pkg` will always fail

## Expected behavior:
TO Go plugin dependencies should be fetched.

## Minimal reproduction of the problem with instructions:

Reference a Go library in a plugin that is not already installed by the TO build.

**Comment by ocket8888** [comment]
should those not just be vendored?

**Comment by shamrickus** [comment]
Yes
