### ISSUE TITLE
Un-informative error message when creating server with non-existent Profile

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5284]
## I'm submitting a ...
-  bug report
-  other 

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
Trying to create a server with a `profileId` that doesn't belong to any existing Profile gives the error message:

> associated profile must have a cdn associated

## Expected behavior:
Should say e.g.

> "no such Profile #{{Profile ID}}"

## Minimal reproduction of the problem with instructions:
Create a server with a non-existent `profileId`.

**Comment by rimashah25** [comment]
I can take this one.
