### ISSUE TITLE
Edge case in checking server interface MTU

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5288]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
If you create a server having an interface with an MTU of exactly 1280, you get back a 500 Internal Server Error response. This is because the validation in the API checks for MTU >= 1280, but the database check is strictly MTU > 1280 (or NULL).

## Expected behavior:
The API and database constraints should be consistent - I think the intended behavior is for 1280 to be a legal value.

## Minimal reproduction of the problem with instructions:
Create a server having an interface with an MTU of exactly 1280.

**Comment by rimashah25** [comment]
I can take this one.
