### ISSUE TITLE
Log Spam from Riak services in Traffic Ops

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5291]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
Traffic Ops will sometimes emit the error:

```
ERROR: riak_services.go:343: 2020-11-17T14:10:49.716927165Z: getting riak servers: querying riak servers: sql: transaction has already been committed or rolled back
```

when encountering an error in Riak-related endpoint logic. It's probably calling `HandleErr` without returning.

## Expected behavior:
When a fatal error occurs, handling should end and no further attempts should be made to roll back the linked transaction.

## Minimal reproduction of the problem with instructions:
I think you can actually just see it in the default CDN-in-a-Box setup logs.

**Comment by rob05c** [comment]
>It's probably calling HandleErr without returning.

If it is, you should see this in the logs:
https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/api/api.go#L134

> called after a write already occurred! Not double-writing!

FWIW I've seen that `transaction has already been committed or rolled back` in the past, after strange query errors. Certain bad queries -- which didn't commit or rollback -- seem to cause all future queries on the same transaction. I don't fully understand why.

**Comment by ocket8888** [comment]
Riak KV as a backend for Traffic Vault is deprecated, so we won't be fixing this.
