### ISSUE TITLE
Column filter does not persist when multiple columns share a valueFormatter

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5294]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Portal

## Current behavior:
Navigate to https://tp.domain.tld/#!/servers and set a filter on the Reval Pending column like such:

![image](https://user-images.githubusercontent.com/251272/99455788-90639800-28e5-11eb-91c3-4673d6afa734.png)

check local storage and you should see the following entry:

```
servers_table_filters: {"revalPending":{"filterType":"text","type":"contains","filter":"true"}}
```

Refresh your browser. The filter is lost.

## Expected behavior:
Refresh your browser. The filter persists.

## Minimal reproduction of the problem with instructions:
See above

## Anything else:
The same seems to happen with the Status Last Updated and Last Updated columns. What do these things have in common? The columns share a valueFormatter (UpdateCellRenderer and dateCellFormatter respectively) with another column. That is my guess.

**Comment by shamrickus** [comment]
I will take a look at this
