### ISSUE TITLE
TP: Invalid method call to clear ag-grid table filters

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5295]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Portal

## Current behavior:
https://tp.domain.tld/#!/types/253/servers

![image](https://user-images.githubusercontent.com/251272/99458878-7d06fb80-28ea-11eb-9d3d-3c3aedd30b0a.png)

## Expected behavior:
Should be `Clear Table Filters` and call the `clearTableFilters()` function.

## Minimal reproduction of the problem with instructions:
Navigate to https://tp.domain.tld/#!/types/253/servers and try to clear the filters. It does nothing because it's calling a function (ClearColFilters()) that was renamed (clearTableFilters())

**Comment by ocket8888** [comment]
I don't think you need to re-name the button to do that. In fact, "Clear Table Filters" sounds like it'll also clear the page size and "Quick search..." filters, not just the filters on the columns. Which I don't think it does.

**Comment by mitchell852** [comment]
yeah, `Clear Table Filters` actually does clear the quick search as well..hence the reason i renamed it....but does not reset the page size (maybe it should. not sure.)

**Comment by ocket8888** [comment]
Idk I'd consider the pagination filtering for the first N results. But even if it only clears the quick search, I think that's a good rename :+1:

**Comment by shamrickus** [comment]
Fixed by #5321
