### ISSUE TITLE
Cannot update any regex in Traffic Ops/ Traffic Portal

### ISSUE THREAD

**Issue by srijeet0406** [apache/trafficcontrol#5296]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  CDN in a Box
-  Traffic Ops

## Current behavior:

If you have a regex for a delivery service, you cannot update it.
## Expected behavior:

All regexes should be updateable, with the exception of the following:
1.) If the regex in question has set number `0` and type `HOST_REGEXP`
2.) If there already is another regex with the same order.

## Minimal reproduction of the problem with instructions:

Go to Traffic Portal.
In an existing or new delivery service, try changing the pattern of a regex thats associated with this DS.
You'll notice that it fails stating that there already is another regex with the same order.
This is incorrect, because "updating" something means that it has to be already available.

**Comment by mitchell852** [comment]
so basically if you are trying to update:

```
my.regex.com, order=1
```
it's failing because it thinks something else is already in position 1? which is not true. nothing else is in postion 1 except for my.regex.com?

**Comment by srijeet0406** [comment]
Yes, thats correct. So basically all updates are disallowed currently, which is obviously wrong.

**Comment by mitchell852** [comment]
fyi as a workaround, the user can simply delete/create to update :)
