### ISSUE TITLE
When adding multiple interfaces on a server, a router host and router description shoudl also be created per interface

### ISSUE THREAD

**Issue by saoyag001** [apache/trafficcontrol#5316]
-  improvement request (usability, performance, tech debt, etc.)

-  Traffic Ops
-  Traffic Portal

## Current behavior:
When creating a second, third etc interface in to 5 only a single router hostname and router port exists.

## New behavior:
adding more interfaces require more router(s) port(s) TP should reflect this

**Comment by srijeet0406** [comment]
I can take this one.
