### ISSUE TITLE
TO pre 5.0 server list, network ip and ilo ip were clickable without going into server details.

### ISSUE THREAD

**Issue by saoyag001** [apache/trafficcontrol#5317]
-  bug report

-  Traffic Portal

## Current behavior:
in TP clicking a link in server list page(ilo/network IP) opens a new window with ssh:// and brings you to that server details page.
## Expected behavior:
in TP clicking a link in server list page (ilo/network IP) opens a new window with ssh:// and existing window remains on server list page.
## Minimal reproduction of the problem with instructions:
click on any network link from the server list page

## Anything else:
also ilo ip link should be https:// not ssh://
-->

**Comment by mitchell852** [comment]
Here are the "ip addresses" associated with a server object. 

```
ILO IP Address
ILO IP Gateway
ILO IP Netmask
IPv6 Address
IPv6 Gateway
Network IP
Network Subnet
Mgmt IP Address
Mgmt IP Gateway
Mgmt IP Netmask
```
What is the desired behavior when clicking each?

**Comment by rgresino** [comment]
ILOs tend to be Graphical although they do have CLIs in some cases.  As an SRE, I'd prefer to be able to set the desired behavior.
When I click on the ILO IP, I'd like to be able to set a static https://staticUserName@[ILO_IP_Address] or for other users that might wish ssh://$USERNAME@[ILO_IP_Address] 

I think the use case is similar for IPv6 Address and IPv4 Address in that I'd like to be able to send:  ssh://$Username@IPv4|6_Address.  

Typically we would never do anything with Netmasks or Gateways (although smaller CDN might.)

**Comment by MylesBock** [comment]
I'll take a crack at this, mostly to redeem myself to @saoyag001 for those RLR DS's about this time last year :joy_cat: 

May I be assigned this issue?

**Comment by MylesBock** [comment]
Thanks!

**Comment by MylesBock** [comment]
@rgresino I will break out that desired behavior into a separate issue

**Comment by mitchell852** [comment]
Based on the feedback, I'm going to implement this functinality:

```
IPv4 Address click takes you to ssh://$Username@IPv4_Address
IPv4 Gateway click does nothing
IPv4 Subnet click does nothing
IPv6 Address click takes you to ssh://$Username@IPv6_Address
IPv6 Gateway click does nothing
Mgmt IP Address click takes you to ssh://$Username@mgmt_ip_Address
Mgmt IP Gateway click does nothing
Mgmt IP Netmask click does nothing
ILO IP Address click takes you to https://$ILOUsername@[ILO_IP_Address] 
ILO IP Gateway click does nothing
ILO IP Netmask click does nothing
```
