### ISSUE TITLE
Rename TP server columns for IPv4 address fields

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5318]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Portal

## Current behavior:
A server's IPv4-related addresses are referred to as:

```
Network IP
Network Gateway
Network Subnet
```

They might have been named this way before IPv6 was commonly used. 

## New behavior:
Rename them to:

```
IPv4 Address
IPv4 Gateway
IPv4 Subnet
```

so it is more clear what they represent. 

## Minimal reproduction of the problem with instructions:
Navigate to https://tp.domain.tld/#!/servers and observe the IPv4 addresses mentioned above.

**Comment by rimashah25** [comment]
i can take this one.
