### ISSUE TITLE
Suppress DS consistent hash query params change log entry if nothing changed

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5333]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
Every time a DS is created or updated, the following change log entry is created when no consistent hash query params are created.

```
DS: my-ds-xml-id, ID: 999, ACTION: Created 0 consistent hash query params
```

Doesn't make much sense to me.

## New behavior:
Don't do that if nothing changed with regards to a delivery service's consistent hash query params. If it went from 0 to 1 or 1 to 0 or 2 to 4, then the change log makes sense, otherwise, nobody cares. :)

## Minimal reproduction of the problem with instructions:
Create or update a delivery service. Notice the consistent hash query params change log entry.

**Comment by rawlinp** [comment]
I agree, but even if the CHQPs change, do we care enough to give it its own changelog entry? Or is the single DS entry enough?

Also, we should probably suppress the `DS: demo, ID: 442, ACTION: Updated primary origin: demo` changelog entry if the `orgServerFqdn` wasn't changed.

**Comment by mitchell852** [comment]
> but even if the CHQPs change, do we care enough to give it its own changelog entry? Or is the single DS entry enough?

Yes, I think the DS entry is sufficient.

**Comment by mitchell852** [comment]
> Also, we should probably suppress the `DS: demo, ID: 442, ACTION: Updated primary origin: demo` changelog entry if the `orgServerFqdn` wasn't changed.

Agree. Want to create a separate issue for that @rawlinp ?

**Comment by rawlinp** [comment]
Done - https://github.com/apache/trafficcontrol/issues/5335.
