### ISSUE TITLE
Suppress "Updated primary origin" changelog entry if DS orgServerFqdn is unchanged

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5335]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
When updating a delivery service, a changelog entry is created that says "DS: foo, ID: 442, ACTION: Updated primary origin: foo" even if the DS's `orgServerFqdn` wasn't changed.

## New behavior:
The aforementioned changelog entry should only be created if the DS's `orgServerFqdn` is changed. 

## Minimal reproduction of the problem with instructions:
Create a delivery service then make any update it. See the changelog entries.

**Comment by srijeet0406** [comment]
I can take this one
