### ISSUE TITLE
Add/update SSL keys on a delivery service does not create change log entry

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5339]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
It appears that the following route does not create a change log entry:

```
{api.Version{3, 0}, http.MethodPost, `deliveryservices/sslkeys/add$`, deliveryservice.AddSSLKeys, auth.PrivLevelAdmin, Authenticated, nil, 28728785833, noPerlBypass},
```

## New behavior:
Exercise the following API route successfully:

```
{api.Version{3, 0}, http.MethodPost, `deliveryservices/sslkeys/add$`, deliveryservice.AddSSLKeys, auth.PrivLevelAdmin, Authenticated, nil, 28728785833, noPerlBypass},
```
and ensure an message like this is created:

```
DS: testqa, ID: 372, ACTION: Added/updated SSL keys
```

You should see the new entry here:

`GET api/3.0/logs`

## Minimal reproduction of the problem with instructions:
Hit the route. If it didn't create a change log entry, it needs one.

## Anything else:

Also, this endpoint:

```
{api.Version{3, 0}, http.MethodPost, `deliveryservices/sslkeys/generate/?$`, deliveryservice.GenerateSSLKeys, auth.PrivLevelOperations, Authenticated, nil, 2534390513, noPerlBypass},
```

should create an change log like:

```
DS: testqa, ID: 372, ACTION: Generated SSL keys
```

**Comment by TaylorCFrey** [comment]
I got this one

**Comment by mitchell852** [comment]
Actually, looks like generate is working:

```
DS: testqa, ID: 372, ACTION: Added SSL keys
```

Maybe that can simply be changed to "Generated SSL keys" instead of "Added"

**Comment by mitchell852** [comment]
but 


```
deliveryservices/sslkeys/add
```

is definitely not working.

**Comment by mitchell852** [comment]
and this works too

```
DS: testqa, ID: 372, ACTION: Deleted SSL keys
```

i'll update the issue
