### ISSUE TITLE
TP: Add the ability to resend a user registration from the user screen

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5340]
## I'm submitting a ...
-  improvement request

## Traffic Control components affected ...
-  Traffic Portal

## Current behavior:
Currently, you can send a user registration in TP at https://tp.domain.tld/#!/users/register. This requires an email, role and tenant for the new user. The result is a new user is created with:

- user.new_user = true.
- user.username = registration_[random_hash]
- user.email = [specified email]
- user.role = [specified role]
- user.tenant = [specified tenant]

and an email is sent to the user with a link to complete the registration(i.e. change the username and specify a desired password). Note, once the user is updated, user.new_user is set to false. the new_user flag is basically used to determine if registration is complete or not.

However, these registrations tend to never get completed. Maybe the email found its way into the users spam folder or something.

## New behavior:
On the user page (i.e. https://tp.domain.tld/#!/users/42):

1. If user.newUser = true, add a field to TP to display the user.registrationSent value
2. If user.newUser = true, add a button to 'Resend Registration' which will send the existing email, role and tenant to the POST api/users/register endpoint...which will resend the registration email and reset the registrationSent value.

**Comment by rimashah25** [comment]
I can take this one.
