### ISSUE TITLE
Downloads must use mirror system

### ISSUE THREAD

**Issue by sebbASF** [apache/trafficcontrol#5346]
The download page
https://trafficcontrol.apache.org/releases/
currently links to https://downloads.apache.org/trafficcontrol/... for the release artifacts.
Releases must use the mirror system:
https://infra.apache.org/release-download-pages.html#links

**Comment by rawlinp** [comment]
@sebbASF the source links on the website have been updated. Can you verify they're good now?

**Comment by sebbASF** [comment]
Thanks for the very prompt attention to this.
All looks good now
