### ISSUE TITLE
Flexibile topologies - provide ability to mark a topology as active/inactive

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5359]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

-  Traffic Ops
-  Traffic Portal
-  Traffic Router

## Current behavior:
No way to mark a topology as active/inactive.

## New behavior:
Provide the ability to mark a topology as active/inactive as the reality is that creating a topology could take some time and during that time a user might assign an "in progress" topology to a delivery service.

## Anything else:
- Only active topologies can be assigned to a DS. 
-- This probably requires a query param such as GET /topologies?active=true so TP can display only active ones for assignment
-- TO api validation required
- You can't change the active/inactive state of a topology currently assigned to 1+ delivery services.
- Maybe CRconfig does not include inactive topologies? not sure. or maybe it's fine to include them.

**Comment by rawlinp** [comment]
We should probably leave topologies that aren't assigned to any delivery service out of the CRConfig. It doesn't really hurt to have them in there, but if TR isn't using it yet, what's the point of having it in there?

**Comment by zrhoffman** [comment]
Would we ever want to mark a topology as inactive after _after_ you are done building it? If not, I'm not sure that a topology is the right place for that feature.

If the only issue is that the topology is a WIP, why not build it out in a different environment? Topologies use cachegroup names, so IDs should never be an issue and it should be easy to copy tops between environments that use the same set of cachegroups

**Comment by mitchell852** [comment]
> If the only issue is that the topology is a WIP, why not build it out in a different environment?

Not sure we can dictate the process for creating topologies. i.e. create in enviro A first and then copy to enviro B. And yeah, this active flag is really just a way to mark them as WIP. maybe there's a better solution...

**Comment by zrhoffman** [comment]
> Not sure we can dictate the process for creating topologies. i.e. create in enviro A first and then copy to enviro B when ready. And yeah, this active flag is really just a way to mark them as WIP. maybe there's a better solution...

That's true, it's not so convenient to make in environment A, then copy to environment B. Maybe what we really need is an *Export topology* button to show a topology's JSON and an *Import topology* button to parse a topology in TP from JSON.

**Comment by mitchell852** [comment]
> Maybe what we really need is an _Export topology_ button to show a topology's JSON and an _Import topology_ button to parse a topology in TP from JSON.

I think that's a pretty nifty feature. want to create an issue for that? but, not sure it solves the "i want to create a topology in enviro A but i don't want anyone to use it in enviro A _until_ i mark it as ready" or maybe i'm overthinking this. maybe it's just making sure your Ops team is on the same page as the group creating the topology and making sure it is communicated when the topology is ready for prime time.

**Comment by rawlinp** [comment]
I'm kind of on the fence. On one hand, I know how much pain/confusion the `active` field on DSes has caused. On the other, I do like the safety of preventing operators from assigning DSes to topologies that aren't ready yet. Safeties that don't require communication are the best kind. Then again, if you knowingly assign a topology named "DO-NOT-USE" to a delivery service, you have been fairly warned and are probably liable for any negative consequences.

**Comment by mitchell852** [comment]
> Then again, if you knowingly assign a topology named "DO-NOT-USE" to a delivery service, you have been fairly warned and are probably liable for any negative consequences

right. i'm starting to think implementing #5361 accomplishes the ability to have WIP topologies and maybe we can close this issue.

**Comment by mitchell852** [comment]
closing. naming a topology such as "my-topology-IN-PROGRESS" should suffice.
