### ISSUE TITLE
Provide the ability to change the name of a topology

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5361]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Ops
-  Traffic Portal

## Current behavior:
Currently you cannot change the name of a topology

## New behavior:
Allow the user to change the name of a topology thru the API and cascade that change to all appropriate areas. I.e. ds.toplogy

## Minimal reproduction of the problem with instructions:
In TP, navigate to an existing topology and notice that the name field is disabled.

## Anything else:
Changing a topology name will probably dirty the snapshot for that CDN in 2 places: the topology section and the delivery service section (if the topology is assigned to a ds)

**Comment by srijeet0406** [comment]
@mitchell852 I'm guessing this will involve a database migration, since the primary key for the `topology` table is its `name`.

**Comment by rawlinp** [comment]
I believe we can actually change the PK and it auto-updates the FK references.

**Comment by rimashah25** [comment]
I can take this one.
