### ISSUE TITLE
Ansible playbooks still use Traffic Ops API v1

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5377]
## I'm submitting a ...

-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

- Ansible playbooks

## Current behavior:

The following references to the Traffic Ops API in our Ansible playbooks need to be updated:

| HTTP Method | Endpoint | Line of Code |
| ----------- | -------- |:------------ |
| `POST` | `api/1.3/user/login` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/influxdb_relay.yml#L34 |
| `GET` | `api/1.3/servers` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/influxdb_relay.yml#L49 |
| * | `1.3` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L25 |
| `GET` | `internal/api/1.3/federations.json` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L743 |
| `GET` | `api/1.3/profiles/name/{{name}}/parameters` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/dataset_loader/profile.parameter.conversion.md#L23 |
| `POST` | `api/1.2/user/login` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/to_api/tasks/login.yml#L17 |
| `GET` | `api/1.2/cdns` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/to_api/tasks/queue_updates.yml#L20 |
| `POST` | `api/1.2/cdns/{{name}}/queue_update` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/to_api/tasks/queue_updates.yml#L32 |
| `GET` | `api/1.2/servers/hostname/{{name}}/details` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/to_api/tasks/set_server_status.yml#L20 |
| `PUT` | `api/1.2/servers/{{id}}/status` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/to_api/tasks/set_server_status.yml#L43 |
| `GET` | `api/1.2/cdns/{{name}}/snapshot/new` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/to_api/tasks/snapshot.yml#L67 |
| `GET` | `api/1.3/servers/checks` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/roles/traffic_portal/defaults/main.yml#L85 |
| * | `1.3` | https://github.com/apache/trafficcontrol/blob/df92555ddfa90760320c64ec619ac1c34af7f0ca/infrastructure/ansible/sample.lab/ansible/vars.yml#L28 |

## New behavior:

Those lines of code should reference API v3, reference API v4, or be removed.

See https://traffic-control-cdn.readthedocs.io/en/latest/api/migrating-from-v1.html#updating-endpoints-manually for which Traffic Ops API v3 endpoint to update each API v1 endpoint to.

**Comment by jhg03a** [comment]
There are a whole lot more 1.3 API uses in the dataset loader than are noted above.

**Comment by ragen14** [comment]
Picking this up
