### ISSUE TITLE
Trying to update a DS that doesn't exist returns an Internal Server Error

### ISSUE THREAD

**Issue by srijeet0406** [apache/trafficcontrol#5378]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  CDN in a Box
-  Traffic Ops

## Current behavior:

Try making an API call to `PUT` (update) a delivery service that doesn't exist.
You will get back an internal server error (status code 500).
If you tail the logs, you'll see that this happens because the error is `sql: no rows in result set` (which is expected)
## Expected behavior:

This action should return a 404 (not found) if the DS was not found, or maybe a 400 (bad request).
## Minimal reproduction of the problem with instructions:

Same as mentioned above
## Anything else:

I haven't checked if the other resources show a similar kind of behavior, maybe we need to check everything for this.

**Comment by mitchell852** [comment]
yep, should be 404 Not Found
