### ISSUE TITLE
ds topology + required server capabilities + assigned ORG servers not working correctly

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5380]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
GET /api/3.0/servers?dsId={{id}} does not return ORG servers directly assigned to the DS if:
1. a topology is assigned to the DS and
2. one ore more ORG servers are directly assigned to the DS and
3. the ds requires server capabilities that the ORG server(s) does not have

In fact, I don't even think you are allowed to assign server capabilities to an ORG so you'd never be able to accomplish #3.

Note: this issue also seems to affect ORT/atstccfg as the applicable line for the ds in parent.config file is missing altogether when the only parent(s) are ORG servers that don't have the necessary server capability. ORG servers are exempt from server capability filtering and should ALWAYS show up for a ds in which they are directly assigned (server capability or not) but looks like this was addressed with PR #5383 

## Expected behavior:
If I recall correctly, server capabilities are not applicable to ORG servers, therefore, for a ds with a topology AND required server capabilities:
a. show all the servers in the topology in the same cdn as the ds
b. minus the ones w/o the ds's required server caps...except for ORG servers which server caps do not apply to (if assigned, show ORG servers regardless)

## Minimal reproduction of the problem with instructions:
1. assign a topology to a DS
2. assign an ORG to the DS
3. create a server capability (https://tp.domain.tld/#!/server-capabilities) and add it to the DS as a required capability at https://tp.domain.tld/#!/delivery-services/999/required-server-capabilities
4. View the servers associated with the DS: https://tp.cdn.comcast.net/#!/delivery-services/999/servers - despite the assigned ORG server not having the DS's required server capability, it should be displayed.
5. add the server capability to one or more of the topology's servers. Now https://tp.cdn.comcast.net/#!/delivery-services/999/servers  should show the ORG plus the edges/mids that you assigned the server capability to.

**Comment by srijeet0406** [comment]
I can take this one.
