### ISSUE TITLE
Incorrect description of delivery service max dns answers in TP and documentation

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5382]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...

-  Documentation
-  Traffic Portal

## Current behavior:
Incorrect description of delivery service max dns answers found here:

1. https://traffic-control-cdn.readthedocs.io/en/latest/overview/delivery_services.html#max-dns-answers
2. On the TP DNS and HTTP delivery service forms. ie. https://tp.domain.tld/#!/delivery-services/new?type=DNS:

![image](https://user-images.githubusercontent.com/251272/102518602-bd26de80-404e-11eb-97f4-303c508d6e4e.png)

## Expected behavior:
Max DNS answers applies to both DNS* and HTTP* delivery services but I _think_ the behavior is different for each so a different description is required for each. This is probably sufficient for DNS:

```
The maximum number of Edge-tier cache server IP addresses that the Traffic Router will include in responses to DNS requests. When provided, the cache server IP addresses included are rotated in each response to spread traffic evenly. This number should scale according to the amount of traffic the Delivery Service is expected to serve.
```

Not really sure what the description is for HTTP delivery services. Must be related to ETR (edge traffic routing) somehow. Maybe @elsloo can shed some light for us :)

**Comment by rimashah25** [comment]
I can take this one

**Comment by rawlinp** [comment]
That description that @mitchell852 proposed does sound sufficient for DNS delivery services. For HTTP delivery services, I think it only overrides the `edge.http.limit` parameter when both are set: 
```
edge.http.limit | CRConfig.json | Integer that controls the default number of records returned when edge.http.routing is set to true; this can be overridden by the maxDnsAnswers delivery service setting
```
- https://traffic-control-cdn.readthedocs.io/en/latest/admin/traffic_router.html?highlight=edge.dns.limit

So maybe a good description for maxDnsAnswers in the HTTP DS form is:
```
If the Traffic Router profile parameter "edge.http.limit" is set, setting this to a non-zero value will override that parameter for this delivery service, limiting the number of Traffic Router IP addresses (A records) that are included in responses to DNS requests for this delivery service.
```
