### ISSUE TITLE
Internal Server Error when update root tenant

### ISSUE THREAD

**Issue by dpham692** [apache/trafficcontrol#5396]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Portal

## Current behavior:

1. Go to TP 
2. Click on User Admin -> Tenants
3. Try to update root tenant. Notice that it will generate Internal Server Error message
## Expected behavior:

~~TP should let user update root tenant~~
When attempting to update the immutable root tenant, the user should get a 400 Bad Request with a message along the lines of "Root tenant is immutable".
## Anything else:

ERROR: api.go:209: 2020-12-29T17:08:32.859350184Z: 96.118.16.179:37360 checking tenant authorized: sql: Scan error on column index 0, name "parent_id": converting NULL to int is unsupported

**Comment by mitchell852** [comment]
actually, when attempting to update the immutable root tenant, the user should get a 400 Bad Request instead I believe with a message along the lines of "Root tenant is immutable".

**Comment by srijeet0406** [comment]
I can take this one
