### ISSUE TITLE
1.x API permits duplicate servers

### ISSUE THREAD

**Issue by jhg03a** [apache/trafficcontrol#5407]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

Issuing the same POST request to https://{{TO_BASE_URL}}/api/1.3/servers twice creates two identical servers

## Expected behavior:

Issuing the same POST request to https://{{TO_BASE_URL}}/api/1.3/servers should succeed the first time and throw an error the second.

## Minimal reproduction of the problem with instructions:

Make a server POST request twice without changing the body.

**Comment by srijeet0406** [comment]
I can take this one
