### ISSUE TITLE
Capture/display the last time a user successfully authenticated

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5412]
## I'm submitting a ...
-  new feature / enhancement request

## Traffic Control components affected ...
-  Traffic Ops
-  Traffic Portal

## Current behavior:
TP and the TO API will not provide you with any information regarding the last time/date a user successfully authenticated. This information can be helpful when disabling users that no longer use the system. i.e. data cleanup.

## New behavior:
When a user successfully authenticates (POST /user/login), capture the time/date and provide this information via the TO api and TP similar to the way user.lastUpdated is captured. This info should be added to:

TO API:

- GET /user/current
- GET /users
- GET /user?id=

TP:

- https://tp.domain.tld/#!/users
- https://tp.domain.tld/#!/users/{id}
- https://tp.domain.tld/#!/user

**Comment by rimashah25** [comment]
I can take this one.
