### ISSUE TITLE
Servers should not allow the user to update the CDN

### ISSUE THREAD

**Issue by dmohan001c** [apache/trafficcontrol#5418]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Documentation
-  Traffic Ops
-  Traffic Portal

## Current behavior:

Traffic Portal Docs shows CDN can be updated in a server.

## Expected behavior:

The server should not allow the user to update the CDN.

## Minimal reproduction of the problem with instructions:

Document shows CDN can be updated in a Server.
https://traffic-control-cdn.readthedocs.io/en/latest/api/v3/servers_id.html

**Comment by ocket8888** [comment]
> Servers should not allow the user to update the CDN

Why not?

**Comment by mitchell852** [comment]
actually, i think this is a common use case w/ servers - switching the cdn from one to another cdn....but if the server is assigned to delivery services, this action should be blocked i think.

**Comment by dmohan001c** [comment]
Closing the ticket.
