### ISSUE TITLE
Traffic Ops should auto-calculate the max origin connections per mid 

### ISSUE THREAD

**Issue by dneuman64** [apache/trafficcontrol#5427]
## I'm submitting a ...

-  new feature / enhancement request

## Traffic Control components affected ...

-  Traffic Ops
-  Traffic Portal

## Current behavior:

Currently, if the max origin connections field is set in TO, it is only used to determine connections per server for DSs that do NOT use Mids. 

## New behavior:

If the Max Origin Connections field is set, Traffic Ops should automatically calculate the number of connections per Edge OR Mids for a DS.   This should be based on the amount of REPORTED caches.

**Comment by dneuman64** [comment]
It looks like Traffic Portal might not make that field available for all DSs, so TP might need to be fixed as well.

**Comment by ocket8888** [comment]
Also, if it currently does only apply to Edge-tier cache servers, then [the related documentation](https://traffic-control-cdn.readthedocs.io/en/latest/overview/delivery_services.html#max-origin-connections) is wrong, as it specifies that the setting applies to *Mid-tier* cache servers.

**Comment by rob05c** [comment]
ORT should be applying it to Edges for direct DSes (HTTP_LIVE, DNS_LIVE) and to Mids for DSes that use the Mids: https://github.com/apache/trafficcontrol/blob/master/lib/go-atscfg/headerrewritemiddotconfig.go#L153

Unless there's a bug. 

IMO it's better for ORT to do the calculation than TO, just because it's more canaryable.

**Comment by mitchell852** [comment]
> ORT should be calculating and applying it to Edges for direct DSes (HTTP_LIVE, DNS_LIVE) and to Mids for DSes that use the Mids: https://github.com/apache/trafficcontrol/blob/master/lib/go-atscfg/headerrewritemiddotconfig.go#L153

yeah, i thought it did this as well. I originally created this feature in TP/TO and @rob05c moved it into ORT which i believe is the right place to do the calculations.

**Comment by rawlinp** [comment]
We also need to keep topologies in mind here -- the origin connections need to be calculated based upon the number of caches in the last (non-origin) tier of the DS's topology.
