### ISSUE TITLE
Consider breaking the go-test github action down by TC component

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5437]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

-  Traffic Monitor
-  Traffic Ops
-  Traffic Ops ORT
-  Traffic Stats
-  CI tests

## Current behavior:
Currently the Go unit tests for Grove, TM, TO, ORT and TS are contained within the go-test GHA and the readme doesn't make it clear the scope of testing involved in this GHA.

## New behavior:
Consider breaking the GHA into grove-unit-tests, tm-unit-tests, to-unit-tests, ort-unit-tests, and ts-unit-tests GHAs to make it very clear the extent of testing being run against PRs and maybe speed up the feedback?

**Comment by ocket8888** [comment]
The README doesn't make it clear what the scope is because the README is for the action. The action has no scope at all, the scope is provided by the workflow.

**Comment by mitchell852** [comment]
> The README doesn't make it clear what the scope is because the README is for the action. The action has no scope at all, the scope is provided by the workflow.

oh, so should i be looking here to get a better sense of the scope of the test-related workflows: https://github.com/apache/trafficcontrol/tree/master/.github/workflows

So in that case, would it make sense instead to split out the go.unit.tests.yaml file?

**Comment by ocket8888** [comment]
Yes, that's where you should look.

I think if anything it'd be better to split the tests into jobs in a single workflow file. But to be honest it doesn't really much bother me the way it is now.

**Comment by ericholguin** [comment]
This was done in #7298
