### ISSUE TITLE
GET /api/3.x/servers?dsId=99 where ds has a topology is not filtering servers correctly

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5439]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:
GET /api/3.x/servers?dsId=99 where 99 has a topology is returning servers outside of the ds's topology.

## Expected behavior:
When a delivery service utilizes a topology, the servers returned from GET /api/3.x/servers?dsId=99 should include all edge/mid servers in the topology's cache groups:
- minus those not in the cdn of the ds
- minus those that do not have the required capabilities of the ds

it should also include any servers of type ORG that are directly assigned to the delivery service.

## Minimal reproduction of the problem with instructions:
- Assign a topology to a ds
- Navigate to the ds servers page in TP and ensure the proper servers are displayed: https://tp.domain.tld/#!/delivery-services/5/servers?type=DNS

**Comment by zrhoffman** [comment]
When a MID_LOC Cache Group is assigned as a parent of an EDGE_LOC Cache Group that is used in a Topology, `GET /servers?dsId=#` where `#` is the ID of a Delivery Service that that Topology is assigned to will result in the MID Servers in that MID_LOC Cache Group being included.
