### ISSUE TITLE
PUT /users/:id sets tm_user.registration_sent (date) to null

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5445]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
PUT /users/:id sets tm_user.registration_sent (date) to null

## Expected behavior:
PUT /users/:id should NOT touch tm_user.registration_sent (date) in any way. if it has a value, leave it. if it has no value, leave it. 

tm_user.registration_sent is set if a user is created via `POST users/register` and should never be nulled once it is set. it can, however, be updated if `POST users/register` is called again with the same email BUT it should never be nulled.

## Minimal reproduction of the problem with instructions:
- Create a user via `POST users/register` and provide email, tenant and role
- check the database for the newly created user. see that registration_sent is set to current date/time
- note the id of the newly created user
- update the newly created user via `PUT /user/:id` and notice that registration_sent is set to null. this is wrong.

**Comment by rimashah25** [comment]
I can take this one.
