### ISSUE TITLE
todb-tests GitHub action does not run the Traffic Ops DB tests

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5449]
## I'm submitting a ...

-  improvement request

## Traffic Control components affected ...

-  Traffic Ops DB
-  CI tests

## Current behavior:

The [`todb-tests` GitHub action](https://github.com/apache/trafficcontrol/blob/master/.github/actions/todb-tests) does not run our existing [Traffic Ops DB tests](https://github.com/apache/trafficcontrol/blob/master/traffic_ops_db/test/docker).

## Expected behavior:

The `todb-tests` GitHub action should run our Traffic Ops DB tests.

## Anything else:

The tests in the GitHub Action itself look valuable, consider including them in the Traffic Ops DB tests.

**Comment by ocket8888** [comment]
I think that would be an improvement, not a bug. But it should be done, regardless.

**Comment by zrhoffman** [comment]
Agreed, changed.

**Comment by srijeet0406** [comment]
@zrhoffman I can take this one
