### ISSUE TITLE
Add change log count to user response payload

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5451]
## I'm submitting a ...
-  new feature / enhancement request

## Traffic Control components affected ...
-  Traffic Ops
-  Traffic Portal

## Current behavior:
I don't believe there is a way currently via TP and/or the TO API to see how many change log entries have been created by a particular user. IMO this information would be helpful when evaluating user activity along with #5412 

## New behavior:
Do one of 2 things or maybe both:
1. Add changeLogCount to the response payload of the user TO api endpoints (this would require a join to the log table)
2. add query param support such as GET /logs?username=

## Anything else:
If this is added to the api, then it needs to be added to TP as well. I.e. 
- https://tp.domain.tld/#!/users should show the changeLogCount in the grid
- https://tp.domain.tld/#!/users/{{id}} should have a new button called 'view change logs' or something.

**Comment by ocket8888** [comment]
Per API spec guidelines if you did `GET /logs?user=someone&limit=0` then you could get back

```json
{
	"response": [],
	"summary": {
		"count": 50
	}
}
```

assuming `someone` had 50 associated changelog entries. If we implement `summary` on that endpoint, that is.

**Comment by mitchell852** [comment]
what i meant was something like this for `GET /users`

```
"response": [
      {
        "username": "my-username",
        "email": "email@email.com",
        "changeLogCount": 50,
      }
    ],
```

**Comment by rimashah25** [comment]
I can take this one.
