### ISSUE TITLE
Provide operations+ users with the ability to add a CDN-level message/alert via TP/TO API

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5460]
## I'm submitting a ...
-  new feature / enhancement request

## Traffic Control components affected ...
-  Traffic Ops
-  Traffic Portal

## Current behavior:
Currently, there is no way to create a global alert/message in TP to notify users of moratoriums, maintenance, whatever. 

## New behavior:
Provide a mechanism to create a cdn-level alert/message to communicate with all users of TP. This alert should show who created it and should be displayed in TP. Any operations+ user should be able to create and/or dismiss these messages.

**Comment by jhg03a** [comment]
Given that the input here is arbitrary and driven by humans, I don't believe this is satisfactory for automation outside the scope of ATC to accommodate for safely handling the global mutexes of queue/snap.

If the goal is to add more programmatic access around those two mutexes, it would be better served by a lock and unlock method in the API taking an arbitrary or enumerated string as to which lock you were attempting to acquire either as a human or non-human.

**Comment by mitchell852** [comment]
@jhg03a - i changed the description of this issue. it's simply a way to display an alert/message - created by humans, used by humans. nothing more. it's not really intended to be used with automation or serve as a mutex.

**Comment by mitchell852** [comment]
this was implemented with #5179
