### ISSUE TITLE
Provide filter for Serverchecks by ID

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5463]
## I'm submitting an ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
The only way to get "serverchecks" is to fetch all of them for all servers at once. If you only want/need them for one server, you must request potentially huge amounts of garbage data and then manually sift through it for the information of interest.

## New behavior:
The servercheck API route supports the `id` query parameter to get the checks for a single server.

**Comment by rimashah25** [comment]
I can take this one.

**Comment by ocket8888** [comment]
Duplicate of #3577
