### ISSUE TITLE
Settings for max origin connections changed in ATS 9.0

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5477]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Ops ORT

## Current behavior:
Currently, ORT uses a delivery service's `max_origin_connections` field to configure/override the ATS records.config setting `proxy.config.http.origin_max_connections`. In ATS 9.0, this setting was removed and replaced: https://docs.trafficserver.apache.org/en/9.0.x/release-notes/upgrading.en.html#connection-management.

## New behavior:
When generating configs for ATS < 9.0, ORT should continue to use the `proxy.config.http.origin_max_connections` setting, but for ATS >= 9.0, ORT should use the new settings instead.

**Comment by rob05c** [comment]
Fixed by https://github.com/apache/trafficcontrol/pull/5641
