### ISSUE TITLE
GET /servers?dsId={{dsId}} not filtering out cache servers (edges/mids) w/o required server capabilities

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5493]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
GET /servers?dsId={{dsId}} is returning mids that do not have the ds's required server capabilities.

## Expected behavior:
If a delivery service requires one or more server capabilities, the results of GET /servers?dsId={{dsId}} should never include cache servers (edges or mids) that do not have all of the ds's required server capabilities. ORG servers are different thanks to MSO and are returned regardless.

## Minimal reproduction of the problem with instructions:
- create a ds that employs both the edge and mid tier. i.e. a DNS delivery service
- add a required server capability to the ds
- add the same server capability to a handful of edge servers (ensure those edge servers are in a cache group that is parented by a mid cache group) and assign those edges to the ds
- GET /servers?dsId={{dsId}} and notice that mids are returned when mids were never assigned the server capability

## Anything else:
Note: this does not seem to affect the behavior of "server capabilities" which was designed to include/exclude cache servers (edges/mids) from the crconfig (snapshot) and relevant ats config files (parent.config).

**Comment by mitchell852** [comment]
looks like the root of the problem is probably in here:

https://github.com/apache/trafficcontrol/blob/master/traffic_ops/traffic_ops_golang/server/servers.go#L1218

^^ the query does not exclude mids that don't have the required server capability.

**Comment by srijeet0406** [comment]
I can take this one.
