### ISSUE TITLE
Modify existing TP tests GHA to run new TP tests

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5504]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

-  CDN in a Box
-  Traffic Portal
-  CI tests

## Current behavior:
Currently the [TP GHA](https://github.com/apache/trafficcontrol/tree/master/.github/actions/tp-e2e-tests) runs the E2E TP tests found here: https://github.com/apache/trafficcontrol/tree/master/traffic_portal/test/end_to_end

## New behavior:
the [TP GHA](https://github.com/apache/trafficcontrol/tree/master/.github/actions/tp-e2e-tests) should run the E2E TP tests found here: https://github.com/apache/trafficcontrol/tree/master/traffic_portal/test/integration

**Comment by shamrickus** [comment]
I will work on this.
