### ISSUE TITLE
GET /servers?dsId={{nonexistent DS ID}} returns 403 forbidden

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5548]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

`GET /servers?dsId={{dsId}}` returns 403 forbidden when the dsId does not correspond to a Delivery Service that exists. Examples: 0, 99999999, etc.

```json
{
	"alerts": [
		{
			"text": "Forbidden",
			"level": "error"
		}
	]
}
```

## Expected behavior:

`GET /servers?dsId=0` returns 200 OK with an empty array of servers

## Minimal reproduction of the problem with instructions:

1. Log in
2. `GET /api/4.0/servers?dsId=0` returns 200 OK with an empty array of servers

**Comment by mitchell852** [comment]
i guess its just doing the tenancy check huh? and ds=0 is in nobody's tenancy scope...

**Comment by zrhoffman** [comment]
It returns 403 Forbidden for any non-existent dsId like 999999

**Comment by srijeet0406** [comment]
@zrhoffman I can take this one
