### ISSUE TITLE
TM UI needs horizontal scrolling

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5554]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Monitor

## Current behavior:
The TM UI truncates the table so you can't see all the columns, and there is no way to scroll horizontally to view them. In the screenshot below, there are more columns to the right that are not viewable unless your screen is extremely wide.

![Screen Shot 2021-02-22 at 10 26 01 AM](https://user-images.githubusercontent.com/6724053/108745483-616a4d00-74f8-11eb-926e-2793601d6ab2.png)

## Expected behavior:
The TM UI should provide the horizontal scrolling so that all columns can be viewed.

## Minimal reproduction of the problem with instructions:
Open the TM UI in your browser.

**Comment by ocket8888** [comment]
ideally it shouldn't require horizontal scrolling imo

**Comment by rawlinp** [comment]
@ocket8888 then how do you think it should be fixed?

**Comment by ocket8888** [comment]
I think ideally the table just wouldn't be bigger than the screen

**Comment by rawlinp** [comment]
Ok so truncating columns to fixed widths?

**Comment by ocket8888** [comment]
I'd need to check out the current UI to be sure, but I think it might require word-wrapping the 'status' column. I don't think anything else should get too long.

**Comment by rawlinp** [comment]
Well, the nice thing about horizontal scrolling would be that you never have to worry about certain columns becoming too long and/or adding columns to the UI (and making it no longer fit on the screen). Plus, there will always be a screen that is too narrow to fit all the data on it at once.

**Comment by ocket8888** [comment]
That is true, but we could target screens smaller than, say, 1080 px to have horizontal scrollbars and make bigger ones wrap. I just tend to find horizontal scrollbars to be a bad UX; unintuitive and ugly.

It'd be easier to judge, though, if I could replicate this. CDN-in-a-Box displays fine on my browser on my computer; do we know what browser/screen width/table row data is causing the issue?

**Comment by rawlinp** [comment]
You may need to look at a production TM UI. I don't think it's browser specific, but it occurs in at least Chrome.

And it's mostly just a data table -- how intuitive/pretty does it need to be?

**Comment by ocket8888** [comment]
If it's just as easy to make it pretty and intuitive as not, why wouldn't you?

I found a production server I could replicate it on, issue doesn't appear to be specific to any browser or (reasonable) screen size, as you said.
