### ISSUE TITLE
TM UI and /api/cache-statuses reports aggregate bandwidth_kbps as 0 unless interfaces are monitored

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5558]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Monitor

## Current behavior:
In the TM UI, bandwidth is reported as `0` unless the server has interfaces with `monitor = true`.
![Screen Shot 2021-02-22 at 2 08 30 PM](https://user-images.githubusercontent.com/6724053/108770910-2546e480-7518-11eb-997d-8d459686340d.png)

The `/api/cache-statuses` API also has the same issue:
```
  "odol-atsmid-oshob-01": {
    "type": "MID",
    "load_average": 1.55,
    "query_time_ms": 1939,
    "health_time_ms": 1,
    "stat_time_ms": 1,
    "stat_span_ms": 5819,
    "health_span_ms": 1940,
    "status": "REPORTED - available",
    "status_poller": "health",
    "bandwidth_kbps": 0,
    "bandwidth_capacity_kbps": 1000000,
    "connection_count": 16,
    "ipv4_available": true,
    "ipv6_available": true,
    "combined_available": true,
    "interfaces": {
      "ens3": {
        "status": "available",
        "status_poller": "health",
        "bandwidth_kbps": 266,
        "available": true
      }
    }
  },
```
As you can see, this host is doing 266 kbps, but it's not showing in the UI or in the `bandwidth_kbps` field (the aggregate of all interfaces) in this API.

## Expected behavior:
The UI and /api/cache-statuses API should report the aggregate bandwidth of a server's interfaces, even if `monitor = false`.

## Minimal reproduction of the problem with instructions:
Open the TM UI and observe what I've described for servers with no monitored interfaces. Then make one or more of those interfaces monitored and observe that the bandwidth starts reporting correctly.

**Comment by srijeet0406** [comment]
@rawlinp I can take this one
