### ISSUE TITLE
TP "Assign Servers to <deliveryservice>" modal search bar is not responsive with a high number of servers

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5571]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Portal

## Current behavior:
When assigning servers to a delivery service, you typically use the search bar to narrow down your choices. However, with a high number of servers (for instance ~2500), the search bar is not responsive to user input. You type something into the bar, then your input shows up a second later with the search results.

![Screen Shot 2021-02-24 at 10 27 58 AM](https://user-images.githubusercontent.com/6724053/109040342-06b52a80-768b-11eb-859b-17634831c724.png)

## New behavior:
When typing into the search bar, user input should be displayed immediately, even if the search hasn't completed yet.

## Minimal reproduction of the problem with instructions:
In an environment with a high number of `EDGE`/`ORG` servers, go to a DS > More > Manage Servers > Assign Servers, then type into the search bar.

## Anything else:
Note: this would no longer be an issue if deliveryservice-server assignments go away in favor of Topology assignments moving forward. So if that happens before this issue is addressed, feel free to close it out.

**Comment by ocket8888** [comment]
sounds like our next ag-grid candidate.

**Comment by rawlinp** [comment]
This appears to have been ag-grid-ized.
