### ISSUE TITLE
Inconsistent Profile Name restrictions

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5576]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops
-  Traffic Portal

## Current behavior:
When cloning a Profile in Traffic Portal, the Name of the new Profile is allowed to contain spaces. On the Profile's "details" page, it is not. The Traffic Ops API doesn't care if a Profile Name contains spaces.

## Expected behavior:
The restrictions placed on Profile Name should be consistent throughout the Traffic Portal UI, and should match what is required by the Traffic Ops API. This is a bug with Traffic Portal not accepting valid Profile Names, if the intention is to allow Profile Names to contain spaces. If the intention is for Profile Names to not contain spaces, then this a bug with both Traffic Portal and Traffic Ops.

## Minimal reproduction of the problem with instructions:
Clone a Profile in Traffic Portal, put a space or two in the Name, then observe that the field is highlighted as invalid after a successful cloning.

**Comment by rawlinp** [comment]
We have profile names as path parameters, so I imagine we should prohibit spaces in the names. I'm actually surprised we don't already restrict to alphanumeric + `_` + `-` + `.`.

**Comment by ocket8888** [comment]
That'll require a migration to make existing Profiles compliant. Probably by replacing all whitespace with `_`?

**Comment by rawlinp** [comment]
We don't necessarily have to migrate existing names. It can be a new validation on profile creates/updates. If you want to update a profile, first you'd have to fix the name. Plus, the TP validation already (mostly) prohibits it.

**Comment by ocket8888** [comment]
Yeah, that's true. We wouldn't _have_ to use a migration. "Fix it on update" is fine as far as I'm concerned, as long as operators would prefer that to a migration. Though they may not care one way or the other, because since - as you said - TP validation already _mostly_ covers it so there are probably a max of like 5 Profiles in the world with this problem.
