### ISSUE TITLE
Ansible dataset loader uses removed, Perl-only endpoint POST /divisions/{name}/regions

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5580]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  [Ansible-based Lab Creation](https://github.com/apache/trafficcontrol/blob/1cd5046467/docs/source/admin/ansible-labs/ansible_labs.rst#ansible-based-lab-creation)

## Current behavior:

The Ansible dataset loader uses `POST /divisions/{name}/regions` to create regions:
https://github.com/apache/trafficcontrol/blob/1cd50464676b35dedcb41788ab99793972d85449/infrastructure/ansible/roles/dataset_loader/tasks/dataset_loader.yml#L372-L384

Because that was a Perl-only endpoint, it has been gone since #5209 removed Traffic Ops Perl.

## Expected behavior:

The Ansible dataset loader should use `POST /regions` to create Regions.

## Minimal reproduction of the problem with instructions:

1. Run dataset loader
2. See it fail due to
    ```json
    {
        "alerts": [
            {
                "level": "error", 
                "text": "The requested path '/api/1.3/divisions/Eastern/regions' does not exist."
            }
        ]
    }
    ```

**Comment by jhg03a** [comment]
This isn't a problem with the dataset loader.  It's a problem that the backward compatibility promise of the TO API is broken.  This is a problem any consumer of the API might have.  The plan to remove 1.x should not have been separate from the perlectomy if this dependency isn't going to be fixed.

**Comment by ocket8888** [comment]
It isn't separate. The two are intended for the same release. The API v1 removal is currently just waiting on the few places like this still using APIv1 - atm it's really just ORT, I think. Unless the dataset loader will also explode when that happens?

**Comment by jhg03a** [comment]
Yes, it will.

**Comment by ocket8888** [comment]
Then I'll open an issue for that as well.

**Comment by zrhoffman** [comment]
> Then I'll open an issue for that as well.

An issue (#5377) already exists to update the Ansible playbooks past API v1.

**Comment by ocket8888** [comment]
Oh, my bad.

**Comment by serDrem** [comment]
I will take care of this.
