### ISSUE TITLE
Upgrade Ansible data set loader to supported API version

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5581]
## I'm submitting a ...
- tech debt

## Traffic Control components affected ...
None/Other

## Current behavior:
Ansible data set loader uses Traffic Ops API version 1.

## Expected behavior:
Ansible data set loader should use the latest stable API version - currently 3.

## Minimal reproduction of the problem with instructions:
Notice the Ansible data set loader is using API version 1.

**Comment by zrhoffman** [comment]
Dup of #5377

**Comment by ocket8888** [comment]
Duplicate of #5377
