### ISSUE TITLE
Traffic Ops no longer serves static files

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5587]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops
-  Traffic Router

## Current behavior:

Traffic Ops Perl included a static web server for files in the `/opt/traffic_ops/app/public` directory, but Traffic Ops (Golang) does not include this functionality (and TO Perl was removed in #5209).

For several files, Traffic Router polls a URL to update that resource. Examples:

- https://github.com/apache/trafficcontrol/blob/d0b2f8ae59a11f19afed87e18eb589d60a8a8ae0/infrastructure/cdn-in-a-box/traffic_ops_data/profiles/040-CCR_CIAB.json#L14-L16
- https://github.com/apache/trafficcontrol/blob/d0b2f8ae59a11f19afed87e18eb589d60a8a8ae0/infrastructure/cdn-in-a-box/traffic_ops_data/profiles/040-CCR_CIAB.json#L29-L31

In the case of CDN in a Box, we could add a static web server to CDN in a Box and serve them from that.

If we decide to use a static web server:
- The RPM spec should no longer create the `public` directory: https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/traffic_ops/build/traffic_ops.spec#L225
- The Ansible dataset loader needs to be updated to not expect to get those files from Traffic Ops:
    * https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L28
    * https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L30
    * https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L32
    * https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L34

## Expected behavior:

We should either let Traffic Ops continue to serve static files or agree on a standard, different place to serve static files from.

## Minimal reproduction of the problem with instructions:

Visit https://trafficops.infra.ciab.test/GeoLite2-City.mmdb.gz , observe 404

**Comment by ocket8888** [comment]
Since TR can be configured to get the files from any URL, I'd vote that we leave it out of Traffic Ops itself, and maybe just make some optional plugins that you can use to serve them. Or not, and serve them elsewhere, at your own discretion.

**Comment by rawlinp** [comment]
I kind of think the convenience factor isn't really necessary. It's super easy to set up a static file server -- I don't see why TO should have to provide one itself.
