### ISSUE TITLE
GET /tools/write_crconfig/{cdn} redirects to removed /tools/flash_and_close/{message} endpoint

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5597]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

`GET /tools/write_crconfig/{cdn}` (endpoint includes no API version) redirects to `/tools/flash_and_close/{message}` (also includes no API version).

## Expected behavior:

Because `/tools/flash_and_close/{message}` was only implemented in Traffic Ops Perl and #5209 removed Traffic Ops Perl, `GET /tools/write_crconfig/{cdn}` should instead redirect to `/api/1.1/cdns/{name}/snapshot`:
https://github.com/apache/trafficcontrol/blob/f21adfd6e76d7d359ac174e2fe168b69aae2b1ba/traffic_ops/traffic_ops_golang/routing/routes.go#L1616

**Comment by rawlinp** [comment]
We really need to remove those non-API routes: https://github.com/apache/trafficcontrol/blob/f21adfd6e76d7d359ac174e2fe168b69aae2b1ba/traffic_ops/traffic_ops_golang/routing/routes.go#L1772

I would consider them part of the "v1 removal," but others may disagree.

**Comment by srijeet0406** [comment]
@zrhoffman I got this one

**Comment by srijeet0406** [comment]
@rawlinp @zrhoffman Are we tackling the removal of the non-API routes as part of this issue/ PR?

**Comment by zrhoffman** [comment]
No, those routes can be removed in #5539.
