### ISSUE TITLE
/servercheck does not filter when extra query parameters are given

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5609]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
GET requests to `/servercheck` can be filtered by ID and/or hostName, but if an extra query parameter is provided it breaks filtering. That is, `GET /servercheck?id=1` returns only the serverchecks for server 1, but `GET /servercheck?id=1&foo=bar` returns all serverchecks for all servers.

## Expected behavior:
The API should perform requested filtering and ignore all unrelated query parameters.

## Minimal reproduction of the problem with instructions:
make a GET request to `/servercheck` with an `id` query string parameter set to the ID of some cache server, plus any other query parameter (except `hostName`, `limit` or `offset`) with any value.

**Comment by rimashah25** [comment]
i'll take this one.
