### ISSUE TITLE
API GET call "/cdn_notifications" keeps giving internal server error

### ISSUE THREAD

**Issue by rimashah25** [apache/trafficcontrol#5666]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops
-  Traffic Portal

## Current behavior:

If you visit any page on Traffic Portal, we see an `500 Internal Sever Error`. On further inspection, the REST API: /cdn_notifications is the one that is giving this error.

## Expected behavior:

One shouldn't see this error.

## Minimal reproduction of the problem with instructions:

Login to Traffic Portal and you will see the error. Go to inspect element and check the network tab for HTTP status code: `500`

**Comment by rimashah25** [comment]
Issue resolved.

**Comment by zrhoffman** [comment]
For the sake of anyone who finds this page in the future, what was the issue?
