### ISSUE TITLE
TP: large CIDR warning should only warn for IPv4 masklen < 24

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5676]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Traffic Portal

## Current behavior:
In TP, if you use an IPv4 CIDR w/ a masklen < 27, you get the following warning:
![Screen Shot 2021-03-25 at 9 57 41 AM](https://user-images.githubusercontent.com/6724053/112503755-ce1f7400-8d50-11eb-8d7f-b471a40cf6b3.png)

## New behavior:
Since /24 is an extremely common IPv4 masklen, TP should really only warn if the IPv4 masklen is < 24. Also, the wording should be changed from `Large CIDR detected. IPv4 with CIDR < 27 or IPv6 with CIDR < 64 can be problematic.` to `Large CIDR block detected (IPv4 masklen < 24 or IPv6 masklen < 64)`. It shouldn't really say that "it can be problematic", when there may be valid reasons for a server to be on a network w/ a large CIDR block. Network addressing is not really within the scope of the CDN.

## Minimal reproduction of the problem with instructions:
In TP, assign a server IP address with an ipv4 masklen < 27.

**Comment by ocket8888** [comment]
> Network addressing is not really within the scope of the CDN.

Should we even have a warning at all?

**Comment by rawlinp** [comment]
I think so, because it was asked for due to someone making a typo in the masklen without realizing it IIRC.
