### ISSUE TITLE
about the error of traffic_ops postinstall db migration

### ISSUE THREAD

**Issue by edylam** [apache/trafficcontrol#5697]
Hi, when I install ATC(5.1.0) according to the documents(latest release），there is an error during db migration:

goose: migrating db environment 'production', current version: 2021010900000002, target: 2021012200000000
2021/03/31 23:17:20 FAIL 2021010900000003_server_interface_ip_address_cascade.sql (pq: constraint "ip_address_interface_fkey" of relation "ip_address" does not exist), quitting migration.
Can't run goose: exit status 1

any suggestion?

**Comment by ocket8888** [comment]
What version are you upgrading from?

**Comment by edylam** [comment]
> What version are you upgrading from?

not upgrading，just new installatioin（5.1.0）

**Comment by ocket8888** [comment]
Ah, okay. Could you tell us a bit more about your environment? OS, go version, postgresql version?

Also, I know you said 5.1.0, but are you building from the source from the 5.1.0 git tag/tarballs/RPM files in the release, or are you building from master? Until a few hours ago, master's RPMs were versioned as 5.1.0 (should be 6.0.0 as of #5702)

**Comment by edylam** [comment]
> Ah, okay. Could you tell us a bit more about your environment? OS, go version, postgresql version?
> 
> Also, I know you said 5.1.0, but are you building from the source from the 5.1.0 git tag/tarballs/RPM files in the release, or are you building from master? Until a few hours ago, master's RPMs were versioned as 5.1.0 (should be 6.0.0 as of #5702)

ok,

**Comment by ocket8888** [comment]
As of yesterday there is an update to v5.1 at tag v5.1.1 - can you replicate the problem with the latest 5.1?

**Comment by rawlinp** [comment]
Technically postgresql 13.2 is not supported in any official release yet. It's only supported in master.

**Comment by edylam** [comment]
> As of yesterday there is an update to v5.1 at tag v5.1.1 - can you replicate the problem with the latest 5.1?

ok, I will have a try.

**Comment by edylam** [comment]
> Technically postgresql 13.2 is not supported in any official release yet. It's only supported in master.

so, I should use postgresql-9.6 in ATC official release, right?

**Comment by ocket8888** [comment]
Yeah, it'll be one less thing that could be causing issues

**Comment by edylam** [comment]
> Yeah, it'll be one less thing that could be causing issues

Right. when I changed posstgresql version to 9.6, TO(v5.1.0 RPM) can be installed successfully.
The other problem is the example command line in Docs (5.1.1) still used  ATC RPM version 3.0.0, maybe should be updated.

**Comment by ocket8888** [comment]
Yes, it should probably not specify the version information at all, so that it doesn't have to be updated unless the actual process changes.
