### ISSUE TITLE
PUT /api/3.x/servers with no xmppId (hashId) results in an internal server error

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#5724]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
PUT /api/3.x/servers with no xmppId (hashId) results in an internal server error

```
ERROR: api.go:209: 2021-04-08T18:39:19.577714586Z: [ip] original server had no XMPPID
```

## Expected behavior:
No ISE. You can't change xmppId after server create so i'm not even sure why the api is checking for one.

## Minimal reproduction of the problem with instructions:
Create a server, in the db, delete the xmppId.

PUT /api/3.x/servers/your-new-server-id and you should get a 500 Internal Server Error.

## Anything else:
Workaround: add an xmppId to the db for that server and the error goes away

Also, i see lots of instances of xmppId defined like this in the documentation which is not accurate:

```
xmppId
An identifier to be used in XMPP communications with the server - in nearly all cases this will be the same as hostName
```

**Comment by rawlinp** [comment]
Yeah, I think the intent was to return an error to the user if they try to change a field that was made immutable. But in that case, the server update code should assume that a `nil` original XMPPID means that the original XMPPID is the server's `host_name` for comparison purposes.

Also, we should consider adding a DB migration to set nil/empty `xmpp_id` to `host_name`. That is what the CRConfig generation code basically does already.
