### ISSUE TITLE
`go vet`: Assignment copies lock value

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5758]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Grove

## Current behavior:

`go vet -copylocks ./...` finds 1 issue:

<table><thead><th>Message</th><th>Line of code</th></thead><tbody>

<tr><td><code>assignment copies lock value to newTransport: net/http.Transport contains sync.Mutex</code></td><td>

https://github.com/apache/trafficcontrol/blob/61e423f33b8f4b61a6228c9e3d0fbac646d231f2/grove/remap/remap.go#L500
</td></tr>
</tbody></table>

## Expected behavior:

`go vet -copylocks ./...` should find 0 issues.

## Minimal reproduction of the problem with instructions:

```shell
go vet -copylocks ./...
```

**Comment by rob05c** [comment]
This is not a bug, the copy is necessary. Do not remove the Transport copy.

I don't object to making `go vet` happy. But if someone is "fixing" this, please make sure the entire Transport is still copied. Changing it to not copy the Transport will be a serious and probably subtle bug.
