### ISSUE TITLE
`go vet`: unreachable code

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5766]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops
-  Traffic Ops ORT

## Current behavior:

`go vet -unreachable ./...` finds 2 issues:

<table><thead><th>Message</th><th>Line of code</th></thead><tbody>

<tr><td><code>unreachable code</code></td><td>

https://github.com/apache/trafficcontrol/blob/61e423f33b8f4b61a6228c9e3d0fbac646d231f2/traffic_ops_ort/plugin_verifier/plugin_verifier.go#L261
https://github.com/apache/trafficcontrol/blob/61e423f33b8f4b61a6228c9e3d0fbac646d231f2/traffic_ops/traffic_ops_golang/login/logout_test.go#L135
</td></tr>
</tbody></table>

## Expected behavior:

`go vet -unreachable ./...` should find 0 issues.

## Minimal reproduction of the problem with instructions:

```shell
go vet -unreachable ./...
```

**Comment by Ayushsunny** [comment]
Hello @zrhoffman Can I work on this?

**Comment by zrhoffman** [comment]
Go for it! Looks like @ocket8888 has already assigned you.

**Comment by Ayushsunny** [comment]
Well, Thankyou for assigning me @ocket8888 but as I am new to open source, Can you help me more to get this issue solved I mean what exactly I need to do here.

**Comment by ocket8888** [comment]
If you start from the repository root and run the command `go vet -unreachable ./...` it should tell you almost exactly what you need to do to fix it.

**Comment by Ayushsunny** [comment]
> go vet -unreachable ./...

But Sir @ocket8888 It's telling the same thing mentioned above in the issue -
![Screenshot from 2021-04-23 02-01-10](https://user-images.githubusercontent.com/73520373/115781460-08277880-a3d8-11eb-9b18-e36dc156a7d8.png)

**Comment by zrhoffman** [comment]
If you want more info on what unreachable code is, see: https://en.wikipedia.org/wiki/Unreachable_code

**Comment by Ayushsunny** [comment]
Hello @zrhoffman could you review this [PR](https://github.com/apache/trafficcontrol/pull/5823) please.

**Comment by zrhoffman** [comment]
Will do!
