### ISSUE TITLE
Traffic Ops encountering 401s on `cdn_notifications` even after a user logs out from traffic portal

### ISSUE THREAD

**Issue by srijeet0406** [apache/trafficcontrol#5787]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops
-  Traffic Portal

## Current behavior:

If you are logged in to the TP, and then log out, you'll notice that traffic ops continues to report 401s on the `cdns_notifications` endpoint

## Expected behavior:

Once the user logs out of TP, TO should not report any more 401s.

## Minimal reproduction of the problem with instructions:

Run TO and TP locally.
Tail the access logs for TO.
Log in to TP, and then log out of it
You'll notice that the TO access logs keep reporting 401s even after the user has logged out of TP
## Anything else:

Logs: 
This line occurs repeatedly:
`127.0.0.1:49869 - - [27/Apr/2021:10:57:50 -0600] "GET /api/4.0/cdn_notifications? HTTP/1.1" 401 92 0 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" 2221224514 NON_IMS`

**Comment by ocket8888** [comment]
> TO should not report any more 401s.

Because TP shouldn't be sending notification requests for unauthenticated users, right?

**Comment by srijeet0406** [comment]
> > TO should not report any more 401s.
> 
> Because TP shouldn't be sending notification requests for unauthenticated users, right?

Yes, thats correct

**Comment by mitchell852** [comment]
That cdn notification is on a timer. i just need to destroy the timer. I can take this.
