### ISSUE TITLE
Traffic Monitor API documentation is incomplete

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5799]
## I'm submitting a ...

-  bug report
-  other 

## Traffic Control components affected ...

-  Documentation
-  Traffic Monitor

## Current behavior:

Traffic Monitor `/api/` and `/publish/` endpoints are largely undocumented.

Link to documentation: https://github.com/apache/trafficcontrol/blob/f64365c3f1/docs/source/development/traffic_monitor/traffic_monitor_api.rst

## Expected behavior:

Traffic Monitor `/api/` and `/publish/` endpoints should be fully undocumented.

## Minimal reproduction of the problem with instructions:

GET Endpoint | Status
-|-
`/api/bandwidth-capacity-kbps` | Undocumented
`/api/bandwidth-kbps` | Undocumented
`/api/cache-available-count` | Undocumented
`/api/cache-count` | Undocumented
`/api/cache-down-count` | Undocumented
`/api/cache-statuses` | Undocumented
`/api/crconfig-history` | Undocumented
`/api/monitor-config` | Undocumented
`/api/traffic-ops-uri` | Undocumented
`/api/version` | Undocumented
`/publish/CacheStats` | Documented response is inaccurate
`/publish/CacheStats/{{hostname}}` | Request path is incorrect: https://github.com/apache/trafficcontrol/blob/f64365c3f1bbf0e9bc35a9502279ca1e362a7ab8/docs/source/development/traffic_monitor/traffic_monitor_api.rst#L215
`/publish/CacheStatsNew` | Undocumented
`/publish/ConfigDoc` | Response is undocumented
`/publish/CrConfig` | Response is undocumented
`/publish/CrStates` | Response is undocumented
`/publish/DsStats` | Response is undocumented
`/publish/DsStats/{{xmlId}}` | Response is undocumented
`/publish/EventLog` | Response fields `ipv4Available` and `ipv6Available` are undocumented
`/publish/PeerStates` | Response is undocumented
`/publish/Stats` | Response is undocumented
`/publish/StatSummary` | Response is undocumented

**Comment by zrhoffman** [comment]
* Added a link to the TM API documentation
* Added `/publish/CacheStats/{{hostname}}` to the list

**Comment by ocket8888** [comment]
Duplicate of #3351 ?

**Comment by zrhoffman** [comment]
Right you are. Copied the table over there, closing as a duplicate of #3351.
