### ISSUE TITLE
ORT outputs incorrect mid/inner header rewrite for Delivery Services with a Service Category

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5809]
## I'm submitting a ...
-  bug report

## Traffic Control components affected ...
-  Traffic Ops ORT

## Current behavior:
When a Delivery Service has a Service Category, ORT will output a header rewrite file (inner or mid, as appropriate for whether the DS uses a Topology) that is missing the directive to add the `CDN-SVC` HTTP header. This behavior occurs in 5.1.1 and the latest 5.1.2 Release Candidate/the head of the 5.1.x branch, but *not* at the head of master at the time of this writing.

## Expected behavior:
When a Delivery Service has a Service Category, ORT should populate the appropriate header rewrite file for that Delivery Service on mid-tier (inner) cache servers with a directive to add the `CDN-SVC` header.

## Minimal reproduction of the problem with instructions:
In CDN-in-a-Box you can observe this bug by adding a service category to the Demo 1 Delivery Service, then queuing updates on either `mid-01` or `mid-02` (or both, or their respective Cache Groups, or the entire CDN-in-a-Box CDN), then connecting to the affected host's container (with `docker exec`) and observing that `/etc/trafficserver/header_rw_inner_demo1.config` is written with a single line containing only the standard header comment. Be sure to give ORT a minute or to to run.

**Comment by rob05c** [comment]
This isn't in `master`, I think it should be a 5.1.x milestone, not 6.

So, `master` has a significant refactor of header rewrite, removing a lot of code duplication. The `5.1.x` branch has also had a lot of cherry picks out of order, so backporting new config gen changesets seem to have a lot of conflicts, and trying to fix those is dangerous and creates even more conflicts.

So, I think we should probably fix this (and any future bugs) in 5.1.x with a new changeset, and not try to backport anymore, and hopefully 5.1.x won't need much more fixing.

**Comment by zrhoffman** [comment]
Oops, my bad. Re-added to the 5.1.2 milestone

**Comment by ocket8888** [comment]
This was fixed by #5815, not really sure why it didn't auto-close...
