### ISSUE TITLE
ORT outputs incorrect mid/inner header rewrite for Delivery Services with a Service Category [5.1.x backport]

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5811]
#5809 should be considered for backport to the next 5.1.x release.

**Comment by rob05c** [comment]
See comment on https://github.com/apache/trafficcontrol/issues/5809 - I think that issue should probably be for `5.1.x`, so we probably don't need this one as well.

**Comment by zrhoffman** [comment]
Closing in favor of #5809
