### ISSUE TITLE
Ansible roles: Traffic Ops no longer serves static files 

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5816]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Ansible roles

## Current behavior:

As mentioned in #5587, Traffic Ops Perl included a static web server for files in the `/opt/traffic_ops/app/public` directory, but Traffic Ops (Golang) does not include this functionality (and TO Perl was removed in #5209). Also, `/opt/traffic_ops/public` itself was removed in #5800.

The Ansible roles still expect to get the MaxMind GeoIP database, coverage zone file, and other static files from Traffic Ops:
* https://github.com/apache/trafficcontrol/blob/b05a5e48b8a7031407de3ffffe3c4da371d02fd8/infrastructure/ansible/roles/traffic_ops/defaults/main.yml#L30
* https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L28
* https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L30
* https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L32
* https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L34
* https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L346

Also, these parameters are unused by the Go implementation of Traffic Ops:
* `tm.logourl` in the `GLOBAL` profile: https://github.com/apache/trafficcontrol/blob/b05a5e48b8a7031407de3ffffe3c4da371d02fd8/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L388-L390
* `geniso.iso_root_path` in `cdn.conf` (this is a directory where generated ISOs can be downloaded after the `POST /isos` response and in TO Perl was within `/opt/traffic_ops/public`): https://github.com/apache/trafficcontrol/blob/b05a5e48b8a7031407de3ffffe3c4da371d02fd8/infrastructure/ansible/roles/traffic_ops/templates/cdn.conf.j2#L18-L20

## Expected behavior:

* The Ansible roles should reference a new static web server that can host these files.
* `tm.logourl` in the `GLOBAL` profile and `geniso.iso_root_path` in `cdn.conf` should be removed.
* we should document the need to set up a static web server to host these files.

**Comment by jhg03a** [comment]
Since a blanket webserver is not part of the stock ATC project, there's not a better alternative.

**Comment by zrhoffman** [comment]
> Since a blanket webserver is not part of the stock ATC project

That shouldn't be an issue if we document the need to set one up.

**Comment by jhowar201** [comment]
Should the TO API endpoint also be updated to a valid version?
* https://github.com/apache/trafficcontrol/blob/eed246c7854f6f9aefab4b65ce6c35846460e8c9/infrastructure/ansible/roles/dataset_loader/defaults/main.yml#L25

**Comment by zrhoffman** [comment]
IMO only if API updates are necessary to close this Issue. The Issue for updating the Ansible roles to use TO API v4 is #5377.

That said, updating the Ansible roles to use TO API v4 seems like it could be a pretty large task, so maybe we can break #5377 into multiple Issues so we can chip away at it.

**Comment by jhg03a** [comment]
The only update that's actually necessary is that the variable default TO_URL should be swapped to localhost to conform with  other fields that have no appropriate default.
