### ISSUE TITLE
Add regex_revalidate support for MISS

### ISSUE THREAD

**Issue by traeak** [apache/trafficcontrol#5825]
## I'm submitting a ...

-  new feature / enhancement request

## Traffic Control components affected ...

-  Traffic Ops
-  Traffic Ops ORT
-  Traffic Portal
-  CI tests

## Current behavior:

No ability to force asset refetch, only refresh.

## New behavior:

A new feature will be added to the ATS regex_revalidate plugin to allow refetch in addition to just refresh.
This is based on ATS PR: https://github.com/apache/trafficserver/pull/6455

This new addition is supported to the regex_revalidate.conf file:

```
http://origin\.tld/images/foo\.jpg 1447483647 MISS
```

the keyword "STALE" may be also be used or left off for the normal regex_revalidate behavior (the next 2 are equivalent):

```
http://origin\.tld/images/foo\.jpg 1447483647
http://origin\.tld/images/foo\.jpg 1447483647 STALE
```

## Anything else:

If possible there should be a safety around this.  Worst case behavior of this could result in the refetch of an entire library and not just refreshes.  Perhaps rules can be made as stale and then "promoted" to MISS by an operator.  Any rule that is switched between MISS and STALE is reset and treated as fresh by the regex_revalidate plugin.

**Comment by TaylorCFrey** [comment]
I'll take this one!

**Comment by TaylorCFrey** [comment]
This work was completed as part of PR: https://github.com/apache/trafficcontrol/pull/6118

Good to close!
