### ISSUE TITLE
Remaining references to traffic_ops_ort in the documentation

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5838]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Documentation

## Current behavior:

After #5826, there are still references to `traffic_ops_ort` in the documentation, mostly just filenames:
https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/building.rst#L68
<strike>https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/index.rst#L30
https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.configuration.rst#L19
https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.main_routines.rst#L20
https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.packaging.rst#L19
https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.rst#L21
https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.rst#L30-L34
https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.to_api.rst#L19
https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.utils.rst#L19</strike>

## Expected behavior:

* `traffic_ops_ort_build` is now `cache-config_build`.
* <strike>Those RST files should be renamed:
    - [docs/source/development/ort/traffic_ops_ort.configuration.rst](https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.configuration.rst)
    - [docs/source/development/ort/traffic_ops_ort.main_routines.rst](https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.main_routines.rst)
    - [docs/source/development/ort/traffic_ops_ort.packaging.rst](https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.packaging.rst)
    - [docs/source/development/ort/traffic_ops_ort.rst](https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.rst)
    - [docs/source/development/ort/traffic_ops_ort.to_api.rst](https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.to_api.rst)
    - [docs/source/development/ort/traffic_ops_ort.utils.rst](https://github.com/apache/trafficcontrol/blob/577eb63803b2c511d4c7ff29b69846d25dc457c6/docs/source/development/ort/traffic_ops_ort.utils.rst)</strike>

**Comment by rob05c** [comment]
The building rst was wrong, but the `trafficcontrol/docs/source/development/ort` are all autodoc for the Python script, which still exists.
