### ISSUE TITLE
TC Cache Config RPM does not depend on `git` and `perl` unless built on RHEL 6, 7, or 8

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5898]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Control Cache Config (`t3c`) RPM spec file

## Current behavior:

Unless the RPM build distribution is RHEL 6, RHEL 7, or RHEL 8, an RPM from [`trafficcontrol-cache-config.spec`](https://github.com/apache/trafficcontrol/blob/60a9ffdcab/cache-config/build/trafficcontrol-cache-config.spec) will have no dependencies.

## Expected behavior:

`trafficcontrol-cache-config` should depend on `git` and `perl`:
https://github.com/apache/trafficcontrol/blob/f126954b4f8753ffa2be9006f996a2a971484a9a/cache-config/build/trafficcontrol-cache-config.spec#L29-L31

## Minimal reproduction of the problem with instructions:

1. Go through the steps to [build the ATC RPMs natively](https://traffic-control-cdn.readthedocs.io/en/latest/development/building.html#build-the-rpms-natively)

2. Build the TC Cache Config RPM outside of Docker, assuming you are not on CentOS 6, CentOS 7, or CentOS 8:
    ```shell
    cd infrastructure/cdn-in-a-box
    make native cache/trafficcontrol-cache-config.rpm
    rpm -q --requires cache/trafficcontrol-cache-config.rpm
    ```

    Output of `rpm -q --requires cache/trafficcontrol-cache-config.rpm` that reproduces the bug:
    ```
    /bin/sh
    /bin/sh
    /usr/bin/perl
    config(trafficcontrol-cache-config) = 6.0.0-11401.60a9ffdc.el8
    perl(Getopt::Long)
    perl(strict)
    perl(warnings)
    rpmlib(CompressedFileNames) <= 3.0.4-1
    rpmlib(FileDigests) <= 4.6.0-1
    rpmlib(PayloadFilesHavePrefix) <= 4.0-1
    rpmlib(PayloadIsXz) <= 5.2-1
    ```

**Comment by ocket8888** [comment]
based on the reproduction instructions' output, it does look like the RPM depends on a Perl interpreter at `/usr/bin/perl` as well as packages which themselves depend on Perl e.g. `perl(strict)` - do those really not result in an implicit dependency on Perl?

**Comment by zrhoffman** [comment]
That's just a result of `rpmbuild` detecting a script with a Perl shebang. We should still explicitly require the dependency until the Perl script is removed.
