### ISSUE TITLE
TO API uses non-RFC3339 date/time strings

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5911]
## I'm submitting a ...
-  other

## Traffic Control components affected ...
-  Traffic Ops
-  unknown

## Current behavior:
Traffic Ops API responses frequently return our custom format for date/times: `YYYY-MM-DD hh:mm:ss-ZZ` (`"2006-01-02 15:04:05-07"` is the actual Go format string).

## Expected behavior:
The Traffic Ops API (in the latest API version, where the behavior is breakable) should respond with RFC3339-format date strings.

## Minimal reproduction of the problem with instructions:
Make most any TO API request.

**Comment by rimashah25** [comment]
All APIs that were affected by implementing RFC3339 have been updated.

**Comment by ocket8888** [comment]
found another
