### ISSUE TITLE
Remove the /deliveryservices/request TO API endpoint

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#5921]
## I'm submitting a ...
-  other

## Traffic Control components affected ...
-  Traffic Ops

## Current behavior:
The `/deliveryservices/request` endpoint exists

## Expected behavior:
It doesn't existt

## Minimal reproduction of the problem with instructions:
Make a request to `/deliveryservices/request` at the latest API version, notice that a 404 response is not returned.

## Anything else:
This endpoint was used internally at Comcast as a part of a process that is no longer used. It represents a point of confusion with actual "Delivery Service Requests" and some additional testing and usage complexity.

**Comment by TaylorCFrey** [comment]
I'm in favor!

**Comment by ocket8888** [comment]
Regarding implementation: we could strip the functionality from all API versions at once, because that reduces the complexity immediately, and then older versions where the endpoint used to exist can return a `410 Gone` response instead of a 404. Either that, or remove it from API v4 and add deprecation notices to earlier versions.

**Comment by rawlinp** [comment]
I'm also in favor, and I think it would be fine to remove the routes without doing the `410 Gone` response or adding deprecation notices to earlier versions. As long as we have an entry in the `Removed` section of the changelog, I think that's fine.
