### ISSUE TITLE
TO API Tests GHA still starts Riak container

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#5946]
## I'm submitting a ...

-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

- GitHub Actions

## Current behavior:

The *to-integration-tests* GitHub Action starts but does not use a Riak Docker container.

## New behavior:

The Riak container should be removed.

## Minimal reproduction of the problem with instructions:

https://github.com/apache/trafficcontrol/blob/295c31e3467d13163ec4a3f87fac5450389801ec/.github/actions/to-integration-tests/entrypoint.sh#L87-L92

**Comment by bueale** [comment]
I'll take this one.
