### ISSUE TITLE
The TR docs for migrating from version 2 to 3 should be removed

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#5978]
## I'm submitting a ...
-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...
-  Documentation
-  Traffic Router

## Current behavior:
The [docs for migrating TR from version 2 to 3](https://traffic-control-cdn.readthedocs.io/en/latest/admin/traffic_router/migrationto2-3.html) are no longer relevant as the current supported versions are 4.x and 5.x (soon to be 5.x and 6.x). However, there is some good examples there for running `mvn` with the `-Djava.library.path=[tomcat native library path on your box]` argument to load the tomcat-native library (which is required).

## New behavior:
The aforementioned docs should be removed, but the example commands for running `mvn`/`java` with the `-Djava.library.path=[tomcat native library path on your box]` argument should be added to the [TR development docs](https://traffic-control-cdn.readthedocs.io/en/latest/development/traffic_router.html).

## Minimal reproduction of the problem with instructions:
Read the linked docs.

**Comment by Ayushsunny** [comment]
Hello, @rawlinp you mean [this](https://traffic-control-cdn.readthedocs.io/en/latest/admin/traffic_router/migrationto2-3.html#id1) part only which is `#57 Example Commands Specifying a Path to the tomcat-native Library` should be kept and moved to TR Development Docs and the rest of the part should be removed from right?

**Comment by ocket8888** [comment]
Yeah, that sounds about right.

**Comment by rawlinp** [comment]
Yes.
