### ISSUE TITLE
TP: click on change log entry to view in its entirety

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#6021]
## I'm submitting a ...
-  enhancement request

## Traffic Control components affected ...
-  Traffic Portal

## Current behavior:
When viewing the change log table page, e.g. `https://tp.example.org/#!/change-logs`, long messages are difficult to read, and you cannot click on the entry to open it up to view it in its entirety.

## New behavior:
I'd like to be able to click on a change log entry in the table in order to "open it up" (e.g. modal or a new page) to be able to easily read the log message in its entirety.

## Minimal reproduction of the problem with instructions:
Go to change log table page, e.g. `https://tp.example.org/#!/change-logs`, and try clicking on an entry.

## Anything else:
Personally, I don't really care if it opens a modal or a new page, I just want to be able to easily read long change log messages.

**Comment by mitchell852** [comment]
this is true of any cell that is too long in the ag-grid column - impossible to read the entire contents. gets truncated with an `...` and looks like you can only read via the onhover tooltip. maybe something that @shamrickus can add to his ag-grid component (#6031) or the next iteration of it?

**Comment by ocket8888** [comment]
FWIW this is trivial with modern Angular Material. Doesn't help current TP, though.

**Comment by mitchell852** [comment]
> FWIW this is trivial with modern Angular Material. Doesn't help current TP, though.

I added this to the TPv2 project so it doesn't get overlooked.

**Comment by mitchell852** [comment]
TPv2 is a ways out. I'm assuming this is low effort so probably worth doing.
