### ISSUE TITLE
Collapse database migrations for ATC 6

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#6027]
## I'm submitting a ...

-  improvement request (usability, performance, tech debt, etc.)

## Traffic Control components affected ...

-  Traffic Ops (database)

## Current behavior:

Our database migrations have not been collapsed since #3524 (first included in 4.0.0).

## New behavior:

We should squash database migrations in each major release, including the upcoming 6.0.0 release.

All migrations included in the 5.1.x branch should be collapsed, but migrations that will be new to the 6.0.x branch should remain uncollapsed.

**Comment by shamrickus** [comment]
I'll take a look
