### ISSUE TITLE
Add ability to assign and remove a server capability for multiple servers at a time

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#6033]
## I'm submitting a ...
-  new feature / enhancement request

## Traffic Control components affected ...
-  Traffic Ops
-  Traffic Portal

## Current behavior:
There is no way to apply a server capability to more than one server at a time (in the UI or the API). Using the API is a lot faster than using the UI to mass-assign capabilities, but it would be much easier if both the API and UI supported the ability to assign a server capability to more than one server at a time.

## New behavior:
Add the ability to mass-assign (and mass-remove) a server capability to more than one server at a time. This should probably be a new TO API route. When in Traffic Portal, going to `Configure` > `Server Capabilities` > _select server capability_  > `View servers` should be similar to how DS-server assignments are handled in TP (i.e. `Services` > `Delivery Services` > _select delivery service_ > `More` > `Manage servers` > `More` > `Assign servers`. The way you can type in the search bar to filter across all fields would be similarly useful in the case of mass-applying server capabilities.

## Minimal reproduction of the problem with instructions:
`Configure` > `Servers` > _select server_ > `More` > `manage capabilities` > `+`

**Comment by srijeet0406** [comment]
This was earlier linked to https://github.com/apache/trafficcontrol/pull/6996 and https://github.com/apache/trafficcontrol/pull/7020. However, those PRs are for adding the ability to add/remove multiple capabilities to a single server. What this issue talks about is the ability to add/ remove a capability to multiple servers at the same time.

**Comment by rimashah25** [comment]
@srijeet0406, You are right. I created a new feature request (#7078) for #6996 and #7020.
