### ISSUE TITLE
`api_capability` table is out-of-date

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#6036]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

The `api_capability` table references 89 endpoints that the Traffic Ops API does not support in any version:

HTTP Method | TO API Endpoint
-- | --
`DELETE` | `api_capabilities/*`
`GET` | `api_capabilities/*`
`POST` | `api_capabilities`
`PUT` | `api_capabilities/*`
`GET` | `asns/*`
`DELETE` | `cachegroup_fallbacks`
`GET` | `cachegroup_fallbacks`
`POST` | `cachegroup_fallbacks`
`PUT` | `cachegroup_fallbacks`
`GET` | `cachegroup/*/parameter`
`GET` | `cachegroups/*`
`GET` | `cachegroups/*/parameter/available`
`GET` | `cachegroups/trimmed`
`GET` | `cachegroups/*/unassigned_parameters`
`DELETE` | `capabilities/*`
`GET` | `capabilities/*`
`POST` | `capabilities`
`PUT` | `capabilities/*`
`GET` | `cdns/*/configfiles/ats/*`
`GET` | `cdns/configs`
`GET` | `cdns/*/configs/routing`
`GET` | `cdns/*/federations/*`
`GET` | `cdns/*`
`GET` | `cdns/name/*/dnsseckeys/delete`
`GET` | `cdns/name/*`
`PUT` | `cdns/*/snapshot`
`GET` | `cdns/usage/overview`
`GET` | `deliveryservice_matches`
`DELETE` | `deliveryservice_server/*/*`
`GET` | `deliveryservices/*`
`GET` | `deliveryservices/hostname/#hostname/sslkeys`
`GET` | `deliveryservices/*/regexes/*`
`GET` | `deliveryservices/*/state`
`GET` | `deliveryservices/*/unassigned_servers`
`GET` | `deliveryservices/xmlId/*/sslkeys/delete`
`DELETE` | `deliveryservice_user/*/*`
`POST` | `deliveryservice_user`
`GET` | `divisions/*`
`DELETE` | `divisions/name/*`
`GET` | `divisions/name/*`
`POST` | `divisions/*/regions`
`DELETE` | `federation_resolvers/*`
`GET` | `hwinfo`
`GET` | `jobs/*`
`GET` | `keys/ping`
`GET` | `logs/*/days`
`GET` | `parameters/*`
`GET` | `parameters/profile/*`
`GET` | `parameters/*/profiles`
`GET` | `parameters/*/unassigned_profiles`
`POST` | `parameters/*/validate`
`GET` | `phys_locations/*`
`GET` | `phys_locations/trimmed`
`GET` | `profiles/*/configfiles/ats/*`
`GET` | `profiles/*`
`GET` | `profiles/trimmed`
`GET` | `profiles/*/unassigned_parameters`
`DELETE` | `regions/*`
`GET` | `regions/*`
`DELETE` | `regions/name/*`
`GET` | `regions/name/*`
`POST` | `regions/*/phys_locations`
`GET` | `riak/bucket/*/key/*/values`
`GET` | `riak/ping`
`GET` | `riak/stats`
`GET` | `servers/checks`
`GET` | `servers/*/configfiles/ats`
`GET` | `servers/*/configfiles/ats/*`
`GET` | `servers/*`
`GET` | `servers/hostname/*/details`
`GET` | `servers/status`
`GET` | `servers/totals`
`POST` | `servers/*/update_status`
`PUT` | `snapshot/*`
`POST` | `stats_summary/create`
`GET` | `statuses/*`
`GET` | `steering/*/targets/*`
`GET` | `tenants/*`
`POST` | `to_extensions/*/delete`
`GET` | `to_extensions`
`POST` | `to_extensions`
`GET` | `traffic_monitor/stats`
`GET` | `types/*`
`GET` | `types/trimmed`
`GET` | `user/current/jobs`
`POST` | `user/current/jobs`
`POST` | `user/current/update`
`GET` | `users/*/deliveryservices/available`
`GET` | `users/*/deliveryservices`

The Traffic Ops API supports 53 endpoints not registered in the `api_capability` table:

HTTP Method | TO API Endpoint
-- | --
`GET` | `about`
`DELETE` | `acme_accounts/*/*`
`GET` | `acme_accounts`
`POST` | `acme_accounts`
`GET` | `acme_accounts/providers`
`PUT` | `acme_accounts`
`POST` | `acme_autorenew`
`DELETE` | `asns`
`PUT` | `asns`
`GET` | `async_status/*`
`GET` | `cache_stats`
`DELETE` | `cdn_locks`
`GET` | `cdn_locks`
`POST` | `cdn_locks`
`DELETE` | `cdn_notifications`
`GET` | `cdn_notifications`
`POST` | `cdn_notifications`
`POST` | `cdns/*/dnsseckeys/ksk/generate`
`GET` | `cdns/dnsseckeys/refresh`
`GET` | `current_stats`
`GET` | `deliveryservice_requests/*/assign`
`GET` | `deliveryservice_requests/*/status`
`DELETE` | `deliveryserviceserver/*/*`
`POST` | `deliveryservices/sslkeys/generate/acme`
`POST` | `deliveryservices/sslkeys/generate/letsencrypt`
`DELETE` | `deliveryservices/*/urlkeys`
`DELETE` | `deliveryservices/xmlId/*/sslkeys`
`POST` | `deliveryservices/xmlId/*/sslkeys/renew`
`DELETE` | `deliveryservices/xmlId/*/urlkeys`
`DELETE` | `federation_resolvers`
`GET` | `federations/all`
`POST` | `letsencrypt/autorenew`
`GET` | `letsencrypt/dnsrecords`
`GET` | `ping`
`GET` | `plugins`
`DELETE` | `regions`
`PUT` | `server_capabilities`
`DELETE` | `servercheck/extensions/*`
`GET` | `servercheck/extensions`
`POST` | `servercheck/extensions`
`GET` | `servercheck`
`GET` | `servers/*/deliveryservices`
`POST` | `servers/*/deliveryservices`
`POST` | `servers/*/update`
`GET` | `servers/*/update_status`
`PUT` | `snapshot`
`POST` | `stats_summary`
`GET` | `steering`
`DELETE` | `topologies`
`GET` | `topologies`
`POST` | `topologies`
`PUT` | `topologies`
`POST` | `topologies/*/queue_update`

## Expected behavior:

Supported endpoints and endpoints registered in the `api_capability` table should be in one-to-one correspondence. We should also consider including an additional column specifying which API version is supported (although `GET /api_capabilities` would not return this info, since the API is already versioned in the URL).

## Minimal reproduction of the problem with instructions:

```shell
api_capability_lines="$(<traffic_ops/app/db/seeds.sql sed -E '/into api_capability/I!d; s/.*(GET|POST|PUT|DELETE)'"'"', '"'"'([^'"'"']+).*/\1 \2/; s/(.*) (.*)/\2 \1/' | sort)"
routes_lines="$(<traffic_ops/traffic_ops_golang/routing/routes.go sed -E '/\{api\.Version\{/!d; s/.*Method(Get|Post|Put|Delete), `([^?$]*)[?$]*`.*/\1 \2/; s/^(Get|Post|Put|Delete)/\U&/; s|/$||; s/\{[A-Za-z_-]+\}/*/g; s/(.*) (.*)/\2 \1/' | sort | uniq)"
<<TEMPLATE cat
registered in api_capabilities table but unsupported:
$(comm -23 <(echo "$api_capability_lines") <(echo "$routes_lines"))

supported endpoints that are not registered in api_capabilities table:
$(comm -13 <(echo "$api_capability_lines") <(echo "$routes_lines"))
TEMPLATE
```

## Anything else
We should have a test to verify that the `api_capability` table is up-to-date.

**Comment by ocket8888** [comment]
If #5848 is merged that information will no longer have meaning - and then we also definitely don't want to add the API version information.

**Comment by ocket8888** [comment]
Now that #5848 is merged, should we close this as "wontfix"?

**Comment by zrhoffman** [comment]
Sounds good to me
