### ISSUE TITLE
DELETE cdns/{name}/federations/{id} takes in CDN ID in the "name" parameter

### ISSUE THREAD

**Issue by srijeet0406** [apache/trafficcontrol#6042]
## I'm submitting a ...

-  bug report

## Traffic Control components affected ...

-  Traffic Ops

## Current behavior:

The `DELETE cdns/{name}/federations/{id}` expects the CDN name as a parameter, but actually takes in the CDN ID. This is misleading and confusing to anyone who uses that API endpoint. 
## Expected behavior:

The endpoint should take in the CDN "name" for the `name` parameter, as do all the other `federation` endpoints.
## Minimal reproduction of the problem with instructions:

Run TO and TP locally
Open the `network` tab of the `inspect` console in TP so that you can see the requests 
Create a federation for one of the CDNs and then try to DELETE it
Note how the DELETE endpoint takes in the CDN ID for the `name` parameter

**Comment by ocket8888** [comment]
Unclear without investigation whether this is a regression bug or just incorrect documentation

**Comment by srijeet0406** [comment]
Turns out the issue was just in Traffic Portal, which was incorrectly using the CDN ID instead of the CDN Name. I'll fix it in my current PR, run some more tests and close this issue.

**Comment by srijeet0406** [comment]
Fixed in https://github.com/apache/trafficcontrol/pull/6043
