### ISSUE TITLE
TP: improve html links that open in a new tab/window

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#6112]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:
- Traffic Portal

## Current behavior:
Search for any instances of:

```
<a href="{{::url}}" target="_blank">
```

example:

https://github.com/apache/trafficcontrol/blob/master/traffic_portal/app/src/common/modules/form/deliveryService/form.deliveryService.DNS.tpl.html#L74

## New behavior:
add noreferrer or noreferrer to the anchor.

**Comment by nickmancari** [comment]
I can work on this. I'd love to help!

**Comment by zrhoffman** [comment]
Assigned!
