### ISSUE TITLE
Inefficient regular expression in Traffic Portal

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#6114]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Portal

## Current behavior:

Traffic Portal has an inefficient regular expression:

https://github.com/apache/trafficcontrol/blob/46a279204af553c51cee69bd03a6fbba2589208b/experimental/traffic-portal/src/app/components/new-delivery-service/new-delivery-service.component.ts#L56-L56

This part, in particular, runs in exponential time:

```regex
([A-z0-9\-]*[A-z0-9])*
```

## New behavior:

The regex should be rewritten to be more efficient.

**Comment by adnanahmed999** [comment]
Hello, Sir can I work on this issue ?

**Comment by zrhoffman** [comment]
It's all yours!

**Comment by adnanahmed999** [comment]
Sir, I am new to Open Source. I wanted to ask that in how much time do I have to fix this ?

**Comment by ocket8888** [comment]
That's an experimental component; you have as long as you want.

**Comment by zrhoffman** [comment]
How is a week to look at the issue? If you don't submit a PR within a week, that is fine, but please leave a comment if a week goes by and you're still looking at it so we don't end up assigning it to someone else.

**Comment by adnanahmed999** [comment]
Ok Sir, I will try to complete it as early as possible. I have worked on regex earlier, but in that project, the complexity did not mattered much. As much I understood the problem statement, I have to optimize the complexity of  ([A-z0-9\-]*[A-z0-9])* part.
Could you please suggest me some docs which I should go through first (especially related to complexity part)  before start working on it.

**Comment by zrhoffman** [comment]
> As much I understood the problem statement, I have to optimize the complexity of ([A-z0-9-][A-z0-9]) part.

Don't feel like you can only change that part. If you end up changing the whole thing, and it does end up optimizing the `([A-z0-9\-]*[A-z0-9])*` part, that is just as good.

> Could you please suggest me some docs which I should go through first (especially related to complexity part) before start working on it.

The inefficiency in this regex that needs to be optimized is called *backtracking*. If you Google *regex backtracking*, you should come across some good resources.

**Comment by adnanahmed999** [comment]
Ok Sir.

**Comment by adnanahmed999** [comment]
Hello Sir, I think the regex is not properly coded.
Here the range specified in bracket is [A-z], which means it will  match any ASCII characters in the range from A to z. Thus it will consider signs such as [  \  ] ^  _ `  in our hostname  which we dont want.
Thus it should be [a-zA-Z] instead of [A-z]. Also a better regex can be formed but I want to point this first.

**Comment by adnanahmed999** [comment]
@zrhoffman  Hello Sir, did you get my point ?

**Comment by zrhoffman** [comment]
@adnanahmed999 Yep you are right, and that is a bug. Feel free to fix that part, too, no reason to leave the character class broken.

**Comment by mitchell852** [comment]
@adnanahmed999 are you still working on this one?
