### ISSUE TITLE
Fix /cdns/{name}/federations?id=# to search for CDN

### ISSUE THREAD

**Issue by mattjackson220** [apache/trafficcontrol#6125]
## This Bug Report affects these Traffic Control components:

- Traffic Ops

## Current behavior:

The API endpoint `/cdns/{name}/federations?id=#` will return the federations information as long as the id is valid, even if the CDN is not valid or does not exist or the federation is not part of that CDN.  

## Expected behavior:

That endpoint should only return the information for federations within the CDN provided

## Steps to reproduce:

Go to the API at `/cdns/nonsense/federations?id=#` with a valid federation id and see that it returns the information even though `nonsense` is not a valid CDN

**Comment by srijeet0406** [comment]
@mattjackson220 I can take this one.
