### ISSUE TITLE
Docs for /users has incorrect field name

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#6130]
## This Bug Report affects these Traffic Control components:
- Documentation

## Current behavior:
The docs say that there's a field containing the Name of the User's Role called `roleName`.

## Expected behavior:
The docs should accurately document the API's output.

## Steps to reproduce:
`toget -kp 'users?limit=1' | jq '.response[0]'` - returns:
```json
{
        "rolename": "admin",
        "username": "admin",
        "registrationSent": null,
        "addressLine1": null,
        "addressLine2": null,
        "city": null,
        "company": null,
        "country": null,
        "email": null,
        "fullName": null,
        "gid": null,
        "id": 2,
        "newUser": false,
        "phoneNumber": null,
        "postalCode": null,
        "publicSshKey": null,
        "role": 1,
        "stateOrProvince": null,
        "tenant": "root",
        "tenantId": 1,
        "uid": null,
        "lastUpdated": "2021-08-20 17:47:38+00"
}
```

Note the field name is `rolename`, not `roleName`.

It's unclear whether this is a regression without digging further into git history than I feel like doing right now, but I think that's unlikely, and it's probably just that the docs have been copied with each successive major API version release from the previous version since v2 was added, and the GoDoc for the field on the `lib/go-tc` struct related to API User representations mentions a difference between API versions in the name of that property. Interestingly, though, the API docs for v2 get the name right, while v3 and v4 both use the incorrect camelCase form.

**Comment by Ayushsunny** [comment]
Hey @ocket8888 can you guide me a bit more for this issue as I want to work on this?

**Comment by Ayushsunny** [comment]
Hey, @ocket8888 Can I pick this?

**Comment by ocket8888** [comment]
sure, all yours

**Comment by Ayushsunny** [comment]
> `toget` is a script provided by the [Python client](https://github.com/apache/trafficcontrol/tree/master/traffic_control/clients/python) which you probably don't have installed. You probably don't have `jq` installed either, I would guess.
> 
> Some API versions are documented as outputting objects containing a `rolename` field when actually those endpoints output objects that have a field named `roleName`, so they'll need to be updated wherever that's wrong. According to the issue, that's in the documentation for `/users` in API versions 3 and 4. But that may have changed for API v4 since the issue was written. Also, it's unclear whether `/user/current` has the same issue.

Now I'm getting this `"Traffic Ops hostname not set! Set the TO_URL environment variable or use '--to-url'."` ?
