### ISSUE TITLE
TP: TLS Supported Versions not captured in delivery service request (DSR)

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#6168]
## This Bug Report affects these Traffic Control components:
- Traffic Ops
- Traffic Portal

## Current behavior:
Making a change to the "Restrict TLS Versions" field and adding or removing supported TLS versions is not reflected in the generated DSR (delivery service request).

Change made to the DS:

![image](https://user-images.githubusercontent.com/251272/132400489-9754c4c4-58ed-4c97-8fe5-55af60a52245.png)

Change reflected in the DSR:

![image](https://user-images.githubusercontent.com/251272/132400508-51b4e370-bc0b-4699-a7ba-f84bdccea0b4.png)

## Expected behavior:
The change should be reflected in the DSR.

## Steps to reproduce:
1. Enable delivery service requests in traffic_portal_properties.json
2. start up TP
3. make a change to a delivery service. specifically the "Restrict TLS Versions" value and add or remove supported TLS versions. Save.
4. Check the generated DSR and note that the change is not reflected.

**Comment by rawlinp** [comment]
If you complete the DSR, does it actually update the underlying DS w/ those changes?

**Comment by mitchell852** [comment]
> If you complete the DSR, does it actually update the underlying DS w/ those changes?

yeah, the change goes through, it's just not reflect in the UI in the DSR....so that's good at least...
