### ISSUE TITLE
t3c: Status API fails because FQDN is used as a hostname

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#6174]
Depending how the system is configured, a call to `os.HostName()` might return the FQDN or the short name of the server. The status API requires a short hostname.

## Current behavior:
```
ERROR: t3c-request.go:59: 2021-09-08T13:59:45.362466293Z: writing data: getting server 'cdn1cdedge0002.coxlab.net' update status: getting server update status: getting uncached: getting server update status from Traffic Ops 'REDACTED': Traffic Ops returned no update statuses for that server
```

## Expected behavior:
Should use the short hostname. This is usually done using `hostname -s`

## Steps to reproduce:
Make sure `hostname` returns the full FQDN. Run t3c-apply and observe the failure.

**Comment by mitchell852** [comment]
categorizing as medium per @rob05c

**Comment by rob05c** [comment]
Code is here: https://github.com/apache/trafficcontrol/blob/814f571/cache-config/t3c-apply/config/config.go#L368

Probably just needs something like:
```
cacheHostName = strings.Split(cacheHostName, ".")[0]
```
