### ISSUE TITLE
Docs have incorrect restriction on TM_PROFILE-type Profile names

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#6193]
## This Bug Report affects these Traffic Control components:
- Documentation

## Current behavior:
[The docs for what Profile Types require what Profile Names](https://traffic-control-cdn.readthedocs.io/en/latest/overview/profiles_and_parameters.html#type) (sort of) says that TM_PROFILEs can have a `RASCAL` _or_ `TM` prefix - but **only* Profiles with the prefix `RASCAL` are considered in Monitoring Snapshot generation.

## Expected behavior:
The docs should be accurate.

## Steps to reproduce:
Read the docs

**Comment by Ayushsunny** [comment]
Hello @ocket8888 So only `TM` part should be removed from the TM_PROFILEs ?

**Comment by ocket8888** [comment]
Yeah. There may be partial support for TM, but the docs shouldn't recommend it, because it won't work fully.
