### ISSUE TITLE
t3c-apply report mode doesn't appear to work (no output)

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#6201]
I'm trying to reproduce the results produced by using the following command:

```
traffic_ops_ort.pl -dispersion=0 report WARN
```

I can't seem to get the diff for the configuration files. If I enable the verbose (`-vv`) mode, it seems to display the configuration, although it is highly cryptic for a human to use. 

The command used is:

```
t3c-apply -m report -o -F
```

- Traffic Control Client 

## Current behavior:
Please see summary

## Expected behavior:
Difference in configuration seen in the output

## Steps to reproduce:

Compare `t3c-apply -m report -o -F` versus `traffic_ops_ort.pl -dispersion=0 report WARN`

**Comment by ocket8888** [comment]
@jrushford
