### ISSUE TITLE
GET logs?days=X limits results to 1000 rows max

### ISSUE THREAD

**Issue by mitchell852** [apache/trafficcontrol#6228]
## This Bug Report affects these Traffic Control components:
- Traffic Ops
- Traffic Portal

## Current behavior:
GET logs?days=X where the `limit` query param is not defined limits results rows to 1000 rows max. This appears to be a regression as this is not how it behaved before. This affects the ability to pull change logs for X days thru the API (obviously) as well as thru TP (https://tp.domain.tld/#!/change-logs).

This appears to be a regression on API version 2.x, 3.x and 4.x.

## Expected behavior:
GET logs?days=X where limit query param is not defined does NOT limit the number of rows returned.

## Steps to reproduce:
Call the API endpoint or change the number of days on https://tp.domain.tld/#!/change-logs and observe that never are more than 1000 rows returned.

**Comment by ocket8888** [comment]
I don't think that was a regression, wasn't 1000 always the default?

**Comment by mitchell852** [comment]
> you're saying that `logs?days={{DAYS}}` is defaulting to a limit of 1000 now?

yes. it didn't do that before. if you defiine days, then 1000000 is the default it sounds like as you said.

**Comment by mitchell852** [comment]
> I don't think that was a regression, wasn't 1000 always the default?

yes. if you don't define days AND limit.

**Comment by dmohan001c** [comment]
I will work on this bug.

**Comment by mitchell852** [comment]
actually i'd probably say ONLY apply a limit if the `limit` query parameter is defined. what do you think @ocket8888 ? 1000000 is basically no limit anyhow :)

**Comment by ocket8888** [comment]
That's a change in behavior, which would need to go into 4.0 only. Which I'd support.

**Comment by mitchell852** [comment]
> That's a change in behavior, which would need to go into 4.0 only. Which I'd support.

so fix (do no apply default limit of 1000 IF days query param is defined) in 2.x, 3.x? and change behavior (only apply a limit IF the `limit` query param IS defined) in 4.0?

**Comment by ocket8888** [comment]
yeah. Then when 2.0 and 3.0 are removed, the endpoint will be simpler for both users and developers to understand.

Also, doesn't look like our docs ever mentioned either default `limit` - that should change

**Comment by dmohan001c** [comment]
PR: https://github.com/apache/trafficcontrol/pull/6235
