### ISSUE TITLE
Missing docs for DELETE method of /statuses/{{ID}}

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#6318]
## This Bug Report affects these Traffic Control components:
- Documentation

## Current behavior:
The `DELETE` method of `/statuses/{{ID}}` is undocumented.

## Expected behavior:
All methods of all endpoints should be documented.

## Steps to reproduce:
Check the docs

**Comment by Ayushsunny** [comment]
Hey @ocket8888 can you guide me more on this, please?

**Comment by ocket8888** [comment]
The endpoint at `/statuses/{{ID}}` supports the DELETE HTTP request method to delete a Status, but that method of that endpoint has no documentation.
