### ISSUE TITLE
Geo Limit Countries should be an array

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#6382]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:
- Traffic Ops

## Current behavior:
Currently, it's a string that represents an array of strings separated by commas e.g. `"US,CA"`.

## New behavior:
Arrays should be arrays e.g. `["US", "CA"]`. If the parser is smart enough (and if we care to do it this way), that could be done in a backward-compatible manner such that if the field is a string it's parsed as a comma-delimited array, and if it's an array it's parsed as such. With the right validation (currently it has none, but country codes can't, for example, legally contain commas) the storage format could even be kept the same, which not only obviates the need for a migration but trivializes supporting old API versions.

**Comment by srijeet0406** [comment]
@ocket8888 I can take this one
