### ISSUE TITLE
TO prevents assigning ORG servers to topology-based delivery services

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#6392]
## This Bug Report affects these Traffic Control components:

- Traffic Ops

## Current behavior:

If you attempt to assign ORG servers to a topology-based delivery service (if you are setting it up for MSO, for instance), and it has no pre-existing DS-server EDGE assignments, TO returns the following error:
```
this server assignment leaves Active Delivery Service #11069 without any 'ONLINE' or 'REPORTED' servers
```

## Expected behavior:

TO should allow you to assign ORG servers to a topology-based DS that has no DS-server EDGE assignments.

## Steps to reproduce:

In TP, go to a topology-based delivery service that doesn't have any pre-existing EDGE server assignments, then More > Manage Servers > More > Assign ORG Servers > select an ORG server to assign > Submit

**Comment by rawlinp** [comment]
FYI I labelled this as medium impact since it has a workaround but could be very tedious if you had to use the workaround for any more than just a few delivery services.

**Comment by mitchell852** [comment]
it seems it has another "impact". we're seeing a bug where same message:

```
this server assignment leaves Active Delivery Service #X without any 'ONLINE' or 'REPORTED' servers
```

when trying to "offline" a server in a cache group that is used by a topology used by an MSO ds. enough to bump it to "high impact"?

**Comment by rawlinp** [comment]
Yeah, I agree, we should be able to offline servers for MSO topology-based DSes as well. Since that is a much more common use case, I think that warrants high impact.
