### ISSUE TITLE
Traffic Portal should filter out the "ALL" CDN option for snapshotting and queuing updates

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#6411]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Portal

## Current behavior:

When snapshotting or queuing updates in Traffic Portal, the `ALL` CDN is listed as an option:
![Screen Shot 2021-12-09 at 9 31 20 AM](https://user-images.githubusercontent.com/6724053/145436836-be091064-73ff-482d-93b3-9c2d127b2a65.png)
![Screen Shot 2021-12-09 at 9 31 30 AM](https://user-images.githubusercontent.com/6724053/145436845-7053a26b-0ee7-4f9e-b88a-264ea675d306.png)

## New behavior:

The `ALL` CDN should not be listed as an option in the snapshot and queue update modals, because it is never valid to snapshot or queue updates for the `ALL` CDN.

**Comment by mitchell852** [comment]
that's odd. i don't recall it doing that...but indeed it does. feels like a regression bug.

**Comment by mitchell852** [comment]
in addition. on the ALL cdn page (https://tp.domain.tld/#!/cdns/{{all_cdn_id}}), those options should not exist:

![image](https://user-images.githubusercontent.com/251272/146610180-03030513-63ea-4c88-8605-1aaecf1ecb2e.png)

**Comment by ocket8888** [comment]
If we really want to treat ALL specially, then we need to make that more formal. It should be immutable, it shouldn't be allowed to contain Delivery Services, etc. Currently, there are some places that treat ALL specially, and some that don't, and it can lead you to a partly correct configuration. It's also not documented anywhere that ALL is special and shouldn't be used for certain things.

IMO, we should actually just _not_ treat ALL specially, and get rid of the notion of some special CDN that isn't really a CDN but sometimes is. If servers don't belong to a CDN, then they can just have `null` CDNs.

**Comment by mitchell852** [comment]
> IMO, we should actually just _not_ treat ALL specially, and get rid of the notion of some special CDN that isn't really a CDN but sometimes is. If servers don't belong to a CDN, then they can just have `null` CDNs.

sure but that's a bigger effort and would require some thought on the plan. for now, i'll hide the ALL cdn from operations it was not designed to support. PR coming...pretty sure this is a regression bug that was introduced when i added cdn notification and decided to use the ALL cdn for that.

**Comment by rawlinp** [comment]
@ocket8888 I agree with your sentiments about the `ALL` CDN, but I do also think it's worth it to treat it specially in certain cases until such a time that we can separate cache servers from non-cache servers, especially since this does seem like a UI regression like @mitchell852 said.
