### ISSUE TITLE
Finding correct tenant is difficult in Traffic Portal

### ISSUE THREAD

**Issue by shamrickus** [apache/trafficcontrol#6427]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Portal

## Current behavior:
With a CDN at scale with many Tenants, any dropdown Tenant selection box has so many options that it makes it quite difficult to find the appropriate option. All children under a tenant are sorted, but that is not sufficient when dealing with nested tenancy. This issue is exasterbated by the face that child tenants are prepended with `--` making the default search functionality most browsers offer unusable (open dropdown, type letter, it goes to first option with that letter).

<img width="1675" alt="Screen Shot 2021-12-15 at 12 00 40" src="https://user-images.githubusercontent.com/5377636/146248548-7dcd33fe-7e47-4200-91b1-c3d3c62f0b3f.png">

## New behavior:
Filtering the drop down or having some way to find a specific tenant would be great.

**Comment by rawlinp** [comment]
Related: https://github.com/apache/trafficcontrol/issues/2980

**Comment by mitchell852** [comment]
yep, definitely an area in need of improvement @shamrickus

**Comment by ocket8888** [comment]
Not sure how hard it would be/if AngularJS Material has been updated in the past 6 years since I last used it, but like I said on [this other comment on #2908](https://github.com/apache/trafficcontrol/issues/2980#issuecomment-983827780) it could be implemented via an Angular Material Tree
