### ISSUE TITLE
Docs: The rpm package name is wrong in the docs/development/debugging.rst 

### ISSUE THREAD

**Issue by walkerxiong** [apache/trafficcontrol#6459]
I found the wrong rpm name at [https://traffic-control-cdn.readthedocs.io/en/latest/development/debugging.html?highlight=docker#traffic-ops](https://traffic-control-cdn.readthedocs.io/en/latest/development/debugging.html?highlight=docker#traffic-ops) and [https://traffic-control-cdn.readthedocs.io/en/latest/development/debugging.html?highlight=docker#traffic-stats](https://traffic-control-cdn.readthedocs.io/en/latest/development/debugging.html?highlight=docker#traffic-stats)

![image](https://user-images.githubusercontent.com/17756514/148677123-13a8f862-bd6b-4d45-8b9f-d762bd6aa751.png)

**Comment by walkerxiong** [comment]
And I think  it would be better to change the `mydc up` to `mydc up [specific service]`.

**Comment by ocket8888** [comment]
`traffic_ops/traffic_ops.rpm` is actually the correct RPM name, as it's the one included by [the Traffic Ops CDN-in-a-Box Dockerfile](https://github.com/apache/trafficcontrol/blob/master/infrastructure/cdn-in-a-box/traffic_ops/Dockerfile#L101). Any other name won't be used.

**Comment by walkerxiong** [comment]
> `traffic_ops/traffic_ops.rpm` is actually the correct RPM name, as it's the one included by [the Traffic Ops CDN-in-a-Box Dockerfile](https://github.com/apache/trafficcontrol/blob/master/infrastructure/cdn-in-a-box/traffic_ops/Dockerfile#L101). Any other name won't be used.

But it is in the `traffic_stats` section, and the `traffic_ops.rpm` is in the `traffic_stats` section.

When I build `traffic_ops`, the console reports an error that `traffic_ops/traffic_ops.rpm` does not exist

**Comment by walkerxiong** [comment]
![image](https://user-images.githubusercontent.com/17756514/148712567-b63c2179-503b-4ace-a9e4-ecb6eacd04b1.png)

**Comment by ocket8888** [comment]
Ohhh, I didn't catch that. Yeah, that should be fixed.
