### ISSUE TITLE
Some routes use hard-coded `RequiredPrivLevel` 0

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#6548]
## This Bug Report affects these Traffic Control components:

- Traffic Ops

## Current behavior:

18 Traffic Ops routes (6 in each TO API version) have a `Route.RequiredPrivLevel` of `0`:

https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/routing/routes.go#L225-L229

https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/routing/routes.go#L258

https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/routing/routes.go#L619-L623

https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/routing/routes.go#L652

https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/routing/routes.go#L996-L1000

https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/routing/routes.go#L1029

https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/routing/routes.go#L652

https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/routing/routes.go#L996-L1000

https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/routing/routes.go#L1029

There is no constant associated with `RequiredPrivLevel` 0:
https://github.com/apache/trafficcontrol/blob/1c6c9b8ca190b7d9a527ed48eb31c814b19432f2/traffic_ops/traffic_ops_golang/auth/authorize.go#L82-L97

## Expected behavior:

A constant should be added to the `github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/auth` package for `RequiredPrivLevel` 0, and those routes should be updated to use it.

**Comment by Ayushsunny** [comment]
Hello @zrhoffman I would like to fix this issue.
but I need some help here `those routes should be updated to use it`

**Comment by zrhoffman** [comment]
> Hello @zrhoffman I would like to fix this issue. but I need some help here `those routes should be updated to use it`

Would you please expand on what help you are looking for?

**Comment by Ayushsunny** [comment]
Like first we will add  `const RequiredPrivLevel = 0` on auth, right?
then how we are going to update those routes to use it

**Comment by zrhoffman** [comment]
> Like first we will add `const RequiredPrivLevel = 0` on auth, right?

The new `const` should not be named `RequiredPrivLevel`. `RequiredPrivLevel` is just the name of a certain field in the `routing.Route` struct: https://github.com/apache/trafficcontrol/blob/1398c02a80dfd4090881f8f90961c11ff57feeaa/traffic_ops/traffic_ops_golang/routing/routing.go#L51-L62

> then how we are going to update those routes to use it

Instances of the `routing.Route` struct that set `RequiredPrivLevel` to `0` should have `0` be replaced with the new `const`.

**Comment by Ayushsunny** [comment]
I'm still little confused here.
sorry if I wasted your time but I think I need more clarity for doing this or I can leave this issue.

**Comment by srijeet0406** [comment]
@Ayushsunny So the basic idea is not using the magic numeral `0` in those routes. Instead, you create a constant like
`const PrivLevel<Whatever you want to name it> = 0` in the `authorize.go` file and then use this new name in place of the 0's in the routes that Zach mentioned.

**Comment by sourikghosh** [comment]
@Ayushsunny are you working on this. If not then I would like to work on this issue

**Comment by Ayushsunny** [comment]
> @Ayushsunny are you working on this. If not then I would like to work on this issue

Hey, Thank you @sourikghosh Yes you can take it.
I'm busy with my Uni's test.

**Comment by sourikghosh** [comment]
@zrhoffman  @srijeet0406 any suggestion for a proper name for this const
