### ISSUE TITLE
build fail traffic_portal

### ISSUE THREAD

**Issue by phusinh** [apache/trafficcontrol#6565]
I am building the traffic port following the instructions of traffic control I created the file *.rpm.Since I want to build it with ubuntu, I converted the rpm file to a deb to build with the command sudo apt-get install *.deb , and i use systemctl start traffic_portal to run traffic port but it gives error and doesn't enable localhost
[](url)
![Screenshot from 2022-02-15 16-23-43](https://user-images.githubusercontent.com/48083638/154034532-0eeb45ac-1a54-4118-8506-bce786f25f06.png)

**Comment by ocket8888** [comment]
Ubuntu is not supported. Versions 5.1.6 and 6.1.0 support CentOS7 and CentOS8, and the current master branch builds support CentOS7 and Rocky Linux 8.

Please refer to [the documentation](https://traffic-control-cdn.readthedocs.io/en/latest/index.html) for information on what Traffic Control is and how to use it. If you need help troubleshooting or want clarification about something, please ask in [our Slack channels](https://s.apache.org/tc-slack-request) or on whichever of [the ATC mailing lists](https://trafficcontrol.apache.org/mailing_lists/) would be appropriate.
