### ISSUE TITLE
building traffic portal with build_rpm.sh failed,

### ISSUE THREAD

**Issue by phusinh** [apache/trafficcontrol#6567]
asked about building traffic portal with build_rpm.sh failed, got an error and don't know how to solve it.Thank 
![Screenshot from 2022-02-16 15-05-35](https://user-images.githubusercontent.com/48083638/154221872-daab662f-d3b0-4779-a9cb-764ac9ccffa6.png)

**Comment by ocket8888** [comment]
`.flat is not a function` means you likely are not using the correct Node version. From [the documentation]():

>Traffic Portal ... requires version 12 or higher [of NodeJS]

Please check your NodeJS version. If you need more help troubleshooting after that, please don't hesitate to reach out on either [the appropriate mailing list](https://trafficcontrol.apache.org/mailing_lists/) (which is probably [the "users" mailing list](mailto:users@trafficcontrol.apache.org)), or in [our Slack channels](https://s.apache.org/tc-slack-request). We're happy to help you troubleshoot in those places, but we try to keep such discussions out of GitHub issues.
