### ISSUE TITLE
ask traffic ops build developer

### ISSUE THREAD

**Issue by phusinh** [apache/trafficcontrol#6575]
let me ask if you want to run traffic portal, you must be able to run traffic ops in developer mode. I'm building traffic ops
I'm building traffic ops in developer mode according to the instructions, but I still don't understand how to build the db/admin [options] command according to the instructions because it doesn't have a db/admin folder. Hope you can answer my question thank you
![image](https://user-images.githubusercontent.com/48083638/154786516-92f94a58-c42d-403f-8418-a1031f5e6b3e.png)

**Comment by ocket8888** [comment]
We do not use GitHub Issues for debugging, troubleshooting, or support, as it states in the Issue template you are deleting. Please instead contact us on [the "users" mailing list](mailto:users@trafficcontrol.apache.org) or [in our Slack channels](https://s.apache.org/tc-slack-request) if you need further assistance.
