### ISSUE TITLE
TM should use TO API 4.0 (once stable) and fall back to 3.1

### ISSUE THREAD

**Issue by rawlinp** [apache/trafficcontrol#6654]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Monitor

## Current behavior:

TM uses TO API 3.1 and will fall back to 2.0 in case 3.1 is unavailable.

## New behavior:

TM should use TO API 4.0 (once stable) and fall back to 3.1 in case 4.0 is unavailable.

**Comment by mitchell852** [comment]
this is dependent on API 4.x being stabilized which is done with #6700
