### ISSUE TITLE
Update Traffic Router Watchers to use a parameter for API version

### ISSUE THREAD

**Issue by mattjackson220** [apache/trafficcontrol#6701]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Ops (maybe)
- Traffic Router

## Current behavior:

Currently, the Watchers in Traffic Router (like LetsEncryptDnsChallengeWatcher and FederationsWatcher) have the Traffic Ops API version hard coded. 

## New behavior:

This should be updated to be a parameter so a new deployment isnt required to change API versions. The new behavior should just use a changeable API version instead of the hardcoded one

**Comment by rawlinp** [comment]
Rather than just controlling the API version, we should have the parameter control the entire URL. That is how most of the TR watchers work today.

**Comment by mitchell852** [comment]
this is currently hard-coded to api 2.x, correct?

**Comment by mattjackson220** [comment]
yea the default url is hardcoded to 2.0

**Comment by mitchell852** [comment]
this is a nice-to-have imo and can be removed from the 7.0.0 milestone IF the default url is hardcoded to a non-deprecated API version (i.e. 3.0+) and i think @rawlinp was going to do that as part of #6653

**Comment by zrhoffman** [comment]
We're using a constant for TO API version as of #6778, which seems preferable so an operator does not have to manually change the API version in the configuration each a TR updaate is intended to change the API version used.
