### ISSUE TITLE
T3C keeps using old cookies on user change

### ISSUE THREAD

**Issue by shamrickus** [apache/trafficcontrol#6722]
## This Bug Report affects these Traffic Control components:

- Traffic Control Cache Config (`t3c`, formerly ORT)

## Current behavior:
If t3c has been ran, a cookie has been stored, and then the t3c user changes, t3c will continue using the old cookie even though it's for a different user. Since cookies are refreshed on request, the old cookie will also never expire (assuming t3c is running on a semi-regular basis).

## Expected behavior:
A user change to t3c should in someway invalidate the cookie if needed.

## Steps to reproduce:
Run t3c as a user
Change the user it runs as
Run t3c again and it uses the old cookie

**Comment by rob05c** [comment]
Easiest way is probably to store the user with the cookie cache, and check that it matches the current user before using it. Should be cheap and easy to do that client-side. @jpappa200
