### ISSUE TITLE
Requesting `/servers/{{ID}}/deliveryservices` where `ID` is non-existent causes Internal Server Error

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#6801]
## This Bug Report affects these Traffic Control components:
- Traffic Ops

## Current behavior:
If no server exists with ID 2, then a POST request to `/servers/2/deliveryservices` results in a `500 Internal Server Error` response.

## Expected behavior:
When a requested URI doesn't exist, the response code should be `404 Not Found`.

## Steps to reproduce:
1. <code>topost -kp 'servers/<var>ID</var>/deliveryservices?replace=false' '[]'</code> where <var>ID</var> doesn't exist.

**Comment by ocket8888** [comment]
My mistake, this is just an occurrence of #6691.

**Comment by ericholguin** [comment]
I think this should be reopened it is a separate issue from #6691

error.log shows:
```
ERROR: api.go:263: 2022-10-03T16:55:00.5425Z: [::1]:54360 querying CDN name from server ID: sql: no rows in result set
```

Which is completely different from that other issue.

**Comment by ocket8888** [comment]
The error message is different because it's a different code path, but the underlying issue is still that not having that specific parameter breaks Delivery Service operations.

**Comment by ericholguin** [comment]
Is it related to delivery services? I've found this same issue when doing a `POST` to `servers/{non-existent-id}/queue_update`

**Comment by ocket8888** [comment]
:shrug: I guess it just breaks a ton of things
