### ISSUE TITLE
Can't enable http2 with ATS9

### ISSUE THREAD

**Issue by smalenfant** [apache/trafficcontrol#6816]
- Traffic Control Cache Config (`t3c`, formerly ORT)

## Current behavior:

ATS 9 deprecated `disable_h2` configuration in sni.yaml
t3c `-2, --default-client-enable-h2` can flip between enabling http2 or not.

## Expected behavior:
When ATS9 is installed, the sni.yaml setting should be `http2: true/false`.

## Steps to reproduce:
Verify with your client of choice if http2 is working or not depending on the setting you'd like.

Notes:

- ATS8 without sni.yaml, http2 enabled by default
- ATS8 with sni.yaml http2 disabled by default.
- ATS9 with sni.yaml, disabled by default and can't enable.

**Comment by mat1010** [comment]
I might misunderstood the issue, but you can enable h2 via a profile per DS. Following steps worked for me

* make sure you have enabled http2 with in the `records.config`
`CONFIG proxy.config.http.server_port [...] proto=http2`
* create a profile of type `DS_PROFILE`
* create a parameter with name `enable_h2`, config file `parent.config` value e.g. `t` or `y`.
* assign that parameter to the newly created porfile
* within the delivery service, assign the profile to it
* snapshot the config and queue the update.
