### ISSUE TITLE
GET /api/4.0/servers?profileId={id} does not include all profiles

### ISSUE THREAD

**Issue by ericholguin** [apache/trafficcontrol#6834]
## This Bug Report affects these Traffic Control components:

- Traffic Ops

## Current behavior:

When making a `GET` request `/api/4.0/servers?profileId={id}` where `id` belongs to a profile that is not index 0 in the `profileNames` array the response will not display that server.

For example if there exists a server with the `profileNames`:
```json
{
...
 "profileNames": [
                "EDGE_TIER_ATS_CACHE", "MID_TIER_ATS_CACHE"
            ],
...
}
```

Where the id of the `EDGE_TIER_ATS_CACHE` profile is 13 and the id of `MID_TIER_ATS_CACHE` is 12.

If we perform a `GET` request:  `/api/4.0/servers?profileId=13` we will see the server above returned in the response, however
if we perform a `GET` request:  `/api/4.0/servers?profileId=12` (the following profile - at index 1 in the array) that server will not be included in the response. 

## Expected behavior:

Should account for all profiles, including profiles not at index 0 in the profileNames array

## Steps to reproduce:

Have a server with multiple profiles, make a `GET` request `/api/4.0/servers?profileId={id}` where `id` belongs to the profile NOT at index 0, you will not see the server included in the response

**Comment by ocket8888** [comment]
`profileId` should be deprecated as a query string parameter, since Profiles are not represented by their IDs on servers as of APIv4. Should be `profileName=` instead in APIv4 and later.

**Comment by mitchell852** [comment]
> Should be `profileName=` instead in APIv4 and later

yes, i would agree with this. no need for a query param of profileId in v4+
