### ISSUE TITLE
 cannot access https error in router traffic "This site can't provide a secure connection"

### ISSUE THREAD

**Issue by phusinh** [apache/trafficcontrol#6843]
generate  ssl in traffic ops
![image](https://user-images.githubusercontent.com/48083638/169257085-76b41c92-4064-44a2-a18c-78b597ade5ea.png)
error This site can't provide a secure connection
![image](https://user-images.githubusercontent.com/48083638/169256698-397f6920-547d-4391-950f-deaa64a5b171.png)

**Comment by ocket8888** [comment]
Please ask for help with troubleshooting and setup in [our Slack channel](https://s.apache.org/tc-slack-request)
