### ISSUE TITLE
Incorrect method on docs for /cdns/dnsseckeys/refresh in APIv4

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#6903]
## This Bug Report affects these Traffic Control components:
- Documentation

## Current behavior:
 In versions of the Traffic Ops API earlier than 4.0, the only supported request method for `/cdns/dnsseckeys/refresh` was `GET`. In APIv4, the method was switched to `PUT`, but the documentation still lists only the `GET` method (which no longer works).

## Expected behavior:
Documentation should be correct.

## Steps to reproduce:
https://traffic-control-cdn.readthedocs.io/en/v6.1.0/api/v4/cdns_dnsseckeys_refresh.html#get

**Comment by deepto98** [comment]
Can I pick this up? Is the doc file within this repo itself?

**Comment by ocket8888** [comment]
Yes, it's at `docs/source/api/v4/cdns_dnsseckeys_refresh.rst`
