### ISSUE TITLE
question about routing dns traffic router

### ISSUE THREAD

**Issue by windwind1** [apache/trafficcontrol#6937]
## This Bug Report affects these Traffic Control components:
- Traffic Router

## Current behavior:
![image](https://user-images.githubusercontent.com/42965621/176816556-434aba8f-e457-4787-876c-f06dced3aecd.png)
![image](https://user-images.githubusercontent.com/42965621/176868410-8586ae51-2db8-42ac-a441-2398d888d61d.png)
![image](https://user-images.githubusercontent.com/42965621/176815535-1ef0f4f9-90e8-448f-bfe4-38226eede82e.png)

## Expected behavior:
I have created delivery service example DS url cdn.test.com . I have assigned DS with tolopogy . But I don't know how to client request using dns to route in router traffic . I request through gateway udp and tcp 1053 of dns, it says read time out error and I request with url delivery service but no response .

**Comment by rawlinp** [comment]
> For *SUPPORT QUESTIONS*, use the #traffic-control channel on the ASF slack (https://s.apache.org/tc-slack-request)
or the Traffic Control Users mailing list (send an email to users-subscribe@trafficcontrol.apache.org to subscribe).
