### ISSUE TITLE
Documentation for cdns/{{name}}/federations is missing a property

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#6947]
## Current behavior:
[The Response Structure section of the documentation for `/cdns/{{name}}/federations`](https://traffic-control-cdn.readthedocs.io/en/latest/api/v3/cdns_name_federations.html#id2) doesn't include a description of the `id` property, which can nevertheless be seen in the Response Example.

## Expected behavior:
Documentation should be accurate.

## Steps to reproduce:
1. Read the docs

**Comment by everly-gif** [comment]
Made PR #7112 please have a look.
