### ISSUE TITLE
Increase State Character Limit

### ISSUE THREAD

**Issue by rsidhaarth** [apache/trafficcontrol#6983]
## This Bug Report affects these Traffic Control components:
- Traffic Portal

## Current behavior:

Topologies -> Physical Location

As of now, the state cannot have more than 2 letters. 

## Expected behavior:

There are many states which have abbreviations of more than 2 letters and up to 4 letters.

**Comment by ocket8888** [comment]
Restriction possibly also exists in TO

**Comment by Mehul721** [comment]
Hi,I would like to work on this issue.

**Comment by zrhoffman** [comment]
Feel free to create PR when one is ready, and please reach out if you have any questions.

**Comment by ntheanh201** [comment]
I have fixed this issue, please take a look!
