### ISSUE TITLE
Problem when install Traffic Ops

### ISSUE THREAD

**Issue by thang86** [apache/trafficcontrol#6984]
/opt/traffic_ops/install/bin/_postinstall.py
 
INFO:root:Starting postinstall
INFO:root:Debug is on
INFO:root:No input file given - using defaults
INFO:root:===========/opt/traffic_ops/app/conf/production/database.conf===========
Database type [Pg]:
Database name [traffic_ops]:
Database server hostname IP or FQDN [localhost]: pg
Database port number [5432]:
Traffic Ops database user [traffic_ops]:
Password for Traffic Ops database user:
Re-Enter Password for Traffic Ops database user:
INFO:root:Database configuration has been saved
INFO:root:===========/opt/traffic_ops/app/conf/production/tv.conf===========
Traffic Vault Database type [Pg]:
Traffic Vault Database name [traffic_vault]:
Traffic Vault Database server hostname IP or FQDN [localhost]: pg
Traffic Vault Database port number [5432]:
Traffic Vault database user [traffic_vault]:
Password for Traffic Vault database user:
Re-Enter Password for Traffic Vault database user:
INFO:root:Database configuration has been saved
Do you want to set up LDAP? [no]: no
INFO:root:Not setting up ldap
INFO:root:===========/opt/traffic_ops/install/data/json/users.json===========
Administration username for Traffic Ops [admin]:
Password for the admin user:
Re-Enter Password for the admin user:
INFO:root:===========/opt/traffic_ops/install/data/json/openssl_configuration.json===========
Do you want to generate a certificate? [yes]: no
Country Name (2 letter code): VN
State or Province Name (full name): Hanoi
Locality Name (eg, city):
Organization Name (eg, company):
Organizational Unit Name (eg, section):
Common Name (eg, your name or your server's hostname):
RSA Passphrase [CHANGEME!!]:
Re-Enter RSA Passphrase:
INFO:root:===========/opt/traffic_ops/install/data/json/profiles.json===========
Traffic Ops url [https://localhost]:
Human-readable CDN Name. (No whitespace, please) [kabletown_cdn]:
DNS sub-domain for which your CDN is authoritative [cdn1.kabletown.net]:
INFO:root:Not generating openssl certification
INFO:root:===========/opt/traffic_ops/app/conf/cdn.conf===========
Generate a new secret? [yes]: yes
Number of secrets to keep? [1]:
Port to serve on? [443]:
Number of workers? [12]:
Traffic Ops url? [http://localhost:3000]:
ldap.conf location? [/opt/traffic_ops/app/conf/ldap.conf]:
DEBUG:root:Secrets found in cdn.conf file
INFO:root:CDN configuration has been saved
INFO:root:paramconf {'tm.url': 'https://localhost', 'cdn_name': 'kabletown_cdn', 'dns_subdomain': 'cdn1.kabletown.net'}
INFO:root:Setting up the database data
DEBUG:root:psql exec failed; stderr: psql: error: could not translate host name "123@pg" to address: Name or service not known

        stdout:
ERROR:root:Failed to set up database: failed to execute database query
ERROR:root:Can't connect to the da

OS : Rocky Linux

**Comment by ocket8888** [comment]
It looks like the host you entered for your database - `pg` - is not reachable.

For troubleshooting help, please reach out in [our ASF Slack channel(s)](https://s.apache.org/tc-slack-request).
