### ISSUE TITLE
Internal Sever Error in TP when updating own role to higher role

### ISSUE THREAD

**Issue by ericholguin** [apache/trafficcontrol#6985]
When current user has a role with a lower privilege level than the role it is updating itself to, will result in an Internal Server Error in Traffic Portal. In Traffic Ops this is not allowed when using the `users/{id}` endpoint however Traffic Portal uses the `user/current` endpoint when updating your self.

This can't be replicated in Traffic Ops due to #3168

## This Bug Report affects these Traffic Control components:

- Traffic Portal

## Current behavior:

Try updating your own role to a role with higher privileges in Traffic Portal  you should see an Internal Server Error alert.

## Expected behavior:

The alert should be: `"users cannot update their own role"` or something similar.

## Steps to reproduce:

Go to Traffic Portal 
Login as a user with an operations role
Try updating your own role to admin you should see an Internal Server Error alert.

**Comment by ocket8888** [comment]
@tinfoil-knight the latter - although I _believe_ this issue actually no longer exists. I haven't checked, but Roles and the user/current endpoint have both had significant changes since this issue was opened.

**Comment by tinfoil-knight** [comment]
@ocket8888 The issue still exists.
- I created a new role with `[ "USER:UPDATE", "USER:READ" ]` permissions using `POST /roles`
- Created a new user with that role using `POST /users`
- Logged in with their credentials using `POST /user/login`
- Attempted to change their role to `admin` with the `PUT /user/current` endpoint. Got an "Internal Server Error".
- Got "users cannot update their own role" error with `PUT /users/{id}` which is the correct description.

Unlike the `Update` method used for `PUT /users/{id}` route, there's no check to prevent "role" changes in the `ReplaceCurrentV4` method used for `PUT /users/current`

See:

https://github.com/apache/trafficcontrol/blob/c35b9f18dc5b6407fdd2509598704451d5e8ef89/traffic_ops/traffic_ops_golang/user/user.go#L993-L999

https://github.com/apache/trafficcontrol/blob/c35b9f18dc5b6407fdd2509598704451d5e8ef89/traffic_ops/traffic_ops_golang/user/current.go#L536-L541

I'll push a fix.

**Comment by ocket8888** [comment]
alright, cool, thanks
