### ISSUE TITLE
Traffic Monitor

### ISSUE THREAD

**Issue by thang86** [apache/trafficcontrol#6992]
I have error 
ERROR: opsconfig.go:78: 2022-07-29T07:10:36.998551108Z: OpsConfigManager: MonitorConfigPoller: error instantiating Session with traffic_ops (<nil>): logging in using legacy client: logging in: requesting: Post "https://ipxxxx /api/2.0/user/login": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

{
        "username": "admin",
        "password": "******",
        "url": "https://ipxx.xxx.xxx",
        "insecure": true,
        "cdnName": "cdn",
        "httpListener": ":80",
        "httpsListener": "",
        "certFile": "/opt/traffic_monitor/key/",
        "keyFile": "/opt/traffic_monitor/key/"
}
key form traffic_ops

**Comment by ocket8888** [comment]
looks like your traffic monitor can't contact traffic ops

For troubleshooting help, please [join our Slack channel(s) on the ASF Slack workspace](https://s.apache.org/tc-slack-request).
