### ISSUE TITLE
Traffic Portal (v1) - Servers do not display for layered/multi profiles

### ISSUE THREAD

**Issue by TaylorCFrey** [apache/trafficcontrol#7049]
## This Bug Report affects these Traffic Control components:
- Traffic Portal

## Current behavior:

The second (+) profile is not filterable on the server table (TP -> Configure -> Servers). The original profile does still work in the filter.

## Expected behavior:

The second profile will also be filterable on the Servers page.

## Steps to reproduce:

Create multiple profiles. On Configure -> Servers, select a server. Add both profiles to the server. There are a couple ways to bring up the "broken" filter, but one such way is to open the list of profiles -> Select the _second_ profile you know you want to filter on -> Click More, View Servers. This will load the server page with the filter for that profile. Alternatively, you can open the server list (Configure -> Servers). Ensure the column for profiles is enabled. Click on the filter -> select Equals and type in the name of the second profile.

Alternatively, I believe you should also be able to edit the URL query params such that they match the second profile, but I'm not having luck with this even for primary/first profiles:
```
https://{{traffic_portal.url}}/#!/servers?profileName={second_profile}
```

**Comment by rimashah25** [comment]
I'll resolve this issue. Similar to https://github.com/apache/trafficcontrol/issues/7052
