### ISSUE TITLE
Assigning a new Server Server capability changes SSC order in the Snapshot for that Server

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#7113]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Ops
- Traffic Portal

## Steps taken

1. Create Server Capability *My_Capability*
2. Assign Server Capability *My_Capability* to Server *edge*
3. Snapshot *dev* CDN
4. Create Server Capability *Another_Capability*
5. Assign Server Capability *Another_Capability* to Server *edge*
6. Look at snapshot diff for *dev* CDN

## Actual result

* Snapshot diff shows that Server Server Capability *My_Capability* is added to server *edge* at index 1
* Snapshot diff shows that Server Server Capability *My_Capability* is updated to *Another_Capability* at index 0

![screenshot](https://user-images.githubusercontent.com/11163823/194619662-d6277d27-7b1d-448d-b2f5-043c0e83d521.png)

## Expected result
Snapshot diff shows that Server Server Capability *My_Capability* for Server *edge* was added

## Also

<strike>Possibly fixed by #7079.</strike> @rimashah25 would know for sure

**Comment by rimashah25** [comment]
#7079 doesn't fix or improve the snapshot look for SSC.
