### ISSUE TITLE
Docs for staticdnsentries API endpoint missing lastUpdated response property description

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#7131]
## This Bug Report affects these Traffic Control components:
- Documentation

## Current behavior:
The documentation for the `staticdnsentries` API endpoint (all request methods except DELETE, all API versions) is missing a description in its Response Structure subsections for the `lastUpdated` property that can be seen in the response examples.

## Expected behavior:
Documentation should be complete.

## Steps to reproduce:
Read the docs for that endpoint, e.g. [the APIv3 docs page](https://traffic-control-cdn.readthedocs.io/en/latest/api/v3/staticdnsentries.html).

**Comment by hanish-rishen** [comment]
Hi, I would like to work on this issue, please assign it to me.

**Comment by hanish-rishen** [comment]
I have finished , please verify #7140 
Thank You
