### ISSUE TITLE
TP: /#!/cdns/{ID}/delivery-services is empty

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#7133]
## This Bug Report affects these Traffic Control components:

- Traffic Portal

## What did you do?

1. Started the CDN in a Box for Developers
2. Went to TPv1 in my browser, https://localhost:444/
3. Navigated to CDNs -> dev
4. From the drop-down, chose *View Delivery Services* (https://localhost:444/#!/cdns/2/delivery-services)

## What happened?

No table showed up, no Delivery Services were shown

![screenshot of https://localhost:444/#!/cdns/2/delivery-services not loading](https://user-images.githubusercontent.com/11163823/195622189-f20dd48c-afea-47bf-b8b7-85d9a4805561.png)

## What did you expect to happen?

A list of Delivery Services in the *dev* CDN

**Comment by ocket8888** [comment]
> /#!/cdns/{ID}/delivery-services

Is that URL accurate? It should be something like `#!/delivery-services?cdn={{ID}}`.

**Comment by zrhoffman** [comment]
Looks like that's been the URL since 2016
https://github.com/apache/trafficcontrol/blob/05e7f2157974d75dd79cedbdc8e9d2582789f921/traffic_portal/app/src/common/modules/form/cdn/FormCDNController.js#L57-L59

The URL format corresponds with that used for the table of Servers in a CDN, https://localhost:444/#!/cdns/2/servers

**Comment by mitchell852** [comment]
@zrhoffman @shamrickus  - was this not fixed with #7104

**Comment by zrhoffman** [comment]
Reproduced at 2697a3fd29, the merge commit of #7104

**Comment by ocket8888** [comment]
I would guess the problem, then, is that link. Should be a link to a filtered DS list, not `$location.path() + '/delivery-services'`.

**Comment by shamrickus** [comment]
It's the same issue,  just a table I missed.
