### ISSUE TITLE
Remove cookie user errors from TO error.log

### ISSUE THREAD

**Issue by ericholguin** [apache/trafficcontrol#7134]
Currently, if a user's cookie is expired or has an incorrect signature these will log as errors in error.log, however this is normal functionality and a user error not a system error that needs to be logged in error.log.

## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Ops

## Current behavior:

error.log:
```
ERROR: api.go:263: --- error parsing cookie: bad signature
ERROR: api.go:263: --- error parsing cookie: signature expired
```

## New behavior:

The error's above should no longer appear in error.log

**Comment by smalenfant** [comment]
Is this coming from a Client that doesn't observe the expiration?

**Comment by ericholguin** [comment]
Yes, in this case I believe t3c isn't observing that expiration.

**Comment by ocket8888** [comment]
Yeah, the official TO Go client does that. You can see it in the logs for CDN-in-a-Box coming from TM and t3c.
