### ISSUE TITLE
CDN-in-a-Box build fails with "No such file or directory" on M1 Pro Mac

### ISSUE THREAD

**Issue by fabikd** [apache/trafficcontrol#7238]
## This Bug Report affects these Traffic Control components:
- CDN in a Box

## Current behavior:
Build fails with: 

```
Wrote: /root/rpmbuild/RPMS/aarch64/trafficserver-8.1.5-1.c16631ab0.el8.aarch64.rpm
Wrote: /root/rpmbuild/RPMS/aarch64/trafficserver-debugsource-8.1.5-1.c16631ab0.el8.aarch64.rpm
Wrote: /root/rpmbuild/RPMS/aarch64/trafficserver-debuginfo-8.1.5-1.c16631ab0.el8.aarch64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.bH6wRi
+ umask 022
+ cd /root/rpmbuild/BUILD
+ cd trafficserver-8.1.5
+ rm -rf /root/rpmbuild/BUILDROOT/trafficserver-8.1.5-1.c16631ab0.el8.aarch64
+ exit 0
Build completed
trafficserver RPM has been copied
cp -f "" "cache/trafficserver.rpm" || (rm ".//cache/ATS_VERSION"; false)
cp: : No such file or directory
make: *** [cache/trafficserver.rpm] Error 1
```

## Expected behavior:
build would complete

## Steps to reproduce:
clone traffic control --> cd trafficcontrol/infrastructure/cdn-in-a-box --> enter commands: make very-clean && make all && docker-compose build --parallel && docker-compose -f docker-compose.yml -f docker-compose.expose-ports.yml up -d

**Comment by fabikd** [comment]
This fixed it for me: 

Reinstalled docker from the command line to use user=[your username] flag, and update the dockerfiles in the code for both enroller and traffic_ops in the cdn-in-a-box folder with the correct architecture for the M1. Link to install info for docker: https://docs.docker.com/desktop/install/mac-install/  and use **Install from command line**. Then update cdn-in-a-box/traffic_ops Dockerfile line 46 to **aarch64/pgdg-redhat-repo-latest.noarch.rpm** after **EL-${RHEL_VERSION%%.*}** and, add in line 18 of the cdn-in-a-box/enroller Dockerfile   **--platform=linux/amd64** after the 1st **FROM**.
 
Build and run of it:
in the trafficcontrol/infrastructure/cdn-in-a-box folder run the following:
 

- make build-builders ~~> this will create all the rpms and copy each rpms into its own folder in the cdn-in-a-box project. this will also create the dist folder under trafficcontrol folder structure even if you delete yours.

- docker-compose up ~~> this will create docker images, and if rebuild is needed ran docker-compose up --build.

**Comment by zrhoffman** [comment]
>> @fabikd: On #7251's branch, are you able to build CDN in a Box without making any modifications to its files?

> I just pulled master and tried it again; and it fails unless I make the changes that I've noted in the readme.

Looks like #7215 just got merged. Does it work for you now?
