### ISSUE TITLE
Incorrect Response Structure documentation for Jobs

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#7246]
## This Bug Report affects these Traffic Control components:
- Documentation

## Current behavior:
The documentation for the APIv4 (and ostensibly APIv5) `/jobs` endpoint lists a description of the fields in a response to a GET request as being identical to those seen in APIv3. The response examples reveal that this is in error.

## Expected behavior:
The documentation should be accurate.

## Steps to reproduce:
Read the APIv4/5 `GET /jobs` documentation, create and fetch "Jobs" to confirm the response descriptions are incorrect.

**Comment by sagar-bansal** [comment]
Hi can I work on this issue :)
