### ISSUE TITLE
Roles creation/update responses incorrectly set `null` permissions when not provided.

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#7247]
## This Bug Report affects these Traffic Control components:
- Traffic Ops

## Current behavior:
When the client creates or updates a Role, they may omit the `permissions` property, or explicitly set it to `null`. This is implicitly the same as an empty collection, as further GET requests will reveal. However, in those cases, the immediate response to the PUT or POST request in question will show `permissions` as `null`.

## Expected behavior:
Representations should be consistent, an empty collection is properly represented as an empty collection, not `null`.

## Steps to reproduce:
1. Create or Update a Role, omitting the `permissions` property thereof in the request payload.

**Comment by JammUtkarsh** [comment]
Hey @ocket8888,
I'm interested in contributing to the Issue and I'd like to learn more about it. I appreciate any information you can provide like and look forward to contributing to the project.
Specifically, can you point out where should I looking for this in the trafic_ops directory?

Thank you,
Utkarsh Chourasia

**Comment by ocket8888** [comment]
Handlers for `/roles` requests live in the `traffic_ops/traffic_ops_golang/role` package
