### ISSUE TITLE
/roles PUT response missing lastUpdated

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#7248]
## This Bug Report affects these Traffic Control components:
- Traffic Ops

## Current behavior:
POST and GET responses show a `lastUpdated` field for Roles, while PUT responses do not include them.

## Expected behavior:
Representations should be consistent.

## Steps to reproduce:
1. Create a Role.
2. Modify it.

**Comment by tinfoil-knight** [comment]
@ocket8888 Was inspecting this issue in https://github.com/apache/trafficcontrol/blob/573f21d1a8673ead63f4ee0c30bb0f17b7ff9835/traffic_ops/traffic_ops_golang/role/roles.go#L340-L342

Seems like we're skipping over the row with the actual result. Can I pick up this issue?

**Comment by ocket8888** [comment]
Sure. Note that `QueryRow` is probably more appropriate here, just looking at the linked sections.
