### ISSUE TITLE
Docs list incorrect request property for `/jobs`

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#7310]
## This Bug Report affects these Traffic Control components:
- Documentation

## Current behavior:
The APIv4 and APIv5 request body descriptions for POST requests to `/jobs` list a required `ttl` property; as seen in the request example, this is incorrect and the actual property name is `ttlHours`.

## Expected behavior:
Documentation should be correct.

## Steps to reproduce:
Read the docs.

**Comment by dilraj-vyas** [comment]
Hi, I Would Like to work on this issue, pls provide the necessary doc, thank you .
