### ISSUE TITLE
Docs for user registration endpoint have incorrect property

### ISSUE THREAD

**Issue by ocket8888** [apache/trafficcontrol#7326]
## This Bug Report affects these Traffic Control components:
- Documentation

## Current behavior:
The documentation for the `/users/register` API endpoint list the `role` property as a number that is the ID of the Role to give to the newly registered user, in all three major API versions.

## Expected behavior:
In APIv4 and later, Roles don't have IDs and use names as their primary identifiers. The `/users/register` endpoint was updated accordingly, and the `role` property should actually be a Role's name, not its ID.

## Steps to reproduce:
Read the docs.

**Comment by haanhvu** [comment]
I'll work on this

**Comment by Rohith-Raju** [comment]
Hi, I would like to work on this issue 😄

**Comment by Rohith-Raju** [comment]
https://traffic-control-cdn.readthedocs.io/en/latest/api/v4/users_register.html 
What should I change the `role` field to?

**Comment by ocket8888** [comment]
> In APIv4 and later, Roles don't have IDs and use names as their primary identifiers. ... the `role` property should actually be a Role's name, not its ID.
