### ISSUE TITLE
[TPv2] Unable to view regions from a division

### ISSUE THREAD

**Issue by rimashah25** [apache/trafficcontrol#7372]
## This Bug Report affects these Traffic Control components:

- Traffic Portalv2

## Current behavior:

When clicking on context-menu to `View Regions` for a division, the url: `http://localhost:4200/core/regions?divisionName=testD1677646171310` shows no result
<img width="847" alt="image" src="https://user-images.githubusercontent.com/22248619/222048659-5fcde235-a53d-4a96-8e5f-53bcfca2c4fe.png">

## Expected behavior:

The URL should show region(s) associated with a division.

## Steps to reproduce:

1. Login to TPv2
2. Go to Divisions under Servers > Cache Groups
3. Right-click on a division to open context-menu
4. Click on `View Regions`

**Comment by ocket8888** [comment]
This is because the column for division in the regions table is using a valueGetter instead of a valueFormatter (I believe).
