### ISSUE TITLE

🇺🇬📡

### ISSUE THREAD

**Issue by 235115** [apache/trafficcontrol#7540]
## This Feature Request affects these Traffic Control components:

- Traffic Control Cache Config (`t3c`, formerly ORT)
- Traffic Control Health Client (tc-health-client)
- Traffic Control Client 
- Traffic Monitor
- Traffic Ops
- Traffic Portal
- Traffic Router
- Traffic Stats
- Grove
- Documentation
- CDN in a Box
- Automation (GitHub Actions, Ansible Roles)
- unknown

**Comment by ocket8888** [comment]
wat
