### ISSUE TITLE
Autoscaling ATS in cachegroup if Traffic router can check the ATS/cachegroup high load 

### ISSUE THREAD

**Issue by xn-zhao** [apache/trafficcontrol#7552]
## This Feature Request affects these Traffic Control components:
- Traffic Monitor
- Traffic Router
- Automation (GitHub Actions, Ansible Roles)

## Description
- When traffic increases in some cachegroup/ATS, and the cachegroup has not enough ATS to serve, Traffic Router can check the bandwidth/load of cachegroup/ATS to run script to auto-scale up ATS in cachegroup.
- Auto-script can run in Ansible to call REST API to update cachegroup name/id in ATS server so that it can add new ATS logically in cachegroup with high load.

**Comment by ntheanh201** [comment]
Hi bro,
Are you Vietnamese?
I'm having trouble when getting ATC up, can I ask you some questions?
