### ISSUE TITLE
Traffic Stats should use TO API v5

### ISSUE THREAD

**Issue by rimashah25** [apache/trafficcontrol#7659]
## This Improvement request (usability, performance, tech debt, etc.) affects these Traffic Control components:

- Traffic Stats

## Current behavior:

Traffic Stats uses TO API v3

## New behavior:

Traffic Stats should use TO API v5, since that is the current stable TO API version, and TO API v3 is being removed.

**Comment by ocket8888** [comment]
> Traffic Stats should use TO API v5, since that is the current stable TO API version, and TO API v3 is being removed.

You mean it should use v4, right?

**Comment by rimashah25** [comment]
Update complete.
