### ISSUE TITLE
Version in "././infrastructure/docker/build/docker-compose.yml" is unsupported

### ISSUE THREAD

**Issue by zrhoffman** [apache/trafficcontrol#8055]
## This Bug Report affects these Traffic Control components:

- Traffic Control Cache Config (`t3c`, formerly ORT)
- Traffic Control Health Client (t3c-health-client)
- Traffic Monitor
- Traffic Ops
- Traffic Portal
- Documentation
- CDN in a Box
- Automation 

## What did you do?

`./pkg -v cache-config_build`

## What did you expect to happen?

`cache-config` successfully builds.

## What actually happened?

```shell
+ ./pkg -v cache-config_build
Version in "././infrastructure/docker/build/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version ("2.0", "2.1", "3.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Building cache-config_build.
Version in "././infrastructure/docker/build/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version ("2.0", "2.1", "3.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Failed to build cache-config_build.
```

Reason:
The `version` key in `docker-compose.yml` has been deprecated for awhile now, but now using it with compose file version 3.8 is explicitly an error. The `version` key should be removed completely. And, to ensure that only recent docker compose versions are used, which ensures that they will support this change, instances of `docker-compose` should be changed to `docker compose`.

If an old `docker-compose` version is used with the `version` key removed from the compose file, it will complain about unknown keys in the compose file, because it will assume that compose file version 1 is used.

**Comment by Solarisbf** [comment]
which version of docker-compose ? 

I solved to this problem by using old docker-compose version. 

i am using docker-compose version 1.28.2 

new version command is changed like this  docker compose <command> .... does not work on cdn-in-a-box
