### ISSUE TITLE
[TC-548] Determine how to handle hostname/routing name change for ssl keys

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#887]
<p>Now when a DS's hostname changes on an update, via UI or API, it changes the hostname field on the record stored in riak, but it does not regenerate the certificate or CSR so there will be a mismatch between the ssl certificate and the hostname it is being used for. </p>

<p>We need to decide what the proper way to handle this is, we can regenerate the certificate and CSR in the manner we currently do from the api or ui but they will still be unsigned without human interaction at this point.</p>

Author: Dylan Volz
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-548">https://issues.apache.org/jira/browse/TC-548</a>

**Comment by ocket8888** [comment]
Superseded by #3776
