### ISSUE TITLE
[TC-291] GenIso can't handle concurrent requests 

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#892]
<p>Because GenIso always changes the same files (no temporary directories created), it can't handle concurrent requests. We sometimes send commands to create 10 Edge Caches at the same time and we found out that the wrong IP address shows up on servers.</p>

<p>I've got the code to fix it up (but need to sign our paperwork). But our GenIso.pm now deviates from what's in Traffic Ops because we wanted to keep the 1.0.0 functionality (don't use the install_cfg directory, keep using the simple network line).</p>

<p>Suggestion: We should have a parameter to call different ISO generator scripts. Seems like this is implementation specific and not really a core function of Traffic Ops.</p>

<p>Basic changes :</p>

<p>use File::Temp;<br/>
use File::Copy::Recursive;</p>

<p>my $tmpdir = File::Temp::tempdir(CLEANUP =&gt; 1);<br/>
...<br/>
GenIso.pm:        my $tmp = File::Copy::Recursive::dircopy($dir,$tmpdir);<br/>
GenIso.pm:  my $cfg_dir = "$tmpdir/$install_cfg";<br/>
GenIso.pm:  print STUF "Dir== $tmpdir\n";<br/>
GenIso.pm:  my $cmd = "mkisofs -joliet-long -input-charset utf-8 -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -R -J -v -T $tmpdir";<br/>
GenIso.pm:  open(IN, "&lt;$tmpdir/ks.src") || die("$tmpdir/ks.src:$!");<br/>
GenIso.pm:  open (OUT, "&gt;$tmpdir/ks.cfg") || die("$tmpdir/ks.cfg:$!");<br/>
GenIso.pm:        File::Path::rmtree $tmpdir;</p>

Author: Dewayne Richardson
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-291">https://issues.apache.org/jira/browse/TC-291</a>
Found Version: 2.1.0

**Comment by dewrich** [comment]
Still an issue
