### ISSUE TITLE
[TC-537] Update TO routing APIs to use Traffic Stats data (InfluxDB)

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#894]
<p>Dependent on <a href="https://issues.apache.org/jira/browse/TC-536" class="external-link" rel="nofollow">TC-536</a></p>

<p>Currently the routing endpoint in Traffic Ops (apis/1.2/cdns/routing, api/1.2/deliveryservices/:id/routing.json) reach out to the crs/stats API on one Traffic Router to get the information.  Traffic Routers are stateless therefore the crs/stats API data from one traffic router is not a full picture.  Once <a href="https://issues.apache.org/jira/browse/TC-536" title="Update Traffic Stats to collect and store /crs/stats data from Traffic Routers" class="issue-link" data-issue-key="TC-536">TC-536</a> is complete the routing APIs in Traffic Ops should be updated to use the data that is stored by Traffic Stats in InfluxDB. </p>

Author: David Neuman
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-537">https://issues.apache.org/jira/browse/TC-537</a>

**Comment by mitchell852** [comment]
@dneuman64 - current functionality queries ALL traffic routers instead of one for the information provided in the TO routing APIs, therefore, I'm going to close this. Please reopen if you disagree or have concerns.
