### ISSUE TITLE
[TC-368] api/1.2/deliveryservices/:id/routing.json hangs when Traffic Router is unreachable

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#902]
<p>I was testing this API "/api/1.2/deliveryservices/:id/routing.json" and found that it would hang and the perl worker had to be killled. This caused 500 Errors back from TO API.</p>

<p>The root cause is Traffic Router not responding to API Port. </p>

<p>We should not poll Traffic Router that are status=OFFLINE and there should be some sort of timeouts in place to make sure it doesn't take more than x seconds to return information from API</p>

<p>There is some comments in the code that seems to indication prior issues.</p>

<p>`# TODO: what happens when the request to CCR times out?`</p>

Author: Steve Malenfant
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-368">https://issues.apache.org/jira/browse/TC-368</a>
Found Version: 1.8.0

**Comment by dneuman64** [comment]
This is not something that will be fixed in 2.1.0.  Moving to 2.2.

**Comment by mitchell852** [comment]
duplicate #896
