### ISSUE TITLE
[TC-339] Traffic Router should not bring unresponsive Traffic Monitor decisions back right away

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#904]
<p>Traffic Monitor split-brain scenario can have a violent recovery path &#8211; potentially taking marking all caches unhealthy.</p>

Author: Zhilin Huang
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-339">https://issues.apache.org/jira/browse/TC-339</a>
Found Version: 2.1.0

**Comment by rob05c** [comment]
From the Jira case:
>Jeff Elsloo added a comment - 15/Aug/17 14:26
>
>I wouldn't call this a bug, but it's something we should consider handling. The scenario is two Traffic Monitors, one or both of which have connectivity issues, which includes peer connectivity. If this happens, the peer state could be ignored or could become stale (not 100% sure on how the golang TM handles this condition). This issue could be compounded if the Traffic Monitor has lost connectivity to some/all caches, so local state is also invalid. If Traffic Router can reach that Traffic Monitor, it has the potential to influence routing decisions by publishing invalid cr-states.

**Comment by rawlinp** [comment]
I believe this situation is addressed by https://github.com/apache/trafficcontrol/pull/4307.
