### ISSUE TITLE
[TC-161] ort does not restart ATS when it should

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#913]
<p>ort does not restart ATS when ATS is already running</p>

Author: John Shen
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-161">https://issues.apache.org/jira/browse/TC-161</a>
Found Version: 2.1.0

**Comment by dneuman64** [comment]
I don't believe this will be included in the 2.1 release.  Moving to 2.2.

**Comment by ocket8888** [comment]
Fixed in commit fabb17dd961bacc18a5a849a6f82185d88790b4b (no PR afaik)

**Comment by ocket8888** [comment]
ORT restarts ATS exactly when it should - when in BADASS mode and **only** in BADASS mode. This is by design, and (sort of) documented.
