### ISSUE TITLE
[TC-157] Failed to restart tomcat in Traffic Router when failed to get SSL keys

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#914]
<p>Stopping tomcat failed with the following log:</p>

<p>WARN  2017-02-17T09:00:05.939 <span class="error">&#91;main&#93;</span> com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesPublisher - Detected destroy setting running to false<br/>
INFO  2017-02-17T09:00:05.943 <span class="error">&#91;pool-2-thread-1&#93;</span> com.comcast.cdn.traffic_control.traffic_router.core.secure.CertificatesClient - Interrupted while pausing for check of traffic ops config<br/>
INFO  2017-02-17T09:00:05.943 <span class="error">&#91;pool-2-thread-1&#93;</span> com.comcast.cdn.traffic_control.traffic_router.core.util.Fetcher - POSTing: <a href="https://192.168.122.181/api/1.1/user/login" class="external-link" rel="nofollow">https://192.168.122.181/api/1.1/user/login</a>; timeout is 15000<br/>
INFO  2017-02-17T09:00:06.005 <span class="error">&#91;pool-2-thread-1&#93;</span> com.comcast.cdn.traffic_control.traffic_router.core.util.Fetcher - GETing: <a href="https://192.168.122.181/api/1.2/cdns/name/kabletown_cdn/sslkeys.jso" class="external-link" rel="nofollow">https://192.168.122.181/api/1.2/cdns/name/kabletown_cdn/sslkeys.jso</a><br/>
n; timeout is 15000<br/>
WARN  2017-02-17T09:00:06.040 <span class="error">&#91;pool-2-thread-1&#93;</span> com.comcast.cdn.traffic_control.traffic_router.core.util.Fetcher - Failed Http Request to <a href="https://192.168.122.181/api/1.2/cdns/name/kabletown_" class="external-link" rel="nofollow">https://192.168.122.181/api/1.2/cdns/name/kabletown_</a><br/>
cdn/sslkeys.json Status 400</p>

Author: Zhilin Huang
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-157">https://issues.apache.org/jira/browse/TC-157</a>
Found Version: 2.1.0

**Comment by dneuman64** [comment]
I don't believe this is a major issue or an issue that will be resolved in 2.1.  I am moving to 2.2.

**Comment by rawlinp** [comment]
Closing this because this doesn't appear to be an issue anymore (was unable to reproduce).
