### ISSUE TITLE
[TC-197] File descriptor leak caused by NIO protocol connector

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#916]
<p>The new default configuration for Traffic Router and Tomcat is to use the <tt>Http11NioProtocol</tt> adapter over the previous <tt>Http11Protocol</tt> adapter. This is accomplished via the <tt>LanguidNioProtocol</tt> connectors specified in Tomcat's <tt>server.xml</tt>.</p>

<p>We observed a file descriptor leak with connections, but have not dug into the cause. We observed roughly 30-40k connections in <tt>CLOSE_WAIT</tt> which caused the machine to exhaust its file descriptors based upon configured limits. We also observed a similar growth curve on total threads, so something is not behaving and being cleaned up appropriately.</p>

<p>The cause could range from a bug in the <tt>Http11NioProtocol</tt> connector due to the ancient version of Tomcat we're using, tuning within the connector itself (max threads, intervals, etc), tuning within the JVM (memory, GC, etc), or at the OS level (kernel params around TCP connections, etc).</p>

Author: Jeff Elsloo
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-197">https://issues.apache.org/jira/browse/TC-197</a>
Found Version: 2.1.0

**Comment by dneuman64** [comment]
Moving to 2.2.0, this should be resolved with the Traffic Router changes to upgrade Tomcat and use the Openssl connector.

**Comment by jeffmart** [comment]
As a work around the following sections in the  /opt/tomcat/conf/server.xml would be changed:

com.comcast.cdn.traffic_control.traffic_router.protocol.LanguidNioProtocol
com.comcast.cdn.traffic_control.traffic_router.protocol.LanguidNioProtocol
com.comcast.cdn.traffic_control.traffic_router.protocol.LanguidNioProtocol

To:
com.comcast.cdn.traffic_control.traffic_router.protocol.LanguidProtocol
com.comcast.cdn.traffic_control.traffic_router.protocol.LanguidProtocol
com.comcast.cdn.traffic_control.traffic_router.protocol.LanguidProtocol

Respectively.

**Comment by rob05c** [comment]
>upgrade Tomcat
Related: #925

**Comment by dneuman64** [comment]
@jeffmart @limited were either of you planning on putting in a PR to make the above workaround the default in the server.xml?

**Comment by limited** [comment]
@dneuman64  Yeah, @jeffmart is going to open a PR for this

**Comment by rob05c** [comment]
Workaround was merged in #1848. The underlying problem will be fixed by upgrading Tomcat, but the workaround mitigates the major issue, so this case can be moved to 2.3.

**Comment by rob05c** [comment]
TC default Tomcat version is now 8.5, this bug was observed in an older Tomcat version, we haven't seen it in 8.5. Feel free to reopen with details if anyone sees this bug again
