### ISSUE TITLE
[TC-318] Chart creation for non-cache servers such as Traffic Routers, Traffic Monitors, Influxdb 

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#920]
<p>copied from <a href="https://github.com/Comcast/traffic_control/issues/1736" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1736</a></p>

<p>On the servers page in TO there is a graph icon which leads to graphs for caches. This icon is currently not present for other types of servers such as Traffic Routers, Traffic Monitors, Influxdb servers, etc. We should create some scripted dashboards and update Traffic Ops so that all server types have graphs with at least grafana data.</p>

Author: Derek Gelinas
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-318">https://issues.apache.org/jira/browse/TC-318</a>

**Comment by mitchell852** [comment]
TO UI was deprecated long ago...closing.
