### ISSUE TITLE
[TC-507] ORT should not use the reverse proxy for security-sensitive files

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#922]
<p>ORT should bypass the reverse proxy in cases where the files being requested are of a sensitive nature.</p>

Author: Derek Gelinas
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-507">https://issues.apache.org/jira/browse/TC-507</a>
Found Version: 2.1.0

**Comment by dg4prez** [comment]
This is fixed in https://github.com/apache/trafficcontrol/commit/959265444899096f9c25a05deb04238d9cb17a70#diff-5c1ab04c7fe5ae614d83bb5867a94d2a
