### ISSUE TITLE
[TC-230] Cache Health Monitor - Add IPv6 Checks

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#923]
<p>We had access to several caches go down over IPv6 but not IPv4 due to a routing issue.  Since the current health check only uses IPv4, these caches were kept in rotation when they should have either been admin downed or at least stopped advertising IPv6.</p>

<p>We are looking for a health monitor check that detects issues on both IPv4 and IPv6.</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-230">https://issues.apache.org/jira/browse/TC-230</a>

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by mitchell852** [comment]
I believe @DylanVolz is looking at this. correct me if i'm wrong @DylanVolz

**Comment by DylanVolz** [comment]
yes I have worked to address this already, we are verifying the changes in this PR still: #1627

**Comment by dneuman64** [comment]
This is a duplicate of #2735 which has a PR open against it, closing.
