### ISSUE TITLE
[TC-499] Traffic Portal logging should be consistent with other TC applications

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#927]
<p>Currently, Traffic Portal's logging is different from other TC components.  It does not contain a log level or a timestamp.  We should make the logging consistent with other TC components so that users can easily discern what is going on and when it happened.</p>

<p>Example of the current logging (these messages were over several hours): </p>

<blockquote>
<p>Error: ENOENT: no such file or directory, open '/etc/pki/tls/private/ca.crt'<br/>
    at Error (native)<br/>
    at Object.fs.openSync (fs.js:641:18)<br/>
    at Object.fs.readFileSync (fs.js:509:33)<br/>
    at Object.&lt;anonymous&gt; (/opt/traffic_portal/server.js:148:29)<br/>
    at Module._compile (module.js:570:32)<br/>
    at Object.Module._extensions..js (module.js:579:10)<br/>
    at Module.load (module.js:487:32)<br/>
    at tryModuleLoad (module.js:446:12)<br/>
    at Function.Module._load (module.js:438:3)<br/>
    at Module.runMain (module.js:604:10)<br/>
error: Forever detected script exited with code: 1<br/>
error: Script restart attempt #116<br/>
Traffic Portal Port         : 80<br/>
Traffic Portal SSL Port     : 443<br/>
error: Forever detected script was killed by signal: SIGKILL<br/>
Traffic Portal Port         : 80<br/>
Traffic Portal SSL Port     : 443<br/>
error: Forever detected script was killed by signal: SIGKILL<br/>
Traffic Portal Port         : 80<br/>
Traffic Portal SSL Port     : 443</p></blockquote>

Author: David Neuman
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-499">https://issues.apache.org/jira/browse/TC-499</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
TP will write to an access.log as you specify in in traffic_portal/conf/config.js. By default it will write it to /var/log/traffic_portal/access.log. In this access.log, a timestamp exists for each log line along with the request path and the response code. Currently, as defined in traffic_portal/server.js, access logs are only captured for response codes 400 or above. That can be changed in server.js.

**Comment by ocket8888** [comment]
Also note that the example used in the issue description is not a log message, it is a stack trace from an unhandled exception. That should never occur - these should be treated as bugs when they're found and not considered normal logging.
