### ISSUE TITLE
[TC-506] Traffic Ops - SSL Cert Expiration Monitoring for Active Services

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#928]
<p>With all services moving towards SSL there will be a constant battle to keep SSL certificates up to date for active services.  Traffic Ops should incorporate an internal monitor for upcoming expirations based on the actual cert source of record.  This could be a part of the delivery service configuration data and would also be useful to customers to examine when certs expire.</p>

<p>1. Record or read SSL cert expiration and put into configuration data<br/>
2. Allow users access to this data through the API<br/>
3. Provide a monitor that runs on a cron to look for certs that expire soon.<br/>
4. Alert root operators daily on upcoming expirations</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-506">https://issues.apache.org/jira/browse/TC-506</a>
Found Version: 2.1.0

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by mitchell852** [comment]
TP/TO API does provide the date of expiration of a delivery service's SSL cert (1 & 2 from above). However, it does not provide 3 & 4 as other tools are used for that. Can we close this @ryandurfey @ashish-timilsina ?

**Comment by mitchell852** [comment]
since 1 and 2 is implemented, i'm going to close this as 3 and 4 are outside of the scope of TO
