### ISSUE TITLE
[TC-283] traffic ops api (PUT api/.../server/...) doc inconsistent with code

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#929]
<p>The Traffic Ops API documentation for "PUT /api/1.2/servers/{:id}" shows that "type" is a required field.   It's actually "type_id".  I think that's true for all the fields representing foreign keys.</p>

<p>Documentation is here: <a href="http://trafficcontrol.incubator.apache.org/docs/latest/development/traffic_ops_api/v12/server.html" class="external-link" rel="nofollow">http://trafficcontrol.incubator.apache.org/docs/latest/development/traffic_ops_api/v12/server.html</a></p>

<p>Code is here: <a href="https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Server.pm#L201" class="external-link" rel="nofollow">https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_ops/app/lib/API/Server.pm#L201</a></p>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-283">https://issues.apache.org/jira/browse/TC-283</a>
Found Version: 2.1.0

**Comment by dangogh** [comment]
I see in current docs that it correctly shows `typeId` (not `type_id`) as the field name
