### ISSUE TITLE
[TC-496] Monthly Report Generation Automation and API Endpoint

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#930]
<p>We need a method to schedule regular CDN service reports to be emailed out from the traffic portal/traffic ops.  The long term vision is to allow customers to schedule email delivery of any report they can view in the portal. </p>

<p>In the short term, we have to email monthly summary reports of each service with summary metrics to customers.  We need a method to schedule the generations of these monthly summaries so we are not manually building 100's of reports.</p>

<p>Currently these reports consist of going into the portal for each service and setting the start and end date for 00:00:00 GMT at the start and end of the month and then viewing all charts and summary metrics.</p>

<p>We need an automated method of generating these in an emailable format like PDF.</p>

<p>See <a href="https://cwiki.apache.org/confluence/display/TC/Reporting" class="external-link" rel="nofollow">https://cwiki.apache.org/confluence/display/TC/Reporting</a> for expanded discussion of use case.</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-496">https://issues.apache.org/jira/browse/TC-496</a>

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by mitchell852** [comment]
TP/TO was not designed with this capability in mind.
