### ISSUE TITLE
[TC-474] link by cache group - delivery services

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#934]
<p>when linking servers to a delivery service it's by server name. being able to add by cache group or profile as per the old version would be much easier. </p>

Author: Sean Aoyagi
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-474">https://issues.apache.org/jira/browse/TC-474</a>

**Comment by mitchell852** [comment]
a filter and select all should accomplish this

**Comment by mitchell852** [comment]
@saoyag001 - if you want to select all servers for profile X, then do a filter by profile X and then hit the "select all" button.

if you want to select all servers for cache group X, then do a filter by cache group X and hit the "select all" button. For example:

![image](https://user-images.githubusercontent.com/251272/33893438-a1871df6-df18-11e7-9010-6eab88646661.png)
