### ISSUE TITLE
[TC-464] Delivery-service tenancy based access control - Federation

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#936]
<p>We have recently added "tenancy" to the project. <br/>
With tenancy, every resource have a tenant, where resource can be a delivery-service, a server (future) and even a user.<br/>
We are now starting to enforce access-control based on the resource tenancy. A user can manage a resource only if the resource is under the user tenancy.</p>

<p>This JIRA deals with another step of "delivery-service as a resource" - enforcing access control on Federations.<br/>
We still need to finalize the specification of this access control.the TC </p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-464">https://issues.apache.org/jira/browse/TC-464</a>

**Comment by nir-sopher** [comment]
resolved
