### ISSUE TITLE
[TC-465] Delivery-service tenancy based access control - JOBs

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#937]
<p>We have recently added "tenancy" to the project. <br/>
With tenancy, every resource have a tenant, where resource can be a delivery-service, a server (future) and even a user.<br/>
We are now starting to enforce access-control based on the resource tenancy. A user can manage a resource only if the resource is under the user tenancy.</p>

<p>This JIRA deals with another step of "delivery-service as a resource" - enforcing access control on Jobs, according to their Delivery service.<br/>
We still need to finalize the specification of this access control, and it would not be included in the first phase of tenancy introduction, assuming that the application hide from the user the ability to deal with DSes which are not under his tenancy.</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-465">https://issues.apache.org/jira/browse/TC-465</a>

**Comment by mitchell852** [comment]
this should be done. you can't create a "job" for a ds that is outside your tenancy i don't think.

**Comment by nir-sopher** [comment]
Resolved
