### ISSUE TITLE
[TC-220] Logging System Creation

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#943]
<p>Create an open source system to gather ATS request / response logs.</p>

<p>1. Must be built from all open source components.<br/>
2. Must be able to ingest 1MM records a second on a reasonable amount of hardware and be horizontally scalable to add additional capacity.<br/>
3. Must allow storage of raw logs for configurable period of time between 30-90 days.<br/>
4. Must be able to process raw logs from ATS and split based service by assessing configuration of service.<br/>
5. Must be able to split logs into files of no more than 2 hours or 500k logs whichever occurs first.  These should be starter configs and should be configurable on a per service basis.<br/>
6. Log files must be compressed to conserve space.<br/>
7.  Log files should be accessible via a web server interface.<br/>
8. Log files should be accessible via an API request.</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-220">https://issues.apache.org/jira/browse/TC-220</a>
Found Version: 2.1.0

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by mitchell852** [comment]
this is outside of the scope of TC. closing.
