### ISSUE TITLE
[TC-411] Traffic Router Log Aggregation

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#945]
<p>Aggregate Traffic Router logs into one minute intervals </p>

<p>Breaking down bytes, requests,  time to serve (ttms), and users into various buckets allows for rapid charting for analytics, reporting, and monitoring<br/>
Sum of requests, count chi (user IPs)<br/>
by Server<br/>
by Service<br/>
by CDN<br/>
by Type (HTTP Redirect or DNS Nameserver)<br/>
by Service (CDN service)<br/>
by Host (Traffic Router)<br/>
by Destination (Cache Group)<br/>
by Request Type (A or AAAA)<br/>
Other?</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-411">https://issues.apache.org/jira/browse/TC-411</a>

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by mitchell852** [comment]
this is outside of the scope of TC. closing.
