### ISSUE TITLE
[TC-392] Traffic Server Log aggregation in 1 min intervals for delivery service charting

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#946]
<p>Breaking down bytes, requests,  time to serve (ttms), and users into various buckets allows for rapid charting for analytics, reporting, and monitoring<br/>
Sum of bytes, sum of requests, sum ttms(time to serve milliseconds), count chi (user IPs)<br/>
by CDN<br/>
by Service (CDN service)<br/>
by Host (server)<br/>
by Cache Group (site or geo)<br/>
by IPtype (IPv4 or IPv6)<br/>
by pssc (http return code)<br/>
by crc (cache response code)<br/>
by minute</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-392">https://issues.apache.org/jira/browse/TC-392</a>

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by dneuman64** [comment]
I don't think this is a function of Traffic Control.  This should be done by whatever your logging platform is.
