### ISSUE TITLE
[TC-410] Traffic Ops Configuration Change Logs into Traffic Analytics system

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#947]
<p>Push traffic ops configuration change logs into the Traffic Analytics system</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-410">https://issues.apache.org/jira/browse/TC-410</a>

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by mitchell852** [comment]
this is outside of the scope of TC. closing.
