### ISSUE TITLE
[TC-409] Traffic Router Logs push into Traffic Analytics system

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#948]
<p>Push Traffic Router request logs into Traffic Analytics system.</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-409">https://issues.apache.org/jira/browse/TC-409</a>

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by mitchell852** [comment]
this is outside of the scope of TC. closing.
