### ISSUE TITLE
[TC-400] incomplete error message from TO api

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#952]
<p>When doing a `POST /api/1.2/deliveryservices` with the attached json,  I get this error:</p>

<p>{"alerts":[</p>
{"level":"error","text":"parameter profileName is must."}
<p>]}</p>

<p>I assume it means that a profile name must be provided,  but is poorly worded and incomplete.</p>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-400">https://issues.apache.org/jira/browse/TC-400</a>
Found Version: 2.1.0

**Comment by dangogh** [comment]
this will go away when rewritten in Go
