### ISSUE TITLE
[TC-394] Scale Components to Handle > 2,000 delivery services

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#953]
<p>We have several resellers that are interested in using our CDN.  These companies have 1,000+ small delivery services spread across ~250 sub-tenants.  We need to ensure that core components will scale to handle this many services without impacting existing customers.</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-394">https://issues.apache.org/jira/browse/TC-394</a>

**Comment by mitchell852** [comment]
@ryandurfey - there are methods to scale TC to meet the ds demands. i.e. more TRs, more TMs, more traffic servers, etc. in addition to GSLBs for traffic ops. can you please reopen with more specific info if had something else in mind?
