### ISSUE TITLE
[TC-389] pkg build script should be more helpful

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#959]
<p>Tried out the ./pkg build script with docker and docker-compose properly installed.</p>

<p>It failed, but gave me no information whatsoever.  Also,  no dist directory,  so no log files from docker-compose:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">
$ ./pkg source traffic_ops_build
Building source.
Building traffic_ops_build.
Failed to build source traffic_ops_build.
</pre>
</div></div>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-389">https://issues.apache.org/jira/browse/TC-389</a>

**Comment by dangogh** [comment]
using the `-v` flag gives more info now
