### ISSUE TITLE
[TC-212] Configurable Dashboards in Portal

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#962]
<p>Create a framework in the CDN Portal so that users have a base set of dashboards that they inherit, and can then create new dashboards based on any service data available to them.</p>

<p>*Allow users to CRUD dashboards.<br/>
*Allow users to save these dashboards.<br/>
*Allow users to share dashboards they have created with other users so they can save to their account.</p>

<p>The vision is something along the lines of what Kibana or Grafana already do. May require some query language to be used to create the dashboard.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-212">https://issues.apache.org/jira/browse/TC-212</a>

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina
