### ISSUE TITLE
[TC-299] Change Log. Expand status to human readable string

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#965]
<p>Opened on bugs scrub, based on <a href="https://github.com/Comcast/traffic_control/issues/620" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/620</a></p>

<p>smalenfant:<br/>
Sometimes I've got a hard time following what Ops is doing. Having a better understanding from the Change log would help a long way... I can't tell what happened here without knowing that "6" is OFFLINE. We should be expand this easily.</p>

<p>Would also be nice to see the "From Status" to "To Status".</p>

<p>2015-09-15 12:27:04 UICHANGE    Update server edge04 status-&gt;6 user <br/>
2015-09-15 12:26:52 UICHANGE    Update server edge03 status-&gt;6 user <br/>
2015-09-15 12:26:41 UICHANGE    Update server edge02 status-&gt;6 user <br/>
2015-09-15 12:26:28 UICHANGE    Update server edge01 status-&gt;6 user</p>

<p>Sometime we see the following.. probably different code path.</p>

<p>2015-09-18 13:20:23 UICHANGE    Update server edge04.kabletown.net new status = REPORTED user   <br/>
2015-09-18 13:20:18 UICHANGE    Update server edge02.kabletown.nett new status = REPORTED user</p>

<p>dewrich:<br/>
If you can make a list of all of the Change Log tweaks you'd like to see like this, I will put it in the backlog to enhance them.</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-299">https://issues.apache.org/jira/browse/TC-299</a>

**Comment by mitchell852** [comment]
closing as the change log was improved in #3771
