### ISSUE TITLE
[TC-304] Ping each Riak server

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#966]
<p>Based on: <a href="https://github.com/Comcast/traffic_control/issues/1306" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1306</a></p>

<p>We should connect to (ping) each Riak server on startup to make sure that we have an SSL session established. Perhaps we should ping() each Riak server before marking it "online"?</p>

Author: Nir Sopher
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-304">https://issues.apache.org/jira/browse/TC-304</a>

**Comment by mitchell852** [comment]
closing as riak is soon to be deprecated.
