### ISSUE TITLE
[TC-213] Purge Functionality - Add to Portal

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#967]
<p>We found that in some cases corrupted content can get trapped in the edge cache with proper ETAGs, so invalidation requests are not able to cause the content to reload. We also found there is a business case to remove content from cache. We need a mechanism that works similar to invalidation but actually purges content from the caches.</p>

<p>This would be done without wildcards as a restriction.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-213">https://issues.apache.org/jira/browse/TC-213</a>

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina
