### ISSUE TITLE
[TC-216] Chart Add - Unique User Count Chart Added to data API and Traffic Portal Charts

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#968]
<p>Unique user count per minute per delivery service.</p>

<p>Depends upon log data aggregation into time series database.</p>

Author: Ashish Timilsina
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-216">https://issues.apache.org/jira/browse/TC-216</a>
Found Version: 2.1.0

**Comment by ashish-timilsina** [comment]
@ryandurfey 
@ashish-timilsina

**Comment by mitchell852** [comment]
log aggregation is currently outside the scope of TC.
