### ISSUE TITLE
[TC-356] license cleanup for vendored files

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#972]
<p>The following list of files are signaled by apache-rat as not having Apache-compatible licenses.  Some need the license to be added while others may need to be added to the .rat-excludes file:</p>

<ul>
	<li>BUILD_NUMBER</li>
	<li>traffic_ops/experimental/auth/server.key</li>
	<li>traffic_ops/experimental/ui/app/src/common/modules/table/_table.scss</li>
	<li>traffic_ops/experimental/ui/app/src/common/modules/widget/cacheGroups/_widget.cacheGroups.scss</li>
	<li>traffic_ops/experimental/ui/app/src/common/modules/widget/capacity/_widget.capacity.scss</li>
	<li>traffic_ops/experimental/ui/app/src/common/modules/widget/routing/_widget.routing.scss</li>
	<li>traffic_ops/experimental/ui/app/src/styles/loading.scss</li>
	<li>traffic_ops/experimental/ui/app/src/styles/theme.scss</li>
	<li>traffic_ops/experimental/webfront/server.key</li>
	<li>traffic_ops/experimental/webfront/simpleserver/server.key</li>
	<li>traffic_portal/app/src/styles/loading.scss</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/client/v2/client.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/client/v2/udp.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/models/consistency.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/models/inline_fnv.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/models/inline_strconv_parse.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/models/points.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/models/rows.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/models/statistic.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/models/time.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/pkg/escape/bytes.go</li>
	<li>traffic_stats/vendor/github.com/influxdata/influxdb/pkg/escape/strings.go</li>
	<li>traffic_stats/vendor/github.com/pkg/errors/appveyor.yml</li>
	<li>traffic_stats/vendor/github.com/pkg/errors/errors.go</li>
	<li>traffic_stats/vendor/github.com/pkg/errors/stack.go</li>
	<li>traffic_stats/vendor/golang.org/x/net/PATENTS</li>
	<li>traffic_stats/vendor/golang.org/x/net/publicsuffix/gen.go</li>
	<li>traffic_stats/vendor/golang.org/x/net/publicsuffix/list.go</li>
	<li>traffic_stats/vendor/golang.org/x/net/publicsuffix/table.go</li>
</ul>

Author: Dan Kirkwood
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-356">https://issues.apache.org/jira/browse/TC-356</a>
Found Version: 2.1.0

**Comment by dangogh** [comment]
Fixed by #659
