### ISSUE TITLE
[TC-329] hosting.config not matching with dynamic regex remap 

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#974]
<p>See <a href="https://github.com/Comcast/traffic_control/issues/1562" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/1562</a></p>

<p>The hosting.config has an entry for the origin created in the Delivery service UI for a live server (volume=2 which is RAM). The problem comes when we use a REGEX to set an origin dynamically.</p>

<p>Example Origin URL : <a href="http://server01.kabletown.net" class="external-link" rel="nofollow">http://server01.kabletown.net</a></p>

<p>Then the Regex is the following : ^/(server\w\d\d)/(<span class="error">&#91;^?&#93;</span>+)(?:\.m3u8|)(.*)$ <a href="http://$1-.kabletown.net/$2" class="external-link" rel="nofollow">http://$1-.kabletown.net/$2</a></p>

<p>The result in the hosting.config is :</p>

<p>hostname=server01.kabletown.net volume=2<br/>
hostname=*   volume=1<br/>
If the remap ends up with server02.kabletown.net then disks are used instead of RAM.<br/>
 @smalenfant smalenfant added bug Traffic Ops labels on Jun 28, 2016<br/>
 @smalenfant<br/>
     Member<br/>
smalenfant commented on Jun 28, 2016<br/>
There is also another side effect with the parent.config.<br/>
 @knutsel<br/>
     Member<br/>
knutsel commented on Jun 29, 2016<br/>
We could add hosting_override and parent_override columns to the delveryservice table, but that seems a bit too ATS specific? Or an overrides table that is linked to the ds table that has file -&gt; override line?</p>

<p>@dg4prez : you had similar use cases recently, I think? Any thoughts on this?<br/>
 @dg4prez<br/>
     Collaborator<br/>
dg4prez commented on Jun 29, 2016 • edited<br/>
Perhaps rather than cluttering up regex remap with more overrides for that specific use case, we remove regex remap in favor of adding more manual options to any_map. Then we could directly write the configs entries we want. I've given some rough thought to how we'd do that, though I haven't applied it to the hosting.config so we'd need to add that in there as well. Note that these would all be for advanced users who fully comprehend how traffic server works. In my opinion this is already the case for any_map and regex remap, anyway.</p>

<p>Database changes</p>

<p>add table anymap (deliveryservice_anymap)<br/>
ID, remap text, edge_header, mid_header, type (edge, mid, etc), last updated</p>

<p>add table anyparent (deliveryservice_edgeparent)<br/>
ID, parent text, type (edge, mid, etc), last updated<br/>
#autogenerated by cachegroup for edge types, fully manual for mid</p>

<p>add table includes (deliveryservice_includes)<br/>
ID, file_name, file_content (this would need to be a large field), type (edge, mid, etc), last updated</p>

<p>UI</p>

<p>Origin server base URL - remove this<br/>
Use MSO feature - remove this</p>

<p>Remap Entries - create entries the same way we create them for regex entries - add one or a whole bunch. probably don't need order. Group of the following for each.</p>

<p>Raw Remap Text:<br/>
Edge Header Rewrite:<br/>
Mid Header Rewrite:<br/>
Tier Assignment: (edge, mid, etc checkboxes)</p>

<p>Note that in order to include header rewrite entries for each the header name would need to be something like xml_id_1, xml_id_2, etc. Not sure of the best answer, yet. Maybe the best way would be to place a line under each header saying what the user would need to add to the remap line in order to include it, or maybe the best way would be to have the system automatically append it.</p>

<p>Parent entries - Same as remap entries, add as many as needed</p>

<p>Mid Parent text:<br/>
Tier assignment: (edge, mid, etc checkboxes)</p>

<p>Manual includes - files we want to reference on the map lines like header rewrites etc that don't exist. We'd add each one, and the user would include the filename and contents.</p>

Author: Jan van Doorn
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-329">https://issues.apache.org/jira/browse/TC-329</a>

**Comment by knutsel** [comment]
@dg4prez - can we close this? I think we should. Voluspa may change all this in any case, and @rawlinp is also working on some BYOT ideas....
