### ISSUE TITLE
[TC-357] Edge Server Parent Configuration Validation

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#975]
<p>We recently had an issue where several edge servers received configs which did not indicate a mid tier parent cache.  These configs caused the edge caches to try to reach the origins directly which caused 502 responses for several customers since their origins are locked down.</p>

<p>I am proposing a edge server config validation for this type of misconfiguration that would either prevent it or at least alert the person submitting the config that there may be a problem.</p>

Author: Ryan Durfey
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-357">https://issues.apache.org/jira/browse/TC-357</a>

**Comment by mitchell852** [comment]
@ryandurfey - can you provide a bit more information around this? for example, what type of delivery service was this if you remember?
