### ISSUE TITLE
[TC-86] Add default delivery service <> cache assignment

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#976]
<p>Cache assignments for a new delivery service should be "all", which should prevent us from having to track each-and-every cache for each-and-every delivery service. </p>

<p>PS: We might need to split this into a separate JIRA for each component.</p>

Author: Mark Torluemke
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-86">https://issues.apache.org/jira/browse/TC-86</a>

**Comment by mitchell852** [comment]
closing as this can be satisfied using a topology instead.
