### ISSUE TITLE
[TC-435] TPv2 - add the ability to clone DS assignments from one server to another

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#981]
<p>Add the ability to clone DS assignments from one server to another.</p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-435">https://issues.apache.org/jira/browse/TC-435</a>

**Comment by mitchell852** [comment]
@DylanVolz has been working on this. @DylanVolz can you add a comment that links this issue to your PR?

**Comment by DylanVolz** [comment]
#1197 addresses the api changes needed for this issue.

**Comment by mitchell852** [comment]
this is done
