### ISSUE TITLE
[TC-551] TO API - add the ability to filter parameters by name or config file

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#982]
<p>Examples:</p>

<p>/api/1.2/parameters?name=LogFormat.Format<br/>
/api/1.2/parameters?configFile=records.config</p>

Author: Jeremy Mitchell
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-551">https://issues.apache.org/jira/browse/TC-551</a>

**Comment by ocket8888** [comment]
According to [the route's documentation](https://traffic-control-cdn.readthedocs.io/en/latest/api/v3/parameters.html#request-structure) this has been done. Please re-open if there's a bug that prevents this functionality from working as documented.
