### ISSUE TITLE
[TC-199] Configurable consistent hash attributes for cache selection

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#985]
<p>Add a feature to Traffic Router and Traffic Ops that allows one to specify attributes to use when consistent hashing for cache selection on a per-delivery service basis. One specific use case is to allow us to consider the query string, as the default is to ignore it. Beyond that, we might want to allow additional strategies, such as a regex that will match parts of the attribute (path, header), or allow URL + header, header only, etc.</p>

<p>Other options:</p>
<ul>
	<li>short hostname</li>
	<li>domainname</li>
	<li>fully qualified domainname</li>
	<li>Partial path</li>
	<li>Path segments/delimiter (<tt>;</tt>)</li>
	<li>Headers</li>
	<li>Combinations of the above</li>
	<li>Regular expressions applied to the URL or header(s)</li>
</ul>

Author: Jeff Elsloo
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-199">https://issues.apache.org/jira/browse/TC-199</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
2 features have been introduced since this issue was created:

- consistent hash query params that allows the user to specify on a ds which query params should be part of the consistent hash and
- consistent hash regex

i believe these 2 features should solve part of this issue.
