### ISSUE TITLE
[TC-296] ANY_MAP doesn't get applied to the mids

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#987]
<p>Delivery services of type ANY_MAP only gets a line in remap.conf for caches of type EDGE.</p>

<p><a href="https://github.com/Comcast/traffic_control/issues/740" class="external-link" rel="nofollow">https://github.com/Comcast/traffic_control/issues/740</a></p>

Author: Eric Friedrich
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-296">https://issues.apache.org/jira/browse/TC-296</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
I believe this is working as designed as when you add raw remap text to an any_map ds, it gets appended to the remap.config file for the servers directly assigned to the ds which would be the edges only. @limited do you understand differently?

**Comment by limited** [comment]
Closing for age
