### ISSUE TITLE
[TC-294] Missing location parameter leads to broken remap.config

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#992]
<p>From the original GH issue #195:</p>

<p>For things like header_rewrite, cacheurl, etc, there isn't value in managing the 'location' parameter outside the delivery service assignment to the caches...is there?</p>

Author: Mark Torluemke
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-294">https://issues.apache.org/jira/browse/TC-294</a>
Found Version: 2.1.0

**Comment by mitchell852** [comment]
this is a duplicate
