### ISSUE TITLE
[TC-426] Postinstall -- answering "no" to certificate generation does not skip

### ISSUE THREAD

**Issue by limited** [apache/trafficcontrol#998]
<p>Answering 'no' to 'Do you want to generate a certificate?:' forces certificate generation.  That section should have been skipped.</p>

<p>===========/opt/traffic_ops/install/data/json/openssl_configuration.json===========<br/>
Do you want to generate a certificate?: no<br/>
Country Name (2 letter code): US</p>

Author: Dewayne Richardson
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-426">https://issues.apache.org/jira/browse/TC-426</a>
Found Version: 2.1.0

**Comment by dewrich** [comment]
Looks like this line fixes this issue now: https://github.com/apache/trafficcontrol/blob/master/traffic_ops/install/bin/_postinstall#L682
